### ISSUE TITLE
Better handle deleting a parent taxonomy field

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#1005]
### Is your feature request related to a specific problem?

It is possible to delete a top level taxonomy field (for instance, `system` in `data_category`) while it still has children field (i.e. `system.authentication`). Right now, the top level field will delete, but the children will stick around. This potentially breaks things since some parent keys will be missing.

### Describe the solution you'd like

Ideally, this either would not be allowed, or the children would cascade delete as well.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

https://ethyca.slack.com/archives/C01TEJVMYSX/p1661195800544009

Also pretty closely related to the delete UI ticket https://github.com/ethyca/fides/issues/859

**Comment by allisonking** [comment]
@ThomasLaPiana @mfbrown what should be the desired behavior here when a parent taxonomy field is deleted?

1. forbid because there are children
2. delete it and all of its children

**Comment by ThomasLaPiana** [comment]
I'd prefer to _warn the user first_ but then go with option 2. If they really know they want to delete it, I think we should make it easier for them

**Comment by allisonking** [comment]
okay, that makes sense. this ticket was meant to be for the backend though—so maybe this ticket can cover cascade deleting in the backend, and then another ticket for showing a warning in the UI when deleting a parent field?

**Comment by ThomasLaPiana** [comment]
oh roger that, sounds good!
