### ISSUE TITLE
Update docs on the `unified-fides` branch to merge fidesctl & fidesops

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#1008]
### Docs Update Description

 Right now the docs exist side-by-side, but they need to be properly integrated

**Comment by conceptualshark** [comment]
@ThomasLaPiana Should this be fidesctl and fidesops, or is there an expectation around fidesplus docs being merged with unified-fides? I didn't think we had any docs separation for fidesplus atm, so I want to make sure I understand the ask.

**Comment by ThomasLaPiana** [comment]
@conceptualshark 100% a mistype on my part! Fixed the title :) 

It's for merging ctl/ops

**Comment by ThomasLaPiana** [comment]
I'm going to contribute on this PR as well to clean up some of the docs infra/testing we have going on
