### ISSUE TITLE
Add support for python 3.7+ in unified-fides

### ISSUE THREAD

**Issue by sanders41** [ethyca/fides#1017]
### Is your feature request related to a specific problem?

_A description of what the problem is._
Currently Python versions that are still receiving active support are Python 3.7+. In fidesctl we currently specify support for 3.9+ and fidesops specifies support for 3.8+. Looking at download metrics we do have users on older versions so we should look to support them. Among the older versions, 3.8 use looks to be fairly with 3.7 being used, but rare. So worst case supporting 3.8+ would still be beneficial.

In theory both fidesctl and fidesops will currently work with 3.7+, however we only test on 3.9.

### Describe the solution you'd like

Add tests for 3.7+ to verify everything works as expected. If no issues show up we can officially say we support 3.7+.

### Describe alternatives you've considered, if any

Leave things as they are with only testing 3.9. I don't think we are doing anything 3.9+ specifically currently so things _should_ work in 3.7+.

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by ThomasLaPiana** [comment]
Do you already have a solution for testing multiple python versions in CI? I guess we can leverage docker?

**Comment by sanders41** [comment]
If that will work it will probably be the easiest way. I have been looking into running the tests on different python versions outside docker, still using docker for databases, redis, etc. What I am finding is the fidesctl/ops code and/or test code are very tied to running inside docker so it will take a lot of refactoring to get it to work.

**Comment by ThomasLaPiana** [comment]
Ok that makes sense, I think using a build arg is the most elegant solution then and we just have to accept that we're virtually quadrupling the tests we're running or so

@NevilleS ran into an issue with `fidesctl` on Python 3.10 as well, so this will definitely be worth the squeeze

**Comment by sanders41** [comment]
I agree it's worth it to add the extra tests and the build args will be our fastest path to get there.

We can always follow-up later with a refactor to allow the tests to run outside of docker that would significantly speed things up. At that point we would also have some options. We could even keep running 3.9 in docker like we do now and everything else outside so we only need one build.

**Comment by ThomasLaPiana** [comment]
> I agree it's worth it to add the extra tests and the build args will be our fastest path to get there.
> 
> We can always follow-up later with a refactor to allow the tests to run outside of docker that would significantly speed things up. At that point we would also have some options. We could even keep running 3.9 in docker like we do now and everything else outside so we only need one build.

Oh I kinda like that idea...that way we can confirm that our docker builds are working as intended while also more easily testing multiple versions 🤔 

FWIW so many of our tests need to get run inside of docker containers anyway (including the webserver during the tests!) That I'm not really sure how feasible it would be at this point to run tests outside of docker, but we can discuss that later

**Comment by ThomasLaPiana** [comment]
Helpful link, this is preferable to building a docker container for each version!

https://bgasparotto.com/install-pyenv-ubuntu-debian
