### ISSUE TITLE
Ask for user email and organization on first run.

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#1024]
As an Ethyca PM, I want to know which users and from what organization are successfully cloning and running Fides (Ops and CTL), so that I can measure user acquisition and provide to sales as leads.

**Details**

Today, we are effectively blind as to who is cloning and running our open source fides projects. We need to transparently ask users to provide this info the first time Fides runs then save this info so we can access it.

**Acceptance Criteria**

- Must ask on the CLI
- Must ask for email address 
- Must ask for organization as an optional input
- Must send this info via Fideslog to our data warehouse
  - Email
  - Organization
  - Fidesctl (what project are they running)
- Must ensure that the user data will be deleted upon request to erase through our privacy center.
  - Will have to create a manual DSR in Ethyca Pro
- Must explain what the info will be used for
- Must update our annotations to describe this data use.
- Create a view in Snowflake so that sales can view this information.

"When you opt to share your information with us upon using Fides, you agree that we can store the information and may use the information to aid in our sales enablement processes. However, at any time you can request to erase your personal information from our systems through the Ethyca Privacy Center by clicking on the following link: [https://privacy.ethyca.com/"](https://privacy.ethyca.com/)

<br/>

<br/>

**Comment by ThomasLaPiana** [comment]
This will require updates to:
* Fides(ctl)
* Fideslog
* Snowflake

We'll also require some copy to explain why this is requested (a la our current copy for the analytics id)

**Comment by mfbrown** [comment]
@ThomasLaPiana The copy is in the description: 

"When you opt to share your information with us upon using Fides, you agree that we can store the information and may use the information to aid in our sales enablement processes. However, at any time you can request to erase your personal information from our systems through the Ethyca Privacy Center by clicking on the following link: [https://privacy.ethyca.com/"](https://privacy.ethyca.com/)

**Comment by NevilleS** [comment]
I know we're (rightfully) worried about the potential privacy risk of storing identifiable user data on every event, so one option we could do would be:
* keep the existing structure of fideslog events (with a pseudonymous client ID)
* add a new "client identity" table with user information that links to their pseudonymous client ID
* collect consent for the `user.contact` data we want to collect
* populate the "client identity" table upon registration once we've collected consent

This allows us to trivially pseudonymize a given user's data by just masking the client identity table, and we continue to maintain that the events table will always be pseudonymous.

**Comment by malaethyca** [comment]
Cannot collect this at the level of downloading docker
2. UI: Need UX registration flow for collecting data
3. CLI: Need UX registration flow for collecting data (exists today, the message needs to be updated)
4. API - nothing can be done

**Comment by Kelsey-Ethyca** [comment]
This has been fully broken out and refined and assigned to Thomas

**Comment by NevilleS** [comment]
Yes, we broke this out into:
* https://github.com/ethyca/fideslog/issues/82
* https://github.com/ethyca/fides/issues/1365
* https://github.com/ethyca/fides/issues/1366
* https://github.com/ethyca/fides/issues/1367
