### ISSUE TITLE
FidesCtl - Human Readable output for fides evaluate

### ISSUE THREAD

**Issue by malaethyca** [ethyca/fides#1048]
https://ethyca.atlassian.net/jira/servicedesk/projects/FIDES/queues/custom/46/FIDES-46

**Comment by ThomasLaPiana** [comment]
@malaethyca I can't see that page, can you update the description here to include all of the relevant information?

**Comment by malaethyca** [comment]
I'll attach it here, but I think you should get access to Jira by messaging Dave. It's not practical for me to copy each customer ticket into Github.

**Comment by malaethyca** [comment]
![image-20220831-202904](https://user-images.githubusercontent.com/108771409/188549852-d258ba2b-d073-4da6-8ad0-c81872af3018.png)
