### ISSUE TITLE
Remove mssql dependency from default docker build to improve performance

### ISSUE THREAD

**Issue by ssangervasi** [ethyca/fides#1051]
### Is your feature request related to a specific problem?
The fides Docker build includes installation of Microsoft SQL Server dependencies, such as `mssql-tools`. These dependencies increase build time significantly, even though the mssql features are [optional "dangerous" extras](https://github.com/ethyca/fides/blob/6e7c80b565388a535b6eea8adf8b916d41202c85/setup.py#L33-L34). 
[Fidesops](https://github.com/ethyca/fidesops/blob/main/Dockerfile#L37) has already introduced an env var to avoid these dependencies.

These dependencies also force us to use [AMD64 base docker image](https://github.com/ethyca/fides/blob/0f9c9062/Dockerfile#L1), because the packages are published for ARM64:
`FROM --platform=linux/amd64 python:3.9-slim-bullseye as base`

This introduces a dramatic performance degradation on Apple M1 chips, which are common for developer machines. Docker Desktop warns about this problem:

> ⚠️ AMD64
> Image may have poor performance, or fail, if run via emulation.

### Describe the solution you'd like

The main docker build stages should all avoid mssql and the platform restriction: base, builder, dev, and prod.

To support Microsoft SQL users, there are a few options:
1. Documentation on the MSSQL extras and the dependencies required.
    - Perhaps a sample Dockerfile for using fides a base and layers in the platform + dependencies
2. A build stage that includes the platform specifier and the dependency installation
    - Could this image be published with a dedicated tag? 

### Describe alternatives you've considered, if any
- Have the "with mssql" be the default and document how to build "without mssql"
    - This reduces how much the image will change in the next release
    - But mssql usage is not the 90% use case
- Throw M1 chips into the ocean
    - The macbook "professional" doesn't support two+ external displays. This machine is a $1,500 prank.
    - Unfortunately I already keep all my used car batteries in the ocean.

**Comment by ThomasLaPiana** [comment]
@pattisdr discovered in #1151 that this is also causing very poor performance when running pytest from within the docker shell
