### ISSUE TITLE
Add dataset classification field in editor panel

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#1077]
* Design: [Fidesops-Management-UI](https://www.figma.com/file/MTbZohIGvB4bq2f2wkiDHO/Fidesops-Management-UI?node-id=3527%3A57357) ([old](https://www.figma.com/file/ArkIrEHQuWeQAQQtuKUXNJ/Classify?node-id=22%3A7634))
* When no category has been manually assigned, the selected category shows classifier's best category match.
* Clicking on "search taxonomy" (left half) shows the original checkbox tree to manually set the categories.
* Clicking on the selected categories area (right half) shows a dropdown with a list of the suggested categories and their confidence. Clicking on a suggested category selects it, just like selecting it from the checkbox tree.

❓Open questions:   
* Is there an API to assign set this field? Does it live on the dataset model? - _**This should ultimately be returned by this new endpoint I believe: https://github.com/ethyca/fidesctl-plus/issues/99**_
* What even is this? - _**This is the list of classification suggestions which were generated for the field. Classify will often return more than one suggestion and we want to give users the option to review and select from them if necessary.** (Note: this question was asked when the design had the "classification" separate from the category dropdown. It should be clear now.)

**Comment by ssangervasi** [comment]
Note: this ticket can cover updating the visual changes and selection state without worrying about how the data comes from the API. When the API is ready I'll transform the result into whatever is convenient for this interface.

**Comment by allisonking** [comment]
@mfbrown can you confirm if the output of this glorified select multi-box is a single value, or an array of values? the left side (checkbox tree) gives an array at the moment, but the right side looks more like a single select? if someone chooses something from the right side, does that remove anything chosen by the left? or is it always adding?

**Comment by allisonking** [comment]
We've decided that we will output arrays, and the box on the right will be a multiselect
