### ISSUE TITLE
List: API that returns list of connectors in Fides

### ISSUE THREAD

**Issue by malaethyca** [ethyca/fides#1089]
Requirement: Fides should have an API that would return the current list of connectors supported.

User Story:
As a connector developer, I want to know what connectors exist in Fides before I build one. So this API should return the current list of connectors supported in the Fides platform.

Notes:
* Not sure if the argument of the API needs to specify the type of connector such as "Database", "SaaS", etc.
* This API would be used in Fides UI to show the user the list of connectors to avoid building one if it already exists.

**Comment by ThomasLaPiana** [comment]
@malaethyca given the use-case here appears to be to inform a developer of the existing connectors, is this requirement more simply met by putting it in our docs?

**Comment by malaethyca** [comment]
@ThomasLaPiana these are building blocks to be able to have a connector builder in Fides UI

**Comment by ThomasLaPiana** [comment]
makes sense!

**Comment by malaethyca** [comment]
According to Neville, there is an API that does this already.
