### ISSUE TITLE
Build: API that generates SaaS config

### ISSUE THREAD

**Issue by malaethyca** [ethyca/fides#1090]
Given the endpoint to an API enabled application, generate a framework for SaaS config file in Fides Lang.
Arguments of the API: Login information of the application
Response of the API: the SaaS configuration yaml that can be extended by the connector developer

User Story:
As a connector developer, I want to be able to automatically generate a framework for the SaaS configuration in Fides Lang, for a given SaaS application.

Note:
This will be used in Fides UI so a non technical user can generate the framework for the SaaS config.

**Comment by Kelsey-Ethyca** [comment]
We did not do this in Phase 1. The functionality exists just not the api. Assigning to @saiatethyca to say whether this is needed or close as not planned.

**Comment by saiatethyca** [comment]
Closing the issue as we already have a button to generate SaaS config.
