### ISSUE TITLE
Recharge - Access

### ISSUE THREAD

**Issue by malaethyca** [ethyca/fides#1101]

**Comment by galvana** [comment]
Adaptor account not available, will need to create a new account for connectors.

**Comment by azazeldt** [comment]
It looks like a test account is not required for this one. This is according to our own analysis `https://ethyca.atlassian.net/wiki/spaces/EPRO/pages/507281507/Recharge+Analysis`

**Comment by Kelsey-Ethyca** [comment]
Blocked when using the shopify account, you have to setup a payment gateway.
