### ISSUE TITLE
Search: API that returns a boolean to indicate a connector exists

### ISSUE THREAD

**Issue by malaethyca** [ethyca/fides#1104]
Requirement:
Given a connector name, return a boolean if the connector exists

User Story:
As a connector developer, I want to check if a connector already exists before I build a new one.

Note: This will be used by the Fides connector builder UI.

**Comment by ThomasLaPiana** [comment]
Is this functionally different than #1089 ?

**Comment by malaethyca** [comment]
@ThomasLaPiana One is search, the other is a list of all connectors.

**Comment by Kelsey-Ethyca** [comment]
We have a search api that does partial match
