### ISSUE TITLE
Add a `fides deploy` command for users to run an example local environment for demoing or testing

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#1115]
### Is your feature request related to a specific problem?

Currently if a user wants to run fides via the docker-compose file, the only choice they have is to clone the repo and run it that way. This is not a common way for end-users to interact with a tool (repos are usually for development, not for deployment of any kind) and feels like it increases the barrier to entry.

### Describe the solution you'd like

Include docker-compose files as part of the `pip` package and add a CLI command to spin it up. We could also include a subset of the test data scripts (see #1291) to fully configure a data map and privacy request automation.

If we could make it as easy as `pip install ethyca-fides` and `fides deploy` (in the same vein as `fides webserver` and `fides worker`) we could really simplify the act of deploying an instance of `fides` for local or simpler use-cases!

**Comment by ThomasLaPiana** [comment]
Wrote this up a bit, here are some examples of commands...

Valid version:
```
fides> fides deploy
Loading config from: .fides/fides.toml
----------
Docker Compose version v2.10.2
Docker version 20.10.17, build 100c701
----------
Starting application...
[+] Running 5/22
 - fides Pulling           
```

Invalid version:
```
fides> fides deploy
Loading config from: .fides/fides.toml
----------
Docker Compose version v2.10.2
Docker Compose version is not compatible, please update to at least version 2.29.10!
```

**Comment by NevilleS** [comment]
Updated this and add to the overall Test Automation Improvements project. This would be really powerful and a nice way to repurpose the exact same test & demo commands we use internally to the repo to allow others to test out the tools for themselves

**Comment by seanpreston** [comment]
> @PSalant726: we might want to consider a new name for this command to something more accurate

Suggestions are welcome!

**Comment by ThomasLaPiana** [comment]
`fides demo`, considering it'll load the environment with the demo data, etc.?

**Comment by ThomasLaPiana** [comment]
I thought about that, but the goal is to be as absolutely simple as possible. When might someone want to `seed` without also `running` it? And vice versa, if someone does `fides demo start` we shouldn't throw an error and say "actually, you have to run this other command first", as a user I'd think "well just run it for me if you know that!"
