### ISSUE TITLE
Datamap Endpoint doesn't handle multiple data subjects in a privacy declaration

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#1123]
### Bug Description

When you push a system with multiple data subjects in a privacy declaration, that declaration doesn't show in the datamap response.

Similarly - when you have more than one privacy declaration which share the same data categories, all the privacy declarations which contain that category are removed.

#### Steps to Reproduce

1. Push the attached files to a fides server
2. make a GET request on /api/v1/datamap/default_organization
3. The request will succeed, but it will be empty. The system isn't in it.
4. Edit the privacy declarations so that there are unique data categories and unique data subjects in each declaration. 
5. Push the resources again- - All the declarations should show.

### Expected behavior

Data subjects is an array, the data map output should be able to show it.

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._
[Archive.zip](https://github.com/ethyca/fides/files/9657183/Archive.zip)

**Comment by ThomasLaPiana** [comment]
chatted with Michael, turns out this happens via the endpoint as well as a local export, so the bug is most likely somewhere in the `export.py` code
