### ISSUE TITLE
Share datasets between ctl and ops

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#1142]
### Is your feature request related to a specific problem?

Currently unified fides requires datasets to be loaded twice, once for ops and one for ctl, with minor differences between the two. The models should be updated to be cross-compatible and we should reduce it to a single endpoint, thereby unifying the datasets across the two functions

**Comment by ThomasLaPiana** [comment]
Question from Andrew in slack:

> Hey, I'm starting to take a look at https://github.com/ethyca/fides/issues/1142. I think I get the gist but I want to make sure I'm tracking everything correctly. It seems like the issue is that ALL datasets need to be uploaded to both ctl and ops apis thus duplicating the same data. Unifying them would mean making one endpoint that that effectively combines the ops DatasetConfig  and the ctl  Dataset models.  Does this seems correct?
Here are the models that I'm look at. I'm not super familiar with ctl so I'm still getting the hang of things there.
https://github.com/ethyca/fides/blob/ea2b8530583963ac006995bcc2ad1f0320c5b1ee/src/fides/api/ctl/sql_models.py#L181-L195
https://github.com/ethyca/fides/blob/ea2b8530583963ac006995bcc2ad1f0320c5b1ee/src/fides/api/ops/models/datasetconfig.py#L28-L48 (edited)

**Comment by ThomasLaPiana** [comment]
@TheAndrewJackson this is actually what would need to be unified:

**Comment by TheAndrewJackson** [comment]
@seanpreston Should this be closed or marked as done? This issue turned into a spike. I think all the issues that were created from the epic cover what this issue planned on covering.

**Comment by seanpreston** [comment]
This has been superceded in the Unified Fides Resources epic.
