### ISSUE TITLE
Update all fidesops/fidesctl logos to use the default Fides logo

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#1149]
### Bug Description

Now that we've merged the separate UIs, we can replace the logo! There's at least two usages (nav bar and login screen), but we should be comprehensive here.

I've attached a high quality SVG to use, but if we need a rasterized version, reach out.

![fides-logo-primary](https://user-images.githubusercontent.com/1834295/193289572-60b593bd-6f13-460e-b926-5dbf14ebef58.svg)

### Screenshots

In the nav bar:
<img width="977" alt="image" src="https://user-images.githubusercontent.com/1834295/193289095-478d1041-0429-4fed-b701-445d43f71789.png">

**Comment by chriscalhoun1974** [comment]
Within clients/admin-ui folder, the following components reference the logo.svg:

- Header.tsx
- 404.tsx
- login.tsx

From our discussion yesterday, the clients ops folder is obsolete. 

![Screen Shot 2022-09-30 at 11 40 51 AM](https://user-images.githubusercontent.com/68459950/193313626-0cce7846-31b1-4342-b551-558b5db59229.png)
![Screen Shot 2022-09-30 at 11 41 28 AM](https://user-images.githubusercontent.com/68459950/193313629-7e3fe412-6cf5-4c0c-ab38-d554ea9d6817.png)
![Screen Shot 2022-09-30 at 11 53 01 AM](https://user-images.githubusercontent.com/68459950/193313631-535445b2-b8d5-4fd5-aaf9-179fbe63e5f6.png)

**Comment by chriscalhoun1974** [comment]
@NevilleS Good afternoon! We need another Fides logo .svg file. Seems the "des" is pixelated.

![193289572-60b593bd-6f13-460e-b926-5dbf14ebef58](https://user-images.githubusercontent.com/68459950/193313799-508aac96-b83f-4c4c-ac55-8f60f3f07341.svg)

**Comment by chriscalhoun1974** [comment]
Here is the [PR](https://github.com/ethyca/fides/pull/1158)
