### ISSUE TITLE
[Unified Fides] Slow Speeds Running Pytest in Shell

### ISSUE THREAD

**Issue by pattisdr** [ethyca/fides#1155]
### Is your feature request related to a specific problem?

Running pytest within the `fides` shell feels too slow to be usable

- Running `nox -s dev -- postgres shell`
- Wait awhile for this to come up, 3-5 minutes
- Target a specific test within the shell, for example: `pytest tests/ops/api/v1/endpoints/test_user_permission_endpoints.py::TestCreateUserPermissions::test_create_user_permissions_not_authenticated `
- Wait 3+ minutes for the test session to start and test to be collected before I get results. 

### Describe the solution you'd like

_A description of what you want to happen._

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

I'm on an M1 mac but previously didn't experience these sorts of delays when running pytest in the shell.

**Comment by ThomasLaPiana** [comment]
@pattisdr can you remove the `--platform=linux/amd64` from your `Dockerfile` and see if this is still the case?

**Comment by sanders41** [comment]
I have noticed this lately even in fidesops (but not as bad as you have here). It does look to be docker related:

`time pytest --collect-only`

In Docker: 3m7.151s
Outside Docker: 11.20s

**Comment by sanders41** [comment]
That is possible. I'm on M1 mac also, and running outside docker wouldn't be using emulation. What kind of times in docker do you get on your Windows computer with `time pytest --collect-only`.

**Comment by pattisdr** [comment]
Thank you @ThomasLaPiana good suggestion that sped up the test collection a lot. I had to comment out pieces in optional-requirements.txt and the other mssql related code in the Dockerfile but that did the trick.

This was something I used to do in fidesops too but not for just running tests.

**Comment by ThomasLaPiana** [comment]
related to #1051
