### ISSUE TITLE
[Unified Fides] Can not submit through the PC

### ISSUE THREAD

**Issue by azazeldt** [ethyca/fides#1164]
### Bug Description

_A description of what the bug is._

#### Steps to Reproduce

1. spin up privacy center the while unified fides is running 
2. first get this message `Port 3000 is in use, trying 3001 instead.` `ready - started server on 0.0.0.0:3001, url: http://localhost:3001/`
3. navigate to `http://localhost:3001/`
4. You will see the PC but when trying to submit the download request you get the error "Your request has failed. Please try again."  In the console you get 404 errors from `http://localhost:3001/api/auth/session` and `http://localhost:3001/api/auth/_log`

### Expected behavior

You should be able to submit

### Screenshots

![image](https://user-images.githubusercontent.com/7914716/193352360-e5e0a696-e88c-41b7-a3cb-46e5a199c970.png)

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by sanders41** [comment]
Can you show how you started the privacy center? Did you map port 3000 locally to 3000 in the container and it changed on it's own? If so I'm guessing the port in the container and port on the computer get mismatched because of this.
