### ISSUE TITLE
user can not log out 

### ISSUE THREAD

**Issue by azazeldt** [ethyca/fides#1165]
### Bug Description

Rootuser can not log out

#### Steps to Reproduce

1. Log in with the rootuser
2. navigate to the tab user management 
3. create a new user with all privileges
4. save the new user
5. sign out from the top right
6. I can see that post is getting a 403 (see screen shot)

### Expected behavior

user should be logged out 

![image](https://user-images.githubusercontent.com/7914716/193354166-a534ae04-500c-4d3c-aab4-2f405e3d5755.png)

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by sanders41** [comment]
This issue has been fixed on fidesops main, but had not been merged over to this project.

**Comment by NevilleS** [comment]
Great- thanks @sanders41. We should expect that this bug will be fixed when the latest merge lands. Reassigning to @azazeldt to confirm - this is a perfect chance to do a re-test 👯

**Comment by azazeldt** [comment]
verified.
