### ISSUE TITLE
Add a CLI command to tell users when they haven't annotated something

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#1173]
### Is your feature request related to a specific problem?

I can _not_ add data categories or qualifiers to a dataset and nothing yells at me/warns me

### Describe the solution you'd like

We should add stricter checking possibly by default or via flag to one of our commands...potentially `fides parse --strict` ?

### Describe alternatives you've considered, if any

Adding an entirely separate command feels like too much, maybe we would only add it to the `evaluation` flow?

### Additional context

This would make annotating a huge dataset file so much easier...being able to pinpoint exactly what needs annotation and not letting potentially dangerous use-cases slip through

**Comment by ThomasLaPiana** [comment]
@mfbrown @NevilleS any opinions here from a product standpoint? On multiple occasions we've noticed that the lack of strict checking, specifically at parse/push time has come to bite us, and will therefore surely bite our customers

I'm thinking making `fides parse` do this by default is also a viable alternative to `fides parse --strict`, and instead give users the escape hatch of `fides parse --no-strict` or something

**Comment by rsilvery** [comment]
Would this fit better as a Q4FidesCls Enhancements @mfbrown ?

**Comment by ThomasLaPiana** [comment]
I don't think this is `fidescls` related specifically, it affects `fides` as well

**Comment by rsilvery** [comment]
@ThomasLaPiana , @seanpreston  can you help me understand this function? How does this compare to our UI implementation?

**Comment by rsilvery** [comment]
@ThomasLaPiana we're rethinking this whole flow right now. We're going to bench this ticket in the meanwhile unless you think it's urgent right now.

**Comment by ThomasLaPiana** [comment]
@rsilvery this is related to the CLI-flow, not the UI flow (if that was in question)

What was happening here is that I was working on annotating a dataset, and it would parse without issue, but then it would false the `fides scan` command because I had left out data categories. I wish I could have known without running the `scan` command that I was missing certain fields, hence the potential for some kind of `--strict` command which we use elsewhere sometimes
