### ISSUE TITLE
[Unified Fides] Missing Fidesops Docs in Index

### ISSUE THREAD

**Issue by pattisdr** [ethyca/fides#1186]
### Bug Description

The combined fides/fidesops mkdocs.yml file is missing references to `manual_webhooks.md` and `connection_types.md`

- `manual_webhooks.md`
- `connection_types.md` 

#### Steps to Reproduce

1. _Do this..._
1. _Then This..._

### Expected behavior

_A description of what you expected to happen._

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by ThomasLaPiana** [comment]
since this is a docs issue I'm going to assign it to @conceptualshark , they handled the large bulk of the docs updates

**Comment by conceptualshark** [comment]
This should be taken care of by https://github.com/ethyca/fides/pull/1236 - the `connection_types` docs were folded in elsewhere!

**Comment by ThomasLaPiana** [comment]
confirmed this is fixed elsewhere
