### ISSUE TITLE
root_user is not able to delete users

### ISSUE THREAD

**Issue by azazeldt** [ethyca/fides#1190]
### Bug Description

root_user is unable to delete users from the user management tab 

#### Steps to Reproduce

1. Log in with the root_user
2. navigate to the user management tab 
3. create a user 
4. once user is created attempt to delete that users 
From the screen shot below you can see the response from the api 403 with the message `{"detail":"Users can only remove themselves, or be the Admin UI Root User."}`

### Expected behavior

root_user should be able to delete users. 

### Screenshots
![image](https://user-images.githubusercontent.com/7914716/193684586-826e86d3-b830-4099-90b7-48afa54aeb81.png)

![image](https://user-images.githubusercontent.com/7914716/193684666-e6409ec9-403d-4028-9f4b-f54644e54e55.png)

![image](https://user-images.githubusercontent.com/7914716/193684813-71141d9f-c915-461c-87a0-b9d6acc0bba6.png)

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by ssangervasi** [comment]
Lol: https://github.com/ethyca/fides/pull/2148#discussion_r1065031275

**Comment by allisonking** [comment]
Confirmed that this is fixed as of the above PR
