### ISSUE TITLE
[Unified Fides] saas config update initialization action no longer exists

### ISSUE THREAD

**Issue by adamsachs** [ethyca/fides#1195]
### Bug Description

In fidesops, on webserver bootup we [ran](https://github.com/ethyca/fidesops/blob/main/src/fidesops/main.py#L248) an update "script" for saas configs to pick up any updates coming from a new version of their corresponding templates. See https://github.com/ethyca/fidesops/pull/1307 and associated issue https://github.com/ethyca/fidesops/issues/1098 for more context.

Unless I'm missing something, we seem to have removed this functionality from unified fides. Was there a particular reason for that? We will need this functionality moving forward.

**Comment by adamsachs** [comment]
@ThomasLaPiana @pattisdr just looping you in, in case you have any context on whether this was intentional or just an oversight of the merge. i can try to take a stab at adding it back in, just have a couple of things higher on my queue so may take me a bit to get to it

**Comment by pattisdr** [comment]
good catch @adamsachs I assume this was just an oversight

**Comment by ThomasLaPiana** [comment]
I'd also agree it was an oversight, there was code that didn't appear to do anything (tests passed with or without it) so I might've missed reimplementing it, good catch!
