### ISSUE TITLE
Configure Connector after creation

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#1204]
Backend work found in #1227

### USER STORY

As an admin, I want to a be able to update a connector after creation.

### AC

- in the meatball menu for a connector in the Datastore Connections tab, add Configure option
- reuse the connector's creation form pre-populated with the current data
- fix the bug that throws an error when you hit save twice - aka allow for updates

### DESIGNS

[https://www.figma.com/file/4qgQpYc1bX4dXg2PHmRORL/DSR-Error-Handling?node-id=88%3A4993](https://www.figma.com/file/4qgQpYc1bX4dXg2PHmRORL/DSR-Error-Handling?node-id=88%3A4993)

### Extra Info

[Epic Requirements Doc](https://ethyca.atlassian.net/wiki/spaces/PM/pages/2374730475/DSR+Error+Handling)

**Comment by Kelsey-Ethyca** [comment]
reach out to design to discuss this as a drawer to make the work easier and design more consistent

**Comment by Kelsey-Ethyca** [comment]
mask api keys?

**Comment by Kelsey-Ethyca** [comment]
FYI there are 2 separate endpoints to save 1. the name and other config 2. the secrets

**Comment by chriscalhoun1974** [comment]
1. When creating a DB connection should I display a toast informing the user that the connection was created if the config secrets fail to save?

**NOTE**: Currently, the UI makes 2 separate API calls from the FE to the BE to create a connection and save the config secrets. Each API call is mutually exclusive. My upcoming commit does NOT display a toast for a connection created if the config secrets fail to save.

2. Should we auto redirect the user to the Dataset configuration or DSR customization form after the user clicks the Save button via the Connector parameters form upon creating a Manual, Database, or 3rd party integration (Says) connection type?

**NOTE**: Currently, the user is auto redirected. Given the auto redirect the user cannot click the Test connection button for a Database or Saas connection on the Connector parameters screen after clicking the Save button initially. After the auto redirect the user can navigate manually to the Connector parameters form via left hand side navigation and click the Test connection button.

3. When editing a Manual connector  connection, should the following statement be omitted?

```
To begin setting up your new Manual Webhook connector you must first assign a name to the connector and a description.
Please suggest additional verbiage if needed.
```

4. On the Datastore Connections landing page if a given connection does not have a description supplied, should I create an empty placeholder within the given connection card?

![Image](https://user-images.githubusercontent.com/68459950/194919210-6544a3d7-bdd3-4c0e-a925-8ad0072245db.png)
![Image](https://user-images.githubusercontent.com/68459950/194919209-5f87db39-d177-4ed7-881f-9870536ba8e7.png)

**Comment by chriscalhoun1974** [comment]
Here is the initial [PR](https://github.com/ethyca/fides/pull/1356)
