### ISSUE TITLE
Bulk select and reprocess DSRs that have errored

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#1205]
BE work will be covered in [https://github.com/ethyca/fides/issues/1225](https://github.com/ethyca/fides/issues/1225)

### USER STORY

As an admin, I would like to resolve an issue such as system failure that caused all subject requests to error out, followed by a bulk approval/denial of errored subject requests.

### REQUIREMENTS

Bulk reprocessing of DSR requests: Reprocessing errored subject requests

### AC

- Add checkboxes next to every DSR
- checkboxes should only be enabled for errored DSRs This is temporary as I am sure we will add the ability to bulk approve/deny in the future
- after checking a box display a "reprocess" button
- upon reprocessing display success toast and update status to in progress
- Like individual processing we are only aiming for current "retry" parity. Will need another ticket for long term reprocessing.

### DESIGNS
User Flow:
[https://www.figma.com/file/4qgQpYc1bX4dXg2PHmRORL/DSR-Error-Handling?node-id=4%3A9387](https://www.figma.com/file/4qgQpYc1bX4dXg2PHmRORL/DSR-Error-Handling?node-id=4%3A9387)

Final Screens:
https://www.figma.com/file/MTbZohIGvB4bq2f2wkiDHO/Fidesops-Management-UI?node-id=4006%3A60640

### Extra Info

[Epic Requirements Doc](https://ethyca.atlassian.net/wiki/spaces/PM/pages/2374730475/DSR+Error+Handling)

**Comment by chriscalhoun1974** [comment]
@Kelsey-Ethyca @mfbrown @sanders41 Good morning! Currently, I completing the FE development work for [Bulk select and reprocess DSRs that have errored#1205](https://github.com/ethyca/fides/issues/1205). Paul has an existing [PR](https://github.com/ethyca/fides/pull/1470) for the BE work to support the FE development. Both of us did a walkthrough earlier this morning. We have question which is where on the UI/UX Figma design will the API bulk retry endpoint be triggered from? Is there suppose to be a Reprocess button in the upper right hand corner? For illustration purposes, I have mocked the following:


![Image](https://user-images.githubusercontent.com/68459950/196480967-eee4adf7-e6c5-48ca-8b65-214925e7ac75.png)

The Reprocess button will only be rendered if there is at least one privacy request in the result set which has a status of ERROR . In addition, the button will be disabled until a user has clicked at least one privacy request or clicks the checkbox column header. Thoughts?

**Comment by chriscalhoun1974** [comment]
Here is the PR[https://github.com/ethyca/fides/pull/1489](url)

**Comment by Roger-Ethyca** [comment]
Tested in Test_env 


![Image](https://user-images.githubusercontent.com/115798183/198380228-88a72712-c3ae-44cb-ae1a-e7b6618a4e7e.png)
![Image](https://user-images.githubusercontent.com/115798183/198380227-8dda414b-a27a-4506-9ed7-09fb9e2cf61b.png)
![Image](https://user-images.githubusercontent.com/115798183/198380226-571da1d2-b270-479f-9ff7-8faa1f10ba9a.png)
