### ISSUE TITLE
Run Fides from a single command

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fides#1210]
## Description

Currently the Fides server requires a set of configuration variables to function. As part of https://github.com/ethyca/fidesops/pull/1395 we updated Fidesops to run with sane defaults where possible. In other circumstances, it's considered a security vulnerability to provide those defaults ([think: `root_user`, `root_password`, `app_encryption_key` etc](https://github.com/ethyca/fides/blob/unified-fides-2/.fides/fides.toml#L39-L40)).

> As a developer testing Fides, I want to run a command like `nox` or `docker compose up` to run so that I can bring up a released build of Fides easily.

In order to facilitate this we'll need to store variables where we're unable to provide a default in the database, and automatically generate them at runtime if they aren't provided by config. The variables we'll need to do this for are any in the [config file](https://github.com/ethyca/fides/blob/unified-fides-2/src/fides/ctl/core/config/__init__.py) where no default can be provided.

**Comment by NevilleS** [comment]
Food for thought: we could update `fides init` to just helpfully generate secure defaults for everything.

**Comment by NevilleS** [comment]
OK, this is definitely a duplicate of #1115. Closing in favour of that one instead 👍
