### ISSUE TITLE
Move from `setup.cfg`, `setup.py`, `MANIFEST.in`, and `requirements.txt` to `pyproject.toml`.

### ISSUE THREAD

**Issue by wiseaidev** [ethyca/fides#1219]
Duplicate of [fidesops#1415](https://github.com/ethyca/fidesops/issues/1415).

### Is your feature request related to a specific problem?

Hey fellas! As you may already know, the use of `setup.cfg`, `setup.py`, `MANIFEST.in`, and `requirements.txt` files is quite [outdated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html). Because of [PEP 517](https://peps.python.org/pep-0517/), [PEP 660](https://peps.python.org/pep-0660/), and [PEP 631](https://peps.python.org/pep-0631/), the packaging is now being standardized on the usage of the `pyproject.toml` file.

### Describe the solution you'd like

Given the above info, I am going to spend some time updating the project packaging to support `pyproject.toml`, and ultimately add support for `poetry`(optional).

### Describe alternatives you've considered if any

Not available.

### Additional context

That's pretty much it. What do you think?

**Comment by ThomasLaPiana** [comment]
@wiseaidev we appreciate the contribution! check the `unified-fides-2` branch for our current packaging setup, as that is about to get merged into `main`

**Comment by ThomasLaPiana** [comment]
@wiseaidev I had to close the other PR due to it becoming too out-of-date after our huge move to a 2.0, would you be interested in reopening a PR with these fixes? I want to make sure you get your credit! Otherwise I can do it myself but still credit you as a co-author on our GitHub :)

Huge thanks again for your contribution and I'm sorry it's taken me so long to circle back to this!

**Comment by wiseaidev** [comment]
Hey @ThomasLaPiana, thanks for the response. I will try my best over the weekend to work on it. But in any case, Co-authoring sounds like a good idea. Let's do this.

**Comment by ThomasLaPiana** [comment]
@wiseaidev awesome! I'll start on this in a few days if you haven't already and we can knock it out :)
