### ISSUE TITLE
Generate and save consent cookie

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#1220]
### USER STORY

As an user who has set my consent config in a company's privacy center to opt out of data sales and sharing, I want the company to reflect my preference in a cookie that is set on my browser, so that my preferences can be read from the cookie to prevent client side sales and sharing to third parties.

### AC

- Given that I have chosen to opt out of data sales ~and sharing~, when I save my preferences, then a cookie is placed on my browser with a property that explicitly indicates I have opted out of data sales ~and sharing~.
- Given that I have chosen to opt out of data sharing, when I save my preferences, then a cookie is placed on my browser with a property that explicitly indicates that I have opted out of data sharing.
- Given that I make any of the above selections, when I save then both choices are recorded in the same cookie.

### DESIGNS

N/A

### Extra Info

- [https://github.com/ethyca/fidesops/pull/1407](https://github.com/ethyca/fidesops/pull/1407)
- You can see the design of the Ethyca Pro Cookie [here](https://support.ethyca.com/docs/how-to-configure-consent-for-ccpas-do-not-sell-my-personal-information#understanding-ethycas-global-consent-object--cookie). We will eventually expand this cookie to also support opt-in/out status of other types of cookies - Essential, Functional, analytics, Advertising.
- We may need to add an explicit "data sales and sharing" consent type to the privacy center config, so that we know that when it is set, to set the cookie ( [https://github.com/ethyca/fidesops/blob/main/clients/ops/privacy-center/config/config.json](https://github.com/ethyca/fidesops/blob/main/clients/ops/privacy-center/config/config.json))

**Comment by mfbrown** [comment]
@ssangervasi @Kelsey-Ethyca  Updating this a bit to separate data sales and data sharing into two preferences. We should set the cookie with unique properties for both.
