### ISSUE TITLE
[Unified fides] `logging` logger messages are not getting through to stdout

### ISSUE THREAD

**Issue by adamsachs** [ethyca/fides#1228]
### Bug Description

Once the db migration `command.upgrade` is [run](https://github.com/ethyca/fides/blob/unified-fides-2/src/fides/api/ctl/database/database.py#L42) as part of our startup hook, it seems like all logging messages throughout the app that are coming from the builtin `logging` loggers are no longer getting through to stdout.  Only `loguru` logger messages get through to stdout.

If I comment out the migration command above, then we do get messages from `logging` loggers in stdout.

Note that I'm seeing the following error come as my migration executes locally:
```
fides-fides-1  | 2022-10-04 21:32:30.448 [DEBUG] (crud:get_resource:67): Fetching resource | {'sql_model': 'Organization', 'fides_key': 'default_organization'}
fides-fides-1  | 2022-10-04 21:32:30.698 [ERROR] (crud:create_resource:38): Failed to insert resource | {'sql_model': 'Organization', 'fides_key': 'default_organization', 'error': 'resource already exists'}
```
perhaps this is contributing to the problem somehow? maybe that error needs its own issue...

Update: clearing my db volume made this particular error above disappear, though i still do see other errors coming from the migration. in both cases, the messages from `logging` loggers still don't appear - so i'm feeling like this is _not_ related to the issue at hand...

#### Steps to Reproduce

1. checkout the latest from `unified-fides-2`
2. run `nox -s dev`
3. notice that after this message - `DEBUG:fides.ctl.core.config:Using config: FIDES__ADMIN_UI__ENABLED = True`, no other messages from `logging` loggers are being output to stdout/your terminal
    - for example, you can test this explicitly by running a test masking request like the following: 
```
curl --location --request PUT 'http://0.0.0.0:8080/api/v1/masking/mask' \
--header 'Content-Type: application/json' \
--data-raw ' {
    "values": ["test@example.com"],
    "masking_strategy": {
        "strategy": "random_string_rewrite",
        "configuration": {
            "length": 20,
            "format_preservation": {
                "suffix": "@masked.com"
            }
            
        }
    }
}
```
and then seeing that it does not produce the expected log message: 

```
logger.info(
            "Starting masking of %s value(s) with strategy %s",
            len(values),
            masking_strategy.strategy,
        )
```

### Expected behavior

_A description of what you expected to happen._

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by adamsachs** [comment]
just wanted to bump/re-visit this. i'm still hitting this locally and given that (almost?) all of our fidesops app code uses the built-in logger, it leads to a pretty confusing dev experience at best; at worst, i think this also means we are losing many log statements if/when a client deploys fides and uses `ops` functionality?

i'm happy to take on some work here, but wanted to understand if there's an established plan. did we want to replace all of our logging with `loguru`? or should we look to fix whatever is preventing the builtin `logger` messages from coming through? generally, what's the motivation for using `loguru`?

maybe this is only affecting me locally for some reason, or maybe i'm not properly understanding the consequences and blowing this out of proportion. happy to discuss more offline

**Comment by sanders41** [comment]
I can confirm this issue. I don't know the original motivation for `loguru` so I'm not sure if we want to stick with it. I would say we either go all in with it, or remove it completely. Anyone else have more context on `loguru` and thoughts on direction we should take?

**Comment by ThomasLaPiana** [comment]
[PR for historical context here](https://github.com/ethyca/fides/pull/287)

I just want things to work (don't we all 😂 ) so I'm perfectly fine tearing out `loguru` in favor of the built-in logging module.

That being said, can we do due diligence on `loguru` and make sure it's not actually the better solution here? It _seems_ nice, so I don't want to tear it out and then in the future realize actually we should've replaced `logging` instead of `loguru`

**Comment by adamsachs** [comment]
i just want to bump this again. recently i've found myself needing to remote debug my local application _a lot_ to get useful error messages, rather than relying on application logs. the latest example is described in #1832 - i'm not totally sure that this issue was causing the error suppression there, but if it is, then it gives an idea about the types of problems that are not making their ways up to error logs.

maybe there are other problems lingering around in our error handling and logging - i'm just not sure. but we know this is an issue, and so i think we need to prioritize resolving it - and then we can identify and tackle any additional problems once we know this is out of the way. if suppressed logging is causing annoyances for developers like me, those inconveniences will pale in comparison to the problems it's going to cause when we've deployed the application with customers, with no access to remote debugging and limited test cycles.

i'd like to take on the due diligence task you requested myself, i'm just pushing hard on a client priority for this sprint (unified fides) and am pretty saturated on that...is there anyone else that could look into this soon?

cc @Kelsey-Ethyca @seanpreston

**Comment by adamsachs** [comment]
seems like this will be covered by https://github.com/ethyca/fides/issues/1842, unless i'm mistaken. let's make sure to close this out once that's completed.

**Comment by adamsachs** [comment]
closed by https://github.com/ethyca/fides/issues/1842
