### ISSUE TITLE
placeholder - refactor front end to remove SaaSType enum

### ISSUE THREAD

**Issue by adamsachs** [ethyca/fides#1235]
### Is your feature request related to a specific problem?

With https://github.com/ethyca/fides/pull/1197, we removed the `SaaSType` enum from the backend, and made the `type` field on SaaS configs fully dynamic. The frontend still contains a static `SaaSType` enum that should be removed to reflect the dynamic nature of SaaS config types accordingly. According to @chriscalhoun1974 , there's some nontrivial refactoring work that needs to be done on the frontend codebase to make this possible. This issue is a general placeholder to account for that work so that we don't lose track of it - more specific issues can be created as the refactoring work is better defined.

https://github.com/ethyca/fides/issues/1230 and https://github.com/ethyca/fides/issues/1231 are backend features that are likely needed in order to make this frontend refactoring possible.

@chriscalhoun1974 please feel free to update this as you see fit!

### Describe the solution you'd like

_A description of what you want to happen._

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

- Likely blocked by https://github.com/ethyca/fides/issues/1230 and https://github.com/ethyca/fides/issues/1231.
- Generally part of an effort to make the frontend more robust/dynamic in its handling of SaaS connector types

**Comment by galvana** [comment]
Removed as part of https://github.com/ethyca/fides/pull/3018/
