### ISSUE TITLE
Update `DataCategoryDropdown` component `buttonProps` type

### ISSUE THREAD

**Issue by TheAndrewJackson** [ethyca/fides#1259]
The recent merge of main and unified-fides-2 introduced a subtle typescript linting error but that doesn't effect runtime functionally. To get around the issue the prop object was casted as the correct type.

It would be better to properly type the `buttonProps` prop as `MenuButtonProps` instead `ButtonProps`. This will be more clear than casting the object to the correct type down inside the component. 

These areas are a good starting point for updating this.

https://github.com/ethyca/fides/blob/5a485387d8af247ec6479e4115088cbbb8394d77/clients/admin-ui/src/features/dataset/DataCategoryDropdown.tsx#L59

and 
https://github.com/ethyca/fides/blob/5a485387d8af247ec6479e4115088cbbb8394d77/clients/admin-ui/src/features/dataset/DataCategoryDropdown.tsx#L25

Updating this may cause some downstream changes.

**Comment by rsilvery** [comment]
@TheAndrewJackson should this be assigned to you?

**Comment by TheAndrewJackson** [comment]
@rsilvery Yes, I think that makes the most sense. I'll assign it to myself now 👍

**Comment by TheAndrewJackson** [comment]
As discussed on #1510, this update is no longer needed.
