### ISSUE TITLE
Documentation  links break when updates are rolled out

### ISSUE THREAD

**Issue by malaethyca** [ethyca/fides#1289]
Field ticket: https://ethyca.atlassian.net/jira/servicedesk/projects/FIDES/queues/custom/46/FIDES-65

"When I send a follow up email, I copy the URL such as the below:

https://ethyca.github.io/fides/1.8.0/tutorial/system/

What ends up happening is when 1.81, 1.82, etc roll out we lose the above link which makes my followups very difficult at the rate we are releasing. I suggest we decouple documentation from the version control or persist pervious versions."

**Comment by NevilleS** [comment]
Our new docs site doesn't support any versioning
