### ISSUE TITLE
Create a single `nox` command to setup & run a manual test environment

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#1292]
### Description

Right now **it's too error-prone to setup your local dev environment for manual testing**. If you're comfortable with `nox`, `docker`, and using Postman to manually setup data via the API, you can make it work, but it's not a repeatable setup that we can rely on for release-level verification or building more sophisticated, reliable automated E2E test suites.

For this ticket, we need to create a single `nox` build command to setup & run a "manual test" environment locally (e.g. nox -s manual_test) to be used for manual regression testing, which:
* Runs all Fides services (server, ui, shell, privacy center)
* Automatically injects the necessary secrets
* Runs the basic “test setup scripts” (see #1291)
* Allows the engineer to manually test CLI commands and UI features with no additional steps required

### Acceptance Criteria

* MUST be a single `nox` command (e.g. `nox -s manual_test` or similar)
* MUST run webserver, Admin UI, Privacy Center, and shell
* MUST run the basic "test setup scripts" to configure the environment with data for both data mapping & privacy request automation

**Comment by ThomasLaPiana** [comment]
@NevilleS given the performance issues on M1 chips with SQL Server enabled, do we want to have separate "slow and everything"/"fast and missing sqlserver" commands here? Or truly a single command that spins up everything always and has a performance penalty for M1 users?
