### ISSUE TITLE
Adobe Sign

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#1295]

**Comment by Kelsey-Ethyca** [comment]
0auth issue

**Comment by Kelsey-Ethyca** [comment]
Hey @ctvivek, @galvana found that the auth issue is solved by using postman.com and not the desktop app!

**Comment by ctvivek** [comment]
Hi @Kelsey-Ethyca, oauth is already working fine for me in browser version of postman. im facing this oauth issue while running pytest. i already informed this to @galvana.
