### ISSUE TITLE
Polish Fides Resources documentation

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fides#133]
At this time, the Fides resources documentation page needs some revisiting, namely:
* explanations of each resource type and their descriptions, use cases and examples
* rough sketch of diagram of how the fides resources work together
* 

This will be updated in `~/fides/blob/main/docs/fides/docs/fides_resources.md` and displayed in github pages here:
`https://ethyca.github.io/fides/fides_resources/`

**Comment by ThomasLaPiana** [comment]
@iamkelllly these changes are done with #192 right?

**Comment by iamkelllly** [comment]
Closing with last last week's merge of #192. Thanks!
