### ISSUE TITLE
Shipstation

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#1338]

**Comment by Kelsey-Ethyca** [comment]
I have reached out to Shipstation as there free account expires. 


https://ethyca.atlassian.net/wiki/spaces/EN/pages/2708439041/Shipstation+Connector+Specification

**Comment by Kelsey-Ethyca** [comment]
We have a paid adaptors account that only allows for one user so we can swap that out for a connectors account if needed

**Comment by nicolas-ethyca** [comment]
@Kelsey-Ethyca Whats the ask? To try and get a perpetual low-volume free account for testing?

**Comment by nicolas-ethyca** [comment]
Made partner request



![Image](https://github.com/ethyca/fides/assets/111306317/b14a67b5-c38b-4d21-9029-b27eadc75736)

**Comment by nicolas-ethyca** [comment]
Email is currently adaptors.india@ethyca.com, goal is to get this to be free

**Comment by Kelsey-Ethyca** [comment]
met with Acutane June 20
