### ISSUE TITLE
Tremendous

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#1345]

**Comment by Kelsey-Ethyca** [comment]
We can make a free account but we need a paid account to access apis

**Comment by nicolas-ethyca** [comment]
Awaiting - 

![Image](https://github.com/ethyca/fides/assets/111306317/244a3cf0-3f7d-4818-a7f3-1e189f4797a1)

**Comment by nicolas-ethyca** [comment]
Request submitted

![Image](https://github.com/ethyca/fides/assets/111306317/a4cf84c4-d584-4f19-b661-ed9cf77e5220)
