### ISSUE TITLE
Fix Snowflake integration tests

### ISSUE THREAD

**Issue by galvana** [ethyca/fides#1352]
### Bug Description

The integration tests are currently pointing to an incorrect or misconfigured Snowflake instance.

#### Steps to Reproduce

1. `nox -s dev -- shell snowflake`
2. `pytest -m integration_snowflake`

### Expected behavior

The tests should pass

### Additional context

The `SNOWFLAKE_TEST_URI` Github secret must be updated once we've determined the correct value and our Snowflake instance has been properly configured.

**Comment by ThomasLaPiana** [comment]
@galvana did this get fixed after Sean updated the secrets?

**Comment by galvana** [comment]
Yes @ThomasLaPiana, all good now!
