### ISSUE TITLE
Update Fides UI to prompt user to register their server

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#1367]
Initial loading of the UI should do a check to see if the user has been "registered" and if not, prompt the user to do so. The form must collect:

* user email
* user organization

and then send that information to the webserver's `registration` endpoint

Depends on https://github.com/ethyca/fideslog/issues/82

**Comment by seanpreston** [comment]
@ThomasLaPiana / @NevilleS — do we have designs for this?

**Comment by ThomasLaPiana** [comment]
@seanpreston I'm not sure I'm the best person for this ticket, is it ok to find someone else for this one?

**Comment by rsilvery** [comment]
We have no design for this or design ticket. @mfbrown , @malaethyca  priority?
