### ISSUE TITLE
Design input needed: Add OAuth2 auth workflow to connector configuration page

### ISSUE THREAD

**Issue by galvana** [ethyca/fides#1384]
### Is your feature request related to a specific problem?

Connectors using the `oauth2_authorization_code` authentication strategy require the user to follow an authorization URL and log into the auth provider before the connection can be usable.

### Describe the solution you'd like

1. Save the secrets in the connector configuration page
2. Click on test connection
3. If the connection is not authorized (no access key is found in the secrets) then the user should be redirected to the URL returned from calling `/connection/{{fides_key}}/authorize`
4. After the user has entered their credentials, the 3rd party API will post the auth code back to Fides' `/oauth/callback` endpoint where it will be exchanged for access/refresh tokens (all of this is already implemented).
5. The UI should poll the server to show a connection test status after an access key is available and the connection test is attempted

**Details**
- Poll every second (does it need a timeout?)
- May need to pass a prop based on the connection type (if OAuth is present in the config)
- There needs to be a new backend endpoint to return a status

**Comment by mfbrown** [comment]
@mfbrown @galvana @chriscalhoun1974 Work on a quick workflow diagram

**Comment by galvana** [comment]
![oauth_ui_flow](https://github.com/ethyca/fides/assets/2092272/2ea771b5-1f63-4ee2-81f3-68e1055ffde0)

**Comment by rsilvery** [comment]
@galvana  do we need them to enter their secret to know oAuth is required or can we infer this in another way?

**Comment by galvana** [comment]
Good callout, it's not clear from the doc but the enter "credentials > authorize connection" portion is just to indicate that the connection can't be authorized until all secrets are provided. However, we will know if a connection needs OAuth when the connector form is loaded initially and reflect it in the UI with the presence of the "authorize connection" button.

**Comment by galvana** [comment]
Final design

![Image](https://github.com/ethyca/fides/assets/2092272/41a1447b-baff-492e-973e-950b25a412df)
