### ISSUE TITLE
Add a new Data Use Case Type for data sharing and Sensitive PI Processing (FE)

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#1397]
### DETAILS
In Pro's Control Panel today an admin can create Data Use Cases. These use cases show under Consent Management in the Privacy Center for a user to opt in or out. We need to add Data Sharing as a new type when creating data use cases to comply with CPRA/VCPA.

**USER STORIES**
Within Ethyca Pro, I want to add an activity flag for my website for Data Sharing consent uses, so that the Ethyca cookie is updated on user’s browsers.

Within Ethyca Pro, I want to add an activity flag for data integrations for Data Sharing use cases, so that end users who apply a consent option have that choice reflected in API requests made by external integrators.

Within Ethyca Pro, I want to add an activity flag for my website for Sensitive Personal Information Processing use cases, so that the Ethyca cookie and consent object is updated on user's browsers.

Within Ethyca Pro, I want to ad an activity flag for data integrations for Sensitive Personal Information Processing use cases, so that end users who apply a consent option have this choice reflected in an API response.

[Pro Docs](https://support.ethyca.com/docs/how-to-set-up-consent-management-for-ccpas-do-not-sell-in-the-control-panel
)

### AC

- Add Data Sharing as a new type under Apply Consent for Websites
- Add Data Sharing as a new type under Apply Consent for Data Integrations 
- Add Sensitive Personal Information as a new type under Apply Consent for Websites
- Add Sensitive Personal Information as a new type under Apply Consent for Data Integrations

![Image](https://user-images.githubusercontent.com/101993653/195244982-f11e3fc5-d4a8-4a7c-9b75-a022f2533b0c.png)

**Comment by eastandwestwind** [comment]
Closing as not needed, since this back-end work (https://github.com/ethyca/fides/issues/1398) exposes these options to Front-end (both in control panel AND privacy center)

**Comment by Kelsey-Ethyca** [comment]
https://ethyca.atlassian.net/browse/HELM-2088
