### ISSUE TITLE
Expose the user's consent choice for Data Sharing and Sensitive Personal Info

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#1399]
### USER STORY 
As a website visitor, when I opt-in or out of a data sharing use case, my choice is reflected in the Ethyca cookie (likely in a new group) so that embedded trackers that classify as data sharing services can be blocked.

As a website visitor, when I opt-in or out of a Sensitive Personal Info (SPI) use case, my choice is reflected in the Ethyca cookie (likely in a new group) so that embedded trackers that classify as data sharing services can be blocked.

### DETAILS
In Pro's Control Panel today an admin can create Data Use Cases. These use cases show under Consent Management in the Privacy Center for a user to opt in or out. We will add Data Sharing as a new type when creating data use cases to comply with CPRA/VCPA in #https://github.com/ethyca/fides/issues/1397 and #https://github.com/ethyca/fides/issues/1398. 

We need add this Data Sharing type to the `eth_cmp` cookie as `GROUP5` and SPI as `GROUP6`

[Pro Docs - Ethyca's Global Consent Object & Cookie](https://support.ethyca.com/docs/how-to-configure-consent-for-ccpas-do-not-sell-my-personal-information#understanding-ethycas-global-consent-object--cookie)

[**EPIC DOC**](https://ethyca.atlassian.net/wiki/spaces/PM/pages/2497773595/Ethyca+Pro+CPRA+and+VCDPA+Opt-in+Opt-out+Support)

### AC

- Given that I have verified my identity in the privacy center, when I choose to not allow data sharing and save, then the Ethyca cookie is placed on my browser with a new group set to false to reflect my choice for the data sharing use case.
- Given that I have verified my identity in the privacy center and already opted out of data sharing, when I opt back in and save, then the Ethyca cookie is updated on my browser with the new group set to true to reflect that I opted back in to data sharing
- Given that I have verified my identity in the privacy center, when I choose to not allow SPI processing and save, then the Ethyca cookie is placed on my browser with a new group set to false to reflect my choice for the SPI use case.
- Given that I have verified my identity in the privacy center and already opted out of SPI processing, when I opt back in and save, then the Ethyca cookie is updated on my browser with the new group set to true to reflect that I opted back in to SPI processing

**Comment by eastandwestwind** [comment]
Done as part of https://github.com/ethyca/fides/issues/1398 and verified complete.

The below screenshot of my cookie is a result of me opting out of data sharing and SPI on the privacy center, where group 5 is data sharing, and group 6 is SPI:

<img width="577" alt="Screen Shot 2022-11-15 at 12 07 38 PM" src="https://user-images.githubusercontent.com/7697292/201995081-fba338ba-c13d-45a9-a4a3-ac75898f669b.png">
