### ISSUE TITLE
Update FE to leverage SaaS icon image data returned in response

### ISSUE THREAD

**Issue by adamsachs** [ethyca/fides#1413]
### Is your feature request related to a specific problem?

https://github.com/ethyca/fides/pull/1370 adds base64 encoded image binary in a field called `encoded_icon` within the response body of the `api/v1/connection_type` endpoints. this field is only populated for records referring to SaaS connection types; for non-SaaS connection types, the field is `None`.

We've done this to enable developers to more easily develop and "register" their new SaaS connector on the backend, along with an associated image that can then be leveraged dynamically by the front-end, without needing to go and update assets in the front-end codebase.

### Describe the solution you'd like

On the front-end, we should render the icon image for connectors using this encoded data that's passed back, rather than relying on static image files stored in the frontend. For connector types that _don't_ populate an `encoded_icon` field in their response, then default to the existing logic on the frontend, for now. (Eventually we may try to just return the icon images for all connector types from the backend?)

### Describe alternatives you've considered, if any

It may eventually get unsustainable to pass back all this image data in the API response, once we have enough connectors. At that point we should probably evaluate other options that would make it simple for SaaS connector developers to somehow register the image as a front-end asset that may not need to be passed over the wire.

### Additional context

Generally part of an effort to make the frontend more robust/dynamic in its handling of saas connector types, and to remove the SaaSType enum from the frontend codebase as it no longer exists on the backend.

**Comment by galvana** [comment]
Closed by #3018
