### ISSUE TITLE
Add CI reference files for documentation

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fides#143]
The new tutorial and updated readme has a section for "integrating with your CI". It would be great to get a few references that folks can look at when it comes time to hook fidesctl up to their live environment. We should be able to support having the following references:
* GH actions
* Gitlab
* Jenkins
* CircleCI

They don't have to be full, real examples, but would be great to have a reference of what they can add to their ci config yaml to review.

**Comment by ThomasLaPiana** [comment]
the github actions example will be in #155
