### ISSUE TITLE
Tables jump around when adding categories to fields.

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#1436]
Field Request: https://ethyca.atlassian.net/jira/servicedesk/projects/FIDES/queues/custom/46/FIDES-82

### Bug Description

When you add a data category on a field which is in a dataset in a collection other than the first collection of a system, then on save, the table jumps back to the first collection, without updating the dropdown.

Load a dataset with multiple collections (see attached zip)

#### Steps to Reproduce

1. Load the attached dataset
2. Load the collection: cls_classification_detail
3. Modify the data category on a field
4. Save

You'll see the table jump around

### Expected behavior

The table should continue to show the collection that was just edited.

### Screenshots

![Image](https://user-images.githubusercontent.com/101993653/195899063-e343e582-eeec-45f6-84f6-55d61ebf92ab.gif)

### Additional context

_Add any other context about the problem here._
[dataset.yml.zip](https://github.com/ethyca/fides/files/9779171/dataset.yml.zip)

**Comment by nicolas-ethyca** [comment]
https://github.com/ethyca/fides/blob/1675bedb2b445f8ddadb55ca40adb067ce6f1ed3/clients/admin-ui/src/features/dataset/DatasetCollectionView.tsx#L74
