### ISSUE TITLE
Research: Update Fides consent cookie with interoperable format option

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#1444]
### Description

At a really _basic_ level Fides should ship with an "opinionated" mapping of the cookie to five "groups", so that the resulting cookie records the consent value in multiple ways:
1. Using the Fides `data_use` key, e.g. "advertising.first_party -> true"
2. Using a generic "group" label, e.g. "GROUP4 -> true"

We'll need to meet a bit more to discuss exactly how the resulting cookie should be structured and what to label each group, but the point here is that we want to guide users of Fides towards categorizing their consent records in a standard fashion, to aid the interoperability of reading this cookie into downstream tools like GTM, GA, Segment, etc.

**Comment by ssangervasi** [comment]
Going to look into some other CMP cookie examples. Here's the research:
https://ethyca.atlassian.net/wiki/spaces/EN/pages/2510782535/Research+Update+Fides+consent+cookie+with+interoperable+format+option+1444
