### ISSUE TITLE
Further test_env improvements

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#1476]
### Is your feature request related to a specific problem?

Now that #1457 is shipped, there are a few further refinements we'd like to make that make sense as their own incremental PR.

### Describe the solution you'd like

* inject a test `fides.toml` into the test env
* make sure that a `touch` isn't required for the server to boot
* reduce the number of containers that get started (only start the ones that are necessary)

**Comment by NevilleS** [comment]
So, quick update on this:
* #1512 adds a new `fides.test_env.toml` which covers the first request
* #1552 fixes the issue I noticed with `touch` (that was misdiagnosed hugely by me!)
* #1552 removes the need for a worker container, so definitely better

With that in mind, we can close this out
