### ISSUE TITLE
[Field request] When creating a new dataset in the UI - if the schema is empty, indicate to the end user that the schema is empty

### ISSUE THREAD

**Issue by malaethyca** [ethyca/fides#1487]

**Comment by malaethyca** [comment]
When creating a new dataset in the UI - if the schema is empty, indicate to the end user that the schema is empty

In today’s state, we show a blank state in the component which gives the impression the product is broken. Instead, render a message such as:

”No collections were found in the public schema”

or something of this sorts

Field request: https://ethyca.atlassian.net/jira/servicedesk/projects/FIDES/queues/custom/46/FIDES-85

**Comment by NevilleS** [comment]
I reviewed this with @nicolas-ethyca and found a really easy way to reproduce on the latest version of `fides` on `main`.

This is what the UI looks like when you load a dataset that has no collections:
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/1834295/196804125-fc7161fb-46b3-4505-bdd9-672158e89f32.png">

To reproduce:
1. Run `nox -s test_env`
2. Open http://localhost:3000/dataset
3. Select `demo_users_dataset` and click "Load dataset"
4. Click the more menu ("...") > "Modify collection"
5. Click the delete icon to delete the `users` collection
6. Observe the empty state

We should handle this state and render some kind of helpful message about the dataset having no collections. The suggestion above of "Dataset ({dataset_name}) has no collections" would at least indicate an issue!
