### ISSUE TITLE
DSR configure alerts btn

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#1491]
### USER STORY
As an admin I want a big red banner or some prominent signal on the Fides UI that tells me that the DSR automation is failing/throwing errors. 

I also want to be able to configure alerts - such as to send me an email or a text on my phone when there are failures (I should be able to set a threshold such as if a connector throws errors more than or less than n number of times, start/stop notifying me).

I want to be able to generate a report of the number of errors thrown per connector (type of DSR execution error).

### REQUIREMENTS 
Notifications (email only) and alerts (toast messages) will be used just for DSRs today but plan for a future state where they can be used for other features. 

### AC
- add configure alerts and option under the more button

**Comment by chriscalhoun1974** [comment]
This story is currently blocked by [DSR configure alerts (BE)#1493](https://github.com/ethyca/fides/issues/1493)

**Comment by Roger-Ethyca** [comment]
verified on test env 


![Image](https://user-images.githubusercontent.com/115798183/210645074-cfcbd027-d040-4bb4-9375-9ea97eb1300c.png)
