### ISSUE TITLE
DSR configure alters (FE)

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#1492]
### USER STORY
As an admin I want a big red banner or some prominent signal on the Fides UI that tells me that the DSR automation is failing/throwing errors. 

I also want to be able to configure alerts - such as to send me an email or a text on my phone when there are failures (I should be able to set a threshold such as if a connector throws errors more than or less than n number of times, start/stop notifying me).

I want to be able to generate a report of the number of errors thrown per connector (type of DSR execution error).

### REQUIREMENTS 
Notifications (email only) and alerts (toast messages) will be used just for DSRs today but plan for a future state where they can be used for other features. 

### AC
- add configure alerts screen

**Comment by chriscalhoun1974** [comment]
This story is currently blocked by [DSR configure alerts (BE)#1493](https://github.com/ethyca/fides/issues/1493)

**Comment by chriscalhoun1974** [comment]
Here is my initial [PR](https://github.com/ethyca/fides/pull/1895/).

**Comment by Roger-Ethyca** [comment]
verified on Test env


![Image](https://user-images.githubusercontent.com/115798183/210644890-4cd04f95-0385-4871-97a2-ff42950e3547.png)
