### ISSUE TITLE
Fix the Stepper in the config wizard

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#1514]
As a user, I want the Config Wizard Stepper to reflect the steps which are required for the flow that I select, so that I have an accurate preview of the steps required to add new systems.

**AC**
- Given that I select the manual inputs, when the first step loads, then the stepper updates to show 3 scanning steps
- Given that I select the AWS Scanner, when the first step loads, then the stepper updates to show steps specific to the AWS Scanning
- Given that I select the Okta Scanner, when the first step loads, then the stepper updates to show steps specific to the Okta scanner.

**Figma**
- Updated stepper: https://www.figma.com/file/NeFvOOb1RT2fcdqZT0vBF2/Fidesctl-Management-UI?node-id=110%3A6861
- Okta Scanning: https://www.figma.com/file/NeFvOOb1RT2fcdqZT0vBF2/Fidesctl-Management-UI?node-id=108%3A5125
- AWS Scanning: https://www.figma.com/file/NeFvOOb1RT2fcdqZT0vBF2/Fidesctl-Management-UI?node-id=29%3A943
- Manual Input: https://www.figma.com/file/NeFvOOb1RT2fcdqZT0vBF2/Fidesctl-Management-UI?node-id=110%3A6861

TBD: Just need to determine the final number of steps.

**Comment by Kelsey-Ethyca** [comment]
Note to myself to add these details to the ticket https://ethyca.slack.com/archives/C0114BAK160/p1666633875802189

**Comment by Kelsey-Ethyca** [comment]
[My "designs"]( https://www.figma.com/file/NeFvOOb1RT2fcdqZT0vBF2/Fidesctl-Management-UI?node-id=29%3A943) are in the pink box. We should review with Design Team and have a mini planning meeting to finalize

**Comment by LKCSmith** [comment]
@mfbrown - I am still extremely confused by the Figma designs I am meant to follow, and when I click your Figma links, for some reason they don't lead to a specific node or design. There are also multiple flows on the page.

Could you please show me (maybe in screenshots added here for simplicity):
1) The starting state of the stepper, before a scanner or the manual entry is chosen
2) What the stepper looks like with manual entry
3) What the stepper looks like with AWS
4) What the stepper looks like with Okta

**Comment by LKCSmith** [comment]
Moving to blocked until the above is clearer to me ^ Just want to make sure we're all on the same page for the stepper. Thank you.

**Comment by Kelsey-Ethyca** [comment]
1. The starting state of the stepper, before a scanner or the manual entry is chosen
There will be no stepper until a scanner/manual entry is chosen
2. What the stepper looks like with manual entry
There is no stepper for manual entry now
3. What the stepper looks like with AWS
see the second row with the pink background 
4. What the stepper looks like with Okta
see the second row with the pink background

**Comment by rsilvery** [comment]
Stepper is not coming back, for now. Can close @mfbrown , @Kelsey-Ethyca , I think
