### ISSUE TITLE
Host consent script

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#1516]
We are creating a script to reflect consent choices to the browser in #1395, and need to develop a way to serve the script so that Fides users can load it from a CDN without necessarily deploying it on their own.

**Details**
- As part of our release process, publish the script to the CDN.
- It will require documentation on how it interacts with the cookies, so that if a user wants to override it, they know that they'll have to serve their own script.
- The file should also be easily accessible from the privacy center
- Work with Dave/Robert to configure a Fides specific public bucket.

**Comment by ssangervasi** [comment]
Submitted an access request for S3.

**Comment by ssangervasi** [comment]
Dicussion 11/22/22: may not need the CDN performance of S3, could just be a asset in GH.

**Comment by mfbrown** [comment]
Closed - Ethyca's not
