### ISSUE TITLE
Config Wizard says to view DataMap after adding a system in OS

### ISSUE THREAD

**Issue by malaethyca** [ethyca/fides#1529]
After you add a system manually using config wizard, it says to go view your datamap.
1. In open source, datamap is not available as it's a paid feature, so this would be an incorrect UX flow. Instead it should ask the user to view systems and provide a link to the systems page (right now, it ends abruptly with the only option out being to click on "Cancel setup"
2. In fides plus, it can ask the viewer to go view the datamap, but again it should provide a link perhaps (considering the menu has disappeared when you are in the config wizard). The only option out again in this case too is to "Cancel setup" in order to continue to use the product. This is not ideal as it's confusing that you just managed to setup a system successfully, but the next step is to "Cancel setup" in order to exit.

![Image](https://user-images.githubusercontent.com/108771409/197447016-646c1d59-7305-4bae-b0b2-20732d79f674.png)

**Comment by rsilvery** [comment]
I'm going to move this to automation team @Kelsey-Ethyca , @mfbrown . We're working on this flow now.

**Comment by allisonking** [comment]
I just checked and here's the flow for a Plus user:

https://user-images.githubusercontent.com/24641006/204370592-bd145190-39d5-49fb-a3a9-5f3b18f8077f.mov

So it doesn't seem like the screenshot Mala left exists anymore. For an OS user, it brings you to the systems page.
