### ISSUE TITLE
Approved subject requests don't automatically updated to Completed

### ISSUE THREAD

**Issue by malaethyca** [ethyca/fides#1534]
Something is wrong with the last subject request in the queue that it doesn't automatically switch from "Approved" to "Completed". You have to refresh it.

Here's how it looks after you approve a request:

![Image](https://user-images.githubusercontent.com/108771409/197496390-48ec971e-2793-4d7b-bba3-1185e9748155.png)

After a browser refresh:

![Image](https://user-images.githubusercontent.com/108771409/197496636-10c4425b-2c4f-4c74-aa7c-a95c039027bd.png)

If you have multiple requests you are approving, all the ones except the last one automatically switch from Approved to Completed.

**Comment by Roger-Ethyca** [comment]
verified on uat. DRS automatically moves to completed status 


![Image](https://user-images.githubusercontent.com/115798183/200052392-117421a8-6f70-4e39-971f-fa8dbb41a98b.png)
