### ISSUE TITLE
Delete Config Wizard flag and incorporate into navigation

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#1540]
Once the Config Wizard work is complete, we want to delete all `configWizardFlag` code and reinstate the tests. 

related to #1539 and #1453 

Make sure that we don't add it back to the nav.
The Wizard experience should still exist for the first time users.
---
Update the wizard entry points and routing so that it becomes the tool for adding systems via a scanner or individually via manual entry. 

Exact entry points are likely to be from new items in the new navigation.

WORK IN PROGRESS DESIGNS: https://www.figma.com/file/BCXCf8X8hfAut5mIgY6CbQ/Navigation-2.0?node-id=1031%3A1697&t=ciTZwKl1u1JzOVcx-4

**Comment by rsilvery** [comment]
@allisonking  is any of this going to conflict with what we're doing with Add Systems?
@Kelsey-Ethyca  we've repurposed the config wizard tab/link so I want to make sure.

**Comment by allisonking** [comment]
Add Systems already deleted the config wizard flag. it's still accessible via the nav, but under the disguise of "Add Systems". It might be safe to call this ticket done, but would probably want Michael or Kelsey to play around with it to make sure

**Comment by allisonking** [comment]
It's `/add-systems` right now. see https://github.com/ethyca/fides/issues/1825#issuecomment-1322611416 for some of my mumble-y thoughts on that

**Comment by mfbrown** [comment]
Thanks this all sounds good. Will groom with the team, but I think this will get rolled into the new nav story.

**Comment by mfbrown** [comment]
Closing since this is back as "Add Systems" and will also be accessible through the new navigation
