### ISSUE TITLE
User Management - password criteria should be stated upfront

### ISSUE THREAD

**Issue by malaethyca** [ethyca/fides#1573]
When you create a new user in the admin console, it requires a password of a certain number of letters + capitalized letter + special char etc. This criteria should be stated upfront so that you don't land up iterating over user creation to read the error messages one at a time to find out what the criteria are to set the password!

**This is the screen for this issue**
![Image](https://user-images.githubusercontent.com/4807009/197243114-9f140bc8-97d6-457f-8ce3-1cf9a7a5f7c2.png)

http://localhost:8081/user-management/new

**Comment by daveqnet** [comment]
Folks, can I ask where these password complexity requirements came from?

8 chars is about the bare minimum, but it'd be better if we implemented something like the [ASVS v4.0 Password Security Requirements](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v21-password-security-requirements).

Ideally we would allow Admin UI users to define their own password policy.

**Comment by sanders41** [comment]
This has been the default since I started so unfortunately I don't know where the requirements came from.

**Comment by daveqnet** [comment]
Fair enough, @sanders41, and apologies for only coming with this feedback now. I wasn't aware that this issue existed until I saw @LKCSmith's PR raised earlier today.

Leave it with me, I'll talk to Product.

**Comment by daveqnet** [comment]
@sanders41 Just to check, does the backend impose any other requirements than the one you give [above](https://github.com/ethyca/fides/issues/1573#issuecomment-1292073638)?

Is there a maximum password length e.g. 64 or 128 chars, for example?

**Comment by sanders41** [comment]
The ones listed above are the only ones I am aware of. These are the ones that run when the password is initially taken in, so anything additional would be set outside this. I would be surprised if this is happening anywhere.

**Comment by daveqnet** [comment]
Okay, thanks for clarifying! I'm going to unblock the PR, since it's only real purpose is to mirror in the UI what's already been done in the backend.

I have some thoughts about our current backend password requirements, but I've discussed them with @mfbrown and I'll handle them separately with the Product team. This may result in future GitHub issues that result in both front-end and backend changes in password handling, and I'll try to link back to this one when they're created.
