### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by Roger-Ethyca** [ethyca/fides#1575]
### Bug Description

spinning up a new test_env results in a fatal error right away int he ui

#### Steps to Reproduce

1. Bring up the test_env
2. Open the Fides UI 

### Screenshots

![image](https://user-images.githubusercontent.com/115798183/198082412-e5161af8-2bee-47f5-95ef-0f69038da4e3.png)
### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by chriscalhoun1974** [comment]
Here is the [PR](https://github.com/ethyca/fides/pull/1578)

**Comment by chriscalhoun1974** [comment]
@Roger-Ethyca [PR](https://github.com/ethyca/fides/pull/1578) has been merged into main branch.

**Comment by Roger-Ethyca** [comment]
![Screen Shot 2022-11-01 at 11 02 35 AM](https://user-images.githubusercontent.com/115798183/199267112-c7113197-61f6-40b0-a47f-7556b034a2c8.png)
![Screen Shot 2022-11-01 at 11 03 17 AM](https://user-images.githubusercontent.com/115798183/199267116-37730008-5e5a-48dc-975d-f54db08ed83d.png)
