### ISSUE TITLE
OwnBackup

### ISSUE THREAD

**Issue by adriaaaa** [ethyca/fides#1584]
Requirements [here](https://ethyca.atlassian.net/wiki/spaces/OSS/pages/2260434945/OwnBackup+Connector+Specification)

Due: 6/29

**Comment by Kelsey-Ethyca** [comment]
Note from Adrian: 

> I've been researching the OwnBackup connector now that I have access, I don't see a way we can make a generic OwnBackup connector, we'll probably have to make a custom one for each client that asks for it. It's dependent on the objects a customer is archiving from Salesforce (which is configurable in OwnBackup) and any custom fields

**Comment by Kelsey-Ethyca** [comment]
Close as not planned since we determined there is not personal data in OwnBackup
