### ISSUE TITLE
Navigation bar changes

### ISSUE THREAD

**Issue by malaethyca** [ethyca/fides#1586]
Minor Navigation bar changes:

Subject Requests should change to Privacy Requests
Datastore Connections should change to Connections
User Management (no changes)
Systems (no changes)
Datasets (no changes)
Taxonomy (no changes)

[Remove Config Wizard]

**Comment by NevilleS** [comment]
On it 🫡!

**Comment by NevilleS** [comment]
So, in starting this, I of course realized that making the copy changes for "Subject Request" -> "Privacy Request", and "Datastore Connections" -> "Connections" consistent with the Nav Bar is _quite a lot_ of search & replace.

Pretty sure it's doable, it'll just require a thorough clicking around to see if I missed anything.

**Comment by conceptualshark** [comment]
@malaethyca @NevilleS There's a current docs ask to remove the entirety of this nav structure for the 2.0 IA - with that, is this needed?

We also discussed phasing out using "Privacy Requests" when we want to emphasize that we offer DSRs. I just want to make sure we're aligned on this sort of terminology across the docs/teams.

**Comment by NevilleS** [comment]
The main thing this issue does is update the UI itself with this updated terminology, so that it can be consistent with the future state we want to get to without feeling like a breaking change post-2.0.

I've done a quick search & replace on the existing docs to keep them as consistent as possible, but won't feel too bad if you remove a lot of that in your IA restructuring 👍

**Comment by conceptualshark** [comment]
Absolutely! Saw the auto docs tag and got confused with the upcoming docs nav update. 👍 Thank you!

**Comment by Roger-Ethyca** [comment]
![Screen Shot 2022-11-01 at 10 40 18 AM](https://user-images.githubusercontent.com/115798183/199261256-99c2c199-cc89-4c7c-8a39-9edf18e277a7.png)
![Screen Shot 2022-11-01 at 10 42 53 AM](https://user-images.githubusercontent.com/115798183/199261262-c587b409-86ea-4b50-a2b0-281241ea87c8.png)
