### ISSUE TITLE
FE: Add Supress Error button to Events and logs section via Subject Request Detail page

### ISSUE THREAD

**Issue by chriscalhoun1974** [ethyca/fides#1630]
**USER STORY**
As an admin, I would like for a **Suppress Error** button to be displayed on the Subject Request Detail page specifically within the **Events and logs** section. When the button is clicked, the user will navigate directly to the **Error Suppression** menu item within the **3rd party integrations** (SaaS) connection workflow.

**REQUIREMENTS**

- Add a Suppress Error button to the Events and logs section via the Subject Request Detail page. 
- Display Suppress Error button only if DSR has ERROR status
- Clicking the button will navigate the user directly to the Error Suppression menu item within the 3rd party integrations (SaaS) connection workflow.

**AC**

**Comment by Kelsey-Ethyca** [comment]
Going to close this since we won't be working on this till Q2 2023
