### ISSUE TITLE
restore access to root_user

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#1637]

**Comment by ssangervasi** [comment]
If my quick debugging is correct, this should be a backend fix. It looks like the login API accepts the special "root_user" who has no `fidesuser` records, but other routes like `user/{id}/permission` don't give that user the same special treatment.

**Comment by sanders41** [comment]
@ssangervasi you are correct, the root user purposefully does not get a user created. Is there a specific error we are seeing?

**Comment by ssangervasi** [comment]
@sanders41 A 404 for `GET /api/v1/user/fidesadmin/permission`. The `fidesadmin` is the hard-coded Id of "root_user" but requests like this don't account for it.
