### ISSUE TITLE
Add classic api hint to salesforce connector

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#1650]
As a user, when I am configuring Salesforce, I want to be notified that I should use the classic API domian, so that I get the full support of the connector.

notes from Adrian 10/31
* the lightning apis completely overlap so only the urls change so we just need to give a hint 

AC
* Update the SaaS config for Salesforce to indicate that the users should configure the connector using the classic API domain.

**Comment by galvana** [comment]
Closed by #1828
