### ISSUE TITLE
Support the ability for users to run `fides` without a `.fides` dir or file-based config

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#1661]
### Is your feature request related to a specific problem?

Currently `fides` will _always_ try to write out a config file if it can't find one. This doesn't really make sense in the context of deploying an application via a container.

### Describe the solution you'd like

A lot of UX thought will need to be put in here, but generally the CLI should be able to run by itself unless maybe a command gets called that requires further configuration?

### Additional context

Suggesting that users run the `init` command if no config file is found also seems helpful, and figuring out a way for user analytics prompt to maybe not run unless they run `init`?

We shouldn't need to run the `create_config` function every single time, as it also outputs logging that is noisy on every command

**Comment by ThomasLaPiana** [comment]
@NevilleS now that I'm revisiting this...does it actually hurt anything to write out the configuration file? We've fixed the configuration issues now, so I don't think this is a problem?

**Comment by ThomasLaPiana** [comment]
> It's still surprising behavior to have that happen and I'd prefer it not to. In some extreme cases it can get pretty messy- imagine for example you `pipx install` the CLI so it's generally available, and then start running seemingly innocent `fides status`, `fides generate` commands in a variety of subdirectories in your project... you might end up creating a dozen different TOMLs littered around without realizing, etc. Another example is running the CLI on a container that has a strict read-only volume. I'm pretty sure that could be a common problem we run into where an unnecessary write to disk might trigger warnings or errors.
> 
> If we truly fix the config setup such that we have sane defaults for all values and only enforce required values for certain commands that need them (eg `fides webserver` requires several), what in the codebase would still require it to exist?

All good points, and to address your last question, there is no reason for it to exist! 

Let's relegate it to `fides init` and call it a day? That seems like the only place that it really really makes sense to create a dir and write out a file. I see now after your explanation how that could be quite surprising behaviour and not optimal from a UX perspective 🙂 thanks for walking me through the thought process!

**Comment by NevilleS** [comment]
Yes- `fides init` is the place that makes sense for it. Thanks
