### ISSUE TITLE
Dataset section in Fides resource types is out of sync with the current implementation.

### ISSUE THREAD

**Issue by iokamoto-sm** [ethyca/fides#168]
[Dataset](https://github.com/ethyca/fides/blob/main/docs/fides/docs/fides_resources.md#dataset) in Fides resource types is out of sync with the current implementation.

For instance, it is missing `collections: List[DatasetCollection]` and also the document is missing `DatasetCollection`.

**Comment by ThomasLaPiana** [comment]
this has been updated/fixed here: https://ethyca.github.io/fides/language/resources/dataset/

**Comment by ThomasLaPiana** [comment]
thanks for the catch @iokamoto-sm
