### ISSUE TITLE
Improve the Identity Verification Email 

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#1686]
### Bug Description

When a user gets the identity verification email in the hosted demo environment the email sender name, and the design of the email should be updated so that it appears nicely branded with some Fides or Ethyca branding. 

#### Steps to Reproduce

1. _Do this..._
1. _Then This..._

### Expected behavior

_A description of what you expected to happen._

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by mfbrown** [comment]
None of the Fides emails are "branded" right now - this should probably be a feature request for all emails, including the ability for customers to add their own branding.

**Comment by eastandwestwind** [comment]
@NevilleS one concern I have is putting the template creation responsibility on our customers. How do you envision that looking, from a setup perspective? As far as I know, when a customer configures a domain sending key with Mailgun, that only allows us to send messages via the API, not create full templates.

**Comment by NevilleS** [comment]
In general, we'd want users to maintain their own email/SMS providers. This gives them *way* more control over how their emails would look, so it's win/win. This is especially true for pure OSS usage where we can share anything from our own infra.

In *some* cases we might help a customer use our own Mailgun, but that'd be more of a special case

**Comment by NevilleS** [comment]
Created #1865 as a feature enhancement instead of trying to rewrite this one 😄
