### ISSUE TITLE
Add a test that verifies version upgradeability

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#1699]
### Description

Add a test that does the following:
* download the latest major release
* spin it up
* populate the application with data
* spin it down
* bump the application version to the current branch version
* spin it up again
* run tests

### Purpose

The objective of this feature/test is to confirm for ourselves compatibility between versions of our application and to make sure we aren't "surprised" when our users are "surprised"

**Comment by rsilvery** [comment]
@seanpreston  is this a priority for Q4? Trying to update Aha! dashboard

**Comment by ThomasLaPiana** [comment]
I would say no, but that's just my opinion!

**Comment by ThomasLaPiana** [comment]
this will be way easier with #3093 implemented
