### ISSUE TITLE
Discussion: should `account` be a sub-category of `user.provided.identifiable`?

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#172]
Something that's been bothering me for awhile is the top-level `account` category. It's meant to capture "Data related to an account on the system." which, in my opinion, is pretty much by definition user provided identifiable data, and almost always includes some kind of contact information (like an email).

Because of that, to me it feels like user `account` information should live as a sub-category of the `user` branch, i.e.
```
user
└─provided
  └─identifiable
    └─contact
    └─name
    └─account
      └─contact
```

Instead of:
```
user
└─provided
  └─identifiable
    └─contact
    └─name
account
└─contact
```

Looking at the ISO spec, the top-level `Account Data` category is separate and distinct from `Customer Content Data`, but that's because the ISO spec is organized very differently at the very top-level and doesn't attempt to distinguish between user and system data, it's all mixed together (e.g. "Account Data" is for either users or administrators, "Customer Content Data" is exclusively user data that belongs to the user independent of the service, "Derived Data" is data derived either about users or their organizations, etc.)

I think it took me about this long to finally grok the ISO categories, which seem to be organized into top-level categories for convenience wrt regulations, which makes them hard to grok as an engineer when you think about data ownership. I think we can maintain compatibility with these ISO categories while still reorganizing the hierarchy around owners (users, systems, and maybe organizations?) as long as it wouldn't be *inaccurate* to consider `account` data a sub-category of `user.provided.identifiable`...?

Does this make sense? Other thoughts?

**Comment by iamkelllly** [comment]
closing in favor of discussion #218
