### ISSUE TITLE
Fides CLI permanently overwrites commands during testing

### ISSUE THREAD

**Issue by TheAndrewJackson** [ethyca/fides#1736]
Currently the top level click `cli` function that is used as the cli entry is overwriting the commands each time the cli is called. This is done to dynamically show local only vs local and api related commands. This functionality causes issues for downstream packages that are adding additional commands to fides (ex: [fidesplus](https://github.com/ethyca/fidesctl-plus)).

This behavior doesn't affect normal cli usage in fidesplus because the newly added commands are ran before they get overwritten. The cli is loaded fresh every time so nothing appears to be wrong. In testing however, the issue crops up. This is because the cli stays loaded in memory for the duration of the test run. Only the first test that tries to call the cli is able to pass. After the command is ran all of the new fidesplus commands overwritten and aren't available for future tests.

It would be good to update the entrypoint function to handle dynamically loading the local and api commands differently so testing in downstream projects runs as expected.

**Comment by ThomasLaPiana** [comment]
@TheAndrewJackson while I agree this is janky behavior, considering a found a fix for test cases I'm not sure this is still required.

Outside of testing quirkiness (or even including!) do you have any other reason for a refactor here?

**Comment by TheAndrewJackson** [comment]
The main reason for a refactor is that it's not obvious that the cli would work this way. I think a developer adding a new command to fidesplus would expect it to be a permanent additive change to the cli. It was fairly surprising to learn that the cli actually removes all of the fidesplus commands (after the command executes of course). Updating it would make adding new fidesplus commands match the described mental model and have no surprises. The current behavior feels like a foot gun. Does that make sense? @ThomasLaPiana 

We could potentially group the fidesplus commands into the local vs api categories as well and maintain what it's already doing while keeping the fidesplus commands in the cli.

That being said, the code does work in it's current state at runtime so it's not urgent. It's more a under the hood developer UX type change.

**Comment by TheAndrewJackson** [comment]
@ThomasLaPiana That works for me. This isn't a huge priority. A docstring will help make this more discoverable.
