### ISSUE TITLE
Windows/Active Directory Account support for Microsoft SQL

### ISSUE THREAD

**Issue by malaethyca** [ethyca/fides#1759]
Pre-sales ticket: https://ethyca.atlassian.net/jira/servicedesk/projects/FIDES/queues/custom/46/FIDES-91

As we expand into larger enterprise accounts, they tend to be Microsoft eco-system oriented and use federated identities (and user principal names) to sign into Databases and other systems. On the November first call, I noticed his microsoft sql had an “email” attached to it but it suspiciously looked like a Azure federated identity

Please view both slack threads to show the findings

https://ethyca.slack.com/archives/C01LKAC5210/p1667398980549019

https://ethyca.slack.com/archives/CBKK8TS74/p1667400247696819

**Comment by mfbrown** [comment]
Seeking more information on the request.
