### ISSUE TITLE
Remove dataset yaml storing code from `datasetconfig` endpoint

### ISSUE THREAD

**Issue by TheAndrewJackson** [ethyca/fides#1763]
❗ Depends on #1762 ❗ 

Now that dataset yaml configs will only be stored on `ctl_datasets` all of the code that handles storing them on `datasetconfig` needs to be removed.

Acceptance criteria
- Remove legacy code from `datasetconfig` endpoint that stored data on the `dataset`column
- Port all of the code that handled validating `fidesops_meta` and saas configs outside of pydantic to the `ctl_datasets` endpoint.
- Dataset and saas config endpoints still work as expected

**Comment by pattisdr** [comment]
Also make sure ctl_dataset endpoints are validating data categories -
