### ISSUE TITLE
Move `datasetconfig` yaml file endpoint over to `ctl_datasets`

### ISSUE THREAD

**Issue by TheAndrewJackson** [ethyca/fides#1767]
❗ Depends on https://github.com/ethyca/fides/issues/1763 ❗

There is a `datasetconfig` [endpoint](https://github.com/ethyca/fides/blob/4408279869ce49f19ea39c6b8a60d4a0992d7b57/src/fides/api/ops/api/v1/endpoints/dataset_endpoints.py#L199) that allows users to upload yaml files directly without converting them to json. Now that datasets are entirely managed `ctl_datasets` it would be helpful to port that endpoint to the `ctl_datasets` endpoints.

Acceptance criteria
- Users are able to upload yaml files directly to `/yml/dataset/`
- deprecating the existing dataset config yaml endpoint

**Comment by pattisdr** [comment]
@TheAndrewJackson would this also involve deprecating the existing dataset config yaml endpoint?

**Comment by TheAndrewJackson** [comment]
@pattisdr Yes, I believe so. If we left the original in it would need to be updated to create a `ctl_dataset` record behind the scenes.

**Comment by pattisdr** [comment]
thank you!

**Comment by pattisdr** [comment]
Updating: the current state is that the existing ops PATCH connection/connection_key/dataset endpoints for both the JSON and yaml versions both upsert a DatasetConfig and a CTL Dataset.  However, these endpoints will be deprecated after https://github.com/ethyca/fides/issues/1766

**Comment by pattisdr** [comment]
Separate ticket to handle deprecation: https://github.com/ethyca/fides/issues/2092

**Comment by pattisdr** [comment]
Closing in favor of https://github.com/ethyca/fides/issues/2124.  This functionality isn't exactly necessary at the moment.
