### ISSUE TITLE
Update Privacy Center Icons

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#1800]
Update the default icons on the privacy center to match those provided in the attached designs.

**Details**
- Update the hover state
- Update the card designs
- Update the icons (the consent icon TBD as of 11/18)

**Design Link**
https://www.figma.com/file/p3AJEdylT9S8JQGD3VE0Rv/Privacy-Center?node-id=903%3A4308&t=IRUPZ1s68kdk63ff-0

**Comment by chriscalhoun1974** [comment]
Here is my [PR](https://github.com/ethyca/fides/pull/2139).

**Comment by Roger-Ethyca** [comment]
verified on test env

**Comment by Roger-Ethyca** [comment]
Now verified on test env 


![Image](https://user-images.githubusercontent.com/115798183/211577377-1bc2609b-4cf7-4f61-8a1e-026f930ca764.png)
