### ISSUE TITLE
Method to populate users into test environment

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#1813]
As a product manager or tester, I want a method to create knowable data subjects in the Fides test environment, so that I can test privacy requests. 

**Details**
- The method for this can be anything, but the goal is that either as part of a nox command when creating the test environment or a Fides CLI command, I can create one or more test users, with either an email or phone number as an identity. 
- This is in-lieu of the 

**Acceptance Criteria**
- Given that I am testing Fides, while running the project, then I can add one or more data subjects to test a data subject request.

**Comment by NevilleS** [comment]
I'm assuming you want something a little more flexible than the hardcoded ones that are populated into `test_env` right now? Those use the database schemas we use for automated tests and populate sample data for subjects using these identities:
* jane@example.com
* customer-1@example.com
* customer-2@example.com

For reference you can see the raw SQL for the Postgres data here: https://github.com/ethyca/fides/blob/main/src/fides/data/sample_project/postgres_sample.sql#L130
