### ISSUE TITLE
Healthcheck UI on the /config-wizard flow

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fides#1843]
Implement the healthcheck UI as discussed [here](https://github.com/ethyca/fidesctl-plus/issues/221#issuecomment-1324241819)

**Comment by rsilvery** [comment]
Should this be on Fides? or Fidesplus?

**Comment by rsilvery** [comment]
I can't find this indicator when using most recent build. Can somebody else test and verify this is working? @seanpreston

**Comment by allisonking** [comment]
@rsilvery are you still having problems seeing this?

**Comment by rsilvery** [comment]
Nope!
