### ISSUE TITLE
Postie

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#1878]

**Comment by Kelsey-Ethyca** [comment]
https://ethyca.atlassian.net/wiki/spaces/EN/pages/2595028993/Postie+Connector+Specification

**Comment by Kelsey-Ethyca** [comment]
The only endpoint is CCPA deletion and it does not appear to actually delete users.. More testing is required and possibly another plan

**Comment by galvana** [comment]
Account credentials are no longer active, password reset does not work either.
