### ISSUE TITLE
TurnTo

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#1889]

**Comment by nicolas-ethyca** [comment]
Do we know which account needs this? Requested a demo and put title as head of tech partnerships so they get the message. I want to come prepared before I start reaching out over LinkedIn etc

**Comment by nicolas-ethyca** [comment]
@galvana @sadaqatullah @Kelsey-Ethyca

**Comment by nicolas-ethyca** [comment]
Context from adaptors inbox  - Hi Kelly,

That's great to hear. Please let me know if you have any questions.

Andy Hills
Technical Services Manager
Pixlee TurnTo
[(419)290-9251](tel:(419)%20290-9251)

**Comment by nicolas-ethyca** [comment]
privacy@turnto.zendesk.com
