### ISSUE TITLE
Add email connector option to the DSR connections UI.

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#1906]
As a privacy eng/admin, I want to add a connection for third party systems which don't have an API to handle privacy erasure requests, so that I can ensure the third party is notified to process an erasure.

**AC**
- Given that I am adding a connection, when I view the available connectors list, then I can choose the type "Email"
- Given that I have selected the email connector, when I am configuring the connector, then I can name the system I am configuring
- Given that I have selected the email connector, when I am configuring the connector, then I can specify a recipient email address

**Details**
- The connector itself was implemented by stories that can be found here: https://github.com/orgs/ethyca/projects/13/views/2?filterQuery=is%3Aissue+epic%3A%22Maildrop+Connector%22
- The connector was hidden from the connection screen here: https://github.com/ethyca/fidesops/pull/1142/commits/583f378d1f88e45b77f01363758aeedc03f418ba

**Comment by mfbrown** [comment]
Things we need to figure out:
- What fields need to be on the email connector type screen.
   - We'd almost certainly need email address. (we have a component for this) - @mfbrown 
- Can we/should we ignore the dataset screen? If we do ignore it, it still needs to be auto-generated. - @mfbrown 
- Email icon for the connector type: @adamczepeda 
- This will require that the user/customer has set up an email service already, if not they'll need to set it up for this specifically. - Check the docs for this.

**Comment by mfbrown** [comment]
Some additional info
- We likely just need the recipient to be configurable. Last question - can we support multiple recipients? Should we?
- We can't ignore the dataset tab. The dataset and connections within the dataset provide content to the email which can guide the recipient on the data that needs to be deleted. This is very well explained in this PR: https://github.com/ethyca/fidesops/pull/1246 and a follow up which improves the email copy: https://github.com/ethyca/fidesops/pull/1270
- Can the copy at the top of the dataset screen be changed? @chriscalhoun1974 ?

**Comment by chriscalhoun1974** [comment]
@mfbrown I'm not sure you are referring to the **Connector parameters** or **Dataset configuration**? My assumption is your question is related to the Connector parameters fields such as Name (Required), Description (Optional), and Connection Identifier (Required - only shown for DB and 3rd party integrations (Saas) connector types). The answer to your question if yes.

**Comment by mfbrown** [comment]
Might be worth revisiting the need for a dataset here and just send the identity. @mfbrown find out if the current mail templates include identity by default today.

**Comment by saiatethyca** [comment]
I think the email connector should not be a generic one, it should be specific to a third-party SaaS. The user is looking to build a connector for a third-party SaaS which may have an email connector. 

This way, it's easy for the user to configure and keep track of all the email connectors.
