### ISSUE TITLE
Reveal PII preference persists across pages

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fides#1926]
## Replication steps
- Load the subject request dashboard
- Toggle reveal PII on
- Navigate to a subject request details page
- Notice that the PII is still revealed, despite the toggle for this page being off

Please note: this also replicates by toggling reveal PII on in the detail view and then navigating back to the dashboard

**Comment by saiatethyca** [comment]
Duplicate of https://github.com/ethyca/fides/issues/2286

**Comment by NevilleS** [comment]
Duplicate of #2286
