### ISSUE TITLE
[Admin UI] Dropdown menu data

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fides#1930]
### Bug Description

The `username` field is not passed to the dropdown menu in the top right hand corner. This could be an issue for privacy and security, if you can't see who you're logged in as easily.

**Comment by Kaushik-Iyer** [comment]
Should I try to work on this?

**Comment by NevilleS** [comment]
Thanks @Kaushik-Iyer - we reviewed this and decided it wasn't something we wanted to add quite yet!
