### ISSUE TITLE
[Admin UI] Port Cypress tests into the Fidesops Admin UI

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fides#1935]
### Is your feature request related to a specific problem?

As part of https://github.com/ethyca/fidesui/issues/1 we'll be adding Cypress testing to the FidesUI main repo, we should bring that framework over to the main Fidesops Admin UI.

### Describe the solution you'd like

_A description of what you want to happen._

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by NevilleS** [comment]
This is done!
