### ISSUE TITLE
Greenhouse

### ISSUE THREAD

**Issue by adriaaaa** [ethyca/fides#1948]
### Is your feature request related to a specific problem?

To create tests for Greenhouse Connector

**Comment by Kelsey-Ethyca** [comment]
We have an adaptors account for Greenhouse recruiting but not Greenhouse onboarding. The adaptors account doesn't look to be an admin so I cannot create other users. 

I submitted a partnership request. This would provide us with a sandbox env.

**Comment by Kelsey-Ethyca** [comment]
Looks like we are in a partnership program with them already so I am trying to work with them to update our information

**Comment by nicolas-ethyca** [comment]
With respect to this, if we have a partnership with them, where do we stand? Who is the partner manager over there?

**Comment by Kelsey-Ethyca** [comment]
I'm guessing we have partnership based on the automate emails we are getting to adaptors@ethyca.com

**Comment by Kelsey-Ethyca** [comment]
We need access to both Onboarding and Recruiting for connectors@ethyca.com
