### ISSUE TITLE
Add “default” storage used by all DSR policies by default

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#1974]
Today, every DSR policy rule needs to explicitly link to a named “storage destination” that it uses for uploads. This allows the use of different storage destinations for different DSR policies, but in practice the more likely use case is that a customer would want to use the same storage configuration for all their policies.

Ultimately with the eventual UI, the steps for setting up and using a storage location will look like this:
- Add “default” storage used by all DSR policies by default - this should be explicitly stated on the storage location config itself.
- Admin UI to configure “default” storage 
- Settings variables to configure “default” storage 

This issue will satisfy the final bullet, in the above list, but we can do this work before the UIs are complete.

AC
- I can specify the default storage location in the config
- Update the policies to use the default when nothing else is configured.

**Comment by adamsachs** [comment]
implementation note based on offline conversations --

we should implement the default storage config on the backend in such a way that would allow users to keep multiple storage configs on the system simultaneously, with only one at any time being selected as the active default storage configuration
