### ISSUE TITLE
Confirm SendGrid works with current emails

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#1975]
Ensure that our existing emails can be sent using SendGrid, so that we can ensure that adding templates in #1866 will work without additional testing and debugging of the service itself.

**AC**
- Configure Sendgrid in a test environment or locally
- Test that all existing email templates are sent correctly.

**Comment by eastandwestwind** [comment]
Note that this ticket does not include support for fides templates through sendgrid.
