### ISSUE TITLE
When a DSR fails - the row in the privacy request dashboard gets stuck in an hover state

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#1979]
When a DSR fails - you'll see the row go into an active/hover state and get stuck. 

hover state meaning the row is light grey and the reprocessing button is showing. 

Steps 
1. Spin up the test_env
2. Create a bogus saas connector
3. Do a privacy request on the privacy center
4. Approve the privacy request

It will error and the row will get stuck in an active state.

**Comment by mfbrown** [comment]
@adamsachs To try to reproduce this in the testing of #1710

**Comment by adamsachs** [comment]
> @adamsachs To try to reproduce this in the testing of #1710

just noting that i was able to reproduce the problem in testing, and https://github.com/ethyca/fides/issues/1710 does not resolve the issue. seems to be more isolated on the front-end.

**Comment by LKCSmith** [comment]
@mfbrown @adamsachs - Could either of you clarify what the 'fixed' state looks like for a DSR row? In the code, it looks like it is intentionally showing the Reprocess button on error. Are we wanting different options when it errors?
