### ISSUE TITLE
Remove all docs now that they've been deprecated

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#2021]
### Docs Update Description

We have a beautiful [new docs site](https://docs.ethyca.com/fides/overview) now, so it is time to retire the old one.

We can remove the `docs` subdir as well as associated CI workflows, nox sessions, etc.

**Comment by ThomasLaPiana** [comment]
@conceptualshark are you ok with this change?

**Comment by conceptualshark** [comment]
I believe @suchiroll looked into it and a redirect wasn't possible (so we went with a banner) - let me confirm a process/timeline for when we want to remove everything, and I can get back to you!

**Comment by ThomasLaPiana** [comment]
@conceptualshark ok, so let me clarify the current situation a bit:

1. We have a new docs site (docs.ethyca.com/fides/overview)
2. We have an old docs site (ethyca.github.io/fides) that we are pointing to in some places

I have a few questions:
1. What is pointing to the old docs site?
1. What is pointing to the old docs site that we can't update?
1. How long do you propose keeping the old site around for?
1. How do we handle docs updates during this transition period?

**Comment by seanpreston** [comment]
Hey @ThomasLaPiana — do we have the knowledge in the eng. team at this time to keep the new docs up to date? If not, I'll add a ticket to action that.

**Comment by ThomasLaPiana** [comment]
Closed this via refactoring the docs
