### ISSUE TITLE
Update db backend to be compatible with SQLite instead of only postgres

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#203]
Would like to update the database code so that passing in a SQLite database url is also valid, this would remove postgres as a dependency and lower the barrier to entry for people that want to just get started

**Comment by ThomasLaPiana** [comment]
i did some research on this and it would actually be significant work since the types that sqlite supports are more basic than what we use with postgres. this would not be a drop-in replacement and would require rewriting the db layer basically

**Comment by ThomasLaPiana** [comment]
in the meantime, a semi-workaround will be #232 , which would allow evaluations to be run with no webserver/database set up. this follows in the spirit of this ticket, which is to decrease the friction required to get to the state of "running evaluations"

**Comment by ThomasLaPiana** [comment]
@iamkelllly i kicked this out of 1.1.0, given the scope and breaking changes

**Comment by ThomasLaPiana** [comment]
I believe this issue should be closed. With the `local` flag the barrier to entry is very low and allows people to do some very light-weight testing. However, for proper production deployments, I don't condone using sqlite and therefore I don't think this issue needs to get completed.

The spirit of the issue was to lower the barrier to entry, and we've done that. I don't think this would really add anything but complexity to fidesctl at this point, but I'm open to hearing other opinions

**Comment by ThomasLaPiana** [comment]
@iamkelllly any objections to closing this?

**Comment by iamkelllly** [comment]
do we support any other db other than postgres? might it make sense that we would support different db types as the fidesctl backend? 

if so, would it be appropriate to backlog this until we're ready to add additional db support?

**Comment by ThomasLaPiana** [comment]
supporting different backends for application databases adds a lot of complexity, I don't think it is worth doing unless we have lots of users stating they want a certain dialect specifically. Between a hosted Fides and postgres being ultra common, I'm not convinced of the value proposition here

**Comment by iamkelllly** [comment]
Closing this for now as the project and use cases aren't in a mature enough state to determine whether additional backend dbs are required. Will open a discussion for this at a later time when/if folks require a different db!
