### ISSUE TITLE
Clicking to `Configure` a custom SaaS connector leads to blank screen - BE

### ISSUE THREAD

**Issue by adamsachs** [ethyca/fides#2049]
### Bug Description

For database connectors and _standard_ (i.e. templated) saas connectors, the admin UI allows users to `Configure` the connector, i.e. configure the connector's properties, including its secrets.

For _custom_ connectors (i.e. those _without a template_, which must be added to Fides "manually" via API at this point), the connector shows up as an entry in the `Connections` UI, but the `Configure` button leads to a blank screen - a dead end for the user with no helpful information.

#### Steps to Reproduce

1. run fides with the admin UI
2. add a custom saas connector to your fides instance via API. A fake example derived from hubspot:
```
curl --location --request PATCH 'http://0.0.0.0:8080/api/v1/connection/' \
--header "Authorization: Bearer $TOKEN" \
--header 'Content-Type: application/json' \
--data-raw '[
    {"name": "Sample Custom SaaS Connection Config",
    "key": "sample_custom_saas_config",
    "connection_type": "saas",
    "access": "write"
}]'
```
and then
```
curl --location --request PATCH 'http://0.0.0.0:8080/api/v1/connection/sample_custom_saas_config/saas_config' \
--header "Authorization: Bearer $TOKEN" \
--header 'Content-Type: application/json' \
--data-raw '{
  "fides_key": "sample_custom_saas_config",
  "name": "Sample custom SaaS config",
  "type": "custom-type",
  "description": "A sample schema representing a sample custom saas connector for Fidesops",
  "version": "0.0.1",
  "connector_params": [
    {
      "name": "domain"
    },
    {
      "name": "apikey"
    }
  ],
  "client_config": {
    "protocol": "https",
    "host": "<domain>",
    "authentication": {
      "strategy": "query_param",
      "configuration": {
        "name": "apikey",
        "value": "<apikey>"
      }
    }
  },
  "test_request": {
    "method": "GET",
    "path": "/companies/v2/companies/paged"
  },
  "endpoints": [
    {
      "name": "contacts",
      "requests": {
        "read": {
          "path": "/crm/v3/objects/contacts/search",
          "method": "POST",
          "body": "{ \"filterGroups\": [{ \"filters\": [{ \"value\": \"<email>\", \"propertyName\": \"email\", \"operator\": \"EQ\" }] }] }",
          "query_params": [
            {
              "name": "limit",
              "value": 100
            }
          ],
          "param_values": [
            {
              "name": "email",
              "identity": "email"
            }
          ],
          "postprocessors": [
            {
              "strategy": "unwrap",
              "configuration": {
                "data_path": "results"
              }
            }
          ],
          "pagination": {
            "strategy": "link",
            "configuration": {
              "source": "body",
              "path": "paging.next.link"
            }
          }
        },
        "update": {
          "path": "/crm/v3/objects/contacts/<contactId>",
          "method": "PATCH",
          "body": "{<masked_object_fields>}",
          "param_values": [
            {
              "name": "contactId",
              "references": [
                {
                  "dataset": "hubspot_connector_example",
                  "field": "contacts.id",
                  "direction": "from"
                }
              ]
            }
          ]
        }
      }
    },
    {
      "name": "owners",
      "requests": {
        "read": {
          "path": "/crm/v3/owners",
          "method": "GET",
          "query_params": [
            {
              "name": "email",
              "value": "<email>"
            },
            {
              "name": "limit",
              "value": 100
            }
          ],
          "param_values": [
            {
              "name": "email",
              "identity": "email"
            }
          ],
          "postprocessors": [
            {
              "strategy": "unwrap",
              "configuration": {
                "data_path": "results"
              }
            }
          ],
          "pagination": {
            "strategy": "link",
            "configuration": {
              "source": "body",
              "path": "paging.next.link"
            }
          }
        }
      }
    },
    {
      "name": "subscription_preferences",
      "requests": {
        "read": {
          "path": "/communication-preferences/v3/status/email/<email>",
          "method": "GET",
          "param_values": [
            {
              "name": "email",
              "identity": "email"
            }
          ]
        },
        "update": {
          "path": "/communication-preferences/v3/unsubscribe",
          "method": "POST",
          "body": "{ \"emailAddress\": \"<email>\", \"subscriptionId\": \"<subscriptionId>\", \"legalBasis\": \"LEGITIMATE_INTEREST_CLIENT\", \"legalBasisExplanation\": \"At users request, we opted them out\" }",
          "data_path": "subscriptionStatuses",
          "param_values": [
            {
              "name": "email",
              "identity": "email"
            },
            {
              "name": "subscriptionId",
              "references": [
                {
                  "dataset": "hubspot_connector_example",
                  "field": "subscription_preferences.id",
                  "direction": "from"
                }
              ]
            }
          ],
          "postprocessors": [
            {
              "strategy": "filter",
              "configuration": {
                "field": "status",
                "value": "SUBSCRIBED"
              }
            }
          ]
        }
      }
    }
  ]
}'
```
3. navigate to the admin UI --> `Connections` --> select the 3 dot menu for your custom saas connector --> click `Configure` --> encounter blank screen

### Acceptance Criteria

- I can see the custom connector details configured via API in the connector management tab. This experience is similar to what we currently have for connectors configured via the UI.
- I can click on configure to see the variables and the respective configuration values.

### Screenshots

![image](https://user-images.githubusercontent.com/9750285/207949969-b53f84f3-b840-454b-8c21-954fa69f5ca3.png)
![image](https://user-images.githubusercontent.com/9750285/207950020-dad17646-42e1-4da6-bdc7-56fab06b6a7b.png)

### Environment

`test_env`,  or any fides env with admin UI running

### Additional context

Encountered on a client environment with their custom connector and the behavior left the client in an understandably confused state.

cc @galvana @saiatethyca @malaethyca

**Comment by adamsachs** [comment]
reviewing this further to add some more context. i found a slack conversation between me and @galvana at the time the ticket was created (pasted below), which provides further context on the current backend limitations that prevent this from working.

Generally, i think what's needed here is:
- a BE update to include a new endpoint which can determine the secrets schema for a given saas config _without_ relying on the saas config's template, but instead deriving it from an instantiated `saas_config` present in the database. this will allow us to generate a secrets schema even for "custom" saas connectors that do not have templates
    - this endpoint _must_ take the connection config _key_ as a param, rather than the `connection_type` param that's used now. this is because, for a "custom" connector, its `connection_type` is useless; we need the actual connection config instance in the db to look up its associated `saas_config`.
- FE update to be able to call the new endpoint above when the user clicks to edit a custom saas config. 
    - TBD on how/whether the FE would determine its a custom saas config and call a different endpoint, or whether our new BE endpoint just handles all connection configs, whether they are custom saas or not, and returns the appropriate secret schema. Latter option seems preferable but not 100% sure it'll be feasible, requires a bit of investigation on the BE.


-- abbreviated slack convo below for context -- 

**Adam Sachs**
i don't think the custom connectors are configurable from the UI? that UI relies on the `GET  /connection_type/{connection_type}/secret` endpoint i believe, and if you look at that method `get_connection_type_secret_schema`, you'll see it looks for the template
_[for clarity: I was referring here to the saas config template. notably, custom saas configs do **not** have a template, and so that's why they are not currently supported by this functionality_ 
...

**Adrian Galvan**
that makes sense, but it also doesn't seem too big of a lift to fallback to the saas config in the DB to derive the schema

...

**Adam Sachs**
Agree that it should be possible, but don’t think it’d be on that endpoint right?
Since that’s for connection types specifically

**Adrian Galvan**
you're right, we wouldn't want to overload that endpoint

**Comment by saiatethyca** [comment]
We need a icon to signify custom connector.

**Comment by saiatethyca** [comment]
This ticket deals with the following backend changes:

- a BE update to include a new endpoint which can determine the secrets schema for a given saas config without relying on the saas config's template, but instead deriving it from an instantiated saas_config present in the database. this will allow us to generate a secrets schema even for "custom" saas connectors that do not have templates
this endpoint must take the connection config key as a param, rather than the connection_type param that's used now. this is because, for a "custom" connector, its connection_type is useless; we need the actual connection config instance in the db to look up its associated saas_config.
