### ISSUE TITLE
Support third party integrations with Fides consent script-Shopify

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#2052]

**Comment by ssangervasi** [comment]
Spun out from https://github.com/ethyca/fides/issues/1422

**Comment by ssangervasi** [comment]
Write up with test shopify test page: [Shopify + fides-consent.js](https://ethyca.atlassian.net/wiki/spaces/EN/pages/2579038241/Shopify+fides-consent.js)
