### ISSUE TITLE
Search and Filter needs to be fixed in Privacy Request Admin page

### ISSUE THREAD

**Issue by malaethyca** [ethyca/fides#2080]
1. Seems like the search bar on the Privacy Review page is to be able to search on a privacy request ID. It would be ideal if the search had some assistance to educate the user on this constraint. It could be a look-ahead search where it tells you what you need to search for and to offer a list of request IDs. Or it could be a drop down of request IDs with a search that helps you search within the list. If you go this route, the drop down list needs to support pagination.

3. I have a button that says "Clear Filters" which doesn't tell me how I would set filters in the first place, and what filters have been set that I am looking to clear. What is its purpose? Does it need to exist?

 https://www.loom.com/share/d8825c5fd01a43c0a68bc217580b17aa

**Comment by rsilvery** [comment]
Will replace filters
