### ISSUE TITLE
Broken docs links in Scanner UI

### ISSUE THREAD

**Issue by malaethyca** [ethyca/fides#2081]
When you start configuring the AWS scanner, it comes up with broken links to the docs:

https://www.loom.com/share/ccc291c62d1145dabc93171fb67ed066

**Comment by allisonking** [comment]
Thanks @malaethyca ! Yeah, that link is for sure not working. But I couldn't find an appropriate link to replace it with. I found [this link](https://docs.ethyca.com/fides/data_mapping/scanners#authenticate-with-aws) but that doesn't have a sample IAM policy. Maybe we need to change the copy?

Let me know what it should be changed to and we can have this fixed quick ⚡
