### ISSUE TITLE
Consistent handling of Snowflake object quoting

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#2091]
### Is your feature request related to a specific problem?

Currently, the handling of quoted object names in Snowflake-related code is inconsistent. `fides generate` will produce lower-cased table names, while DSR processing double quotes all table names and therefore will end up throwing `relation not found` errors. This will become a bug once we fully unify the dataset resources.

### Describe the solution you'd like

Refactor how we handling quoting objects in all snowflake-related code (or maybe all database connectors?) to be consistent across the application

**Comment by SteveDMurphy** [comment]
Also noted in #1838
