### ISSUE TITLE
Refactor Evaluation logic

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#211]
This is by far the most complex area of the codebase currently, and there are some known inefficiencies in those modules. Need to go in and profile that code from performance, readability and complexity perspectives

**Comment by ThomasLaPiana** [comment]
Specifically [here](https://github.com/ethyca/fides/blob/main/fidesctl/src/fideslang/relationships.py#L68) I think we can do some more recursion instead of hard-coding all of these values in

**Comment by ThomasLaPiana** [comment]
the evaluation process also seems to take a long time when it does the check for missing resources, let's check and see how many API calls we're making and how we might be able to speed that up/reduce the number of calls

**Comment by earmenda** [comment]
> the evaluation process also seems to take a long time when it does the check for missing resources, let's check and see how many API calls we're making and how we might be able to speed that up/reduce the number of calls

I'm thinking part of what slowed down the evaluate is also the validation of existing keys. For every combination of privacy declaration / dataset declaration + privacy rule we do this check:
https://github.com/ethyca/fides/blob/main/fidesctl/src/fidesctl/core/evaluate.py#L181-L188

This seems bad and could use some work for sure

**Comment by ThomasLaPiana** [comment]
This PR should also update the evaluation message as per #264
