### ISSUE TITLE
Remove the connector configuration dataset YAML upload form

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#2114]
### Is your feature request related to a specific problem?

There are two YAML forms that can be used to create datasets right now, one from the dataset management UI, and one from the connector configuration management UI. We should only have one now that we are [unifying the ops and ctl datasets](https://github.com/orgs/ethyca/projects/18/views/5?filterQuery=is%3Aopen+epic%3A%22Unified+Fides+Resources%22)

### Describe the solution you'd like

IMO it would make sense to remove the connector configuration YAML form:

<img width="1216" alt="Screen Shot 2022-11-14 at 10 08 02" src="https://user-images.githubusercontent.com/17103888/201694729-a39b0c3f-6d15-4855-8e1b-68505f4b148e.png">

And replace it with a multiselect that allows you to connect existing datasets to this connector. If they need to create a new one, then we should redirect them to the dataset management UI to create a dataset.

### Describe alternatives you've considered, if any

Leave as-is, but there are some caveats described in https://github.com/ethyca/fides/pull/2113 which make this UX a bit strange if we leave it.

### Additional context

Follow up to https://github.com/ethyca/fides/issues/1766

I'd like to get @rsilvery 's thoughts on how/if we should go about this. If we do, we may also need designs.

**Comment by rsilvery** [comment]
I know we'd like to keep the more featured one. Working with @mfbrown to figure out how to sunset one of them.

**Comment by rsilvery** [comment]
Most of this is being handled in https://github.com/ethyca/fides/issues/1531. We need to make sure that there's some protection to prevent overwriting datasets.

**Comment by rsilvery** [comment]
Suggestion from @mfbrown : check for the existence of the fides key for the dataset and, if found, confirm user wants to overwrite.

**Comment by allisonking** [comment]
https://github.com/ethyca/fides/issues/1531 will handle upgrading the dataset YAML form to use the same YAML editor as the connector one.

This ticket should focus on replacing the existing YAML form with a select dropdown of existing ctl datasets. If the dataset the user wants to link does not exist yet, we should redirect them to the adding a dataset flow.

**Comment by allisonking** [comment]
Decision:

* Add a drop down to the Connectors dataset UI to select an existing dataset.
* If a dataset is selected in this menu, the editor is disabled. If it's unselected, the editor returns
* Once we've implemented this and can show it to design, get feedback and adapt as needed.

**Comment by pattisdr** [comment]
Nice path forward here! ^
