### ISSUE TITLE
Does Fides integrate with Circle CI? Is it in the roadmap?

### ISSUE THREAD

**Issue by nathanawmk** [ethyca/fides#213]
Does Fides integrate with Circle CI? Is it in the roadmap?

**Comment by iamkelllly** [comment]
Yes, fides does integrate with CI products like circleci @nathanawmk ! We are going to be adding additional [CI reference implementations here soon](https://github.com/ethyca/fides/blob/main/docs/fides/docs/tutorial/ci.md)!

**Comment by nathanawmk** [comment]
Cool, very cool!

**Comment by ThomasLaPiana** [comment]
@nathanawmk we've added a [CI Reference page](https://ethyca.github.io/fides/ci_reference/) to our docs that includes CircleCI! This will still require the end-user to tweak the file to their own individual deployment, but hopefully it serves as a good starting point :)

**Comment by ThomasLaPiana** [comment]
closing this issue as it seems to be resolved, we can reopen it if needed
