### ISSUE TITLE
APIs for `RuleUse` management

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fides#2143]

**Comment by pattisdr** [comment]
Note that the `RuleUse` table has now been removed in https://github.com/ethyca/fides/issues/2146, in favor of having the `config.json` be the one source of truth regarding whether consent preferences are executable.  We may be able to close this once we determine there are no issues with this.

**Comment by seanpreston** [comment]
Thanks for the update @pattisdr — I'll close this for now
