### ISSUE TITLE
Hard-coded Mailchimp Transactional (Mandrill) consent request execution

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fides#2150]
In https://github.com/ethyca/fides/issues/2144 we identify a format for specifying consent request generation and execution. Before we implement that, we'd like to hook in a string of requests off to Mandril in the [`run_consent_request`](https://github.com/ethyca/fides/pull/2125/files#diff-35fed73a3a47b2a6c6e7d3d413edf8c493406cb51aceb07a28025574fd293c3fR407) function. The benefits of this are that it:
- buys us some time to finalise the spec so that it fits into the existing SaaS connector DDL well
- gives us a higher chance of having something demo-able by the end of this sprint

**Comment by saiatethyca** [comment]
Key decisions:

1. For the scope of current Mailchimp and other connector dev work, assume that we will have only one data use case and all the connectors available will be fired. So the connector SaaS config doesn't need to know about the data use it will be triggered on.
2. Have an executable flag for a data use in the privacy center.
3. Multiple identities can be either capture from the privacy center UI or from a database depending on the connector requirements.
