### ISSUE TITLE
Loosen installation requirements

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#217]
Right now the versions we have pinned are too specific and could make Fides difficult to use in existing Python projects. We need to make them looser and give ranges instead of exact matches.

Main issue here is how to test it

**Comment by earmenda** [comment]
Peeked over at fidesops and they also have some strict requirements at the moment but also use `~=` for some:
https://github.com/ethyca/fidesops/blob/main/requirements.txt

I would think that adding wildcards to minor and patch versions would be safe. We could confirm that for each library they follow semantic versioning for releases.

**Comment by ThomasLaPiana** [comment]
fidesops is different in that they are meant to be a standalone application that is run in a docker container, but there are situations in which someone would want to add fidesctl to their own python project dev requirements.

I agree on the wildcard for minor/patch, lets start there as a first iteration and figure out if there is any extra testing we want to do around that

**Comment by ThomasLaPiana** [comment]
My method of attack here is going to be to pin everything to the lowest minor/major version that they're at now, confirm they all work, and then loosen the requirements and test it again with the highest version
