### ISSUE TITLE
Automate generation of a single number that represents total test coverage

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#2179]

**Comment by ThomasLaPiana** [comment]
@sanders41 I'm going to test out [Code Climate](https://codeclimate.com/quality) today and see how it looks

**Comment by ThomasLaPiana** [comment]
@NevilleS it looks like Code Climate is able to union the coverage results from multiple coverage reports to come up with a single source of truth number. Additionally, it supports `coverage.py` which is already the tool we are using, so this shouldn't be too hard to get up and running

**Comment by sanders41** [comment]
If we are happy with the test PR my vote is we go with Code Climate. codecov is having too many upload issues lately and will add to the flaky test issue.

**Comment by ThomasLaPiana** [comment]
Code climate seems to have everything we're looking for, will continue down that road then 🙂
