### ISSUE TITLE
Home screen header scaling and responsiveness issues

### ISSUE THREAD

**Issue by renderbits** [ethyca/fides#2200]
### Bug Description

The responsive header on the Fides Home Screen isn't behaving as expected

#### Steps to Reproduce

1. Open Fides Home Screen
1. Adjust the browser width

### Expected behavior

1. The image shouldn't scale
2. The text should wrap correctly
3. The image should remain pinned to the right side of the screen
4. The image should not overlap the header text area

### Screenshots
![Screenshot 2023-01-11 at 12 17 48 PM](https://user-images.githubusercontent.com/93470872/211805688-7e69b64b-4991-44b2-9190-33b2309632e6.png)
![Screenshot 2023-01-11 at 12 18 04 PM](https://user-images.githubusercontent.com/93470872/211805702-b29c2781-d665-4e37-818a-d99d55fea986.png)

### Environment

* Version: Safari Version 16.2 (18614.3.7.1.5)
* OS:13.1 (22C65)
* Python Version:3.10.8
* Docker Version:4.12.0 (85629)

**Comment by chriscalhoun1974** [comment]
Here is my [PR](https://github.com/ethyca/fides/pull/2277).

**Comment by Roger-Ethyca** [comment]
verified on test_env


![Image](https://user-images.githubusercontent.com/115798183/213791188-adaeff08-30e9-46a6-9db7-4bce68f2ac01.png)
![Image](https://user-images.githubusercontent.com/115798183/213791189-a017c652-9c3f-4252-916d-588062d050a2.png)
![Image](https://user-images.githubusercontent.com/115798183/213791190-7ad139a4-3e08-4dbc-9193-b804a907d872.png)
