### ISSUE TITLE
Add anonymous analytics to fidesctl

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#221]
So we can get a better idea of how people are using fidesctl, we should add a _completely anonymous and respectful_ analytics phone-home to fidesctl that is optional

**_-- updated 12/20_** 
as a product manager, we're trying to answer the questions, 
* "what commands and flags are adopters using the most?"
* "what errors are adopters running into?" so that we can make the experience or documentation better
* "how are adopters deploying fidesctl, if at all?" so we know what types of infra/configurations to support or create documentation around 
* "what resources are being used? and how are they being used?" as we're looking to improve the language/taxonomy, the experience around creating manifest files, and where we can help with documentation or CLI features

With these questions in mind, here we can aspire to having a standardized event message format that contains:

1.  the usual anonymous analytics suspects (version, unique clientid, timestamps, etc)
2. cli command(s) and flag(s) used
3. nonspecific errors returned from commands run 
4. whether using our vscode plugin?
5. whether pinging from webserver or from local?
6. fides resource utilization metrics (quantity of systems? datasets? policies? further, number of declarations?)
7. fideslang utilization metrics (high level, which qualifiers are being used? categories? and how many of each?) 

in functional requirements, the user should be opted-in, with the option to opt-out as part of our commitment to building and enabling privacy respecting systems.

**_-- updated 01/25_** 

This work is moving to the `fideslog` repo and will be integrated here once it is ready

**Comment by ThomasLaPiana** [comment]
here's some examples from notable OSS project:

https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/tracking.py
https://gitlab.com/meltano/meltano/-/blob/master/src/meltano/core/tracking/ga_tracker.py

**Comment by ThomasLaPiana** [comment]
@ethyca/fides-control need your thoughts on this!

**Comment by brentonmallen1** [comment]
I think the following are probably the key things we want to meet :

- transparency through legible code
  - like the examples
- transparency through clear and concise documentation (outside the codebase)
  - doc page that says `what we track and why`
- clear means to opt out

**Comment by PSalant726** [comment]
> we should add a _completely anonymous and respectful_ analytics phone-home to fidesctl

If we are committed to this, both through implementation and documentation, then why should we allow an opt-out? My thought is that if we _do_ allow users to opt out, then we can expect the vast majority of users to do it. This would lead to skewed analytics, and the potential misprioritization of changes.

As an example, Mozilla suffers mightily from this problem. They frequently change or even remove Firefox features that leave the community...less than pleased, but it's because everyone disables telemetry!

**Comment by ThomasLaPiana** [comment]
@PSalant726 while that is unfortunate, I do not see a world in which this feature ships without the ability to opt-out, it is a key part of respectful systems. If users opt-out and as a result features are incorrectly prioritized, that is the nature of things and we could attempt to do user interviews/other avenues of figuring out what our users want

**Comment by PSalant726** [comment]
Do we have an internal analytics endpoint? Is there any existing framework for telemetry? Or, are both of these part of the work described by this issue? If so, I highly recommend [OpenTelemetry](https://opentelemetry.io/) as a FOSS, future-proof solution.

**Comment by iamkelllly** [comment]
as a product manager, i'm trying to answer the questions, 
* "what commands and flags are people using the most?"
* "what errors are people running into?" so that we can make the experience or documentation better
* "how are people deploying fidesctl?" so we know what types of infra/configurations to support or create documentation around 
* "what resources are being used? and how are they being used?" as we're looking to improve the language/taxonomy, the experience around creating manifest files, and where we can help with documentation or CLI features

With these questions in mind, here we should probably aspire to go is having a standardized event message format that contains:

1.  the usual anonymous analytics suspects (version, unique clientid, timestamps, etc)
2. cli command(s) and flag(s) used
3. nonspecific errors returned from commands run 
4. whether using our vscode plugin?
5. whether pinging from webserver or from local?
6. fides resource utilization metrics (quantity of systems? datasets? policies? further, number of declarations?)
7. fideslang utilization metrics (high level, which qualifiers are being used? categories? and how many of each?) 

in functional requirements, the user should be opted-in, with the option to opt-out as part of our commitment to building and enabling privacy respecting systems.

**Comment by NevilleS** [comment]
@PSalant726 we've used some external tools previously (Segment/GA/Pendo/etc.) but for Fides I'd prefer to have a really simple internal solution for this to avoid any 3rd party data sharing. So OpenTelemetry might be a good fit though it seems to be designed to capture a lot of o11y data which feels like a separate use case when you look at the types of event data we'd want to be capturing in @iamkelllly's comment

**Comment by ThomasLaPiana** [comment]
> as a product manager, i'm trying to answer the questions,
> 
> * "what commands and flags are people using the most?"
> * "what errors are people running into?" so that we can make the experience or documentation better
> * "how are people deploying fidesctl?" so we know what types of infra/configurations to support or create documentation around
> * "what resources are being used? and how are they being used?" as we're looking to improve the language/taxonomy, the experience around creating manifest files, and where we can help with documentation or CLI features
> 
> With these questions in mind, here we should probably aspire to go is having a standardized event message format that contains:
> 
> 1. the usual anonymous analytics suspects (version, unique clientid, timestamps, etc)
> 2. cli command(s) and flag(s) used
> 3. nonspecific errors returned from commands run
> 4. whether using our vscode plugin?
> 5. whether pinging from webserver or from local?
> 6. fides resource utilization metrics (quantity of systems? datasets? policies? further, number of declarations?)
> 7. fideslang utilization metrics (high level, which qualifiers are being used? categories? and how many of each?)
> 
> in functional requirements, the user should be opted-in, with the option to opt-out as part of our commitment to building and enabling privacy respecting systems.

thank you for the input here! this is directly designed to help _you_ so your feedback is what we will go off of

**Comment by earmenda** [comment]
+1 focusing on transparency. 

One thing that isnt clear to me is where this data being published from. Do we want to focus on cli usage or do we want a general solution in the fidesctl webserver? The cli and webserver are separate components and have access to different kinds of information. The webserver provides endpoints for simple crud operations and it has the benefit of persisting a state. An example where the cli and webserver don't have access to the same information is with the `evaluate` command. All of the evaluation logic is in the cli and the webserver is only aware of evaluations if a result is persisted(`-- dry` is not used).  So metadata for running evaluations would be hard to publish from the webserver. It will also be the case that some of the data we need will be more accessible on the server, like for _fides resource utilization metrics_ .

The webserver having access to a state has the benefit of pre-aggregating analytics data which could be published periodically. In the case that we want to publish analytics data from cli invocations, then I would think we have two options:
* Each cli invocation reaches out to "home" server and publishes its analytics data
* Each cli invocation reaches out to its fidesctl webserver and publishes its analytics data. The webserver then reaches out to the "home" server at some point.

**Comment by PSalant726** [comment]
> where this data being published from

I believe the implementation would have to involve the creation of a new fidesapi endpoint (`/analytics`?) that receives requests whenever the desired CLI operations are executed, and includes relevant information in the request body. This endpoint's handler would in turn have to make a request to our internal telemetry endpoint, but the details surrounding that endpoint are unclear to me.

Alternatively, the CLI could make requests directly to the internal telemetry endpoint, but that would increase the configuration complexity re: opt-out (it would have to be set for both the CLI and the API server), and potentially impact CLI command latency (even if the requests are async).

**Comment by ThomasLaPiana** [comment]
I think the majority of the important data will be coming from the CLI, but @earmenda i like your idea that we could actually clean it up/aggregate/anonymize on the server side. The only problem is that if people are running in local mode or --dry like you said, the CLI still needs a way to send that data without _needing_ the webserver.

In our general implementation we try to make the CLI as feature-rich as possible without overreliance on the webserver, so I think we should stick to that principle here as well. For the first-iteration we can test only having the CLI send analytics data (on each command) and then brainstorm later how we might want to expand that to the webserver as well

**Comment by NevilleS** [comment]
I'd agree that we want *both* the CLI and webserver to have the ability to submit analytics events. Let's start from there and have a clear API that those will send to (e.g. `fidesanalytics.ethyca.com` or similar). In the future, we could support the ability for the webserver to "proxy" CLI analytics to the hosted API, but that seems overcomplicated for now.

Note that we really *do* want to know the number of unique CLIs running, so we can answer questions like "what's the average CLI:server ratio? 2:1? 10:1?" etc.

**Comment by ThomasLaPiana** [comment]
@PSalant726 immediate next steps are for a design doc in confluence, covering the following things:

* researching OSS analytics frameworks (e.g. OpenTelemetry) that could provide a good solution
* selecting either an OSS framework or building our own event format
* adding event reporting to the CLI
* adding event reporting to the server
* setting up a hosted analytics API to receive & store events
