### ISSUE TITLE
Add button and modal to upload connector

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#2214]
### Backend considerations
The branch `custom_connector_templates` in the `fides` repo contains an implementation of the `api/v1/connector_template/register` endpoint that can be used as a reference.

```
@router.post(
    REGISTER_CONNECTOR_TEMPLATE,
    dependencies=[Security(verify_oauth_client, scopes=[CONNECTOR_TEMPLATE_REGISTER])],
)
async def register_custom_connector_template(
    connector_template: UploadFile,
    db: Session = Depends(deps.get_db),
) -> None:
    contents = await connector_template.read()
    zip_file = BytesIO(contents)
    ...
```

For this front-end ticket it would be enough to be able to post a zip file to a stubbed version of this endpoint.

**Comment by galvana** [comment]
Covered by #2213

**Comment by Roger-Ethyca** [comment]
moving to done 

![Image](https://user-images.githubusercontent.com/115798183/231579389-102e0a8e-f8c6-44e8-ad92-7841c62beaf0.png)
