### ISSUE TITLE
Identity verification pop-up doesn't close and errors out on multiple submit clicks

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2219]
### Bug Description

Identify verification pop-up doesn't close and errors out on multiple submit clicks. This seems to happen when the manual approval process is disabled.

#### Steps to Reproduce

1. Disable the manual approval process.
2. Start any DSR request and enter the verification code in the UI pop-up.
3. Click submit once and see that the pop-up doesn't close.
4. Click on submit again and see that the pop-up closes but an error banner is shown in the UI.
5. DSR request is successfully triggered.

### Expected behavior
1. Pop-up should be closed on the first click of submit button, and there shouldn't be any error banner in the UI.

### Screenshots
<img width="1024" alt="image-20230105-182439" src="https://user-images.githubusercontent.com/117193073/211957390-0dd4a6e2-9abf-4b14-b609-d4edc79ee906.png">

**Comment by Roger-Ethyca** [comment]
@Roger-Ethyca  look into this with `masking_strict = false`

**Comment by Kelsey-Ethyca** [comment]
I was able to repo this.. you need to click rapidly on step 3 and 4

**Comment by Kelsey-Ethyca** [comment]
I would consider disabling the 'Submit code' btn after initial slick.
