### ISSUE TITLE
Phone Number Format not validated on Front End

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2220]
### Bug Description

When a data subject enters their phone number with an incorrect format, we don’t validate it on the front end, but instead return a 422 from the Fides server. 

#### Steps to Reproduce

1. Enter the wrong number while creating a DSR request.
2. See the error in the logs.

### Expected behavior
1. Phone number should be validated on the front end before submitting.

### Screenshots

<img width="624" alt="image-20230105-180710" src="https://user-images.githubusercontent.com/117193073/211957789-c41c754e-6aaf-4ed0-971c-c2281b8fea1f.png">

**Comment by SteveDMurphy** [comment]
@saiatethyca I ran into this briefly as well when using the swagger docs, I think the frontend forms the phone number correctly. Did you experience this in there as well? Once I changed the phone number to the example format the response gave mine succeeded

**Comment by ssangervasi** [comment]
Looks like the validation is not run when the phone number is configured to be optional. The input still does prevents invalid characters, but it would allow the phone to be too long (>15 characters).

**Comment by Roger-Ethyca** [comment]
@mfbrown  out of the box this front end validation looks a bit wonky... I'd like to get a little clarity on the acceptance criteria for this one. 

These are US examples... I'll try international numbers next. 
accepted numbers are
415-555-555
1-415-555-555
415-555-55
415-555-55555555
Would it make more sense to only allow the following?
1-415-555-5555
415-555-5555
