### ISSUE TITLE
Improve the dataset linking UX on connectors

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#2224]
### Is your feature request related to a specific problem?

https://github.com/ethyca/fides/pull/2162 made some good progress in allowing users to link a dataset to a connector. However, the UX can be much improved!

### Describe the solution you'd like

Preliminary designs are [here](https://www.figma.com/file/dmEwdK3xZwjKfGVQ9t66xe/Fides-v.2-Master-Working-Files?node-id=1681%3A36313&t=h1krRG4RoQLkJD8Q-0) though still in progress

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by seanpreston** [comment]
Please do this after https://github.com/ethyca/fides/issues/2262 so we can make the change directly to `main`.

**Comment by seanpreston** [comment]
On talking to @rsilvery I'm going to close this out as more thoughtful designs are coming down the pipeline to address this.
