### ISSUE TITLE
Listen to GPC Signal and set initial consent properties accordingly

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#2228]
As a user, when I have a global privacy control signal, I want to be automatically opted out of any browser based tracking which serves the function of data sales or data sharing, so that I don’t need to verify my identity with the privacy center to have my GPC choice reflected.

**AC**

- Given that I have an opt-out signal set on my global privacy control, when I access a site with Fides consent, then any client side record of my consent is automatically updated to reflect my GPC signal.
- Given that I have a global privacy control opt-out signal set on my browser, when I access a site with Fides consent for the first time, then I am opted out of systems designated as supporting data sales or sharing.
- Given that I have a global privacy control opt-out signal set on my browser, when I access a site with Fides consent, then my consent object includes an indication that my choices are influenced by GPC
- Given that I have a global privacy control opt-out signal set on my browser, when I access a site with Fides consent, then my consent cookie includes an indication that my choices are influenced by GPC

**Comment by ssangervasi** [comment]
This should be covered by the code changes in:
-  https://github.com/ethyca/fides/pull/2341#issue-1553979189
- https://github.com/ethyca/fides/pull/2596

There are cypress tests that cover the with/without GPC, and with/without the user having already stored their consent, using the static page at `/fides-consent-demo.html`.

I want to confirm the functionality more completely by building `fides-consent.js` and putting it into an external page: - 
- [ ] My [place for GTM testing](https://ethyca.atlassian.net/wiki/spaces/EN/pages/2563637409/j1407b+fides-consent.js+Google+Tag+Manager) is disabled at the moment, so I can't do that yet: https://ethyca.slack.com/archives/C01TUEAGCR1/p1676511482711419
- [ ] I should be able [test the Shopify page](https://ethyca.atlassian.net/wiki/spaces/EN/pages/2579038241/Shopify+fides-consent.js) though.
