### ISSUE TITLE
Record all applications of a Global Privacy Control Signal

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#2232]
As a compliance person, I want a record of each consent selection which is made because of a global privacy control signal so that I can demonstrate to regulators our compliance and so I can understand the impact and use of the feature in my customer base.

**AC**
- Given that I have enabled global privacy control support on one or more data use cases, when a user has consent settings applied to adhere to their GPC signal, then a record is created with the use case and information about the data subject, to the extent possible
- If the user has accessed the privacy center, save the identity.

**Comment by mfbrown** [comment]
De-scoped for now.
- TODO: need to determine what to save when they just visit the site but don’t verify their ID.
- Given that i was opted out of a use case via GPC prior to verifying my identity in the privacy center, when I do verify my ID in the privacy center, then an attempt is made to join my previous consent log and my new log.

**Comment by ssangervasi** [comment]
This will need the API from https://github.com/ethyca/fides/pull/2599, at which point it will be a quick addition to the payload.

**Comment by Roger-Ethyca** [comment]
![Image](https://user-images.githubusercontent.com/115798183/221302104-db97dfa9-c749-44a2-8fa2-72e6dae2e954.png)
