### ISSUE TITLE
"Configure your privacy requests" screen

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2234]
### Description

As a Privacy Engineer, I want to know all the required steps and their respective statuses to complete the Fides DSR setup.

### AC

1. I know all the necessary configuration tasks (configure messaging provide and storage) I need to do to complete the configuration for DSR.
2. The user has all the required permissions.

Figma [link](https://www.figma.com/file/dmEwdK3xZwjKfGVQ9t66xe/Fides-v.2-Master-Working-Files?node-id=1322%3A24913&t=yJ9ZYgRM06OHj2N2-0)

**Comment by mfbrown** [comment]
@saiatethyca  Update the acceptance criteria as needed. - For example, during refinement we werent quite sure what #2 meant.

**Comment by saiatethyca** [comment]
Expand on what user permissions mean here.

**Comment by Roger-Ethyca** [comment]
![Image](https://user-images.githubusercontent.com/115798183/219105771-0b923039-714f-4874-8d21-8d3fa7d01668.png)
![Image](https://user-images.githubusercontent.com/115798183/219105770-0903912d-4d78-4745-b166-8ebe28593eae.png)
![Image](https://user-images.githubusercontent.com/115798183/219105769-9fb7025e-e4fe-4314-b178-8d7250f268e2.png)
