### ISSUE TITLE
Configure storage destination via UI

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2235]
### Description
As a  Privacy Engineer, I want to complete storage configuration via UI.

### Assumptions

1. Users already have a storage destination setup in their internal infrastructure (S3 or local).
2. They have all the necessary credentials to access the storage destination ready.

### AC

1. I can select between local and s3 storage options.
2. When a storage type is selected, I’m presented with a form with all the necessary details required for the storage type.
3. I can save a configuration setting for a storage type or cancel to remove the details entered.
4. Configuration settings have defined drop downs where we already know the possible set of values.
5. I can switch storage types, and the previously saved details for a storage type are retained.
6. When all the details necessary for a storage type are entered, I’m notified that all the details have been successfully updated.
7. I can see why a request failed.

Figma [link](https://www.figma.com/file/dmEwdK3xZwjKfGVQ9t66xe/Fides-v.2-Master-Working-Files?node-id=1322%3A24913&t=yJ9ZYgRM06OHj2N2-0)

**Comment by Kelsey-Ethyca** [comment]
In future we will want to check permissions

**Comment by saiatethyca** [comment]
Backend work for this ticket is being done here https://github.com/ethyca/fides/issues/1974
