### ISSUE TITLE
Support and synchronize configuration changes via CLI

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2239]
### Description

As a Privacy Engineer, I want to add/update the configuration for a component via CLI.

### Assumptions

1. The user has all the required permissions to add/update the configuration.

### AC

1. We should consider all the existing use cases of environment variables, Toml files for deployment.
2. Document the decisions taken to change existing behavior.

Figma [link](https://www.figma.com/file/dmEwdK3xZwjKfGVQ9t66xe/Fides-v.2-Master-Working-Files?node-id=1322%3A24913&t=yJ9ZYgRM06OHj2N2-0)

**Comment by saiatethyca** [comment]
Check with @RobertKeyser on the implementation plan to ensure HELM deployment scripts are not impacted.

**Comment by adamsachs** [comment]
closing this as it's covered more specifically by:
https://github.com/ethyca/fides/issues/2453
https://github.com/ethyca/fides/issues/2456
