### ISSUE TITLE
Docs for Consent Request setup

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fides#2252]
For the customer facing docs the expectation is that Dawn will provide basic technical detail and Lalitha (new tech writer) will write the doc we deliver.

Internally it would be useful to have a doc. for engineering too so that we can set it up internally and test.

**Comment by seanpreston** [comment]
@rsilvery / @NevilleS — is there a desired format for the handover doc we give to Lalitha?

**Comment by seanpreston** [comment]
Hey @pattisdr — a good starting point would be to open a PR against [this repo](https://github.com/ethyca/fidesdocs), and Lallitha can pick it up from there.

**Comment by pattisdr** [comment]
Thank you @seanpreston can do
