### ISSUE TITLE
CLI Overview Docs reference Config File Page, which is a broken link

### ISSUE THREAD

**Issue by RobertKeyser** [ethyca/fides#227]
# Overview
Page: https://ethyca.github.io/fides/cli/cli/#:~:text=fidesctl%20Configuration%20File

> Identifies a file that you can use to configure the fidesctl environment. For more information about the file, **see fidesctl Configuration File**. To see the current configuration file, do fidesctl view‑config.

The link to "fidesctl Configuration File" points to https://ethyca.github.io/api/configuration-file, which is a 404. 

This can be changed here:
https://github.com/ethyca/fides/blob/75ec54afad2e3965f7d758d3bce2464a36d2466a/docs/fides/docs/cli/cli.md?plain=1#L36

My guess is that it should point to https://ethyca.github.io/fides/tutorial/add/#configure-fidesctl instead, but not sure that's the perfect page either.

**Comment by RobertKeyser** [comment]
I think that https://github.com/ethyca/fides/pull/200 has a section for the configuration.toml file. That might be a good candidate.

**Comment by ThomasLaPiana** [comment]
yep, we now have a page about configuration specifically: https://ethyca.github.io/fides/installation/configuration/
