### ISSUE TITLE
On the User Management page, rename "Privileges" to "Permissions" and add a "Select All" toggle

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2278]
### Description
The experience of creating a user and setting user privileges is really painful - the list of "privileges" is incredibly long, but for most common use cases we actually want all created users to have all permissions. The right solution to this problem is to introduce a few basic roles (e.g. "Admin", "User") but that's a larger change that we will plan & design carefully - in the short-term though, we should make the current page slightly more functional!

We should make two UX improvements here:
1. Add a "Select All" toggle to select everything
2. Rename them from "Privileges" to "Permissions" to be consistent with our documentation and user expectations

### Acceptance Criteria
- I can select all user permissions or clear all in the User Management page
- Current copy that says "Privileges" is renamed to "Permissions"

**Comment by seanpreston** [comment]
![Image](https://user-images.githubusercontent.com/1667340/214708784-d9d6479c-2e7a-453b-9212-cdf4e42a5346.png)

We'd like to add a checkbox to the top of this list that allows the user to select or deselect all of the options. Importantly, if deselecting all, `View privacy requests` must remain selected.

**Comment by NevilleS** [comment]
Thanks @seanpreston - I updated the description for clarity. I'm also recommending we rename "Privileges" to "Permissions" for clarity here
