### ISSUE TITLE
Email body should say "No data generated for the request" instead of sending empty json files

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2279]
### Description
If a user doesn't have any data and they trigger an access request, we currently return empty JSON, which is confusing as it can be interpreted as the request failed.
### Acceptance Criteria
- If no user data is generated, I can clearly understand that from the email. I shouldn't see an empty JSON file.

### Mockups

**Comment by cilliankieran** [comment]
Just want to clarify on this in case it gets evaluated for implementation. The requirement here is that we should not return empty JSON when there are no records for an access request, however separate from this, emails should notify a user when their request returned no data but this must be a configurable message.
In Ethyca Pro, the default message reads _"We have completed your request but were unable to find data related to the identity you provided. If you believe this is an error, please contact our <link>customer support team</link>"_
