### ISSUE TITLE
Parallelize CI Jobs

### ISSUE THREAD

**Issue by PSalant726** [ethyca/fides#228]
To reduce the time spent running the CI pipeline configured through GitHub Actions, it should be refactored into parallel jobs. A task should exist to build the Docker images and expose them as artifacts used by downstream jobs. Separately formatting, linting, type checking, complexity checking, and testing should happen in parallel.

**Comment by NevilleS** [comment]
Word of warning: see https://github.com/ethyca/fidesops/issues/90 where we have all CI jobs in parallel, but it's a really inefficient use of CI minutes...!

**Comment by NevilleS** [comment]
See my follow-up comment here too: https://github.com/ethyca/fidesops/issues/90#issuecomment-974196096

Looks like enabling docker caching across jobs will be a rather non-trivial thing, unfortunately
