### ISSUE TITLE
User has to click twice to close the DSR request modal. 

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2281]
### Bug Description

- In the modal to collect user information for DSR requests, if the user focuses on email and clicks on cancel, the modal doesn't close and the "Email is required error" appears.
- The user has to click cancel again to close the modal.

#### Steps to Reproduce

1. Click on Access or Erasure in the privacy center.
2. Focus on the email and click cancel
3. Click cancel again to close the modal

### Expected behavior
1. Modal closes on the first click with no errors

### Screenshots

![Screen Shot 2023-01-19 at 10 33 34 AM](https://user-images.githubusercontent.com/117193073/213485939-0147805b-edfa-4668-b209-944d1abb94d1.png)

![Screen Shot 2023-01-19 at 10 33 23 AM](https://user-images.githubusercontent.com/117193073/213485950-9928cc78-ead7-4b4d-94b9-00b753228826.png)

**Comment by NevilleS** [comment]
I figured out what's going on here - when the validation error appears, it nudges the Cancel / Continue button down enough that the click doesn't "fire" through the to the Cancel button.

That's really frustrating in practice... in general we should leave enough room for the errors to appear without having to relayout the form.

**Comment by Kelsey-Ethyca** [comment]
Options 

1. add space for the error messages 
2. move the error messages to the bottom 
3.possibly "interrupting" the onblur call or adding a conditional in so that validation does not run until we know the next focused element,

**Comment by Roger-Ethyca** [comment]
verified on test_env using repro steps
