### ISSUE TITLE
"Request Type" on Privacy Requests page shows the policy key instead of the request type (Access / Erasure)

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2282]
### Description
On the Privacy Requests page, the "Request Type" column shows the policy key (e.g. `default_access_policy`) instead of the user-friendly "Request Type" (e.g. `Download` or `Delete`).

This should be updated to be consistent with the Request Details page, which does show the Request Type correctly.

Also (this is an extra ask from @NevilleS here) - for consistency in our language, let's also update the Request Type in the UI to be consistent with the API "action type" it reflects. In the API we constrain these actions to Access/Erasure/Consent/Update, which are more inline with the legal terms for these concepts. We added "Download" and "Delete" in the UI to be more user-friendly but in practice this has led to confusion.

### Acceptance Criteria
1. Privacy Requests table should show the Request Type
2. Policy key should no longer be shown in the table view
3. Change the request types in the UI to be consistent with the action type in the API: "Access", "Erasure", "Consent", "Update"

### Screenshots

**Current**
![Screen Shot 2023-01-19 at 10 40 44 AM](https://user-images.githubusercontent.com/117193073/213486497-fa324644-0f74-45a9-9c00-294089a65d72.png)

### Implementation Notes

See the `RequestType` component that is used for the details page: https://github.com/ethyca/fides/blob/67a50d16d97030d9bd7afb18b417db68209dc8be/clients/admin-ui/src/features/common/RequestType.tsx#L15

This is also related to issue #2288 and should likely be fixed together!

**Comment by NevilleS** [comment]
Hi @TheAndrewJackson - quick note that I tacked on an ask for a copy change here as well.
