### ISSUE TITLE
PII toggle state between request detail page and privacy request manager page are not maintained

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2286]
### Bug Description

The PII toggle state between the request detail page and the privacy request manager page is not maintained as expected.

#### Steps to Reproduce

1. Go to privacy requests page and click to reveal PII. 
2. Now go to a detail page for any privacy request. PII toggle is disabled but the PII is visible.
3. Click to enable and go back to the privacy requests page. PII is visible for all the requests and the toggle is off.

### Expected behavior
- PII toggle for the privacy requests page and request detail page should be independent and the default state should have no PII visible.

### Screenshots
![Screen Shot 2023-01-19 at 10 52 16 AM](https://user-images.githubusercontent.com/117193073/213490342-0f690fbf-89e0-456c-8e5f-d7bab5a0cd3f.png)

![Screen Shot 2023-01-19 at 10 52 06 AM](https://user-images.githubusercontent.com/117193073/213490326-c4120e3e-ff5d-4b33-a060-59cf86e6361c.png)

**Comment by NevilleS** [comment]
Note that this was previously reported here: https://github.com/ethyca/fides/issues/1926, but we'll keep this issue as it has screenshots! 😄
