### ISSUE TITLE
Add a pre-commit hook for linting/formatting

### ISSUE THREAD

**Issue by PSalant726** [ethyca/fides#229]
To prevent the creation of commits that simply fix linter and formatter errors, a pre-commit hook should be added to the repository which rejects commits that don't pass these checks. As a prerequisite, we may need to align on our expectations for enforced linter and formatter rules.

**Comment by earmenda** [comment]
Hi @PSalant726, I'm not familiar with pre-commit hooks. Is there a specific framework you know about which makes this simple? or do we just integrate directly with [git to create the hooks ](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks)?

**Comment by edthedev** [comment]
@earmenda You are correct - a `pre-commit hook` is a built-in feature of `git`.

**Comment by ThomasLaPiana** [comment]
should use this: https://pre-commit.com/
