### ISSUE TITLE
Add "Approve/Deny Request" button on the Request Details page to be consistent with Privacy Requests page

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2290]
### Description
Add the ability to Approve or Deny a privacy request from the Request Details page. This should have the exact same behavior as the Approve or Deny options that are accessible from the Privacy Requests page (the table view), but just be accessible from the page for convenience.

#### Current "Reprocess" Button
Today, the only action accessible from the Request Details page is the "Reprocess" button is shown when an error occurs:
![Image](https://user-images.githubusercontent.com/1834295/214709795-0b3b9827-1a61-4414-a4b6-a63154af0639.png)

#### Approve/Deny Design
For consistency, we should show the same "Approve/Deny" toggle that is visible on the Privacy Requests page today:
![Image](https://user-images.githubusercontent.com/1834295/214710162-6c2cdca2-c5e8-412d-85a9-316b54a9f1b0.png)

This Approve/Deny option should be shown where the "Reprocess" button appears (see above).
 

### Acceptance Criteria
1. I can approve or deny a DSR request from the Request Details
2. Approve behaves exactly the same as if clicked from the Privacy Requests page (e.g. shows a confirmation modal)
2. Deny behaves exactly the same as if clicked from the Privacy Requests page (e.g. shows a confirmation modal with a required field for denial reason)

**Comment by NevilleS** [comment]
@saiatethyca I rewrote the description here and provided a few screenshots but stopped short of doing a mockup.

To @TheAndrewJackson / @seanpreston : let me know if you want to huddle on this one or have questions! My ask is that we make the behaviour here consistent, so hopefully the screenshots I included above show you what I mean

**Comment by Roger-Ethyca** [comment]
![Screen Shot 2023-02-10 at 2 40 03 PM](https://user-images.githubusercontent.com/115798183/218186197-c6b1b636-bbba-4670-b3c9-78dd31aa1384.png)
![Screen Shot 2023-02-10 at 2 54 12 PM](https://user-images.githubusercontent.com/115798183/218186204-e2f061c2-374e-44be-be72-13b4e1a5b51f.png)
![Screen Shot 2023-02-10 at 2 56 14 PM](https://user-images.githubusercontent.com/115798183/218186206-a627f27a-686c-483c-afc4-e53dcc7e8d52.png)
![Screen Shot 2023-02-10 at 2 58 16 PM](https://user-images.githubusercontent.com/115798183/218186230-a7153e2d-5142-4cf4-b28a-24bfb7261461.png)
