### ISSUE TITLE
Add a confirmation modal when approving any privacy request

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2291]
### Description
Today we allow privacy requests to be approved from the Privacy Requests page with a single-click. While this is convenient, we're also finding in some user testing that it's surprising behavior: after all, when a privacy request is approved, it'll immediately start querying databases, making API calls, and (in the case of an erasure) will also start deleting data!

To avoid this, we should add a confirmation modal to the workflow. Here's a quick mockup from @NevilleS with some proposed copy:
```
Are you sure you want to approve this privacy request?

[Cancel] [Confirm]
```

We should use our existing confirmation modal pattern for this, so follow the existing conventions for consistency!

### Acceptance Criteria
1. When a privacy request is approved, a confirmation modal appears
2. If the confirmation modal is cancelled, the request remains unapproved
3. If the confirmation modal is confirmed, the request is approved and begins processing

**Comment by saiatethyca** [comment]
Need to get feedback from design on this modal.

**Comment by NevilleS** [comment]
Thanks @saiatethyca - I updated the description with a quick "design" with some suggested copy. We have existing confirmation modals we can leverage here, so there shouldn't be any extra legwork required to provide a mockup.

To @TheAndrewJackson / @seanpreston: let us know if we need to provide some more feedback on this!

**Comment by seanpreston** [comment]
@TheAndrewJackson and I have spoken about how this will affect #2289 — if the `deny` button is no longer clickable with a modal showing, then we can postpone that ticket and let this one take precedence.
