### ISSUE TITLE
`fides user create ...` doesn't work in zsh

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fides#2310]
The following was recorded from the `fides user create ...` step in the QA steps [here](https://github.com/ethyca/fides/pull/2153)

```
(fides) ➜  fides git:(main) ✗ fides user create newuser HolyCow1*1
zsh: no matches found: HolyCow1*1
```

**Comment by sanders41** [comment]
`*` is a special character in zsh. I believe wrapping it in quotes will work.

```sh
fides user create newuser "HolyCow1*1"
```

**Comment by ThomasLaPiana** [comment]
@seanpreston also the username/password are options, not arguments

`fides user create -u newuser -p Testpassword1!`

Otherwise it will prompt you for them

**Comment by seanpreston** [comment]
Thanks! Will close this issue.
