### ISSUE TITLE
Unable to reprocess DSR that failed due to unreachable nodes

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fides#2311]
When a DSR fails due to unreachable nodes

`fides.api.ops.common_exceptions.TraversalError: Some nodes were not reachable: postgres_two:product`

we are not able to re-process that DSR through the Admin UI, as there is no failed step or collection, even after deleting the offending collection entirely. Looking at the event log, it doesn't appear to have tried to visit any collection.

![Image](https://user-images.githubusercontent.com/1667340/213872460-5b106e32-fe45-43f7-a1d9-7313063e1871.png)

**Comment by seanpreston** [comment]
From @pattisdr:

> This is something we could improve.  I don't think you'll ever be able to restart that privacy request. When we run a privacy request there are several steps that are run in sequence if applicable.  If we fail on the erasure step for example, we cache that it failed on the erasure step, and we cache which node we stopped on.  This is because the current behavior is to try to "restart from the failure point", not restart from the beginning. I imagine there are several places it can fail especially if you were setting up a system and didn't have everything set up properly that failed outside one of these specific steps. Further improvements might be just restarting from the beginning if there are no failure steps cached, or adding more checkpoints from which to restart from

**Comment by pattisdr** [comment]
Right now the behavior is that we first check to see if we can build a complete graph from the nodes, and if we can't, we fail early.
Our current restart behavior is limited and assumes a failure happened within the graph, not before, so we have no "failure checkpoints" and it can't restart.
I think 1) we need better alerting on if the graph is in a non-traversable state and 2) allow restarts from the beginning provided there's no checkpoint saved.

**Comment by rsilvery** [comment]
@Roger-Ethyca  can we confirm if this is still an issue?

**Comment by pattisdr** [comment]
I added some behavior in https://github.com/ethyca/fides/pull/4047 that may have addressed!
