### ISSUE TITLE
Groove Labs

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2323]

**Comment by nicolas-ethyca** [comment]
6/8 - NF Called Groove Labs and it appears to be a very small business with no privacy presence at all. They redirected me to the list-serve yes@groovelabs.net as a next step. I have suspicions they don't have the capability to integrate and this will be an email connector

**Comment by nicolas-ethyca** [comment]
@galvana is it this - https://www.groove.co/terms/? or groovelabs.net

**Comment by nicolas-ethyca** [comment]
@mfbrown - do you know which of the two Grooves this it?
