### ISSUE TITLE
SendCloud

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2326]

**Comment by Kelsey-Ethyca** [comment]
Sendcloud has no apis to for access/erasure/consent. I have requested a meeting with them. 

https://ethyca.atlassian.net/wiki/spaces/EN/pages/2705063937/Sendcloud+Connector+Specification

**Comment by nicolas-ethyca** [comment]
@Kelsey-Ethyca - can you loop me in on the meeting and I can have a deck ready for them (just to explain who/what we are) and then we can make the ask

**Comment by nicolas-ethyca** [comment]
@Kelsey-Ethyca did this meeting happen?
