### ISSUE TITLE
Fix the healthcheck port and add `curl` to the fidesctl container

### ISSUE THREAD

**Issue by iokamoto-sm** [ethyca/fides#233]
With the recent update, 'docker-compose up -d' did not start postgre database properly. Also, fidesctl container becomes unhealthy. I am suggesting the following change to address these issues.

* add `./` like `- ./postgres-data:/var/lib/postgresql/data` volume mapping
* install `curl` in fidesctl container
* correct healthcheck test so it refers to 8080 instead of 8000

```
diff --git a/.gitignore b/.gitignore
index 5435b80..ed9ec1d 100644
--- a/.gitignore
+++ b/.gitignore
@@ -207,3 +207,6 @@ venv.bak/
 .mypy_cache/
 .dmypy.json
 dmypy.json
+
+# postresSQL data
+postgres-data/
diff --git a/docker-compose.yml b/docker-compose.yml
index b753e35..3a64874 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -5,7 +5,7 @@ services:
       dockerfile: Dockerfile
     command: uvicorn --host 0.0.0.0 --port 8080 --reload fidesapi.main:app
     healthcheck:
-      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/health"]
+      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/health"]
       interval: 5s
       timeout: 5s
       retries: 5
@@ -32,7 +32,7 @@ services:
       timeout: 5s
       retries: 5
     volumes:
-      - postgres:/var/lib/postgresql/data
+      - ./postgres-data:/var/lib/postgresql/data
     expose:
       - 5432
     ports:
diff --git a/fidesctl/Dockerfile b/fidesctl/Dockerfile
index 16bf4af..02f9c8b 100644
--- a/fidesctl/Dockerfile
+++ b/fidesctl/Dockerfile
@@ -3,6 +3,7 @@ FROM python:3.8-slim-buster
 # Install auxiliary software
 RUN apt-get update
 RUN apt-get install -y \
+    curl \
     git \
     ipython \
     make \
```

**Comment by iamkelllly** [comment]
thank you @iokamoto-sm - I'm tagging this as a bug given the description here, we'll get this verified and addressed!

**Comment by ThomasLaPiana** [comment]
@iokamoto-sm the `curl` and healthcheck fix are clear, but what does the volume mapping update do?

**Comment by iokamoto-sm** [comment]
I got the error to start up postresql unless I changed it to sub directory. I realized it is not necessary. Maybe you can update the document so users clean up the existing fides_postgres volume or use the different volume.

It seems fides_postgres volume had the old data in my env. It was made before fides changed its database name from fidesctl to postgres. Somehow it was blocking the database creation.

**Comment by ThomasLaPiana** [comment]
oh I see, sorry about that! We should've added a note about that change

We've also updated the installation guide and quick starts to not point end-users at the development `docker-compose.yml` and `Makefile`, this increases stability for end-users as well. https://ethyca.github.io/fides/installation/installation/

So in summary, for this issue we'll go ahead and fix the `healthcheck` port as well as add `curl` to the container for better debugging

fyi @earmenda

**Comment by ThomasLaPiana** [comment]
@earmenda i just went ahead and made these changes in #236 since they're small and I needed to fix the health check for the testing I was doing anyway :)
