### ISSUE TITLE
Request denial reason should be required for all privacy requests

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2367]
### Description
When you "Deny" a privacy request, currently we shown a confirmation modal and allow the user to supply a denial reason. However, the denial reason is optional, but this is risky - in most regulations (e.g. GDPR), a reason is _required_ to be supplied when a subject request is denied, so we shouldn't allow this to be optional.

### Acceptance Criteria
1. Privacy request denial reason should be required

**Comment by seanpreston** [comment]
The most effective route is to fix this only in the UI for now.
