### ISSUE TITLE
Add a test to ensure Privacy Center always remains backwards compatible with all 2.x config.json files

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#2381]
### Is your feature request related to a specific problem?

We regularly need to add new features and configuration options to the `config.json` file at the heart of the Privacy Center, but we also regularly forget to ensure these are done in a backwards compatible way. A recent example of this is https://github.com/ethyca/fides/issues/2259.

Since this is easy to miss, automated tests that load in an older version of the "default" `config.json` file to check for compatibility issues will help us catch these bugs earlier, instead of waiting for a staging build to fail.

### Describe the solution you'd like

We should check in an older version of the `config.json` like this one from 2.0.0: https://github.com/ethyca/fides/blob/2.0.0/clients/privacy-center/config/config.json

There should be at least one unit or E2E test that confirms the Privacy Center correctly builds and type-checks that an older version of the `config.json` file is still considered valid. This will force our types (e.g. https://github.com/ethyca/fides/blob/main/clients/privacy-center/types/config.ts) to only introduce optional new values, new features will have to have fallbacks when configurations aren't present, etc.

### Describe alternatives you've considered, if any

We can also check for this manually in code review, QA testing, etc. We're already doing these things (and catching issues faster!) but it's more laborious.

Longer term, I also want to remove the reliance on having users manage the `config.json` themselves and replace this with an API so we can programmatically update the format. But that's a much bigger change 😄

**Comment by ssangervasi** [comment]
I think I'm going to spin up a GH discussion about config.json.
