### ISSUE TITLE
Masking Strategies Failing on Null/Non Strings

### ISSUE THREAD

**Issue by pattisdr** [ethyca/fides#2391]
### Bug Description

Hmac, hash, and likely other masking strategies are failing when a null value is passed in in a list, as well as when a non-string value is passed in. 

#### Steps to Reproduce

1. _Do this..._
1. _Then This..._

### Expected behavior

Null values should be returned as null.
For non-string, I think it makes sense to turn into a string.

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by seanpreston** [comment]
Nice catch @pattisdr thanks!
