### ISSUE TITLE
ChiliPiper

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2405]

**Comment by mfbrown** [comment]
Let's hold on this one. I talked to ChiliPiper earlier and they claim not to have any PII or an API. We'll need to reconsider how we work with them.

**Comment by nicolas-ethyca** [comment]
Hey @mfbrown In the privacy policy it calls out the PII (which can be considered sensitive) https://www.chilipiper.com/privacy-policy, can you loop me back in on this?
