### ISSUE TITLE
Add default policies to fideslang/fidesctl

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#244]
An additional way to reduce friction for users would be to have various "default" policies that users could choose from, for example:

1. GDPR
2. No Advertising
3. System Data Only
4. CCPA

This would allow engineers to only worry about their own dataset/system declarations and leave the legal/compliance side to a sensible default policy

This feature should allow users to define which default policies they want to use, if any

**Comment by iamkelllly** [comment]
It would be pretty difficult to create a "default" policy for the geo-specific legal regimes, as GDPR and CCPA have no specific  guidance on _how data is used in an organization_, they really only outline how a covered entity must react to data subject requests on data and consent management. 

The more likely default legally-driven policies (or, better, a repository of declarations) here should be for:
* Do not allow telephone call or text-messaged based-marketing (TCPA, USA) 
* Only allow transactional/relationship-based emails (CAN-SPAM, USA) 
* Allow usage of very sensitive PII specifically for the use of CIP and CDD (KYC, international) 

I think that full, default policies for "No data sales" and "Use anonymized system data only" are reasonable default policies as well, but would fully remove GDPR and CCPA from scope here.

**Comment by ThomasLaPiana** [comment]
I'm a fan of adding all 3 of those, but to start with maybe something a bit simpler like:

1. add a few broad ones that @NevilleS mentioned like "reject all third-party sharing"
2.  create a "Fides recommended default policy" that @iamkelllly proposed, which lays out sensible defaults and can be tweaked from there

**Comment by edthedev** [comment]
@iamkelllly Excellent points.

@ThomasLaPiana This is a great idea. I think even just one or two default policies would help by giving adopters something to work from, even if some need to turn them off or tune them.

**Comment by edthedev** [comment]
Bravo!
