### ISSUE TITLE
Set the default storage based on what user selects for storage configuration

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2453]
### Description
In This [ticket](https://github.com/ethyca/fides/issues/2235), we planned to only work on the UI to configure default storage. The default value propagation to the backend was decided to be a separate work after this [ticket](https://github.com/ethyca/fides/issues/1974) is completed.

We aim to set the default storage value in the backend.

### Acceptance Criteria
1. When a user selects a default configuration value in the front end, the same value is used by Fides for running DSR requests.

**Comment by saiatethyca** [comment]
This work is in review here - https://github.com/ethyca/fides/issues/1974.

**Comment by adamsachs** [comment]
reopening this since it's still technically in review
