### ISSUE TITLE
Make `prod` security env the default for our dev environment

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#2461]
### Is your feature request related to a specific problem?

With the completion of #2267 we should make the project default `prod` instead of `dev`  to make sure we're developing in the most secure environment that should also become our user's default.

**Comment by sanders41** [comment]
I tried running tests in the shell, `nox -s dev -- shell` and things seem frozen. Is there something I need to do? Is this where you were saying I need to log in first?

I'm frozen here:

<img width="876" alt="Screenshot 2023-02-15 at 4 27 21 PM" src="https://user-images.githubusercontent.com/25045024/219172003-a77c62f1-7ed3-428d-812e-ab59f41bb491.png">
