### ISSUE TITLE
Update Logos for shipped connectors

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2464]
### Bug Description

Update Logos for shipped connectors, currently we added a temporary logos.
1. Friendbuy
2. Friendbuy NextGen
3. Recharge

Please find the logos [here](https://www.figma.com/file/3eKQiu7gLA0x0mESz3utZL/Premium-company-logos-UI-kit-%E2%80%93-Untitled-UI-(Community)?node-id=0%3A1) 

#### Steps to Reproduce

Click on create connection in the new release.

### Expected behavior

All connectors have the right logos assigned.

**Comment by saiatethyca** [comment]
https://github.com/ethyca/fides/pull/2002/commits/7eeeb2b1e5712a22581e4cb2e9245be1a76333aa

**Comment by chriscalhoun1974** [comment]
![Image](https://user-images.githubusercontent.com/68459950/218629902-245367c1-edde-4594-84b9-18e7a037941f.png)
