### ISSUE TITLE
Add System nav jumps on entry

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fides#2477]
The side nav flashes when Add Systems is clicked.

https://www.loom.com/share/2e1a62fd2c724e4ea6e2c7facb668dda

The desired functionality is for the side nav to stay visible the entire time.

**Comment by rsilvery** [comment]
@seanpreston , I think this is for Experience team since they did the nav work and might be closer to it.

**Comment by allisonking** [comment]
I think this may be fixed if we move to a stable side nav (i.e. one that doesn't conditionally render)

Right now the side nav needs to make API calls to check if it renders at all, such as seeing if there are any systems registered. I believe if we don't do those checks anymore, then there won't be a lag
