### ISSUE TITLE
Add automated performance profiling

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#248]
To make sure that we keep a good user-experience, there are two performance metrics we should be looking at:

1. How long the CLI takes to respond (this is primarily dependent on package import time)
2. How long the server takes to handle requests

These should be included as part of our automated test suite/CI checks. We should set certain values as limits, such as "fidesctl imports in less than 1 second"

**Comment by ThomasLaPiana** [comment]
De-prioritizing this for now, sharper focus on the existing projects/QOL issues

**Comment by Kelsey-Ethyca** [comment]
closing all tickets older than a year as not planned
