### ISSUE TITLE
Privacy requests approved in quick succession error when not running worker

### ISSUE THREAD

**Issue by adamsachs** [ethyca/fides#2482]
### Bug Description

when not running a celery worker, i.e. with `celery.task_always_eager` set to `true`, and when requiring request approval, i.e. `execution.require_manual_request_approval` is set to `true`, if a user of the admin UI clicks "approve" on two privacy requests in quick succession, then one or both of the requests will almost always error out. 

note that with the latest admin UI on `main`, this is actually rather difficult to achieve, since when a worker isn't running, the "approval" call blocks the UI until the request has completed processing and therefore prevents a user from approving another request until the first request is complete. but we can trigger this behavior/bug by opening two browser tabs and approving two pending requests in quick succession.

even if the current UI on `main` makes this race condition less likely to occur in normal application use, it's ultimately a pretty fundamental bug in our non-worker environments that needs to be fixed.

specifically -- non-worker environments (`task_always_eager = true`) use a celery emulation that does _not_ prevent the celery task from running two requests concurrently, and we make assumptions in our code that requests will not be running concurrently in the same celery task. a given task has only one session across multiple privacy requests, since we assume that those multiple privacy requests will not be executed on the same task concurrently.

also, we hope to address the UI blocking behavior in https://github.com/ethyca/fides/issues/2466 - and at that point, the race condition will once again be easy to hit in normal operation within the admin UI.

#### Steps to Reproduce

1. switch `require_manual_request_approval = true` in your `fides.toml`
2. run `nox -s dev -- ui` or `nox -s 'fides_env(dev)'`
3. make sure you've got at least one connector setup, so that request execution doesn't complete instantaneously. `fides_env` should already have the connectors set up, `dev` will not.
4. submit two privacy requests, which will be pending, awaiting approval in the UI. e.g. 
```
curl --location --request POST 'http://0.0.0.0:8080/api/v1/privacy-request' \
--header 'Content-Type: application/json' \
--data-raw '[
    {
        "identity": {"email": "test@ethyca.com"},
        "policy_key": "default_access_policy"
    },{
        "identity": {"email": "test2@ethyca.com"},
        "policy_key": "default_access_policy"
    }
]'
```
5. open up two browser tabs to the admin UI to review privacy requests (`http://localhost:3000/privacy-requests`)
6. approve one privacy request in one tab, and quickly approve another privacy request in the other tab. 
7. look for errors in logs, look for at least one of the privacy requests to be in a non-complete state.

### Expected behavior

multiple privacy requests that have been approved in quick succession should not cause problems, even when running without a worker. 

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

- manual request approval enabled, i.e. `execution.require_manual_request_approval` set to `true`
- non-worker environment, i.e.  `celery.task_always_eager` set to `true`

### Additional context

- we introduced the shared session across a task, which is ultimately the cause for the problem here, in https://github.com/ethyca/fidesops/pull/944, and with good motivation. if we want to change this shared session behavior, we need to be careful not to introduce regressions in the number of connections we're opening up against our app db.
    - some preliminary sqlalchemy research does indicate to me that it's wouldn't necessarily be a bad pattern to create new sessions for each _invocation_ of a privacy request: https://docs.sqlalchemy.org/en/20/orm/session_basics.html#when-do-i-construct-a-session-when-do-i-commit-it-and-when-do-i-close-it, as long as we ensure we've got only a single `Engine` and `sessionmaker` for the lifecycle of the celery task. but this is just my initial understanding, it requires some more testing/input.
- the fix in https://github.com/ethyca/fides/pull/2015 was also adjacent to this problem, but it punted on resolving this core issue, instead just putting in some upstream changes in our endpoints to make the race condition less likely. what we've now uncovered is another way in normal application use to reliably get to the race condition, so we should likely now address the race condition head-on.

**Comment by Roger-Ethyca** [comment]
tested using the attached script
