### ISSUE TITLE
Update all RTK APIs to have the same base url

### ISSUE THREAD

**Issue by TheAndrewJackson** [ethyca/fides#2497]
## Description

Some of the RTK APIs are using different base urls. I think this is a remnant of the unified fides merge. Some are using the base url that is based off of `process.env.NEXT_PUBLIC_FIDESOPS_API`

https://github.com/ethyca/fides/blob/6f886898e518e3ed61d12e30b88426b8737f98b8/clients/admin-ui/src/constants.ts#L3-L7

while others are based off of `process.env.NEXT_PUBLIC_FIDESCTL_API`

https://github.com/ethyca/fides/blob/6f886898e518e3ed61d12e30b88426b8737f98b8/clients/admin-ui/src/features/taxonomy/taxonomy.slice.ts#L10

## Desired Changes

- Consolidate all of the `.env` files to have one API value for the backend. Use `NEXT_PUBLIC_FIDES_API` instead of the two pre unified fides variables

https://github.com/ethyca/fides/blob/6f886898e518e3ed61d12e30b88426b8737f98b8/clients/admin-ui/.env.development#L1-L3

- Update all RTK APIs to use the `BASE_URL` variable in `constant.ts`
- Update any other areas of the codebase that are directly referencing `process.env` and either update them to use `BASE_URL` where appropriate or create new constants for the `process.env` variables. This will allow us to easily keep track of what code is using any specific `process.env` variable.

**Comment by allisonking** [comment]
@TheAndrewJackson some background on how the next rewrites work https://github.com/ethyca/fides/pull/686#discussion_r880827842
