### ISSUE TITLE
Side nav pushes privacy request filters/controls off screen

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#2528]
### Bug Description

When you load the privacy requests view with the new nav, the controls are pushed off the screen to the right.

#### Steps to Reproduce

1. Load Fides
2. Go to /privacy-requests

You'll see the clear filters button pushed off the screen.

### Expected behavior
The view should fit on a full width of smaller screen.

### Screenshots
<img width="1440" alt="Screen Shot 2023-02-06 at 9 21 31 PM" src="https://user-images.githubusercontent.com/4807009/217131849-8dde3d65-17ec-4d69-8143-9e0bd373a110.png">
<img width="1440" alt="Screen Shot 2023-02-06 at 9 21 27 PM" src="https://user-images.githubusercontent.com/4807009/217131850-531f9e1b-6942-47af-a30b-5c3759cc2897.png">

Audit the whole app for this behavior

### Environment
This was happening on my smaller laptop screen.

**Comment by mfbrown** [comment]
Go all the way down to 1024x768 - if we need to hide UI elements - 
**Start by flexing the controls to another line** - We'll create a design ticket to look at other longer term options.

**Comment by Roger-Ethyca** [comment]
Verified with test_env
![Image](https://user-images.githubusercontent.com/115798183/220693167-cf934b46-3f45-4e5d-90e8-9e459c416112.png)
