### ISSUE TITLE
Firebase issues around erasure request and Firebase

### ISSUE THREAD

**Issue by nicolas-ethyca** [ethyca/fides#2547]
### Bug Description

Firebase having issues around erasure and complaining about masking. 

#### Steps to Reproduce

1. Configure Firebase
2. Perform erasure request
3. Default erasure policy configured 

### Expected behavior

It performs the delete and doesn't error out. 

### Screenshots

![image](https://user-images.githubusercontent.com/111306317/217846957-9493a354-8965-4555-bdf0-df1f8a7806a3.png)
### Environment

* Version: ????? - not showing version correct? 2.5.1-encoders
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by adamsachs** [comment]
are we able to get any of the server logs here? hopefully those would give us some more information - without additional information, it may be a bit hard to debug this further as we do basic erasure request testing against the connector as part of our automated tests.

**Comment by adamsachs** [comment]
logs didn't provide us with a whole lot of info, but one line is possibly telling here;

```
2023-02-09 15:35:28.501 [DEBUG] (query_config:_generate_masked_value:213): Generated the following masked val for field provider_data.0.email: 0088e308f4d5e0385d2fa49c76c1e7a0d920f3c8d5a5c1f4e001120585e1e19a
```

current thinking is that we're getting an error trying to update the email field with a hash, and firebase is rejecting it.

the reason we'd not be seeing this in automated tests is that our masking policy we use for tests does not target `user.contact.email` fields, which is probably a discrepancy between testing and deployed environments that we need to clean up generally...
