### ISSUE TITLE
Convert current access payload to a single HTML document and save it alongside the other formats

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#2549]
As a consumer, I want to view my personal data stored by a company as an HTML document so that I can more easily read the information.

- Convert the JSON to an HTML doc
- Use dataset names instead of keys
- Simple styling to make the table look nice
- Store the HTML file as well as the JSON file.
- The new link is included in both the email and SMS messages for access requests

**Comment by mfbrown** [comment]
**Refinement Notes**
- We have a formatter that currently can do JSON or CSV - we should add an HTML formatter before uploading the HTML.
- We are separating the logo requirement into a different requirement

**Comment by seanpreston** [comment]
How does the user opt-into storing results as HTML? Should there be a `Rule` on the `Policy` indicating that?

**Comment by mfbrown** [comment]
> How does the user opt-into storing results as HTML? Should there be a `Rule` on the `Policy` indicating that?

We want to just switch from the current JSON package to HTML by default for now.

**Comment by seanpreston** [comment]
Are we opinionated with how it's served? ie. should we create a HTML bundle that reads from the original JSON doc, or is it OK to directly inject the HTML into the JSON?
