### ISSUE TITLE
DynamoDB database connection support for `generate` and `annotate dataset`

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fides#256]
To ease the onboarding to Fides, Fidesctl should be able to support highly adopted databases for generating dataset annotations. This will allow adopters to be able to create dataset annotations quickly and directly from the database. 

This issue will include (non exclusive!):
* a database connector for dynamodb: [maybe Dynamo Query](https://github.com/altitudenetworks/dynamoquery) is a good candidate for this?
* updated documentation for setting up the connector
* tests for the DynamoDB connector

**Comment by Kelsey-Ethyca** [comment]
closing all tickets older than a year as not planned
