### ISSUE TITLE
MariaDB database connection support for `generate` and `annotate dataset`

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fides#257]
To ease the onboarding to Fides, Fidesctl should be able to support highly adopted databases for generating dataset annotations. This will allow adopters to be able to create dataset annotations quickly and directly from the database. 

This issue will include (non exclusive!):
* the [sqlalchemy-based connector](https://docs.sqlalchemy.org/en/14/dialects/mysql.html) support for fidesctl. It's possible that since we already support MySQL, MariaDB is implicitly supported already. This issue might just be confirming full support and exposing it in documentation. 
* updated documentation for setting up the connector
* tests for the MariaDB connector

**Comment by Kelsey-Ethyca** [comment]
closing all tickets older than a year as not planned
