### ISSUE TITLE
GCP cloud storage unstructured dataset connection support for `generate` and `annotate dataset`

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fides#259]
To ease the onboarding to Fides, Fidesctl should be able to support unstructured datasets in addition to structured datasets in generating fides annotations. This will allow adopters to be able to create dataset annotations quickly and directly from unstructured datasets. 

This issue is a spike for (final scope WIP):
* handling the connection to GCP storage bucket(s)
* determining file path(s) in bucket(s)
* creating annotation defaults for files in various paths (collection), down to the file-level (field).

**Comment by Kelsey-Ethyca** [comment]
closing all tickets older than a year as not planned
