### ISSUE TITLE
Add a footer to documentation pages that encourages contributions

### ISSUE THREAD

**Issue by PSalant726** [ethyca/fides#260]
In an effort to streamline the maintenance of fidesctl documentation, each page should include a footer that encourages readers to open a PR that corrects mistakes and/or updates outdated information. Ideally the footer dynamically links to the markdown file currently being viewed, in the fides repository.

**Comment by iamkelllly** [comment]
Also adding to scope here to have a link to the Github repo

**Comment by brentonmallen1** [comment]
When attempting to serve the docs, I did a `make clean` but I'm still getting the `FATAL:  password authentication failed for user "postgres"` error when attempting to build.  I thought that was fixed but I could have missed something.

**Comment by ThomasLaPiana** [comment]
not sure how to help with that one, we made some changes but it was awhile ago, and the make clean should've fixed it 🤔  are you testing this PR?

**Comment by brentonmallen1** [comment]
I was attempting to do so by doing a `make docs-serve` but ran into the issue
