### ISSUE TITLE
Logs for reprocessed requests are not being updated

### ISSUE THREAD

**Issue by saiatethyca** [ethyca/fides#2635]
### Bug Description

Logs for reprocessed requests are not being updated

#### Steps to Reproduce

1. Enter wrong credentials for a connector
2. Create a DSR request
3. Approve and see that it fails
4. Enter the right credentials and click re process.
5. Logs are not updated

### Expected behavior

Logs need to reflect the re processed order status

**Comment by Roger-Ethyca** [comment]
@Roger-Ethyca to look at
