### ISSUE TITLE
FE: Custom field selections binding issue on Taxonomy tabs

### ISSUE THREAD

**Issue by chriscalhoun1974** [ethyca/fides#2659]
Custom fields selection binding issue occurs when the CustomFieldSelector component is already mounted. Case situation when a user toggles between different accordions via Data Categories, Data Subjects, or Data Uses tab, the API endpoint `api/v1/plus/custom-metadata/custom-field/resource/system` payload is not binding to the CustomFieldSelector component correctly.

**Comment by chriscalhoun1974** [comment]
Here is the [PR](https://github.com/ethyca/fides/pull/2693/)

**Comment by Roger-Ethyca** [comment]
tested with dev
