### ISSUE TITLE
Create documentation to "Get your existing project started with Fides"

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fides#268]
Currently, our ["Quick Start" documentation](https://ethyca.github.io/fides/quickstart/overview/) delineates how to deploy fidesctl to a local or remote webserver. 

Adopters of this project will likely be adding Fides to an existing project, and thus will need some instruction on how to get started with their project. This documentation should outline:
| topic  | answers the question |
| ------------- | ------------- |
| depending on project type, where one might want to start annotating in their project| <li>i've got `<this type of app>`, where should i start annotating?</li><li>do i start with the database(s)? if so, which one? And how?</li><li>if i start with system, how do i know it's a system?</li>|
| how to think about starting annotations from scratch|<li>what does my software project do? </li><li>for what reasons do I collect PII for this project?</li><li>where does sensitive data travel to?</li>|
| who else to engage | <li>if i do this, does my entire team have to do this?</li><li>do I need company lawyer?</li><li>who should I get buy in from?</li><li>how do i get other teams to help or collaborate on annotating our project?</li>|

**Comment by Kelsey-Ethyca** [comment]
closing all tickets older than a year as not planned
