### ISSUE TITLE
Create documentation on "best practices for maintaining ongoing privacy with Fides"

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fides#269]
In our beta participant feedback session, it was found that developers were seeking more clarity and content on what it would take to maintain and manage Fides in their software projects on an ongoing basis.

This documentation will answer the questions:
* how do i maintain the project after we've already set up Fides for our software project
* what's the best way to get buy-in and operationalize process with the rest of the team to continue to use Fides
* how will I know if our Fides annotations are out-of-date?

**Comment by Kelsey-Ethyca** [comment]
closing all tickets older than a year as not planned
