### ISSUE TITLE
Create documentation for infrastructure-specific use cases of Fidesctl

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fides#270]
It was found in beta testing participants that having ready documentation about known high-level architectural use cases can assist in broader understanding and adoption of fidesctl organizations' software projects.

Working title: "Where Fides fits in your organization" 

A few ideas for diagrams or infrastructures it may be nice to outline for prospective adopters:
* large software companies with federated business units 
* micro-sized company with SPA and single db (and probably a lot of 3rd party SaaS apps) 
* small-sized startup with mobile app, web app, few dbs and SaaS products, SaaS data warehouse
* mid-sized scale-up with few-to-many application dbs, few data warehouses with ETL/replication processes, and 3rd party SaaS products 

This documentation should broadly answer the question:
* will fidesctl work with my data infrastructure?
* where would fidesctl live in my infrastructure?
* will fidesctl meet my organization's data use case, generally? 

where in documentation IA:
```
Fides 
  |--> Introduction to Fides  >
  |--> **Getting Started with Fides**  >
          |--> How to get started with your pre-existing project (working title, #268 )
          |--> **Where Fides fits in your organization**
  |--> Quick Start >
  |--> Installation (Deployment) >
  |--> Tutorial >
  |--> CI/CD references
  |--> CLI
  |--> API
  |--> Fides language >
  |--> Development >
  |--> Community >
  |--> About Ethyca
  |--> License
```

**Comment by Kelsey-Ethyca** [comment]
closing all tickets older than a year as not planned
