### ISSUE TITLE
Removing All Connectors Prevents Reviewing Access Requests

### ISSUE THREAD

**Issue by RobertKeyser** [ethyca/fides#2719]
### Bug Description

When a user removes all of the connectors in a Fides deployment, they can no longer access the `/privacy-requests` route in the UI, even if there were previously created privacy requests.

#### Steps to Reproduce

1. Submit privacy request
2. Remove all connectors
3. Try browsing back to the `/privacy-requests` page.

### Expected behavior

Even without any integrations, a Fides admin should be able to review privacy requests.

### Environment

* Version: 2.7.0

### Additional context

This is probably low priority due to the unlikely workflow of removing all connectors.

**Comment by Roger-Ethyca** [comment]
#2724 will be addressing this

**Comment by NevilleS** [comment]
Ah - since #2762 is merged, this is (probably?) fixed. Popping over to @Roger-Ethyca to double-check!

**Comment by Roger-Ethyca** [comment]
verified on test_env
![Screenshot 2023-03-13 at 5 22 03 PM](https://user-images.githubusercontent.com/115798183/224835468-47f03a1c-8ee7-41c1-830c-51e35d32b2a1.png)
![Screenshot 2023-03-13 at 5 22 11 PM](https://user-images.githubusercontent.com/115798183/224835470-20102f97-a334-4ad9-a1b6-b0749622ba83.png)

**Comment by Roger-Ethyca** [comment]
moving to done.
