### ISSUE TITLE
Import resources (categories, qualifiers, subjects, uses) from external providers

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fides#272]
There are organizations that have already adopted DCS and other GRC tools that the non-technical and technical teams can use to manage data categories for PII classification.

Fidesctl should interoperate with these tools and be able to:
* import fidesctl resources (data categories, data uses, data subjects, and data qualifiers) from external DCS/GRC tools
* reconcile incoming resources with fides default resources (add, update, delete default resources)
* use newly reconciled resources to create fides annotations
* export data categories back to the tool of origin

This issue is a research spike for assessing feasibility of integration to import data from other tools (only).

**Comment by Kelsey-Ethyca** [comment]
closing all tickets older than a year as not planned
