### ISSUE TITLE
Policy Webhooks - Additional Fields

### ISSUE THREAD

**Issue by RobertKeyser** [ethyca/fides#2725]
### Is your feature request related to a specific problem?

Pre/post execution webhooks could be made more usable by including additional fields, such as status (for post webhooks) and DSR type (e.g. access vs erasure)

### Describe the solution you'd like

The following fields added:
- Status (e.g. error, complete, etc)
- Type (access or erasure)

### Additional context

The use case here is to be able to use post-execution webhooks to send logs/events/metrics to a logging platform.

**Comment by rsilvery** [comment]
@RobertKeyser just to be clear, are we only thinking about in the YAML files or also the UI?

**Comment by RobertKeyser** [comment]
> @RobertKeyser just to be clear, are we only thinking about in the YAML files or also the UI?

I was mostly thinking just the YAML, do we have a UI for the pre/post execution webhooks yet?

**Comment by rsilvery** [comment]
No but it's under consideration, possibly, as I think about how to incorporate more configuration options into the UI

**Comment by RobertKeyser** [comment]
I think we should just include it in the payload of a webhook request for all webhooks.
