### ISSUE TITLE
Export resources (categories, qualifiers, subjects, uses) and system/dataset declarations to external providers

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fides#273]
There are organizations that have already adopted DCS and other GRC tools that the non-technical and technical teams can use to manage data categories for PII classification.

Fidesctl should interoperate with these tools and be able to:
* import fidesctl resources (data categories, data uses, data subjects, and data qualifiers) from external DCS/GRC tools
* reconcile incoming resources with fides default resources (add, update, delete default resources)
* use newly reconciled resources to create fides annotations
* export data categories back to the tool of origin

This issue is a research spike for assessing feasibility of integration to export:
* fidesctl metadata to other tools, including system and dataset declarations
* the post-reconciled resources, and default fides resources (categories, qualifiers, subjects, uses)

and ensure that the exported data is viewable and compatible in the destination tool

**Comment by ThomasLaPiana** [comment]
@iamkelllly is this still relevant?

**Comment by Kelsey-Ethyca** [comment]
closing all tickets older than a year as not planned
