### ISSUE TITLE
Autogenerated config docs aren't showing up in the docs site

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#2730]
### Docs Update Description

 This was working locally and I've confirmed it is getting built in the docs publishing step, need to troubleshoot why it isn't showing up as expected (maybe a path issue?)

**Comment by Roger-Ethyca** [comment]
![Image](https://user-images.githubusercontent.com/115798183/225095200-ea1258b9-cdb9-4f82-9239-7977f5132cef.png)

**Comment by ThomasLaPiana** [comment]
@Roger-Ethyca if you scroll to the bottom of the page, `Configuration File Reference` is the section I was referring to

When I run the docs locally there is a nice populated file there

But in the production build/serving it doesn't show up. It must be a path issue, since you can still download the file directly from the docs site
