### ISSUE TITLE
Mongodb database connection support for `generate` and `annotate dataset`

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fides#274]
To ease the onboarding to Fides, Fidesctl should be able to support highly adopted databases for generating dataset annotations. This will allow adopters to be able to create dataset annotations quickly and directly from the database. 

This issue will include (non exclusive!):
* using the [pymongo library](https://pypi.org/project/pymongo/) to create a database connection directly to Mongodb, it's apparently the ["recommended way to work with Mongodb for Python"](https://pymongo.readthedocs.io/en/stable/) 🤷 
* updated documentation for setting up the connector
* tests for the mongodb connector

**Comment by iamkelllly** [comment]
will rely heavily on #261, and vice versa

**Comment by Kelsey-Ethyca** [comment]
closing all tickets older than a year as not planned
