### ISSUE TITLE
Update UI to use `total_scopes`

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#2743]
### Is your feature request related to a specific problem?

After https://github.com/ethyca/fides/pull/2741 goes in, we'll want to have the UI check for `total_scopes` as opposed to just `scopes` since the user will have most of their scopes assigned via roles.

### Describe the solution you'd like

In the `Restrict` component, and possibly other places that look for `scope`, use `total_scopes` instead

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

This needs to be done or else the UI will probably always show users as not having any scopes if they've only been assigned scopes via roles.

**Comment by Roger-Ethyca** [comment]
everything appears to be working, moving to done
