### ISSUE TITLE
Add a system button takes the user to a blank page. 

### ISSUE THREAD

**Issue by Roger-Ethyca** [ethyca/fides#2760]
Add a system button takes the user to a blank page. 

_A description of what the bug is._

#### Steps to Reproduce

1. Log in to Fides plus with root_user
2. From the home screen click Add system
3. From the next page click Add a system 

User is taken to page to manually add systems 

Right now the user is taken to a black page. 

### Screenshots

![Screenshot 2023-03-06 at 4 11 31 PM](https://user-images.githubusercontent.com/115798183/223232289-8e128309-8aae-4a27-ba0f-bc9709e15615.png)

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by mfbrown** [comment]
@Roger-Ethyca I couldn't reproduce this on the nightly build or locally. Is it Fides or Fidesplus?

Loom of both: https://www.loom.com/share/67ea4e52df844c3c97d5234994388823

**Comment by Kelsey-Ethyca** [comment]
Tested and moving to Done
