### ISSUE TITLE
Custom Fields Columns Not Populating on Datamap Route

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fides#2768]
### Bug Description

When exporting my datamap via the UI, custom fields are not visible.

This appears to be due to the column missing from the API response, where columns are listed as the first indexed item.

#### Steps to Reproduce

1. `nox -s dev`
1. `fides user login ...`
2. `fides push demo_resources/`
3. Add some custom field data via the database
4. `GET` datamap endpoint and see the results
5. Verify the field is returned but no column information is

### Expected behavior

Both the column and field information should be returned

### Screenshots

n/a

### Environment

* Version: 2.8.0
* OS: Darwin
* Python Version: 3.9
* Docker Version:

### Additional context

Discovered while doing extra testing with `fidesplus`

**Comment by SteveDMurphy** [comment]
@Kelsey-Ethyca also investigate why the feature flags unset after viewing the datamap in fidesplus

**Comment by Roger-Ethyca** [comment]
![Image](https://user-images.githubusercontent.com/115798183/225158021-c8fb5827-c3ee-4429-82cb-8dd19f5ff3ea.png)
