### ISSUE TITLE
Refactor `annotate dataset` to use the api

### ISSUE THREAD

**Issue by brentonmallen1** [ethyca/fides#277]
Capturing for future work.  I think there's a desire to refactor the `annotate dataset` implementation to take advantage of the API  in lieu of reproducing some functionality.

As part of this effort, we may want to move the `convert_categories_to_nested_dict` function out of `fidesctl.core.visualize.py` and into `fideslang.parse`.  This would put the functionality in a place that makes more sense and we can also add the following functionality (that depends on `convert_categories_to_nested_dict`) which gives us a means to extract all leaf nodes in a resource hierarchy:

```
from fidesctl.core import visualize as _vis
from fideslang import default_taxonomy as _dt

data_category_hierarchy = _vis.convert_categories_to_nested_dict(_dt.DEFAULT_TAXONOMY.dict()['data_category'])

# we want to traverse this hierarchy and when we get to a leaf node, output a string of the path to said node
def get_category_leafs(hierarchy: dict, parent_key:str = '', sep:str = '_'):
    items = []
    for k, v in d.items():
        new_key = parent_key + sep + k if parent_key else k
        if v:
            items.extend(get_category_leafs(v, new_key, sep=sep).items())
        else:
            items.append((new_key, k))
    return dict(items)

list(get_category_leafs(data_category_hierarchy).keys())
```

**Comment by ThomasLaPiana** [comment]
this ended up getting done here -> https://github.com/ethyca/fides/commit/f43466c4bc35f2ac1e38c87deb3f86989d5678cb
