### ISSUE TITLE
Fides pull is not generating system file if not present

### ISSUE THREAD

**Issue by nicolas-ethyca** [ethyca/fides#2772]
### Bug Description

When configuring items in the UI and trying to initialize a fresh repo, fides pull is not working as expected.

#### Steps to Reproduce

1. Create systems and datasets in UI
2. Run fides pull
3. See that systems.yml is not created (note - I happen to have datasets in my repo already, but would see if these get generated too)

### Expected behavior

systems.yml gets created (and synchronizes with cloud deployment)

### Screenshots

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/111306317/223747621-1dc6a60a-d699-49ac-8b58-e0ed4ef1827c.png">

### Environment

* Version: 2.7.2
* OS: OSX Intel
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by ThomasLaPiana** [comment]
@nicolas-ethyca I think you're missing the `-a` option

![image](https://user-images.githubusercontent.com/5105354/223916721-4820b7fe-ac92-4432-9ddf-20b3999de357.png)

`fides pull -a new_objects.yml` will _also_ pull missing resources, and put all of them into `new_objects.yml` in this case
