### ISSUE TITLE
Bug - System keys are case sensitive leading to duplicate system entries

### ISSUE THREAD

**Issue by nicolas-ethyca** [ethyca/fides#2774]
### Bug Description

_A description of what the bug is._

#### Steps to Reproduce

1. Create a system in the UI - key: `hubspot`
2. Create a system in the systems.yaml but accidently change the key to have the first letter uppercase `Hubspot`
3. Push the yaml (I did this via fides evaluate)

### Expected behavior

One of two things:
* Throw a warning that `fides_key` is case-sensitive which may be unexpected, e.g. "WARNING: detected two systems with similar keys (`hubspot` and `Hubspot`). Did you mean to use the same key for both?" (or something actually understandable)
* Make `fides_key` case-insensitive so that `fides_key: Hubspot` and `fides_key: hubspot` edit the same resource

### Screenshots

![image](https://user-images.githubusercontent.com/111306317/223754438-c757b9a2-d19f-49a6-a652-77e64c5fc925.png)

### Environment

* Version: 2.7.2 
* OS: OSX 
### Additional context

_Add any other context about the problem here._

**Comment by nicolas-ethyca** [comment]
yes to case insensitivity, yes to the CLI vs UI.

**Comment by NevilleS** [comment]
OK, edit the description/tile slightly. Does it match your expectation now?

**Comment by Kelsey-Ethyca** [comment]
This will be fixed when we start generating the keys, not allowing for manual entry
