### ISSUE TITLE
Automated Migration Plan: Scopes -> Roles

### ISSUE THREAD

**Issue by pattisdr** [ethyca/fides#2776]
### Is your feature request related to a specific problem?

Need a better migration plan for Access Controls.  Users will abruptly lose their scopes UI, while they still have their existing scopes. We're moving to Role Based Access Controls and need a good plan to transition users. 

### Describe the solution you'd like

Decision from 3/9/22 meeting with @NevilleS , @seanpreston , @mfbrown , @pattisdr , @rsilvery

Decided we would add a data migration to automatically move all users to a `viewer` role and add a warning to contact their Root user to have their role assigned.

- Existing scopes should be removed from the user permissions table (leave column in place for now)
- Existing scopes should be cleared from the associated client table (only those clients associated with users). 
- Users will need to log out and log back in. 

A followup in a future sprint will deprecate users being assigned scopes directly and get rid of the userpermission.scopes column. https://github.com/ethyca/fides/issues/2696

Some customers will be contacted directly 

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by rsilvery** [comment]
Decision from 3/9/22 meeting with @NevilleS , @seanpreston , @mfbrown , @pattisdr , @rsilvery: will move all users to `viewer` role and add a warning to contact Root user to have a role assigned. Will work directly with Momentive, SnackPass, and Papermart to make this easy.
