### ISSUE TITLE
testid request 

### ISSUE THREAD

**Issue by Roger-Ethyca** [ethyca/fides#2783]
### Is your feature request related to a specific problem?

testid requested 

### Describe the solution you'd like

a testid for automation on the check all box after a system scan 

![Screenshot 2023-03-09 at 4 46 12 PM](https://user-images.githubusercontent.com/115798183/224167567-8169670b-7dd3-4188-899f-0912d26b6e37.png)

**Comment by Kelsey-Ethyca** [comment]
QA'd and moving to Done
![Image](https://user-images.githubusercontent.com/101993653/226800074-9af41035-3fe2-44d1-8c2c-8b02d5d0174c.png)
