### ISSUE TITLE
After saving edits to a system in the "View systems" page, warning modal about unsaved changes still appears

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#2788]
### Bug Description

When editing a system via the UI, the "Unsaved changes" modal will popup even after saving, which is unexpected. However, when you reload / refresh, the changes are definitely saved, so this modal is just triggering incorrectly.

#### Steps to Reproduce

1. Run `nox -s "fides_env(test)"
2. Navigate to "Data map" > "View systems", loads the default "System information" tab
3. Edit any system
4. Make a change to the system, hit "Save"
5. Navigate to the "Data use" tab
6. See an unexpected popup warning:
![image](https://user-images.githubusercontent.com/1834295/224346027-919e5d4d-534d-46fb-a097-70a8c9e2d041.png)

### Expected behavior

Since I've already saved my changes, the form shouldn't be considered "dirty" and the warning isn't needed.

### Environment

* Version: 2.8.1
* OS: Mac OSX
* Python Version: 3.9.6
* Docker Version: Docker version 20.10.22, build 3a2c30b

### Additional Context

Please update the `systems.cy.ts` Cypress tests to remove the unnecessary `cy.getByTestId("continue-btn").click()` call to dismiss this popup once it's fixed 👍

**Comment by rsilvery** [comment]
Further testing shows it's not related to whether update are made. Any time you click on the `data use` tab this pop-up appears: https://www.loom.com/share/5ecaf5ee58114e0abf74eb7570f0064e

**Comment by Kelsey-Ethyca** [comment]
QA'd and moving to done 🌵
