### ISSUE TITLE
Update `apply` to use the upsert endpoint

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#279]
### Discussed in https://github.com/ethyca/fides/discussions/246

<div type='discussions-op-text'>

<sup>Originally posted by **ThomasLaPiana** November 23, 2021</sup>
The `apply` logic is currently complex due to the fact that it first checks the database for the object's existence and then does an update or create accordingly. If we switch over to using _only_ upserts, this would greatly simplify the logic.

The downside here is that we currently have pretty robust logging around when something is updated vs. created and what exactly changed (i.e. the `--diff` flag). I would argue that this functionality exists inherently in version control systems, but maybe that inclusion in the `apply` logic is very helpful.

Would love to hear more thoughts on this

fyi @ethyca/fides-control </div>

**Comment by PSalant726** [comment]
We have [an `upsert_resources` function](https://github.com/ethyca/fides/blob/b23ad7657598de1a928892bc855c90794da1a016/fidesctl/src/fidesapi/crud.py#L109) in the CRUD library, but no endpoint wrapping it. This work would have to include the creation of that endpoint. We should also ensure that `upsert_resources` always returns a `Dict`, like it's companion DAL functions.

IMO, `create_resource` and `update_resource` should **not** be removed. We should still support these features even if we don't use them internally.

**Comment by ThomasLaPiana** [comment]
> We have [an `upsert_resources` function](https://github.com/ethyca/fides/blob/b23ad7657598de1a928892bc855c90794da1a016/fidesctl/src/fidesapi/crud.py#L109) in the CRUD library, but no endpoint wrapping it. This work would have to include the creation of that endpoint. We should also ensure that `upsert_resources` always returns a `Dict`, like it's companion DAL functions. Lastly, the information logged currently can/should be preserved using the Postgres `xmax` built-in, but it's not clear to me if/how that's supported in sqlalchemy.
> 
> IMO, `create_resource` and `update_resource` should **not** be removed. We should still support these features even if we don't use them internally.

Can you think of a use-case for keeping the create/update despite having the upsert? 

I agree with all of the other points, good refinement

**Comment by PSalant726** [comment]
> Can you think of a use-case for keeping the create/update despite having the upsert?

Keeping them would support these features for anyone who wants to make programmatic API calls.

It's a common misconception that upsert can serve as a drop-in replacement for insert and update. This happens to be true for our internal use case, but other users might _want_ to see a query fail if they attempt to insert something that violates a database constraint. It's my opinion that since we have these endpoints implemented already, there's no harm in allowing them to continue to exist + expand the API feature set.

**Comment by ThomasLaPiana** [comment]
I don't really like the idea of dead code living there "because we already wrote it", as dead code can fester and rot. If we don't have a clear use-case for it, I don't think it needs to stay. We have version control and we can leverage that to copy/paste the old implementation. If a user wants to know if that API call would fail, they can also just use a `get` to see if that resource already exists, couldn't they?

If this was a major breaking change for our users, I'd agree with you completely. However the API is internal-facing and this is an easy change to make at this point
