### ISSUE TITLE
UX cleanups for Role Assignment UI

### ISSUE THREAD

**Issue by eastandwestwind** [ethyca/fides#2824]
2 remaining items for UX clean up:

### 1. Fix Role Description Drawer
- [x] Update Role Description drawer to be higher up in the page. Currently this is within the "Permissions" tab due to the fact that I'm unsure how to dynamically display the drawer if it's in a parent component. It should only display with the user is on the "Permissions" tab. 

"So on scrolling, the “help panel” for want of a better term should be fixed height, pinned to the top and bottom of the main window, below the main header and nav. Scrolling should be possible within the “help panel” so that we have the flexibility to add more items to the help panel. Otherwise, if  we have 10 help items for example, we would be scrolling the whole page to view them all rather then what is intended as a side by side panel that can be accessed while determining what role to assign. The slide-out that was built for the data map graph and table view used the chakra drawer component to achieve a similar result." -- Simon

There's a possibility we can use Chakra's drawer component so that the Role description UI sticks to the side of the page, like this- https://chakra-ui.com/docs/components/drawer

Desired:
<img width="849" alt="Screenshot 2023-03-10 at 5 09 17 PM" src="https://user-images.githubusercontent.com/7697292/224370502-532af9f2-637e-4d37-b67f-964d4831b002.png">

Current:
<img width="1403" alt="Screenshot 2023-03-10 at 5 09 06 PM" src="https://user-images.githubusercontent.com/7697292/224370770-33798826-9ab7-49c1-a5aa-36915244c11c.png">

### 2. Fix Trash Icon
- [ ] adjust trash can icon throughout to match mocks

Expected:
<img width="611" alt="Screenshot 2023-03-09 at 2 35 50 PM" src="https://user-images.githubusercontent.com/7697292/224039840-e9374879-e229-448d-b915-0a9a65ca1176.png">
Current:
<img width="513" alt="Screenshot 2023-03-09 at 12 33 46 PM" src="https://user-images.githubusercontent.com/7697292/224039847-8fc10b58-7601-45d0-954b-06b50c69f2b6.png">

**Comment by rsilvery** [comment]
Can we add the garbage can icon one to this ticket?

**Comment by rsilvery** [comment]
Could we add a task to show assigned systems in the user table?


![Image](https://user-images.githubusercontent.com/8682444/225638059-8af4e6cc-1c05-4aa6-9730-429f0bd38fa8.png)

**Comment by rsilvery** [comment]
And we need to remove the ability to assign users to Approvers. Unless they're also Viewers, they can't get to Systems:


![Image](https://user-images.githubusercontent.com/8682444/225643938-02d39c5b-79d6-4208-9ab3-917ceb6c6264.png)

**Comment by rsilvery** [comment]
Need to change things so that you all users can view user management UI and change their own password but not change permissions. @eastandwestwind  let's discuss when you have time tomorrow or earlier next week. It's not urgent nor should it block this release.

**Comment by eastandwestwind** [comment]
Role Description drawer updates are complete:

<img width="1322" alt="Screenshot 2023-03-17 at 8 46 30 PM" src="https://user-images.githubusercontent.com/7697292/226012991-c95ccaa2-70a7-46fa-a00a-dfae09fee7fd.png">

**Comment by rsilvery** [comment]
@eastandwestwind we need to mark first and last name as required here: 

![Image](https://user-images.githubusercontent.com/8682444/226381893-5eb8bb07-9dd6-457d-a96c-9e6ccc63da1b.png)

**Comment by eastandwestwind** [comment]
Got trash can icons matching mocks:

<img width="712" alt="Screenshot 2023-03-20 at 4 10 38 PM" src="https://user-images.githubusercontent.com/7697292/226383496-a22dffc0-1cd0-42a7-9f4c-1fb2e512943d.png">
<img width="618" alt="Screenshot 2023-03-20 at 4 10 29 PM" src="https://user-images.githubusercontent.com/7697292/226383500-830f6525-06f5-4d5f-956e-badbc8bbaf1c.png">

**Comment by eastandwestwind** [comment]
First and last name are now required @rsilvery :

<img width="719" alt="Screenshot 2023-03-20 at 4 13 42 PM" src="https://user-images.githubusercontent.com/7697292/226384465-882c9841-d86c-4268-be4f-1b759a170df0.png">

<img width="729" alt="Screenshot 2023-03-20 at 4 14 25 PM" src="https://user-images.githubusercontent.com/7697292/226384726-164602e7-a955-422e-89ec-39d011466cbb.png">

**Comment by rsilvery** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UX fixes for Access Controls](https://trello.com/c/jB5FxfNz/2-ux-fixes-for-access-controls)

**Comment by Roger-Ethyca** [comment]
@eastandwestwind I'm not seeing the required for first and last name 


![Image](https://user-images.githubusercontent.com/115798183/227634949-35346209-4bae-41ab-8b2b-62bd22014d50.png)

**Comment by Roger-Ethyca** [comment]
closing
