### ISSUE TITLE
Allow access to certain FE elements if user is a data steward

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#2828]
### Is your feature request related to a specific problem?

There are some systems that should not be editable _unless_ the user is a data steward for that system. This ticket is to find system managers from the backend and make the frontend render the UI accordingly.

### Describe the solution you'd like

_A description of what you want to happen._

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by pattisdr** [comment]
On the backend, you might call `api/v1/user/user_id/system-manager/` to get a list of systems the user manages.
- Consider adding a new endpoint `GET /api/v1/oauth/system-manager` similar to `GET /api/v1/oauth/role` (which returns all possible roles).  This new endpoint will return the scopes that we give as a one-off to any system manager.

The combination of those two endpoints would let you see if a user could perform a specific action on a specific system.
