### ISSUE TITLE
FE Spike for Consent Modeling

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#2840]
**Notes**
- This will be a paid feature
- Backend design doc: https://ethyca.atlassian.net/wiki/spaces/EN/pages/2636382212/2023-03-10+Backend+Design+Enhancing+Consent+Management+Capabilities+and+Consent+Reporting?focusedCommentId=2644705297#comment-2644705297

**Comment by allisonking** [comment]
I'll work on a design doc for this today/tomorrow

**Comment by allisonking** [comment]
in progress design doc: https://ethyca.atlassian.net/wiki/spaces/EN/pages/2649096193/2023-03-21+Frontend+Design+Privacy+Notices

**Comment by allisonking** [comment]
Going to mark this one as done—the broken out tickets are listed in the rightmost column of the design doc, and are also under the "Consent Modeling" epic
