### ISSUE TITLE
Custom Fields in the map don't align with values - when adding fields at different times

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#2850]
1. Start Fides Plus
2. Create 3 custom fields
3. Add values to fields on 2 systems
4. Check the data map - the columns should align with the right values
5. Go back to a system
6. Add a 4th field
7. Assign a value
8. Go back to the map - the columns and values won't line up.

**Expectation**
At all times, the values of the custom fields columns should match the field name in the column header
![Screenshot 2023-03-16 at 11 30 47 AM](https://user-images.githubusercontent.com/4807009/225678022-9a218442-9482-4b25-a39f-b03fdea9ec74.png)

**Comment by Kelsey-Ethyca** [comment]
QA'd and moving to Done

![Image](https://user-images.githubusercontent.com/101993653/226779740-b530c994-017a-4eac-ab7d-9917ecff1ece.png)
![Image](https://user-images.githubusercontent.com/101993653/226779745-c91e678e-2399-454d-b8c3-ba1830c752d5.png)
