### ISSUE TITLE
fides db reset -y fails due to dependency

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fides#2852]
### Bug Description

When testing `2.8.3` I stumbled across a potential bug and wanted to post it quick, it may just be a me problem due to some other testing I have been doing

```
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table fidesuser because other objects depend on it
DETAIL:  constraint systemmanager_user_id_fkey on table systemmanager depends on table fidesuser
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

Will follow up back here tonight with repro steps (or close)

#### Steps to Reproduce

1. _Do this..._
1. _Then This..._

### Expected behavior

_A description of what you expected to happen._

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by rsilvery** [comment]
@Roger-Ethyca , @SteveDMurphy  can we close this?

**Comment by SteveDMurphy** [comment]
Yep! Old issue either resolved or never needed 👍🏽
