### ISSUE TITLE
Replace hamburger menu on user management table with delete trash icon

### ISSUE THREAD

**Issue by eastandwestwind** [ethyca/fides#2860]
### Is your feature request related to a specific problem?

Replace this:
<img width="485" alt="Screenshot 2023-03-17 at 3 37 54 PM" src="https://user-images.githubusercontent.com/7697292/225935968-f57ce74d-eab4-4309-a964-edcbab136afe.png">

### Describe the solution you'd like

_A description of what you want to happen._

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by eastandwestwind** [comment]
This is blocked because we're waiting for @rsilvery to touch base with @renderbits on best approach. We may need to add ability to change password on the user management table, which would mean possibly keeping the hamburger menu around.

**Comment by rsilvery** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UX fixes for Access Controls](https://trello.com/c/jB5FxfNz/2-ux-fixes-for-access-controls)

**Comment by rsilvery** [comment]
@eastandwestwind  updated ticket for #700 to unblock you here.

**Comment by rsilvery** [comment]
No - sorry. I meant this ticket: https://github.com/ethyca/fidesplus/issues/700

**Comment by eastandwestwind** [comment]
@rsilvery do we want a confirmation modal upon trash icon click, just like we do within the user profile:



![Image](https://user-images.githubusercontent.com/7697292/228242248-9edceaa1-5a50-484c-8c80-1cc59d97ff2c.png)

**Comment by rsilvery** [comment]
Yes, I think so. But we don't need to have them enter any info - just confirm

**Comment by rsilvery** [comment]
@eastandwestwind  are we still blocked here?

**Comment by eastandwestwind** [comment]
Nope I'm picking this up now

**Comment by Roger-Ethyca** [comment]
verified all three on test env
