### ISSUE TITLE
Could we add a task to show assigned systems in the user table?

### ISSUE THREAD

**Issue by eastandwestwind** [ethyca/fides#2861]
Could we add a task to show assigned systems in the user table?

![Image](https://user-images.githubusercontent.com/8682444/225638059-8af4e6cc-1c05-4aa6-9730-429f0bd38fa8.png)

_Originally posted by @rsilvery in https://github.com/ethyca/fides/issues/2824#issuecomment-1472003482_

**Comment by eastandwestwind** [comment]
@renderbits / @rsilvery - I'm going to need some UX input on this one, since we could possibly have many assigned systems for 1 user. This number could be 100 for large clients. Given that info, how do we want to handle displaying this within the table?

**Comment by rsilvery** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UX fixes for Access Controls](https://trello.com/c/jB5FxfNz/2-ux-fixes-for-access-controls)

**Comment by rsilvery** [comment]
Oh sorry - I think my Trello spam screwed you up. Let me ping Simon on this one and see if he has idea.

**Comment by rsilvery** [comment]
Determined we'd show the number of assigned systems here: https://ethyca.slack.com/archives/C0114BAK160/p1679489454645209?thread_ts=1679444799.251679&cid=C0114BAK160

**Comment by Roger-Ethyca** [comment]
@eastandwestwind i'm not seeing the new column 
![Screenshot 2023-03-29 at 2 33 52 PM](https://user-images.githubusercontent.com/115798183/228635207-1290df82-5794-49f7-8987-35fc264c27ca.png)
![Screenshot 2023-03-29 at 2 34 07 PM](https://user-images.githubusercontent.com/115798183/228635415-b68b51d2-ab9c-49e5-bb0c-eab3395025e6.png)

**Comment by Roger-Ethyca** [comment]
change picked up and tested. moving to done 

![Image](https://user-images.githubusercontent.com/115798183/228646754-6166a847-9fd5-4046-977b-f226309111ed.png)
