### ISSUE TITLE
Update the owner role check in `PermissionsForm` to be scope based

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#2896]
### Is your feature request related to a specific problem?

Now that https://github.com/ethyca/fides/pull/2888 has created a scope `USER_PERMISSION_ASSIGN_OWNERS `, we should use that scope instead of doing [our workaround role check](https://github.com/ethyca/fides/blob/main/clients/admin-ui/src/features/user-management/PermissionsForm.tsx/#L68).

### Describe the solution you'd like

Replace the workaround with a scope check

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

We try to avoid using roles in the FE, but did so in this case since the backend didn't have the scope yet. The current solution would probably work for a good while, but could start to cause problems if we ever added a new role that had `USER_PERMISSION_ASSIGN_OWNERS`.

**Comment by Roger-Ethyca** [comment]
verified with test env and added a automation test
