### ISSUE TITLE
[Frontend] Alert Before System Manager Downgraded to Approver

### ISSUE THREAD

**Issue by pattisdr** [ethyca/fides#2898]
### Is your feature request related to a specific problem?

https://github.com/ethyca/fides/pull/2891#discussion_r1144015038

New backend work removes user as system manager if their role is downgrade to Approver behind the scenes.  This behavior should be made obvious to the frontend user.

### Describe the solution you'd like

Something like detecting if a user is a system manager and we're about to make them an approver on the frontend.  Perhaps add a confirmation modal that they are about to be removed as system manager. (There may be better frontend flows, this is just anidea)

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by rsilvery** [comment]
Let's say: "Switching to an approver role will remove all assigned systems. Do you wish to proceed?"

**Comment by rsilvery** [comment]
@allisonking can you help with this?

**Comment by allisonking** [comment]
oh, I think [I might have caught this too](https://github.com/ethyca/fides/pull/2953) and fixed it. let me double check

**Comment by allisonking** [comment]
yup yup, this looks fixed by https://github.com/ethyca/fides/pull/2953

**Comment by pattisdr** [comment]
awesome 🔥

**Comment by Roger-Ethyca** [comment]
wahoo! moving to done
