### ISSUE TITLE
String Displayed to a Data Subject is Strange

### ISSUE THREAD

**Issue by shawnplusplus** [ethyca/fides#2911]
### Bug Description

_A description of what the bug is._
The message displayed to a data subject in the modal after DSR submission is strange.
#### Steps to Reproduce

1. Submit a DSR
2. Read the modal that is displayed to the data subject. 

### Expected behavior

The message displayed should be generic enough that the data subject is confident their request was submitted. 
### Screenshots

![image_720](https://user-images.githubusercontent.com/46225246/227555526-edf1d309-f0a4-4e12-926d-d8668b430349.png)

### Environment

* Version: 2.9
* OS: All
* Python Version: All
* Docker Version: All

**Comment by shawnplusplus** [comment]
https://github.com/ethyca/fides/blob/9082c948c284d04fe77939731083aa8260525114/clients/privacy-center/components/modals/privacy-request-modal/RequestSubmitted.tsx#L42

**Comment by RobertKeyser** [comment]
> https://github.com/ethyca/fides/blob/9082c948c284d04fe77939731083aa8260525114/clients/privacy-center/components/modals/privacy-request-modal/RequestSubmitted.tsx#L42

We could just remove the policy_key part, so it would read as "Thanks for your request" instead.
