### ISSUE TITLE
Genereated Datasets Always Show Unknown State

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fides#2923]
### Bug Description

Unless a `classify` response is returned, the dataset state will always be `unknown`

This is not value-added and could lead to confusion for end users. A tooltip does exist, however it doesn't feel like enough based on feedback.

#### Steps to Reproduce

1. Generate a dataset via the `fides` UI
1. See the `Unknown` state
2. If using `fidesplus`, you can even use the [PUT](http://localhost:8080/docs#/Plus/update_classify_instance_state_api_v1_plus_classify_put) method to manually add a statue, and see it doesn't have an impact.

### Expected behavior

The state should not be visible when Unknown

### Screenshots

<img width="670" alt="image" src="https://user-images.githubusercontent.com/6758661/227999962-2714549a-8d8e-4f1a-a6a6-a211bf2cb8ab.png">

### Environment

* Version: 2.9.3
* OS: Linux
* Python Version: 3.10
* Docker Version: 20.10.22

### Additional context

Discovered and requested by @nicolas-ethyca

**Comment by SteveDMurphy** [comment]
As the state is stored on a `fidesplus` endpoint, there is a default state via the frontend. Adjusting there may be a quick way to handle this, but a longer term solution of either moving the state to the dataset object or separating it from the classify response would be better

**Comment by Roger-Ethyca** [comment]
moving to done 

![Image](https://user-images.githubusercontent.com/115798183/231581496-31c99eb2-b497-4b55-90de-85d8515d9962.png)
