### ISSUE TITLE
Add data flow accordion and modal

### ISSUE THREAD

**Issue by TheAndrewJackson** [ethyca/fides#2941]
https://www.figma.com/file/dmEwdK3xZwjKfGVQ9t66xe/Fides-v.2-Master-Working-Files?node-id=3892-123818&t=deCDCLuWBOGAFzeL-0

**Comment by TheAndrewJackson** [comment]
@rsilvery Does clicking `Confirm` in the modal save and send a request to the backend?



![Image](https://user-images.githubusercontent.com/17103888/230432776-cabbe618-cc43-461b-b5bf-6742a04bb048.png)



Or does it just populate what shows up in the accordion and saving ( request to the backend) only happens when `save` is clicked on the main form?



![Image](https://user-images.githubusercontent.com/17103888/230433200-f91ecaef-672a-4c50-90b3-fc5f09974217.png)

**Comment by rsilvery** [comment]
Please see Simon's response in the design channel. https://ethyca.slack.com/archives/C0114BAK160/p1680799872228429?thread_ts=1680799659.657109&cid=C0114BAK160
If possible, let's post these questions there since he doesn't have access to this repo for some reason :)

**Comment by Roger-Ethyca** [comment]
![Image](https://user-images.githubusercontent.com/115798183/231873868-8eacf94c-4805-4521-8598-bdc8a3409189.png)
![Image](https://user-images.githubusercontent.com/115798183/231873867-3ebb3b1c-0e73-48dd-8b86-8266d166978c.png)
