### ISSUE TITLE
There is no validation in the UI when updating your own password

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#2942]
### Bug Description

Found by @eastandwestwind :

https://github.com/ethyca/fides/pull/2933#issuecomment-1488953735

#### Steps to Reproduce

1. Create a user
1. Log in as that user
2. Try to change your own password to something invalid (i.e. just the letter 'a')
3. Submit
4. No error message

### Expected behavior

An error message at the very least. Ideally, also some validation before submitting like our other password fields do. 

### Screenshots

See linked issue comment

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

We may be able to consolidate this component with NewPasswordModal which does a lot of the same thing (but with better error handling)

**Comment by SteveDMurphy** [comment]
Just noticed this today as well and wanted to give it a ➕ 
I was incorrectly trying to reset a password instead (using new twice instead of old and new) and didn't receive any notification (good or bad)
