### ISSUE TITLE
Copy datamap-ui code into the admin-ui

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#2975]
### Is your feature request related to a specific problem?

After much discussion, we have decided to open source the datamap UI code and merge it with our admin-ui 🎉 

### Describe the solution you'd like

This ticket is to do the bulk of the copying including package.json dependency management. Just enough to get the app building, even if it doesn't look quite right yet.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

This would be part 1 of a multi-step process to get the datamap UI code in here.

**Comment by Roger-Ethyca** [comment]
moving to done 


![Image](https://user-images.githubusercontent.com/115798183/230462890-49cfe640-0aab-47c7-8102-b0e9ecd40cea.png)
![Image](https://user-images.githubusercontent.com/115798183/230462891-77f07312-bc46-45df-a1bf-28d6fc5589e8.png)
![Image](https://user-images.githubusercontent.com/115798183/230462892-b66e6ce6-ccd0-43e4-b18e-69cf53642e58.png)
