### ISSUE TITLE
Merge "forked" PrivacyDeclaration components

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#2976]
### Is your feature request related to a specific problem?

We have copied/pasted a good number of components between the datamap-ui and admin-ui. We should merge these back together now that they are in the same app.

### Describe the solution you'd like

Specifically, we'll need to look at:

* cypress configs
* dirty form hook (perhaps separate ticket to actually use it in admin-ui)
* ConfirmationModal
* Header
* Image
* Layout
* ProtectedRoute
* SearchBar
* toast.tsx
* PrivacyDeclarations

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

Depends on https://github.com/ethyca/fides/issues/2975

**Comment by allisonking** [comment]
Most of this except PrivacyDeclarations is done. That'll take more time to comb through the differences and resolve them

**Comment by Roger-Ethyca** [comment]
moving to done
