### ISSUE TITLE
Remove zone related logic and bring back the nav bar from fidesui

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#2977]
### Is your feature request related to a specific problem?

As part of open sourcing the datamap ui and merging it into the admin ui, we should remove the complicated zone logic since we don't need it anymore. We should also bring the nav config back from fidesui.

### Describe the solution you'd like

* remove zone logic and make sure all navigation still works okay
* bring the nav-config and tests back from their short stint in fidesui

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

Relies on https://github.com/ethyca/fides/issues/2975 and https://github.com/ethyca/fides/issues/2976

**Comment by allisonking** [comment]
Closed by https://github.com/ethyca/fides/pull/2990

**Comment by Roger-Ethyca** [comment]
moving to done 


![Image](https://user-images.githubusercontent.com/115798183/230469793-aa801969-7321-4bfd-951b-0d3599a73a90.png)
