### ISSUE TITLE
Combine datamap UI redux store with admin UI's store

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#2978]
### Is your feature request related to a specific problem?

As we open source datamap UI by merging it with admin UI, they will need to merge their redux stores.

### Describe the solution you'd like

Most of the redux slices can likely just take admin-ui’s version, except for `datamap.slice.ts`
### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

Blocked by https://github.com/ethyca/fides/issues/2975

**Comment by Roger-Ethyca** [comment]
moving to done 


![Image](https://user-images.githubusercontent.com/115798183/230462689-16ca8c97-af6a-4426-82f8-d76084728597.png)
![Image](https://user-images.githubusercontent.com/115798183/230462688-93e8e0c3-c2da-474d-8d4b-d9a3fcf6588b.png)
![Image](https://user-images.githubusercontent.com/115798183/230462687-65effb40-9f83-4694-8b1f-99be0d79be1e.png)
