### ISSUE TITLE
It's possible to reach the datamap UI without the plus flag

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3002]
### Bug Description

Running the `fides` backend, the UI will allow navigating to `/datamap` if you type it in the URL even though that should be a plus protected route.

#### Steps to Reproduce

1. `nox -s dev`
1. `npm run dev`
2. Type in `localhost:3000/datamap`. you should see the datamap UI

### Expected behavior

Be rerouted to the home page if not running the plus backend

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by Roger-Ethyca** [comment]
@allisonking When trying to access `localhost:3000/datamap` I do not see the datamap ui. Instead I end up at the home page. I should note that I was able to see the datamap yesterday. 


![Image](https://user-images.githubusercontent.com/115798183/230669409-6925f57f-4efd-420e-9027-088baffe47a7.png)

**Comment by Roger-Ethyca** [comment]
test

1. running fides OSS you can’t navigate to /datamap
2. running fidesplus you can navigate straight to /datamap

test passed 
moving to done
