### ISSUE TITLE
Upgrade to react-table v8

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3005]
### Is your feature request related to a specific problem?

As we build more fancy tables (datamap, privacy notices), it'd be nice to upgrade to react-table v8. We are currently on v7 which involves using our own [`react-table-config.d.ts`](https://github.com/ethyca/fides/blob/main/clients/admin-ui/src/types/react-table-config.d.ts) to merge types. This causes various other problems though, as those types are global and can't be used per table instance.

v8 is rewritten in typescript, so hopefully many of our typing problems will go away once we upgrade!

### Describe the solution you'd like

Upgrade to react-table v8. Then fix our typing issues!

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

https://github.com/ethyca/fides/pull/3001#discussion_r1160302398

**Comment by rsilvery** [comment]
@allisonking  any sense of the LOE?

**Comment by allisonking** [comment]
> @allisonking any sense of the LOE?

hard to say, depends on if things break 😅 I'd probably give it a 5 in terms of points just since there are quite a few unknowns.

**Comment by rsilvery** [comment]
Has this been done @allisonking ?

**Comment by allisonking** [comment]
@TheAndrewJackson started it here—I think new tables use v8, but old tables still use v7

**Comment by TheAndrewJackson** [comment]
@rsilvery This can probably be closed. That work has been started but it'll be a gradual migration instead of all at once. We now have a new table that uses v8. As Allison said, all new tables will use v8 and the v7 tables will be gradually migrated over.
