### ISSUE TITLE
Fides Local Flag not being honored in CI/CD job

### ISSUE THREAD

**Issue by nicolas-ethyca** [ethyca/fides#3035]
### Bug Description

When running a CI/CD example, we aren't able to run it without a hosted fides dependency

#### Steps to Reproduce

1. Try running local flag without a fides instance
2. https://github.com/ethyca/fides-CICD-Quickstart/actions/runs/4670980885/jobs/8271389814

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by Roger-Ethyca** [comment]
moving to done
