### ISSUE TITLE
Update `fides` test environment to use `fides deploy` for testing (privacy center, connectors, sample app, etc.)

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#3039]
### Description

Our current test environment (`nox -s "fides_env(test)"`) is similar-but-not-quite-the-same as `fides deploy`. I see a few main issues:
1. We don't have a "sample app" to test our frontend consent features on, like installing `fides-consent.js`, reading the `Fides.consent` flags, etc.
2. We have a lot of code duplication between `docker-compose.test_env.toml` and `sample_project/docker-compose.yml`
3. We don't actively test `fides deploy`, which is our primary tool for new users to try out the project

The solution to all of the above is to rewrite the test environment to run `fides deploy` instead of configuring a custom Docker Compose project 👍

**Comment by Roger-Ethyca** [comment]
moving to done. 
E2E tests will need to be slightly modified but those are changes that I am happy to make for this
