### ISSUE TITLE
Typo in Tutorial - Analyitcs --> Analytics

### ISSUE THREAD

**Issue by RobertKeyser** [ethyca/fides#304]
In the ["POP QUIZ" section of Manage Google Analytics with Fidesctl](https://ethyca.github.io/fides/tutorial/pass/#pop-quiz), there's a typo. 

> Modify the Google **Analyitcs** implementation such that it becomes compliant with the "Minimize User Identifiable Data" policy

This can be fixed here: https://github.com/ethyca/fides/blob/main/docs/fides/docs/tutorial/pass.md.

**Comment by shaund16** [comment]
@RobertKeyser can you assign me this

**Comment by iamkelllly** [comment]
@shaund16 all yours :)
