### ISSUE TITLE
Create custom field page scaffolding

### ISSUE THREAD

**Issue by TheAndrewJackson** [ethyca/fides#3077]
# Description
In order to make PR diffs easier to read it will be helpful to have the initial page creation be done in a dedicated PR that only includes a very minimal interface. This will be merged in a feature branch so the incomplete pages are not merged into main. 

## Acceptance Criteria 

- Add new custom fields table page to management tab /management/custom-field
  - Rendering a list of each custom field will suffice for new

**Comment by allisonking** [comment]
instead of a feature branch, would it work to use our feature flags with the `userCannotModify` flag set to true? I'm thinking that'll make merge conflicts easier to handle (especially if we'll be refactoring the tables which touch both custom fields and privacy notices)

**Comment by TheAndrewJackson** [comment]
Sure, I can do that if that's what you prefer. The feature branch was supposed to make things easier but if it makes things worse then lets utilize the flags instead. It makes sense when factoring in the table refactor as well.
