### ISSUE TITLE
Dataset list is cutoff on the data uses sections

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#3100]
When there are more than 1 or 2 datasets in a Fides instance, the list to select them on the data uses panel is cutoff, making it hard to find the right dataset. See the attached screenshot for an example:

![Image](https://user-images.githubusercontent.com/4807009/233114154-4dddb1e9-4c0a-4607-9c7a-5df0027deca4.png)

**Steps to Reproce**
1. Spin up a version of Fides and add or create 3 datasets
2. Create or edit a a system
3. Add a data use
4. Try to select a dataset in the data use. 

These steps should produce something like the screenshot. The expected behavior is that the list appears above the sections so that I can see a larger number of datasets.

**Comment by rsilvery** [comment]
This is going away soon - do we need to fix this?

**Comment by rsilvery** [comment]
This has been fixed.
