### ISSUE TITLE
Rule Targets should allow for custom data categories

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#3103]
Today in Fides, you cannot create or modify rule targets to use custom data categories, which will limit the ability of customers to configure DSR rules based on their own customizations to the Fideslang taxonomy. The rule targets currently only support data categories from the default taxonomy.

**Steps to reproduce**
1. Create a custom data category - this can be done either via a YAML file extension of the taxonomy or via the UI at /taxonomy.
2. Try a PATCH request to: "/api/v1/dsr/policy/{policy_key}/rule/{rule_key}/target"
3. You can use the policy key `default_access_policy` and the rule key `default_access_policy_rule`
4. You should get an error that lists the valid enumeration members as the default data categories only. 

**AC**
- Update the rule target data category validation to allow any data category from the instance of Fides. I should be able to extend the taxonomy and create custom data categories, then create a rule target for a policy that uses my newly created data category.
- The validation should not allow any data category, just those defined in that Fides' instances taxonomy - findable at /api/v1/data_category

**Comment by seanpreston** [comment]
Re-implemented with [this PR](https://github.com/ethyca/fides/pull/3147).
