### ISSUE TITLE
Custom Fields Table Enhancements

### ISSUE THREAD

**Issue by TheAndrewJackson** [ethyca/fides#3127]
# Description

In order to support the custom fields modal the table needs a few updates to handle opening and closing the modal.

### Updates
- Row click (it currently links to a page. It needs to support opening a modal as well)
- Kebab Menu (needs to support linking to pages and opening modals)
    - Delete call (is it possible to delete the field definition?)

**Comment by allisonking** [comment]
Closed by https://github.com/ethyca/fides/pull/3165
