### ISSUE TITLE
Refactor New Privacy Preference Endpoints to Examine Request Headers

### ISSUE THREAD

**Issue by pattisdr** [ethyca/fides#3133]
### Is your feature request related to a specific problem?

We've added some new endpoints to save the new-style privacy preferences with respect to verified identities like email or phone number or with respect to a fides user device id that we've added to the browser.

These requests also collect some user details for consent reporting purposes.  The endpoints have some of these details supplied in the request body, but instead, we should pull what we can from the request headers.

Related:
https://github.com/ethyca/fides/pull/3016
https://github.com/ethyca/fides/pull/3132

### Describe the solution you'd like

Also might be good to add these fields at this time:
- AddThe method of consent preference in a modal (buttons, individual notices)
- Add anonymized ip address

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by Roger-Ethyca** [comment]
moving to done
