### ISSUE TITLE
Add a freshness check to fidesctl

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fides#314]
### Is your feature request related to a specific problem?

Currently there is no way to validate the continuous maintenance of your fidesctl taxonomies. An example from @brentonmallen1 was the idea around a stale taxonomy continually passing ci checks due to non-maintenance.

### Describe the solution you'd like

A staleness/freshness check would help to make this more visible, and the result could eventually be one component in visualizing overall health of how fides is being implemented. Some of the infrastructure scanning work will help to make this easier to do the maintenance, but this feature would help to ensure compliance checks and maintenance of resources are happening regularly.

### Describe alternatives you've considered, if any

Having some of the scanning work baked into the evaluate command could be an interesting riff on this, although I am not sure it would still give us the view into continued validation/compliance that a freshness check would.

### Additional context

There are many levels here that could be validated, potentially starting with the execution of a few commands and their success/failure could be interesting before providing a deeper view of change within the resources themselves

**Comment by SteveDMurphy** [comment]
@brentonmallen1 feel free to add any other context or modify anything that maybe seems misaligned with what you were thinking

**Comment by brentonmallen1** [comment]
I think that captures what I was thinking.  I think the idea of it contributing to the overall health score/grade is a neat idea but there are probably some considerations there.  thank you for capturing this

**Comment by Kelsey-Ethyca** [comment]
closing all tickets older than a year as not planned

**Comment by SteveDMurphy** [comment]
@Kelsey-Ethyca - I still think this may be a valid need, is there a good way to petition to keep an issue open or try to prioritize it in some way?
