### ISSUE TITLE
Investigate pymssql vs pyodbc for MSSQL Support

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fides#3152]
### Is your feature request related to a specific problem?

There have been some user reports around intermittent failures with the `pyodbc` implementation that are resolved by simply switching to `pymssql`. Investigate what this looks like.

### Describe the solution you'd like

1. Investigate and document the cost/benefits of switching from `pyodbc` to `pymssql`
2. If beneficial, replace `pyodbc` with `pymssql`

### Describe alternatives you've considered, if any

Deeper understanding and resolution of the `pyodbc` issues being experienced

### Additional context

There are many known issues related to `mssql` `pyodbc` and Silicon Mac's

When previously investigated, `pymssql` was unmaintained and not recommended for usage. Since then, `pymssql` has seen a resurgence and is currently maintained

**Comment by ThomasLaPiana** [comment]
link to package: https://github.com/pymssql/pymssql

**Comment by Kelsey-Ethyca** [comment]
before merging this can we investigate the longevity of pymssql because it might be deprecated soon?

**Comment by Roger-Ethyca** [comment]
moving to done
