### ISSUE TITLE
Replace mock GET experience and PATCH privacy-preferences endpoints with real calls

### ISSUE THREAD

**Issue by eastandwestwind** [ethyca/fides#3159]
- dependent on https://github.com/ethyca/fides/issues/3228

Replace the following with real API calls:

* GET {{host}}/privacy-experience- this will be a public endpoint in https://github.com/ethyca/fides/issues/3229
* PATCH {{host}}/privacy-preferences- this is currently a public endpoint

**Comment by eastandwestwind** [comment]
Ah good call! https://www.npmjs.com/package/whatwg-fetch looks like a good solution

**Comment by pattisdr** [comment]
Wanted to highlight some intersections: https://github.com/ethyca/fides/issues/3133 and https://github.com/ethyca/fides/issues/3196

I'll be pulling more of these items off of request headers where I can too, but I'll also be adding more fields I need to be in the request body including the experience/experience config history that surfaced the notices to the user to track for consent reporting.

**Comment by Roger-Ethyca** [comment]
moving to done
