### ISSUE TITLE
Update Privacy Center to support fetching experiences, rendering notices, and saving preferences

### ISSUE THREAD

**Issue by eastandwestwind** [ethyca/fides#3162]
Can probably use the same component as https://github.com/ethyca/fides/issues/3161

**Comment by allisonking** [comment]
To be clear, is this to make this page:



![Image](https://github.com/ethyca/fides/assets/24641006/b84a3674-6852-4c1b-807e-f051b9e8ae9c)

be driven by experiences instead of `config.json`? Do we need a plan for still supporting `config.json` while a customer may not have notices set up yet?

**Comment by eastandwestwind** [comment]
Yes, see https://github.com/ethyca/fides/pull/3191/files#diff-ba7bb0c80dbf370b49c211bf0e888dc34cf0f7a713e2b4b685d98b0b46b25014R33-R35 - part of our `http://localhost:3000/fides.js` endpoint on privacy center bundles the legacy `config.json` to be injected in `Fides.init()`, so the logic can be use experiences if that's [enabled](https://github.com/ethyca/fides/pull/3191/files#diff-ba7bb0c80dbf370b49c211bf0e888dc34cf0f7a713e2b4b685d98b0b46b25014R38), else use legacy config.

**Comment by allisonking** [comment]
ah okay! so would the pattern be something like

* `fides-js.ts` always loads in the consent options from `config.json` ([already handled](https://github.com/ethyca/fides/pull/3191/files#diff-ba7bb0c80dbf370b49c211bf0e888dc34cf0f7a713e2b4b685d98b0b46b25014R33-R35))
* if `isDisabled=true`, render the PC through `config.json` like we already have
  * Might need to do some work here to read consent options from the `FidesConfig` object instead? Not sure yet
* if `isDisabled=false`, then we query for experiences and use those results
  * This is the bulk of this ticket's work

**Comment by Roger-Ethyca** [comment]
moving to done
