### ISSUE TITLE
Add a modal for copying a JS tag for privacy experiences

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3168]
### Is your feature request related to a specific problem?

Add a modal with a JS snippet that the user can copy and paste into their own site

### Describe the solution you'd like

Need to coordinate based on https://github.com/ethyca/fides/issues/3160 for what this link should look like

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

![image](https://user-images.githubusercontent.com/24641006/234622523-65184b3c-e1eb-4593-a4bd-3caae5be9684.png)

**Comment by allisonking** [comment]
From @eastandwestwind : 

the script will look like

```js
<script src="https://{privacy-center-hostname-and-path}/fides.js"></script>
```

3 options for path forward to get PC URL:
1. have the customer replace the {privacy-center-hostname-and-path} with their own before pasting on their site
2. have this url configurable in admin-ui, writing to fides db. If we do this, we need to make it obvious this is required to setup fides consent
3. have this url configurable in .env of fides. Downfall is having to redeploy fides if this PC url changes


Option 1 would be the easiest for us at the moment, but puts the burden on the customer. we should think through how we'd go the 2/3 route

**Comment by NevilleS** [comment]
I'd probably vote #2, because won't the components also *need* that URL for their own configuration? For example, we'll need notices/banners to be able to link to the privacy center.

**Comment by Roger-Ethyca** [comment]
moving to done
