### ISSUE TITLE
Optimize Privacy Center `/fides.js` download with cache headers and a local `public/assets/fides.js` file

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#3170]
### Description
In https://github.com/ethyca/fides/pull/3105 we refactored the Privacy Center to serve a custom bundle of the `fides.js` Javascript package, initialized with the tenant-specific configuration sourced from the Privacy Center backend. This works swimmingly, but needs some optimization before it's ready for production use.

### Acceptance Criteria
- [ ] Add reasonable cache headers to the `/api/fides-js` route to ensure both browsers and CDNs will cache the result
- [ ] During the `privacy-center` build, copy the generic `fides.js` package to `/public/assets/fides.js`
- [ ] Test that this "virtual" file is properly cached by browsers and CDNs

**Comment by Roger-Ethyca** [comment]
moving to done.
