### ISSUE TITLE
Save Privacy Experience Id on Privacy Preference History 

### ISSUE THREAD

**Issue by pattisdr** [ethyca/fides#3196]
### Is your feature request related to a specific problem?

We need to record which version of the privacy experience the user saw when saving privacy preferences among other remaining fields to wrap up consent reporting tracking

### Describe the solution you'd like

- Add `privacy_experience_history_id` to the `PrivacyPreferenceHistory` table
- When saving privacy preferences, add this privacy experience history idas field to the pydantic schema

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by Roger-Ethyca** [comment]
moving to done
