### ISSUE TITLE
Server stuff is happening when the CLI runs

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#3204]
### Bug Description

Extra logging shows up when running the CLI

#### Steps to Reproduce

1. `pip` install latest
2. run `fides` and notice the erroneous logging statements

### Screenshots

![image](https://user-images.githubusercontent.com/5105354/235834862-77dce15d-b058-4072-bb09-dff804890754.png)

### Environment

* Version: 2.12.0

**Comment by ThomasLaPiana** [comment]
confirmed this did not happen in `2.11.0`

**Comment by Roger-Ethyca** [comment]
moving to done
