### ISSUE TITLE
`prettier` formatter isn't run on all source files (esp. Cypress tests!)

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#3208]
### Bug Description

I just realized this, and why we're getting some (distracting) whitespace changes when different folks work on the same source files... most of our npm scripts look like this:
```
    "format": "prettier --write src __tests__/",
    "format:ci": "prettier --check src __tests__/",
```

By only targeting src/ and __tests__/, we end up missing a bunch of other files like cypress/, lib/, etc. We also don't run prettier on our package.json and such, which we might as well!

This is a *really easy* change to make, but it'll result in a big boring PR with lots of formatting changes, so I'm carving this out separately for our collective sanity.

#### Steps to Reproduce

1. Edit a Cypress test like fides/clients/admin-ui/cypress/e2e/home.cy.ts
2. Write some code that is poorly formatted
3. Run `npm run format`

### Expected behavior

All code is formatted with `prettier` 🎨

**Comment by NevilleS** [comment]
Zero points intentionally!

**Comment by Roger-Ethyca** [comment]
moving to done
