### ISSUE TITLE
Resource Updates Categories of Processing, Recipients, and Legal Basis

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fides#322]
### Is your feature request related to a specific problem?

As part of exporting a data map (or eventually a ROPA) from `fidesctl`, further information for a data map is required as part of our walk state. 

The following items come from sections 1.b, 1.d, and 2.b in [article 30](https://gdpr-info.eu/art-30-gdpr/) and can be worked concurrently with #321 & #323

### Describe the solution you'd like

The following items will need to be added as part of the walk state of this effort to get us to having an exportable data map as a csv:

* Categories of processing (2.b)
    * Similar here, initial thoughts is this may come from the system
* Categories of recipients (1.d)
    * The type of recipient which personal data is disclosed to (i.e. Processor)
* Purpose of processing (1.b)
* Legal basis categories (Potentially from Article 6)

### Describe alternatives you've considered, if any

N/A

### Additional context

This is the second in a series of a larger group of issues that will continue to update resource models to add attributes and data points that will make up the data map and eventual ROPA. Some minor questions still exist around the placement and possible reuse of existing resource attributes to model the data points

Update 1/28/22 by @SteveDMurphy 
This issue has been updated to isolate some attributes that may be similarly grouped in fides, either through a new taxonomy or an extension of data use. Examples to be built out on PR #329

**Comment by SteveDMurphy** [comment]
@iamkelllly @NevilleS, @earmenda and I were able to chat and focus our time on defining the best plan for the items defined here - can you confirm or add discussion to the following?

1. Link to security policy - would you be able to confirm or course-correct the initial plan for this listed in the issue description? I wasn't able to find a direct mention of this in the gdpr docs or in the provided example.

2. Retention / erasure - based on example, different layers appear to be allowed - planning to have this applied at any level in a dataset, does that make sense to you all as well? [The example](https://docs.google.com/spreadsheets/d/1VqSJUy1lrJSrTSgxp-ncjLnyUg3nsaoJ/edit#gid=258727437) has different retention limits for the top 3 rows, that made us think it could potentially be defined as low as the field, but didn't want to lock users into annotating every field that way

3. Categories of processing - I think Neville had an example listed out for this one in the design doc comments and I think the main question we still had was around if we use custom extensions of the `data_use` would that mean a system would be able to contain a list of data uses or we would define them as separate systems? For instance, it appears the example article has the employees.contact_details processed by HMRC as well as n/a 

@earmenda please feel free to clarify or add to anything above, and thank you for the help today!!

**Comment by iamkelllly** [comment]
thanks for the update! some comments:

1. Re security policy:  Article 30.1(g) states "where possible, a general description of the technical and organisational security measures referred to in [Article 32(1)](https://gdpr-info.eu/art-32-gdpr/)." Generally this is captured in the organization's corporate security policy, but it's not always the depth that Art 32.1 requires. for the scope of the ROPA feature, I think it's safe to not provide additional guardrails about Art 32 requirements and just have the adopter link to their security policy. 
2. Re retention/erasure: your assumption is correct, technically retention and erasure can be set at the individual field level (ie: column-level, or json field-level target). I think it's a really good idea to have optional field-level retention policies but not force users to specify retention for every field. 
3. Re categories of processing: if i understand the question here, to rephrase it, you're asking if it is okay to extend the `data_use` model to allow systems to be annotated with additional data uses?  if so, then yes, that is an appropriate extension of the fideslang model. But...i think you're asking something different here?

**Comment by SteveDMurphy** [comment]
Thank you @iamkelllly ! All super helpful, I think we are good with 1 & 2 then 🙌🏽 

For 3. - The extending makes sense, in the example it looks like that output would potentially require having multiple `data_use`(s) applied, so I (think) my question is around if a system should be able to handle a list of `data_uses` or if a system is more defined as a single use type resource (and you would potentially have multiple systems defined based on the `data_use`)

I'm not actually sure if that makes it more clear or not

**Comment by SteveDMurphy** [comment]
Update around the third item - while chatting with @iamkelllly about categories of processing, we ran into a question around usage of `data_use` (specifically how it currently accepts a single string) and we were hoping to get insight or thoughts from you all @NevilleS and @ThomasLaPiana

Using Snowflake as an example system (with datasets that feed a bi tool, external reporting, and data science teams) I think we would need to model this as three separate systems today to handle a different `data_use` for each.

From any of the early conversations you all had, was there a decision made around having `data_use` be a single item and modeling these all as separate systems? Or could having an array of `data_uses` make sense as well? Any other thoughts around this would be great as well, thank you!!

**Comment by SteveDMurphy** [comment]
Just finished another conversation with @iamkelllly and @earmenda - planning to split the Categories of Processing and Categories of Recipients (#323 currently) to a new issue as they appear to be linked. The feeling was that the `data_use` may not be the best place for this anymore, and having a separate customizable taxonomy object under the `privacy_declaration` could make more sense. It did however feel like that we need to keep the recipients and purpose of processing linked in order to show clear relationships between who is accessing the data and why. Splitting this out will allow for further conversation while we continue to update models with other required attributes.

**Comment by NevilleS** [comment]
Sorry for a slow response, but to clarify a bit about the `System:DataUse` relationship...

Systems can "belong to many" data uses and that's an expected result of the ability to specify multiple `System.privacy_declaration` entries. So, for example, you might have a System that declares it does `provide.system.operations`, `improve`, and `personalize`.

Furthermore, I've always conceptually believed that it makes sense to extend and declare custom `DataUses` that you would reuse across declarations. Today the `DataUse` model is limited to just `fides_key`, `name`, and `description`, but there's no reason we can't store other meaningful metadata about the use.

So for example:
```yaml
data_uses:
- fides_key: provide.system.operations.marketplace
  name: Provide Marketplace
  description: Provide the main features for MyMarketplace.com, which includes product search, checkout, and order flow.
```

One could then reuse `provide.system.operations.marketplace` wherever and that becomes a very clear place to define your main privacy policies, etc.

Nothing stops us from adding more things to that data use as well, assuming they *belong to* that specific concept and should flow from it
