### ISSUE TITLE
Add public API endpoints

### ISSUE THREAD

**Issue by eastandwestwind** [ethyca/fides#3228]
Where do we expose public API for privacy experiences? 

Suggestion from Neville: We can use privacy center as proxy to talk to fides api. 

Acceptance criteria- 

Add minimum public endpoints to fetch privacy experiences and save consent preferences

1. GET {{host}}/privacy-experience
2. PATCH {{host}}/privacy-preferences

**Comment by pattisdr** [comment]
Addressed in https://github.com/ethyca/fides/issues/3229

PATCH {{host}}/privacy-preferences was already public and GET {{host}}/privacy-experience was made public.  We are not using the privacy center as proxy to talk to the fides API at this time.

**Comment by Roger-Ethyca** [comment]
moving to done
