### ISSUE TITLE
Improve security around public API for privacy experiences

### ISSUE THREAD

**Issue by eastandwestwind** [ethyca/fides#3229]
Depending on outcome of https://github.com/ethyca/fides/issues/3228, how do we provide enough security around the public API we expose for privacy experiences? Basically how to we prevent bad actors from using public API?

- Do we want any “auth” using hostname? 
- We can use rate limiting

**Comment by pattisdr** [comment]
This ticket will also make getting the privacy experience list a public endpoint -
