### ISSUE TITLE
Prefetch API calls as part of privacy-center in /fides-js API route

### ISSUE THREAD

**Issue by eastandwestwind** [ethyca/fides#3231]
Right now our assumption is that the `Fides.js` package will be responsible for making the following API calls during initialization:
1. Fetching it's "geolocation" using a location API
2. Fetching it's "experience" configuration using the Fides API, filtered to the component's location

As an optimization, it should be possible to do both of these API calls server-side and bundle the results into the `/fides.js` package returned to the client. This would allow the `Fides.js` package to initialize instantly, instead of delaying to wait for the API calls to complete.

**Comment by Kelsey-Ethyca** [comment]
@Kelsey-Ethyca to add doc

**Comment by Roger-Ethyca** [comment]
moving to done
