### ISSUE TITLE
[Backend] Surface Current Preference under Privacy Experience List endpoint

### ISSUE THREAD

**Issue by pattisdr** [ethyca/fides#3237]
### Is your feature request related to a specific problem?

Reduce number of API calls to figure out current preferences for a user.

### Describe the solution you'd like

In the GET Privacy Experience List Endpoint: GET {{host}}/privacy-experience/ (might as well add detail too here), add a `fides_user_device_id` query param.

If both `region` and `fides_user_device_id` query param are added:

- Every notice under that experience applicable to that region is returned (already supported)
- Each notice has an extra field added, `saved_preference`: if I have a preference saved for the fides user device id for the **current version** of the given notice return that value, otherwise, return null
- Each notice has an extra field added, `default_preference` : return previous preferences for older versions first, otherwise fall back to the default for the overall notice***
- GPC flag isn't factored in here, FE additionally toggles here.

*** Note we may split this out into another field to distinguish between default and saved versions if that is important.

Context: https://ethyca.slack.com/archives/C04S7K0T2V7/p1683303815378149

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by Roger-Ethyca** [comment]
moving to done
