### ISSUE TITLE
Disabled Connectors can't be successfully re-enabled without re-providing credentials

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#3253]
1. Run a Fides instance
2. Add a connector (Hubspot works well)
3. Test the connector (Should be successful)
4. Disable the connector from the menu <img width="810" alt="Screenshot 2023-05-08 at 1 50 30 PM" src="https://user-images.githubusercontent.com/4807009/236894835-d3747673-b0b6-4f09-8979-b9eda1f3f135.png">
5. Re-enable the connector
6. Test again 

This will expose two problems:
1. The UI makes it look like it was successfully tested
2. It doesn't successfully test. If you inspect the request, you'll see a 500 error for the test request.

**AC**
- I should be able to disable a connector, re-enable it, and re-test without providing the credentials again
- If the test request from the connector list returns an error, the UI should indicate that the error occurred by saying the last test failed. 

### Dev Notes
When we disable a connection, we PATCH http://localhost:3000/api/v1/connection with this payload
```
[
    {
        "key": "friendbuy_nextgen",
        "name": "Friendbuy Nextgen",
        "disabled": true,
        "connection_type": "saas",
        "access": "write"
    }
]
```
The unintended side-effect is that we null out the `secrets` field on the `connectionconfig` row. We need to look into the patch connection endpoint and see why the patch is acting like a post.

**Comment by galvana** [comment]
This issue will be resolved in https://github.com/ethyca/fides/issues/3263

**Comment by Kelsey-Ethyca** [comment]
QA notes - This works on the unlinked connectors page, there is no way to enable/disable on the new system integrations page
