### ISSUE TITLE
Unify AWS secret definitions

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fides#3257]
### Bug Description

There are currently multiple places where we define the aws secrets (e.g. `generate` and `connection_configuration`)

It would be better if we were to define these once and avoid having to maintain configurations in multiple places

#### Steps to Reproduce

n/a

### Expected behavior

No functionality change, just better adhering to better practices

### Screenshots

n/a

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

As discussed in this [PR review comment](https://github.com/ethyca/fides/pull/2998#discussion_r1183990366)

**Comment by rsilvery** [comment]
We will be revisiting this soon as we consider the new dataset generation/annotation interface. But that would probably be in Fidesplus.
