### ISSUE TITLE
Create DSR access package export

### ISSUE THREAD

**Issue by TheAndrewJackson** [ethyca/fides#3267]
# Description 
The will use the access request json that's created by the DSR to fill in the export package. It will consist of a few steps:

The file/folder structure will work like this:

- root index page containing a list of datasets: `./index.html`
- index page for each dataset containing a list of collections `./dataset/index.html`
- index page for each collection containing a list of items `./dataset/collection/index.html`
- individual page for each item `./dataset/collection/1.html`

The exact folder structure can change but there needs to be some folder nesting to avoid file name clashing

**Comment by galvana** [comment]
Covered by https://github.com/ethyca/fides/pull/3427

**Comment by Roger-Ethyca** [comment]
moving to done 


![Image](https://github.com/ethyca/fides/assets/115798183/6c828b73-5db2-465a-9515-fafd78931e09)
![Image](https://github.com/ethyca/fides/assets/115798183/3b9c61c3-14e5-4c05-9add-1e34fa650ff2)
![Image](https://github.com/ethyca/fides/assets/115798183/a4a5c067-d9be-44c5-9b0c-fbad01de4cc3)
![Image](https://github.com/ethyca/fides/assets/115798183/3f6facdf-1bb4-4056-80d0-810b714d234e)
