### ISSUE TITLE
Create css stylesheets for DSR export package

### ISSUE THREAD

**Issue by TheAndrewJackson** [ethyca/fides#3268]
> **Warning**
> Dependent on #3267 

[designs ](https://www.figma.com/file/dmEwdK3xZwjKfGVQ9t66xe/Fides-v.2-Master-Working-Files?type=design&node-id=6387-132049&t=9z0eNeuy0dtyx7q9-0)

# Description
Now that the export package has been created it's time to style it. Apply the styling of the designs to the now finished DSR export

**Comment by galvana** [comment]
Covered by https://github.com/ethyca/fides/pull/3427
