### ISSUE TITLE
BE - Add Data Categories to `AccessManualWebhook`

### ISSUE THREAD

**Issue by TheAndrewJackson** [ethyca/fides#3270]
# Description
Currently all field data is stored with a `jsonb` column within the [`AccessManualWebhook`](https://github.com/ethyca/fides/blob/bfbe91805f573df74a4aa136f3271cd8fb78faad/src/fides/api/ops/models/manual_webhook.py#L14-L33) so no migrations are required to add data categories. The data categories should be stored alongside each field like this:

```json
{
    "pii_field": "firstName",
    "dsr_package_label": "First Name",
    "data_category": "user.name"
}
```

The [pydantic schema](https://github.com/ethyca/fides/blob/bfbe91805f573df74a4aa136f3271cd8fb78faad/src/fides/api/ops/schemas/manual_webhook_schemas.py#L27-L31) for `AccessManualWebhook`s will need to be updated to support data categories. The schema should validate that the data categories that are send in with the payload a valid.

The[ patch endpoint](https://docs.ethyca.com/fides/dsr_quickstart/dsr_support/manual_webhooks#upload-manual-webhook-data-for-a-given-privacy-request) for uploading data to a privacy request must make the data category field optional. The data category is only used in the admin ui and the DSR export.

**Comment by Roger-Ethyca** [comment]
moving to done
