### ISSUE TITLE
FE - Add Data Categories to `AccessManualWebhook`

### ISSUE THREAD

**Issue by TheAndrewJackson** [ethyca/fides#3271]
> **Warning**
> Dependent on #3270 

# Description
The manual webhook configuration page will get a new data category dropdown added to the form. It will allow selecting one data category and be required.
![image](https://github.com/ethyca/fides/assets/17103888/8f9e89f3-8767-42bb-86f7-b9bef8b2cb94)

**Comment by Roger-Ethyca** [comment]
moving to done
