### ISSUE TITLE
Add ability to select different locations in the "Cookie House" sample app

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#3277]
### Description

For testing, demos, and general "learn-ability" of privacy notices/experiences/components, we should add a demo feature to the Cookie House to allow the user to manually specify their location. Since new users learn about Fides via the Cookie House nowadays, this should be reasonably polished and presentable, so I'd prefer adding a "country picker" to the header that is visual and clear -  but, for more complex testing and test automation cases, we should also support a `?location=` query param for the Cookie House itself.

In both cases, we can change the script include in the Cookie House HTML to pass along the location param to the bundle:
```
<script src="http://localhost:3001/fides.js?location=$CUSTOM_LOCATION" />
```

### Acceptance Criteria

- [ ] Support specifying a location via a query param, e.g. `http://localhost:3000?location=US-CA`, which modifies the `<script>` include to be `/fides.js?location={location}`
- [ ] Support specifying a location via a dropdown picker in the Cookie House page, which also modifies the `<script>` include to be `/fides.js?location={location}`
- [ ] Support a few regular options to demonstrate some standard notices: `US-CA`, `FR`, etc.

### Mockups
<img width="1344" alt="image" src="https://github.com/ethyca/fides/assets/1834295/1f98d782-0df0-487a-8dbe-b8360e209b82">

**Comment by Roger-Ethyca** [comment]
moving to done
