### ISSUE TITLE
Add accessibility testing to `fides-js` workspace

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3306]
### Is your feature request related to a specific problem?

We should add some automated a11y (accessibility) testing to `fides-js`

### Describe the solution you'd like

We should research what tools are out there that we can set up to make sure we are keeping to accessibility best practices, particularly with the `fides-js` components. I've used [cypress-axe](https://github.com/component-driven/cypress-axe) in the past, but there may be alternatives now!

Ideally these run as part of CI so we know right away if we've broken something.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by rsilvery** [comment]
@allisonking  is this complete now?

**Comment by allisonking** [comment]
Nope we don't have any automated testing for a11y
