### ISSUE TITLE
Accessibility requirements for `fides-js`

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3309]
### Is your feature request related to a specific problem?

We need to make sure our `fides-js` components are as accessible as possible!

### Describe the solution you'd like

Here's a running checklist of things we need to do. I'm not 100% sure if these are strictly requirements are suggestions, so we should do our due diligence with reading the standards, but for now I'm going to drop everything I see.

These don't include standard a11y things, like high contrast text and heading logic, as those things can typically be caught by automated tools (https://github.com/ethyca/fides/issues/3306)

#### Banner
* [x] Banner should be the first focusable element in the page, before skip link and website's nav (so that visitors interact with the banner before anything else)
* [x] Banner buttons must be of type `<button>` 
* [x] When banner closes, we should not be able to tab through it

#### Modals
* [x] Trap focus inside the modal (cannot tab outside the modal)
* [x] Modal size should allow text to be readable at all screen sizes
* [x] Initial focus should be set within the modal (often to the first focusable element)
* [x] Closing a modal (either through confirmation or closing) returns focus to the last focused item on the main screen
* [x] ESC closes the dialog
* [x] Can Tab + Shift Tab through the modal
* [x] Strongly recommended to include a close icon or button
* If the modal is meant to operate such that users cannot interact with anything outside of the modal and dims the background:
  * [x] Element that serves as the dialog container has a role of `dialog`
  * [x] All elements required to operate the dialog are descendants of the element that has role `dialog`
  * [x] Dialog container element has `aria-modal` set to true
* [x] The dialog has either 
  * A value set for the `aria-labelledby property that refers to a visible dialog title
  * A label specified by `aria-label`

#### Toggles
* [x] SPACE changes the state of the switch
* [x] Switch has the role `switch`
* [x] Switch has an accessible label by one of the following:
  * Visible text content contained within the element with role switch.
  * A visible label referenced by the value of [aria-labelledby](https://w3c.github.io/aria/#aria-labelledby) set on the element with role switch.
  * [aria-label](https://w3c.github.io/aria/#aria-label) set on the element with role switch.
* [x] When on, the switch element has state [aria-checked](https://w3c.github.io/aria/#aria-checked) set to true.
* [x] When off, the switch element has state [aria-checked](https://w3c.github.io/aria/#aria-checked) set to false.
* [x] If the switch element is an HTML input[type="checkbox"], it uses the HTML checked attribute instead of the aria-checked property.

#### Disclosures (accordions)
* [x] The element that shows/hides the content has role `button`
* [x] When the content is visible, the element with the `button` role has `aria-expanded` set to true. When the area is hidden, it's `false`
* [x] Optionally, the element with role button has a value specified for [aria-controls](https://w3c.github.io/aria/#aria-controls) that refers to the element that contains all the content that is shown or hidden.
* [x] When disclosure control has focus, ENTER and SPACE activate the visibility

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

Resources:
* https://www.smashingmagazine.com/2023/04/potentially-dangerous-non-accessibility-cookie-notices/
* https://www.youtube.com/watch?v=Uaqo4FOI_DY
* https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/
* https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/
* https://www.w3.org/WAI/ARIA/apg/patterns/switch/
* https://quentin-bellanger.com/blog/accessible-cookies-banner/
* https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/

**Comment by allisonking** [comment]
The modal is going to be tricky—I think we should use a 3rd party lib or else we'll probably mess something up. I'd like to use [this one](https://github.com/KittyGiraudel/react-a11y-dialog) as it is tiny but I haven't been able to get rollup to play well with importing a React package.

Without any intervention, when I try to use the package, rollup gives the error

```
[!] RollupError: "A11yDialog" is not exported by "../node_modules/react-a11y-dialog/dist/index.js", imported by "src/components/ConsentModal.tsx".
https://rollupjs.org/troubleshooting/#error-name-is-not-exported-by-module
src/components/ConsentModal.tsx (3:9)
```

This is solved by using `commonjs`, but commonjs also inflates the bundle size a lot! (the package is only [2.7kb](https://bundlephobia.com/package/react-a11y-dialog@6.2.0), yet the size increases by around 14kb!!)

```
npm run build

> fides-js@0.0.1 build
> NODE_ENV=production rollup -c


src/fides.ts → dist/fides.js...
❌ ERROR: fides.js build failed! Gzipped size (24.06 KB) exceeded maximum size (20 KB)! If you must, update GZIP_SIZE_* constants in clients/fides-js/rollup.config.mjs
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: fides-js@0.0.1 
npm ERR!   at location: /Users/aking/workspace/ethyca/fides/clients/fides-js
```

I tried various parameters passed into both commonjs and node-resolve, but haven't had much luck. 

These articles explain why commonjs causes larger bundle sizes: https://blog.logrocket.com/does-my-bundle-look-big-in-this/ https://web.dev/commonjs-larger-bundles/ but I haven't quite figured out how to get around it yet.

**Comment by eastandwestwind** [comment]
Documenting that Neville did some investigating around bundle size, below:


After some bundle optimization, the impact of this library is now adding ~8.6K to the gzip size, which is still a lot. We're unlikely to optimize that further since it comes from requiring the Preact compat code to import React modules

We have a few options to proceed:

1. Investigate other optimizations to see what I missed
2. Optimize our other code to make room in the bundle
3. Look for Preact modal libraries instead, which wouldn't require the compat import
4. Implement the a11y features ourselves
5. Finish other work first, then investigate options 1-4


For now we'll go with option 5

**Comment by Roger-Ethyca** [comment]
moving to done
