### ISSUE TITLE
Spike: data model changes required to support the "happy path" for connector configs

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#3315]
We need to figure out what data model changes would be required to make the happy path from Phase 1.5 work: https://ethyca.atlassian.net/wiki/spaces/PM/pages/2693464204/Integrations

**Comment by rsilvery** [comment]
@TheAndrewJackson , @galvana ?

**Comment by TheAndrewJackson** [comment]
@adamsachs That makes sense to me. Is there a specific reason why the depth needs to be 1? Would something like this work?

```json
{
  "saas_config": {
    "type":"stripe",
    "icon":"***",
  }
}
```

**Comment by adamsachs** [comment]
> @adamsachs That makes sense to me. Is there a specific reason why the depth needs to be 1? Would something like this work?
> 
> ```json
> {
>   "saas_config": {
>     "type":"stripe",
>     "icon":"***",
>   }
> }
> ```

@TheAndrewJackson good question, thanks for reading closely :)

the "reason" is that the `meta` field on our `System` pydantic model is annotated with a type of `Optional[Dict[str, str]]`, so  our API is gonna reject JSON objects with depth > 1 (gives a `422`). i'm not sure _why_ we didn't choose something more permissive (e.g. `Optional[Dict[str, Any]]` originally (not questioning the decision, just don't know the context!)

we could of course look into making a new field on the pydantic model, or updating the type annotation to be more permissive, but i'm a bit reluctant to do that unless we've got a concrete need to at this point, just to avoid unnecessary fideslang updates.

let me know what you think!

**Comment by TheAndrewJackson** [comment]
ahh, that makes sense. I actually ran into this limitation when working on the web scanner. I overloaded the `meta` property to allow for `dicts` and lists. The schema I was using looked something _roughly_ like this. 

```json
{
  "web_scan": {
    "domains": [
      {
        "url": "***",
        "cookies": [
          "***",
          "***",
          "***",
        ]
      }
    ]
  }
}

```

I think we talked about updating the type annotation to be more permissive with that field. It might make sense to allow users to store whatever they need in it if we've ran into it a couple of times.

Do you think it would be useful to update the type annotation on it? Maybe we can create a ticket in fideslang and have some discussion about it there

**Comment by adamsachs** [comment]
created https://github.com/ethyca/fideslang/issues/111, closing this issue out now since i think the spike has run its course 😄
