### ISSUE TITLE
Update Google Tag Manager (GTM) plugin to subscribe to "events" for preference changes

### ISSUE THREAD

**Issue by eastandwestwind** [ethyca/fides#3348]
As a web developer, I want to add the Fides components to my site and have a simple way to automatically trigger events in my Google Tag Manager (GTM) so that I can enforce consent on my tags via GTM.

Details

Basically, we should update the existing `Fides.gtm()` plugin to automatically subscribe to events

We need to ensure that the GTM data layer is updated whenever the preferences change, including:

- Initializing the script to “defaults” based on the user’s geolocation
- User saving their preferences from the modal
- User rejecting all notices from the banner
- User accepting all notices from the banner

etc.

AC

- When I’ve added Fides consent to my site, then I can call window.Fides.gtm() to enable the Google Tag Manager plugin
- When I’ve enabled the Google Tag Manager plugin, then I should receive an event in GTM when the window.Fides.consent object is initialized
- When I’ve enabled the Google Tag Manager plugin, then I should receive an event in GTM when the `window.Fides.consent` object is updated by the user (saving preferences from modal, rejecting notices from banner, accepting notices from banner, etc.)

**Comment by NevilleS** [comment]
Did some quick research and this is super simple - just need to do `dataLayer.push({ event: "<event name>", ...eventData })`

See https://developers.google.com/tag-platform/tag-manager/web/datalayer

**Comment by NevilleS** [comment]
Closed by https://github.com/ethyca/fides/pull/3454

**Comment by Roger-Ethyca** [comment]
moving to done
