### ISSUE TITLE
Port over Dataset Connector Configuration to system portal

### ISSUE THREAD

**Issue by TheAndrewJackson** [ethyca/fides#3370]
# Description
This entails converting the dataset configuration tab into a form field and integrating into the connector configuration form.

## Acceptance criteria
- Only shows up for database and saas connectors
- yaml editor is readonly for saas connectors
- yaml editor is only editable for database connectors on creation

**Comment by Kelsey-Ethyca** [comment]
![Image](https://github.com/ethyca/fides/assets/101993653/a20c74e7-56b1-4cb1-a7b1-cddd2877fec2)
