### ISSUE TITLE
Refactor initialization of `fides-js` to handle privacy notice defaults

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3377]
### Is your feature request related to a specific problem?

Currently, `fides-js` only makes consent defaults via the config file. It needs to be able to handle creating defaults from privacy notices.

### Describe the solution you'd like

A few things:
* [x] The function [makeConsentDefaults](https://github.com/ethyca/fides/blob/main/clients/fides-js/src/lib/cookie.ts/#L192) should take an additional parameter `experience`.
  * [x] If an `experience` is passed in, it should derive its defaults from the privacy notices, _not_ the config. This also needs to still respect GPC!
  * [x] Otherwise, keep the current config logic
* [x] This means that in the [`init` function for fides-js](https://github.com/ethyca/fides/blob/main/clients/fides-js/src/fides.ts#L117) we need to set the defaults _after_ getting an experience
  * [x] Additionally, setting the `_Fides` object should be the last thing that is done in this function
* [x] `initOverlay` no longer needs to take `consentDefaults` (since `<Overlay />` no longer uses it)
* [x] The current TODO for gpc can go after everything is initialized.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by eastandwestwind** [comment]
Will be complete as part of https://github.com/ethyca/fides/pull/3361. See commit- https://github.com/ethyca/fides/pull/3361/commits/0bfa1a5b47cbddd34d2e4a0313e18a2aae93b7c0

**Comment by Roger-Ethyca** [comment]
moving to done
