### ISSUE TITLE
Update front-end to show values and hide sensitive values

### ISSUE THREAD

**Issue by galvana** [ethyca/fides#3380]
Blocked by design decision needed in https://github.com/ethyca/fides/issues/3537

**Comment by TheAndrewJackson** [comment]
Is this for sprint 11?

**Comment by Kelsey-Ethyca** [comment]
There should be no eye icon to show the sensitive data

**Comment by Roger-Ethyca** [comment]
moving to done
![Image](https://github.com/ethyca/fides/assets/115798183/988bbdd2-1b29-4b73-b71c-77c6abf1da63)
automated test added
