### ISSUE TITLE
Import autogenerated typescript types from a shared package

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3400]
### Is your feature request related to a specific problem?

Right now, whenever one of our frontend apps wants to utilize a backend type, we either:
1. For admin-ui: run `npm run openapi:generate` in the `admin-ui` folder which generates types into [`admin-ui/types/api`](https://github.com/ethyca/fides/tree/main/clients/admin-ui/src/types/api)
2. For privacy-center: copy the relevant types into the `privacy-center` folder in [`privacy-center/types/api/`](https://github.com/ethyca/fides/tree/main/clients/privacy-center/types/api)
3. For fides-js: copy the relevant types into the `fides-js` folder in one file [`consent-types.ts`](https://github.com/ethyca/fides/blob/main/clients/fides-js/src/lib/consent-types.ts)

This results in copies of types often being out of date.

### Describe the solution you'd like

We should keep our autogenerated typescript types (the output from `npm run openapi:generate`) in a shared separate package which all of these projects can import from. Now that we have turbo set up, this should be easier to iterate on.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

See here for more details: https://github.com/ethyca/fides/pull/3340#discussion_r1210455050

**Comment by rsilvery** [comment]
@allisonking  is this still tech debt we should address?

**Comment by allisonking** [comment]
Yup
