### ISSUE TITLE
Clickable Region for Dropdown Select Items Too Narrow

### ISSUE THREAD

**Issue by RobertKeyser** [ethyca/fides#3414]
### Bug Description

In the picture below, representing the "Select Status" dropdown on the privacy request page, the clickable region for a checkbox is shown in blue. The surrounding green (the padding) is not clickable and interferes with normal use of the dropdown.

<img width="237" alt="image" src="https://github.com/ethyca/fides/assets/39230492/ae76cf65-fa36-4969-992a-67a56685852c">

If you click slightly above or slightly below that blue region, no changes will be registered. Similarly, hovering over the select items highlights them, which makes it appear as though clicking will do something—but this is not the case.

#### Steps to Reproduce

https://www.loom.com/share/5990712874b64aa7a74d59a80f57aada

### Expected behavior

* Clicking while highlighted should toggle the checkbox
* Clicking anywhere within the item's region should toggle the checkbox

### Environment

* Version: all
* OS: Mac
* Browser: tested only on chromium based browsers

**Comment by rsilvery** [comment]
Linked here: https://ethyca.atlassian.net/browse/PROD-765
