### ISSUE TITLE
Double-dot treated as valid Fides Key in System UI

### ISSUE THREAD

**Issue by RobertKeyser** [ethyca/fides#3415]
### Bug Description

`Add System` dialog allows invalid input for the `System Fides key` field. In the screenshot below, a double dot is seen as valid input. 

<img width="581" alt="image" src="https://github.com/ethyca/fides/assets/39230492/14ce53d1-f78a-4855-bc20-f3c6d778f332">

Upon creating the system, it can't be updated or deleted, because the browser interprets the double-dot in the URL to mean going up a folder, so API requests are sent to the wrong URL.

#### Steps to Reproduce

1. Browse to `/add-systems/manual?step=2`.on your favorite Fides instance to start adding a system
2. Give it any name and description, in the `System Fides key` field, type `..`
3. Click save
4. Browse to `/systems`
5. Click the three-dot menu on your newly created system and select `Delete System`
6. Click `Continue`
7. Receive toast error message stating that `Method not allowed`, because the Admin UI tried to delete from `api/v1/?resource_type=system` instead of `api/v1/<fides_key>?resource_type=system`

### Expected behavior

* Admin UI should have flagged it as invalid
* Backend should have flagged it as invalid

### Environment

* Version: Tested on 2.13.0; likely other versions too

**Comment by rsilvery** [comment]
Going to mark this as closed since system key is no longer editable.
