### ISSUE TITLE
Parallelize docker publishing

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#3422]
### Is your feature request related to a specific problem?

The Docker publish job takes almost 2 hours in some cases, or an hour at best

### Describe the solution you'd like

Parallelize the commands so that we can build the 3 different images separately

Example Workflow: https://github.com/ethyca/fides/actions/runs/5203045330/jobs/9385379072

**Comment by Roger-Ethyca** [comment]
moving to done
