### ISSUE TITLE
Update fides-js components to pull from updated fields

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3425]
### Is your feature request related to a specific problem?

After https://github.com/ethyca/fides/pull/3387 's refactor, the fides components in `fides-js` and privacy center will need to be updated to use those values.

### Describe the solution you'd like

Updates needed:

In `fides-js`:
* Respect the new `PrivacyExperience.show_banner` field instead of `delivery_mechanism`
* Privacy preferences link 
* Save button 
* Privacy policy link label and url

In privacy center:
* Save button
* Privacy policy link label and url

Also note that some fields were renamed:
* `confirmation_button_label` --> `accept_button_label`
* `acknowledgement_button_label` --> `acknowledge_button_label`
* `banner_title` and `component_title` --> `title`
* `banner_description` and `component_title` --> `description`

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

[This is a good diff](https://github.com/ethyca/fides/pull/3387/files#diff-01ab5a1d5ef436ab324dbbeeea7037a7e57d678fdc88986b0ef6c535a8709d1e) to see what has changed

**Comment by pattisdr** [comment]
There's also a new `PrivacyExperience.show_banner` field! This dynamically calculates if you should show a banner for the experience given the notices, and the value of ExperienceConfig.banner_enabled.

**Comment by allisonking** [comment]
> There's also a new `PrivacyExperience.show_banner` field! This dynamically calculates if you should show a banner for the experience given the notices, and the value of ExperienceConfig.banner_enabled.

Amazing!! Will update the description 💥

**Comment by allisonking** [comment]
Closed by https://github.com/ethyca/fides/pull/3442

**Comment by Roger-Ethyca** [comment]
moving to done
