### ISSUE TITLE
Fix Snowflake UserWarning

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#3433]
### Is your feature request related to a specific problem?

Extra unintended output while running the CLI

### Describe the solution you'd like

Pin the version to fix the warning

### Additional context

![image](https://github.com/ethyca/fides/assets/5105354/424393b5-e88f-45a6-ac54-e068399860b2)

**Comment by Kelsey-Ethyca** [comment]
no more warning 👍
