### ISSUE TITLE
Sample app removes dynamic tags (script, style, etc.) from <head> during page load, nav, etc. 

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#3437]
### Bug Description

When testing some of the new `fides.js` features we've run into a curious problem with styling. On a fresh page load with the banner in place, the CSS styles are lost which results in a completely unstyled banner:
![image](https://github.com/ethyca/fides/assets/1834295/f051b3cd-bc1d-4cf2-ae95-2645f964458a)

After some investigation, it turns out what happens is this:
* As the page loads, the `<script>` for `fides.js` runs synchronously in the `<head>`
* `fides.js` injects a `<style>` tag to the `<head>` component and everything is OK
* NextJS client continues rendering, and while reconciling/hydrating/?/etc. it's `next/head` component it seems to remove dynamic tags

If you carefully add some `debugger` statements you can see our `<style>` tag get added and removed 😢 

It looks like this is caused by some of the inherent behaviour of NextJS, see this issue for the gory details: https://github.com/vercel/next.js/issues/11012

This issue has been marked closed, but only recently and we're a behind on our NextJS versions so it's not too practical to upgrade for that alone.

#### Steps to Reproduce

1. Set up a local test environment with the overlay (banner) enabled for Cookie House
1. Open Cookie House so that the banner appears
1. Refresh the page, change the location, etc.

### Expected behavior

No matter what happens, our `<style>` tag needs to be preserved!

### Screenshots

See above

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

This is a footgun in how NextJS handles the `<head>` tag that appears to also impact usage of GTM, etc. I think the right thing to do here is likely to try out `next/script` and see if that more "encouraged" approach avoids this issue altogether...?

**Comment by NevilleS** [comment]
Closed by #3447

**Comment by Roger-Ethyca** [comment]
moving to done
