### ISSUE TITLE
Investigate fides-js font options

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3440]
### Is your feature request related to a specific problem?

It's difficult to ship a font in fides-js that matches the design since `Inter` is not a browser default. We should investigate what options we have for fonts that can still play nicely with a customer's website.

### Describe the solution you'd like

Let's make a plan for what to do about fonts!

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

https://github.com/ethyca/fides/pull/3429#discussion_r1214402591

**Comment by rsilvery** [comment]
@allisonking  is this still an issue?
