### ISSUE TITLE
Render acknowledge button when there are only `notice_only` notices

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3443]
### Is your feature request related to a specific problem?

Our `fides-js` banner currently always renders 3 buttons—Manage preferences, Reject, and Accept, no matter what kind of notice we have. 

Notice only notices also have to be disabled and permanently set to `true`

### Describe the solution you'd like

If there are only `notice_only` notices, we should render an "acknowledge" button instead, and wire up the user preference to pass "acknowledge"

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

Design: https://www.figma.com/file/dmEwdK3xZwjKfGVQ9t66xe/Fides-v.2-Master-Working-Files?type=design&node-id=6980-351571&t=6PGfme4Uozj1lLtz-0

**Comment by allisonking** [comment]
A few questions:
* Do we still render the modal if there are only notice only notices? There's no "Manage preferences" link in the design
  * If yes: they wouldn't be able to change anything, so do we just render one acknowledgment button?
  * If no: then do we also keep a user's link that they use to open up the modal hidden?
* Same question for the privacy center, what should that page look like when there are only notice only notices?

**Comment by allisonking** [comment]
@mfbrown answered in standup today: yes, we should still show the modal, and then we need the modal to also the conditional acknowledge button

**Comment by Roger-Ethyca** [comment]
moving to done
