### ISSUE TITLE
Make `fides-js` banner responsive

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3444]
### Is your feature request related to a specific problem?

Currently our banner takes up the full width of the screen at every screen size.

### Describe the solution you'd like

There are designs for the banner at different break points. We should implement them!

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

Design: https://www.figma.com/file/dmEwdK3xZwjKfGVQ9t66xe/Fides-v.2-Master-Working-Files?type=design&node-id=6967-208299&t=qGHHmWQyWsAPeCOw-0

**Comment by allisonking** [comment]
Closed by https://github.com/ethyca/fides/pull/3466

**Comment by Roger-Ethyca** [comment]
moving to done 


![Image](https://github.com/ethyca/fides/assets/115798183/1f550bf5-6a72-4561-9c89-0e4ee58689a3)
![Image](https://github.com/ethyca/fides/assets/115798183/9445cc17-44f7-494f-ae36-269aac1cd55f)
