### ISSUE TITLE
Unable to dismiss Fides.js banner or modal

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#3459]
### Bug Description

In the current setup it's not possible to dismiss the banner or modal, which is confusing!

#### Steps to Reproduce

1. Run the E2E tests locally and view the banner or modal
2. Try to dismiss them via a "X" button, hitting "ESC", etc.

### Expected behavior

I'd expect a couple options:
- [x] A visible "X" button to dismiss the banner
- [x] A visible "X" button to dismiss the modal
- [x] Pressing ESC to dismiss the modal

### Screenshots

<img width="1680" alt="image" src="https://github.com/ethyca/fides/assets/1834295/075bac4b-7471-4cbb-a719-38de906aa98b">
<img width="1680" alt="image" src="https://github.com/ethyca/fides/assets/1834295/541f1a13-3768-4448-bde2-c29cbfed65e2">

**Comment by Roger-Ethyca** [comment]
moving to done

![Image](https://github.com/ethyca/fides/assets/115798183/c5801970-6129-4d43-8def-cbb9ccc4e18d)
