### ISSUE TITLE
Improvements to filtering of resources for scan and generate system commands

### ISSUE THREAD

**Issue by earmenda** [ethyca/fides#346]
Fidesctl being extended to support scanning of infrastructure components could make it possible to annotate where organizations store their data. Knowing where pii data is stored is important for allowing users to meet RoPA requirements. 

As part of #343 we added filtering of resources using the organization model to store filters. This issue focuses on the abiility to improve those capabiities 

Requirements:
* Integrate with tagging api in aws to tag resources which users want to ignore

Other Potential Imporovements:
* Tagging updates for resourcees within fidesctl
* Improve the ability to tag at the organization level with new cli command

**Comment by Kelsey-Ethyca** [comment]
closing all tickets older than a year as not planned
