### ISSUE TITLE
Fides.js modal overlay blocks interaction with the website

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#3460]
### Bug Description

In this screenshot, there is an (invisible) modal overlay div that covers the entire page and prevents my ability to click any of the Cookie House buttons, etc.
<img width="1680" alt="image" src="https://github.com/ethyca/fides/assets/1834295/488834bc-6fdd-452b-ab79-57552db4a849">

This is surprising - although we call this component a "modal" I'd expect it to be more like a dialog so I should still be able to scroll the page, click on buttons, etc.

#### Steps to Reproduce

1. Run the E2E test environment locally
1. Open the modal
2. Try to click on any of the Cookie House elements

### Expected behavior

Scrolling & clicking in the original website continue to work

**Comment by allisonking** [comment]
Closed by https://github.com/ethyca/fides/pull/3480

**Comment by Roger-Ethyca** [comment]
moving to done
