### ISSUE TITLE
Remove PrivacyExperienceHistory and Duplication b/t Experiences and Configs

### ISSUE THREAD

**Issue by pattisdr** [ethyca/fides#3465]
### Is your feature request related to a specific problem?

A continuation of the removal of the "delivery mechanism" constraint -

Now that several of the constraints have been lifted between notices and experiences, we are duplicating too much information on PrivacyExperience that is also on PrivacyExperienceConfig.   The introduction of loading in ExperienceConfigs by default is highlighting how there are too many things to keep in sync between PrivacyExperiences and PrivacyExperienceConfigs.  We need to have one source of truth.

Our data model has PrivacyNotices, PrivacyExperiences (for a specific region) and have a FK to Privacy Experience Configs, which contain the copy.  There are a few duplicate fields on PrivacyExperiences and PrivacyExperienceConfigs which are hard to keep in sync, and we are unnecessarily versioning PrivacyExperience.

### Describe the solution you'd like

- Remove disabled, privacy_experience_config_history_id and version fields from PrivacyExperience. 
   - Look to the associated PrivacyExperienceConfig to determine if the resource is disabled.
- Remove the PrivacyExperienceHistory table.  Since we've made some changes that you can't change the type of config once it's created, there's no real need to version this experience any longer.
- When saving privacy preferences, save the privacy experience id rather than the privacyexperiencehistory id (which I'm removing)

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by Roger-Ethyca** [comment]
moving to done
