### ISSUE TITLE
Fides.js must *guarantee* instant initialization of saved consent preferences (to Fides.consent, GTM, etc.)

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#3469]
### Bug Description

Right now, I'm not 100% certain that we can guarantee that the Fides.js script will instantly load saved preferences into the `Fides` object if you already have a `fides_consent` cookie saved locally to your browser. This is important because:
1. It makes it much easier to document & explain the Fides.js behaviour when this is guaranteed
2. It maximizes page load performance for returning visitors
3. It provides clear backwards-compatibility with the existing, statically-configured consent options

This might *already* work, but feels fragile based on the current test harness and initialization logic.

#### Steps to Reproduce

1. Save existing preferences to a `fides_consent` cookie
2. Test that Fides.js initializes instantly with the overlay disabled
3. Test that Fides.js initializes instantly with overlay enabled and geolocation enabled
4. etc.

### Expected behavior

No matter what configuration, it should be guaranteed to initialize instantly when saved preferences exist.

**Comment by NevilleS** [comment]
Tested this in GTM, and confirmed that we need to add an "early-initialization" for saved preferences.

**Comment by NevilleS** [comment]
Closed by #3503

**Comment by Roger-Ethyca** [comment]
moving to done
