### ISSUE TITLE
Corresponding FE update for fields that were cleaned up with delivery mechanism

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3472]
### Is your feature request related to a specific problem?

https://github.com/ethyca/fides/pull/3470 makes a few more changes to the backend regarding privacy experiences.

### Describe the solution you'd like

We need to make a small FE update to make sure this doesn't break anything. From @pattisdr :
> The main change from a front end perspective is that when we're saving preferences in the privacy center and in components, we need to pass in the "privacy_experience_id" instead of the "privacy_experience_history_id" (as the latter no longer exists).  This is important for recording which experience the user was presented.
> There's a few schema changes too, some fields have been removed from PrivacyExperiences - for example, version/is_disabled, etc., these fields are now only on the ExperienceConfig.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

We'll need to update our TS types. Once those types are updated, the fields that need to be changed should become very clear (because of TS errors!)

**Comment by allisonking** [comment]
Closed by https://github.com/ethyca/fides/pull/3479

**Comment by Roger-Ethyca** [comment]
moving to done
