### ISSUE TITLE
Evaluate possible race condition in link rendering for fides.js

### ISSUE THREAD

**Issue by eastandwestwind** [ethyca/fides#3483]
I have a feeling there's a bug here... it's a race condition. What if the link renders to the page after our render method fires?

I think the safest thing to do is not gate _any_ overlay rendering logic on the existence of that link, and throw it into a delayed interval - wait like 200ms and then check the DOM if it exists and add the click handler then, etc.

Sorry!

You can carve that out into a follow-up issue though, as long as it's not going to cause any other problems?

_Originally posted by @NevilleS in https://github.com/ethyca/fides/pull/3467#discussion_r1220479416_

**Comment by eastandwestwind** [comment]
Note that implementing a delay before we show the link will also solve this possible scenario- https://github.com/ethyca/fides/issues/3488. Since we animate the banner on a 100 ms delay, using. 200 ms delay to show the link will ensure that we are never in a state that the user can click the link before the banner is displayed.

**Comment by Roger-Ethyca** [comment]
moving to done
