### ISSUE TITLE
Default privacy notices / experience configurations aren't packaged into the PyPI build

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#3484]
### Bug Description

Subtle one - since the default notices are saved in `/data` instead of `/src/fides/data` they won't be accessible in the PyPI package, and therefore only work via our `ethyca/fides` Dockerfile.

This affects our Fidesplus image immediately because we rely on the Python import 👍 

### Expected behavior

We'll need to move those data files into the `/src` package or otherwise reconfigure the MANIFEST.in, etc.

### Environment

* Version: 2.14.1b1
* OS: macOS
* Python Version: 3.9
* Docker Version: 20.10.24

**Comment by Roger-Ethyca** [comment]
moving to done
