### ISSUE TITLE
Annotate Dataset Should Allow Updating Other Attributes

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fides#349]
### Is your feature request related to a specific problem?

Currently, the `annotate-dataset` command allows a user to update the `data_categories`. As a user, I would like to be able to use that workflow to annotate other attributes as well, such as `retention`.

### Describe the solution you'd like

Update the `annotate-dataset` workflow to handle more attributes than `data_category`

### Describe alternatives you've considered, if any

Currently, updating the resource manually is a viable workaround. As an example, `retention` at the field level may only apply in specific cases but I would like to apply the retention at the same time as annotating the dataset.

### Additional context

Multiple attributes and taxonomies are being added/modified as part of the data map project. As a follow on issue to that effort, circling back to improve usability around the changes will continue to improve the user experience

**Comment by ThomasLaPiana** [comment]
I totally see your point here, but in the context of datasets already being extremely inaccessible, I think this might make it even more difficult. Maybe up front we can ask users what parts of the dataset they'd like to annotate? so for instance they can skip `retention` entirely if they don't care, or have the option to include that as something they annotate

**Comment by SteveDMurphy** [comment]
Thanks for the thoughts @ThomasLaPiana !
I think the idea of having it optional makes a lot of sense, challenges with datasets have become much more clear to me since writing this up.

I'd also like to explore the idea of removing any other attribution from the dataset to keep it as simple as possible, maybe associate `retention` with the data category used instead as an example.

Assuming for instance a system wanted to retain contact info until account terminated, it would be more clear to implement something at the data category level once instead of every field so that fidesops could pick up on it with less user overhead and consistently applied coverage 🤷🏽

**Comment by Kelsey-Ethyca** [comment]
closing all tickets older than a year as not planned
