### ISSUE TITLE
SaaS connector masked_object_fields aren't unflattened correctly

### ISSUE THREAD

**Issue by galvana** [ethyca/fides#3493]
### Bug Description

For SaaS connectors, there are scenarios when we need to mask nested JSON data
```
{
  "emails": [
    {"original": "abc@example.com"}
  ]
}
```

The result we get at the moment after masking is this
```
{
  "emails": {
    "0": {
      "original": "MASKED_VALUE"
    }
}
```
The array is unflattened incorrectly and is represented as an object with each value corresponding to its index. The expected value is this
```
{
  "emails": [
    {"original": "MASKED_VALUE"}
  ]
}
```
The issue is with the `saas_util.unflatten_dict` function, it needs to handle this nested array use case.

**Comment by Roger-Ethyca** [comment]
moving to done
