### ISSUE TITLE
Consent modal doesn't show saved preferences until reloading

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#3514]
### Bug Description

If you adjust preferences on the consent modal, everything *saves* correctly but if you close and reopen the model it doesn't reflect your updated preferences.

#### Steps to Reproduce

1. Clear all your cookies from cookiehouse-plus-rc.fides-staging.ethyca.com
2. Open https://cookiehouse-plus-rc.fides-staging.ethyca.com/?geolocation=US-CA
3. Close the banner (if it's enabled)
4. Click "Manage Preferences" to open the modal
5. Click "Opt-out of all"
6. Confirm `window.Fides.consent.data_sales_and_sharing === false`, which is true!
7. Reopen the modal
8. Observe that the "Data Sales" toggle incorrectly shows as opted-in
9. Reload the page & reopen the modal
10. Observe that the "Data Sales" toggle shows as opted-out now

### Expected behavior

Whenever a preference changes from saving/accept all/reject all, reloading the modal should show the newly saved preference.

### Screenshots

https://www.loom.com/share/f77701b658d242f7a7574523ea98dcc3

### Environment

* Version: 2.15.0rc0

**Comment by Roger-Ethyca** [comment]
moving to done
