### ISSUE TITLE
Legacy/deprecated data uses still exist post-1.4 migration

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#3515]
### Bug Description

When I update to our `2.15.0rc0` release, we've an automated migration that runs to add the new `fideslang` 1.4 data uses, notably the revised `marketing.*` taxonomy as see here in the system panel:
<img width="685" alt="image" src="https://github.com/ethyca/fides/assets/1834295/c8602423-3ace-44f0-a537-1d6ac9772140">

However, I'm also still able to browse and select legacy data uses like `advertising` (which was migrated to `marketing.advertising`):
<img width="689" alt="image" src="https://github.com/ethyca/fides/assets/1834295/2cce44fb-9751-4aae-9248-f9d4946c49e5">

This is likely to attempt to be less destructive, but it's confusing to have both options now.

#### Steps to Reproduce

1. Visit https://fides-plus-rc.fides-staging.ethyca.com/systems/configure/google_ads
2. Add a new Data Use and open the "Data use" select to browse the taxonomy
3. Observe that the `advertising.*` taxonomy still exists

### Expected behavior

The legacy data uses should no longer be available in the system.

### Screenshots

See description

### Environment

* Version: 2.15.0rc0

**Comment by ThomasLaPiana** [comment]
@NevilleS this was most definitely a deliberate choice to make things less destructive, and avoid things blowing up in ways we didn't foresee. If we want to go this nuclear route, we definitely can by updating the Migration to also target the `data_use` table which we purposefully left out

I can also 100% understand how it is confusing though...we'll just need to make sure we message this breaking change

**Comment by NevilleS** [comment]
Hmm - if we want to _stage_ that migration over a release or two to be careful, that's reasonable... but we need to prevent people continuing to use `data_use` values that we want to be able to delete. The current solution doesn't really work - if they continue to be returned by the API and accepted for new records, we're just opening the door to those lingering around forever

**Comment by ThomasLaPiana** [comment]
Agreed, it's slippery

We could warn people _every_ time they use an old data use for a release or two but if its via the API I'm not sure it would really help. Maybe via the UI?

Or we could just consider it a band-aid pull

**Comment by NevilleS** [comment]
Retested this after the change to delete deprecated data uses in #3528, this is fixed 👍
