### ISSUE TITLE
FE: Remove dataset field from system integrations tab for saas connectors

### ISSUE THREAD

**Issue by TheAndrewJackson** [ethyca/fides#3518]
# Description
The dataset dropdown and YAML editor are being removed from connection configuration. This is because datasets are automatically managed by fides. Any changes that are made to the dataset will be wiped out when the saas connector template is updated.

```[tasklist]
### Tasks
- [ ] Remove the dataset dropdown from the system integrations tab for saas connectors
```

**Comment by Roger-Ethyca** [comment]
moving to done
