### ISSUE TITLE
[Spike] Investigate removing unique constraint for `DatasetConfig.fides_key`

### ISSUE THREAD

**Issue by TheAndrewJackson** [ethyca/fides#3524]
# Description
There is a required `fides_key` column on the `DatasetConfig` table that has a unique constraint. This is a legacy column from pre-unified-fides. It looks like it might be unnecessary. Investigate if this column can be removed.

It's also possible that the entire `DatasetConfig` table is no longer needed now that fides is unified. Investigate if it's still required.

CC: @rsilvery @galvana

**Comment by TheAndrewJackson** [comment]
cc: @seanpreston

**Comment by rsilvery** [comment]
@seanpreston  (or @NevilleS ) can you weigh in on this for Andrew?

**Comment by NevilleS** [comment]
Hey @TheAndrewJackson - you can check in with @pattisdr on the data model for ctl_datasets / datasetconfig. On a quick inspection of the model, the `fides_key` is used to point to the `Dataset`, so what you'll want to understand is why the `DatasetConfig` model does and how it is used to glue together the Dataset & ConnectionConfig models, etc.

**Comment by rsilvery** [comment]
@adamsachs  was this fixed with the recent data model changes?

**Comment by adamsachs** [comment]
> @adamsachs was this fixed with the recent data model changes?

don't think so - our recent changes didn't impact the `DatasetConfig` model at all, and i still see the unique constraint in the code.

i've got no context on this issue though and its motivation, so i'm not the best one to know whether this is still a _problem_ or to evaluate its priority!

**Comment by TheAndrewJackson** [comment]
@adamsachs This is probably a lower priority issue but would be nice to have. It would make the code be more clear in that area.

In a nutshell, the `DatasetConfig` model used to have a dataset stored on it before unified fides. After it was unified that column was dropped in favor of the `Dataset` model. 

The unique constraint on the `DatasetConfig.fides_key` was to ensure that the dataset stored on it had a unique id. AFAIK that column isn't really used for anything anymore and it caused confusion during the connection config UI refactor.
