### ISSUE TITLE
Readme Quick Start: Consider making all bulleted titles to be fully executable

### ISSUE THREAD

**Issue by banagale** [ethyca/fides#353]
### Docs Update Description

In the main README.md, Quick Start steps 2 and 4 have:

"Results of `fidesctl evaluate`" 
and
"Run `fidesctl evaluate` again" as the bulleted titles to the expandable explanatory text.

This issue is to suggest using the full command in these bullets:

"Results of `fidesctl evaluate demo_resources/`" and "Run `fidesctl evaluate demo_resources/`"

This tracks with step 3, which includes the complete step: "Run `cat demo_resources/demo_policy.yml`"

To avoid too much repetition, 2. could begin, "Run `fidesctl evaluate` on the  `demo_resources/` folder." This keeps each step's explanatory paragraph focused on what-is-to-be-done, and allows all of the bulleted titles to be executed successfully in order.

### Additional context

Suggesting this because in step 4 I copy-pasted `fidesctl evaluate` alone and got unexpected green output that looked like success.

**Comment by iamkelllly** [comment]
Thanks for adding this @banagale - this is great feedback! Take a look at the PR #356 and see if this matches your expectation!

**Comment by banagale** [comment]
You're welcome! Thanks for the rapid response.

I offered some minor additional suggestions in a review of #356. Take 'em or leave 'em, and feel free to close this issue at will!
