### ISSUE TITLE
`Set-Output` GH Action is being Removed

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#3531]
### Is your feature request related to a specific problem?

See the warnings here: https://github.com/ethyca/fides/actions/runs/5229102877

### Describe the solution you'd like

We need to come up with a different solution for some of our logic within the CI pipelines

### Describe alternatives you've considered, if any

We could pass the version into `nox` directly and do the regex checks there, removing all of the logic from the CI workflow and putting it directly into the nox file (this also makes it testable)

**Comment by ThomasLaPiana** [comment]
@adamsachs Flagging this because I don't want our release workflows to screech to a halt! Going to assign this to next sprint

**Comment by RobertKeyser** [comment]
Just throwing this out there, there's a new way to do the outputs. 

 `run: echo MY_OUTPUT=$(echo -n "output") >> $GITHUB_OUTPUT`

I solved this on some internal repos, so let me know if you'd like me to try it out here.

**Comment by ThomasLaPiana** [comment]
@RobertKeyser I would be stoked if you tried it out here 😄

**Comment by RobertKeyser** [comment]
Opened https://github.com/ethyca/fides/pull/3567 to try it out.

**Comment by Roger-Ethyca** [comment]
moving to done
