### ISSUE TITLE
Underscore in Postgres Username leads to: `Could not parse rfc1738 URL from string`

### ISSUE THREAD

**Issue by RobertKeyser** [ethyca/fides#354]
### Bug Description

When creating a fidesctl webserver in a Docker container with a separate database, I get the following error (all values changed to substitutes for the sake of example)

```
  | 2022-02-09T14:37:39.685-06:00 | Traceback (most recent call last):
  | 2022-02-09T14:37:39.685-06:00 | File "/usr/local/bin/fidesctl", line 33, in <module>
  | 2022-02-09T14:37:39.686-06:00 | sys.exit(load_entry_point('fidesctl', 'console_scripts', 'fidesctl')())
  | 2022-02-09T14:37:39.686-06:00 | File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
  | 2022-02-09T14:37:39.686-06:00 | return self.main(*args, **kwargs)
  | 2022-02-09T14:37:39.686-06:00 | File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
  | 2022-02-09T14:37:39.686-06:00 | rv = self.invoke(ctx)
  | 2022-02-09T14:37:39.686-06:00 | File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1289, in invoke
  | 2022-02-09T14:37:39.686-06:00 | rv.append(sub_ctx.command.invoke(sub_ctx))
  | 2022-02-09T14:37:39.686-06:00 | File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
  | 2022-02-09T14:37:39.687-06:00 | return ctx.invoke(self.callback, **ctx.params)
  | 2022-02-09T14:37:39.687-06:00 | File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
  | 2022-02-09T14:37:39.687-06:00 | return callback(*args, **kwargs)
  | 2022-02-09T14:37:39.687-06:00 | File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
  | 2022-02-09T14:37:39.687-06:00 | return f(get_current_context(), *args, **kwargs)
  | 2022-02-09T14:37:39.687-06:00 | File "/fides/fidesctl/src/fidesctl/cli/cli.py", line 292, in webserver
  | 2022-02-09T14:37:39.687-06:00 | from fidesapi.main import start_webserver
  | 2022-02-09T14:37:39.687-06:00 | File "/fides/fidesctl/src/fidesapi/main.py", line 66, in <module>
  | 2022-02-09T14:37:39.687-06:00 | configure_db()
  | 2022-02-09T14:37:39.687-06:00 | File "/fides/fidesctl/src/fidesapi/main.py", line 34, in configure_db
  | 2022-02-09T14:37:39.687-06:00 | database.create_db_if_not_exists(databse_url)
  | 2022-02-09T14:37:39.687-06:00 | File "/fides/fidesctl/src/fidesapi/database.py", line 49, in create_db_if_not_exists
  | 2022-02-09T14:37:39.687-06:00 | if not database_exists(database_url):
  | 2022-02-09T14:37:39.687-06:00 | File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/functions/database.py", line 483, in database_exists
  | 2022-02-09T14:37:39.687-06:00 | url = copy(make_url(url))
  | 2022-02-09T14:37:39.687-06:00 | File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 711, in make_url
  | 2022-02-09T14:37:39.688-06:00 | return _parse_rfc1738_args(name_or_url)
  | 2022-02-09T14:37:39.688-06:00 | File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 777, in _parse_rfc1738_args
  | 2022-02-09T14:37:39.688-06:00 | raise exc.ArgumentError(
  | 2022-02-09T14:37:39.688-06:00 | sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'fidesctl_user:ABCDEFpassword@redacted-redacted.redacted.us-east-2.rds.amazonaws.com:5432/fidesctldb'
```

I've tried this in both AWS and Azure and received the same error. There are no special characters and it uses the format of `<user>:<password>@<host>:<port>/<database>`, which should be correct.

#### Steps to Reproduce

1. ECS Fargate running Fidesctl 1.3.1 (also tried other versions)
2. RDS in the same security group with network access
3. Deploy Fidesctl as a service to the Fargate instance. Pass in the DB as the environment variable `FIDESCTL__API__DATABASE_URL` with a value in the format of `<username_with_underscore>:<password>@<host><region>.rds.amazonaws.com:<port>/<database>`. 
4. Deploy and review cloudwatch logs

### Expected behavior

The Fidesctl instance should be up and healthy.

### Environment

* Version: Tested from `1.1.0` to `1.3.1`
* OS: Linux on Fargate
* Python Version:
* Docker Version:

### Additional context

Things I haven't checked:

* A non-docker version of the webserver
* Passing the database connection string in the `fidesctl.toml` file
* ~A username that doesn't have an underscore in it. (Which I'm still setting up the test for in AWS).~

On Azure database Postgresql, the username is in the format of `user@servername`, I tried that and also percent encoding the `@` -> `%40`, but I didn't have any luck. That's when I switched to test on AWS and ran into the same issue. 

This certainly might be a configuration issue, but it's had me spinning my gears for the past few days, so maybe some parameter validation or documentation might be a good idea.

### Edit
Found that the cause was that my username was `fides_user`. Once I switched to `fidesuser` it worked.

**Comment by ThomasLaPiana** [comment]
@RobertKeyser thanks for this ticket! It should get resolved by #355

**Comment by ThomasLaPiana** [comment]
@RobertKeyser thats been merged to main, can you confirm it works for you now when using the version on main?

**Comment by ThomasLaPiana** [comment]
@RobertKeyser I tested this locally and it worked for me, I'll close this issue if you confirm it looks good for you too
