### ISSUE TITLE
Improve HTTP Response Code Use - `422`

### ISSUE THREAD

**Issue by RobertKeyser** [ethyca/fides#357]
### Bug Description

We use `422: Unprocessable Entity` to represent a validation error in resources. `422`, however, should be used when the *syntax* is correct, but the content or context cannot be processed. In other words, the server is able to understand the message, but there's something that is stopping it from processing it, e.g. a semantic issue.

Sending a correct json syntax but invalid schema (e.g. trying to upload a policy to the `/system` endpoint results in the `422`, which seems correct; however, sending invalid JSON with a completely bogus payload results in the same error status. Instead of a `422`, we should return a `400: Bad Request`. They both suggest that the request should not be retried without modifications, but it would offer a more accurate feedback to HTTP calls.

#### Steps to Reproduce

1. Set up Fidesctl server
2. `curl -X PUT http://<your_server_here>/system -H 'Content-Type: application/json' -d 'not json' -L -v`
3.  Receive a `422`

### Expected behavior

Invalid JSON payloads should return a `400` instead of a `422`.

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version: tested on 1.3.1
* OS: Linux
* Python Version:
* Docker Version:

### Additional context

It might even make sense to reconsider some of the valid json `422`s we return, based on a quick search of usage.

* [RFC 7231 - HTTP/1.1 - 400](https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.1)
* [RFC 4918 - WebDAV - 422](https://datatracker.ietf.org/doc/html/rfc4918#section-11.2)

**Comment by PSalant726** [comment]
> Sending a correct json syntax but invalid schema (e.g. trying to upload a policy to the `/system` endpoint results in the `422`, which seems correct; however, sending invalid JSON with a completely bogus payload results in the same error status. Instead of a `422`, we should return a `400: Bad Request`.

This is a common point of debate, and I'm not sure there's any one correct answer that applies to all systems. IMO, a malformed request payload is the same regardless of _how_ it's malformed, and the server shouldn't be responsible for guiding the user through building a valid request (that's what documentation is for). A 400 response strongly implies missing or malformed request attributes, such as an empty header or an invalid HTTP method. In the case of a malformed request payload, I would argue that the _request_ is "good" and the _entity_ is unprocessable, thus 422.

> They both suggest that the request should not be retried without modifications, but it would offer a more accurate feedback to HTTP calls.

There are security implications related to differentiating between a "bogus" schema, and a valid schema that applies to a different endpoint. I think it's valid to say that the feedback would be more _precise_, but I question the value of that additional precision given the potential for creating a new attack vector. As you said, both response status codes suggest that the request should not be retried as-is.

I don't believe any changes should be made here.

**Comment by RobertKeyser** [comment]
@PSalant726, not my hill to die on, so I'm ok with whatever your team decides.

**Comment by ThomasLaPiana** [comment]
@RobertKeyser I appreciate the thoughtful feedback around the API design! This is the default FastAPI behavior, so I'm strongly inclined to stick with it as is. Like @PSalant726 said, this is in grey territory and I don't see a strong reason to break default behavior

are you ok with me closing this issue or do you want to invite more discussion around this?

**Comment by RobertKeyser** [comment]
Let's close it then! As long as we have a reason for this stance, we're good to go.
