### ISSUE TITLE
AT: connector template drop-down isn't enabled the first time you visit it after creating a system

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#3588]
When you add a system manually (have not tested other methods), after you save the system, it prompted you to add your data uses but if you go direction to the integrations tab, the connection type dropdown is disabled, so you have to go back to "Vew systems" and then select your edit on your system again to be able to add an integration.
https://www.loom.com/share/4b80abaf169b4e58bdfb61ff7de54dbb?sid=ef4f12e0-bccb-457a-a5b8-dbd9bd2cbc37

**Comment by Roger-Ethyca** [comment]
this is still an issue. FYI, i did test this in fidesplus. 

![Image](https://github.com/ethyca/fides/assets/115798183/90d7bcef-21f1-41e0-8c66-acfdaedfa10b)

**Comment by Roger-Ethyca** [comment]
moving to done 


![Image](https://github.com/ethyca/fides/assets/115798183/9b1fc3ee-da89-41e9-9cf6-71bc82ea90d0)
