### ISSUE TITLE
Fides.js overlay modal doesn't initialize toggles with the right opt-in/opt-out values

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#3596]
### Bug Description

When I test out a first-time visit to the Cookie House sample app with a single opt-in notice enabled (`data_sales_and_sharing`), the toggle shows as opted-out:
<img width="1440" alt="image" src="https://github.com/ethyca/fides/assets/1834295/f5a8b2d1-fb80-40dc-a518-7eb8c538218e">

#### Steps to Reproduce

1. Setup a local build with overlay enabled and an opt-in notice
2. Visit the sample app and view the modal

### Expected behavior

Toggles should display the default preference (true or false).

### Screenshots

See description

### Environment

* Version: 2.15.0rc2
* OS: macOS-13.4-arm64-arm-64bit
* Python Version: 3.9.16
* Docker Version:20.10.24, build 297e128

**Comment by Roger-Ethyca** [comment]
moving to done
