### ISSUE TITLE
`PUT` Requests on a Nonexistent Resource Should Create the Resource

### ISSUE THREAD

**Issue by RobertKeyser** [ethyca/fides#360]
### Is your feature request related to a specific problem?

When creating a resource via the API, a user must use `POST` to create the resource and `PUT` to modify it. Trying to `PUT` a new resource results in a `404` error, suggesting that the resource was not found. According to [RFC 7231](https://www.rfc-editor.org/rfc/rfc7231#section-4.3.4:~:text=The%20PUT%20method%20requests%20that%20the%20state,enclosed%20in%20the%20request%20message%20payload), "The PUT method requests that the state of the target resource be created or replaced with the state defined by the representation enclosed in the request message payload." Further, RFC 7231 states: 
> Proper interpretation of a PUT request presumes that the user agent
   knows which target resource is desired.  A service that selects a
   proper URI on behalf of the client, after receiving a state-changing
   request, SHOULD be implemented using the POST method rather than PUT.

Since our users set the `fides_keys` themselves, we should allow them to create the resource using a `PUT` request.

### Describe the solution you'd like

`PUT` requests can create Fides resources as well as modify them. If it creates the resource, it should respond with a `201`.

**Comment by PSalant726** [comment]
We should be able to repurpose the [`upsert_resources` code](https://github.com/ethyca/fides/blob/6805ee22ec24679e6b9a4650945c1c1487f78cf5/fidesctl/src/fidesapi/database/crud.py#L131) for this, but it would require that an endpoint be built around it. If we're going to touch this code, we may also want to take the opportunity to implement some improved `UPSERT` log output, re: https://github.com/ethyca/fides/discussions/246#discussioncomment-1691386

**Comment by RobertKeyser** [comment]
Didn't even realize there was already that discussion. It also seems similar to #279.

**Comment by ThomasLaPiana** [comment]
@RobertKeyser yep, this is still something I think we should implement, as the crux of this is basically "add an upsert endpoint instead of discrete create/update endpoints". The main blocker here is that there is some logic tied to the existence of these endpoints that would need to get reworked a bit but overall it would simplify the code. Thanks for the feedback!

**Comment by ThomasLaPiana** [comment]
added #279 to the 1.5.0 release, closing this issue as a duplicate
