### ISSUE TITLE
Add success and failure toasts when clicking test connection

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#3601]
Currently you get an inline success/failure message with some details about the connection test. We should be using our standard toast to indicate the test was successful or failed. Will handle test status in another ticket.

Steps to reproduce 
1. run fides test env
2. login as root user 
3. click data map in top nav 
4. click the ellipsis of any system 
5. click edit 
6. click integration tab 
7. click the dropdown and choose amplitude 
8. enter amplitude creds from 1password 
9. click save 
10. click test connection 
11. see no toast

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.

**Comment by Kelsey-Ethyca** [comment]
Hi @tarunsamanta2k20 we will start tagging more things with "good first issue" so be on the lookout for those. We need to get this ticket done quickly and already had plans to assign it to an internal dev. To answer your question though you can use `nox -s "fides_env(test)"` to spin up a test env in fides.

**Comment by rsilvery** [comment]
Hi @jpople , as we discussed earlier, could you also hide the green box that shows up below the test connection button? 


![Image](https://github.com/ethyca/fides/assets/8682444/91526363-bf00-4991-b433-90ca29c8bc12)

**Comment by Roger-Ethyca** [comment]
moving to done 


![Image](https://github.com/ethyca/fides/assets/115798183/70e93add-9a3e-4d66-a088-437d69f4dccd)
![Image](https://github.com/ethyca/fides/assets/115798183/e28d636a-1d8a-4eb1-9892-6fcee26f7794)
