### ISSUE TITLE
Include escape safestr header in fides-js and privacy center

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3606]
### Is your feature request related to a specific problem?

https://github.com/ethyca/fides/pull/3600 adds a header `unescape-safestr` which fides-js and privacy center need to pass in so that the copy renders accurately (admin-ui already passes this in)

### Describe the solution you'd like

* [x] Add the header to redux in privacy center
* [x] Add the header to all fetch calls in fides-js (might be worth making a wrapper function)

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

Otherwise things look like this:

![image](https://user-images.githubusercontent.com/24641006/246878210-5629108b-7e92-427c-ab17-716c0e622b8f.png)

**Comment by pattisdr** [comment]
good catch @allisonking!

**Comment by Roger-Ethyca** [comment]
moving to done 


![Image](https://github.com/ethyca/fides/assets/115798183/dd4e8578-6e02-4cd1-a8b4-ac3fff53f085)
![Image](https://github.com/ethyca/fides/assets/115798183/d7b9ae79-bac7-44ad-8ee7-2ac11b252512)
![Image](https://github.com/ethyca/fides/assets/115798183/21efbc75-59de-48be-afba-63c767accad7)
