### ISSUE TITLE
Add a persistent and simplified "last tested" message to the Integrations tab

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#3607]
The success message will be moved into a toast. But we need a persistent status indicator for last tested status with date. 

Here is an example of what is shown after a test passes. The message will disappear on refresh. 
![Image](https://user-images.githubusercontent.com/8682444/246130200-7ff4b67d-2d77-4dfc-adc4-1e7cb83b2beb.png)

An example of the "last tested" message exists today on the Unlinked Connections page
![Screenshot 2023-06-19 at 9 14 34 AM](https://github.com/ethyca/fides/assets/101993653/36187777-117b-4b9e-806e-0bdb788f3760)

Steps To Reproduce: 

1. run fides test env 
2. login as root_user 
3. click data map in the top nav
4. click add systems in the side nav 
5. click add a system under MANUALLY ADD SYSTEMS
6. fill in the name and key 
7. click save
8. click view systems in the side nav 
9. click the ellipsis of the system you just created 
10. click edit 
11. click the integration tab 
12. add an integration like amplitude 
13. you can find the correct creds in 1 password 
14. click save 
15. click test connection 

Acceptance Criteria: 

- On test fail, a red dot next to the message "Last tested on <Month> <day>, <year>, <time>" for example "Last tested on June 18, 2023, 09:31:28 PDT" persists after navigating away and back or after refresh. The dot and message should look like it does in the Unlinked Connections page and appear under the Test Connection button on the Integrations tab. 
- On test success, a green dot next to the message "Last tested on <Month> <day>, <year>, <time>" for example "Last tested on June 18, 2023, 09:31:28 PDT" persists after navigating away and back or after refresh. The dot and message should look like it does in the Unlinked Connections page and appear under the Test Connection button on the Integrations tab.

**Comment by Roger-Ethyca** [comment]
moving to done
