### ISSUE TITLE
New Style Consent: Only Create Privacy Requests if System-Wide Enforcement Level Exists

### ISSUE THREAD

**Issue by pattisdr** [ethyca/fides#3618]
### Is your feature request related to a specific problem?

New style consent framework creates a PrivacyRequest each time consent preferences are saved, which can flood the admin UI with too many consent requests.

### Describe the solution you'd like

Ru run an early check that if none of the privacy preferences are attached to notices that have a system wide enforcement level, then we don't create a privacy request. 

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by Roger-Ethyca** [comment]
moving to done
