### ISSUE TITLE
Saving one privacy declaration will sometimes delete others

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3619]
### Bug Description

When you create a privacy declaration on a system (in the "data use" tab), then create one more, then go back to edit the first one, the second privacy declaration that was created gets deleted.

#### Steps to Reproduce

1. Go to any system without data uses
1. Create one data use
2. Add another data use
3. Go back and edit the first data use and click 'save'
4. Navigate away from this system and navigate back to the data use tab
5. The second data use will have disappeared

### Expected behavior

No data uses should disappear on edit!!

### Screenshots

https://github.com/ethyca/fides/assets/24641006/cf513d0e-6be4-4e58-a524-37bc59629c52

### Environment

* Version: 2.14
* OS: OSX
* Python Version: 3.9
* Docker Version: 20.10.17

### Additional context

This has probably been a problem for a bit.

**Comment by allisonking** [comment]
> CK hit a bug this week where changes to the connection config were not being saved as well. My point is that this may be a problem beyond just saving a data use when we dig in. ![image](https://user-images.githubusercontent.com/8682444/247156948-821f7a60-c588-43ac-92a4-7d50e43571fb.png)

Thanks Rachel! I dug into this a bit and am pretty sure the screenshot you have here is a separate issue, so you may want to open a separate ticket 👍

**Comment by Roger-Ethyca** [comment]
moving to done
