### ISSUE TITLE
UI flow for SaaS Connector authentication via OAuth

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fides#3620]
### Is your feature request related to a specific problem?

The current authentication flow for SaaS connectors which require OAuth is overly complicated for non-technical users. This is painful because mistakes are more likely to be made in setup, and manual intervention and guidance is always required.

### Describe the solution you'd like

A UI based flow for authenticated an OAuth connector.

**Comment by Roger-Ethyca** [comment]
when authentication is completed but the user had to enter in their creds they are returned to a blank system information screen. however when creds are cashed the user is returned to the integration screen for the connector they are setting up.

**Comment by Roger-Ethyca** [comment]
moving to done
