### ISSUE TITLE
Update connector forms to match designs

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3622]
Update the forms for connector configuration to match new designs.

**Comment by rsilvery** [comment]
@TheAndrewJackson  to create a checklist of what he can do in sprint 13. Remaining tasks will be a new ticket in later sprint.

**Comment by rsilvery** [comment]
@TheAndrewJackson  did you make any progress on any part of this?

**Comment by TheAndrewJackson** [comment]
@rsilvery I haven't been able to start this work yet

**Comment by rsilvery** [comment]
Assigning to @Kelsey-Ethyca  because I think she's working on this
