### ISSUE TITLE
integration search only uses lower case letters

### ISSUE THREAD

**Issue by Roger-Ethyca** [ethyca/fides#3624]
### Bug Description

_A description of what the bug is._

#### Steps to Reproduce

1. click add a system from data map > add systems 
2. add a 3rd party connection ( i used braze)
3. after name and key are added click save 
4. now click integration 
5. under the drop down click connection type 
6. search for Braze with a capital B
7. now search braze with a lower case b

### Expected behavior

after step 6 the Braze integration is displayed regardless upper or lower case

### Screenshots

<img width="1218" alt="Screenshot 2023-06-18 at 10 01 45 PM" src="https://github.com/ethyca/fides/assets/115798183/b311875f-01fc-4039-a3e2-71bd50d405ac">
<img width="1224" alt="Screenshot 2023-06-18 at 10 02 02 PM" src="https://github.com/ethyca/fides/assets/115798183/48982398-7738-4dd7-a17c-f35a35c2fcd4">

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by rsilvery** [comment]
See also: https://github.com/ethyca/fides/issues/3681

**Comment by Roger-Ethyca** [comment]
moving to done 


![Image](https://github.com/ethyca/fides/assets/115798183/a2c4a6ef-0726-420f-9153-bb456d7afd47)
![Image](https://github.com/ethyca/fides/assets/115798183/6d356720-c8e7-4624-b3aa-5fea007450b5)
![Image](https://github.com/ethyca/fides/assets/115798183/19b9989a-82a3-4215-ac62-3532baf25f4b)
