### ISSUE TITLE
Move management from primary nav to gear icon

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#3631]
![Image](https://github.com/ethyca/fides/assets/101993653/a7f719ea-4dc0-4e66-ad0a-9dca084dd44a)

AC
- Remove 'Management' from the primary nav 
- Add a gear icon to the left between the user and tooltip icons in the top right 
- On click of the gear icon nav to /user-management (where 'Management' previously directed the user)

**Comment by rsilvery** [comment]
@jpople  can you also change the order of the nav menu items so Data Map is between Home and Privacy Requests?
