### ISSUE TITLE
Make tiles clickable in View Systems page

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#3632]
AC 
- When clicking the tiles of the View Systems page nav to `/systems/configure/{system-fides-key}` as if you clicked on the ellipsis then edit 
- The ellipsis should remain with the menu items edit and delete, functioning as it does today 

@rsilvery if we want to remove the ellipsis menu we will need to add a delete option in the system config

**Comment by rsilvery** [comment]
Decision: keep kabob menu for now

**Comment by Roger-Ethyca** [comment]
moving to done
