### ISSUE TITLE
Research: Choosing geographies and updating notices for GPP

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#3634]
Design Doc and tickets

**Comment by allisonking** [comment]
Design doc: https://ethyca.atlassian.net/wiki/spaces/EN/pages/2728984588/2023-06-28+Generating+a+GPP+string

**Comment by pattisdr** [comment]
Backend: https://ethyca.atlassian.net/wiki/spaces/EN/pages/edit-v2/2730688607

**Comment by Roger-Ethyca** [comment]
moving to done
