### ISSUE TITLE
[Epic Planning] Research for Privacy Request Service API

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#3645]
https://ethyca.atlassian.net/wiki/spaces/EN/pages/2694316339/Distributed+Fides+Privacy+Request+Service+and+other+solutions+for+remote+DB+connections+May+2023

**Comment by ThomasLaPiana** [comment]
Design Doc + Discussion happened [here](https://ethyca.atlassian.net/wiki/spaces/EN/pages/2730426428/2023-06-30+Privacy+Request+API+DSR+2.0), this is good to start breaking into issues and executing

**Comment by Roger-Ethyca** [comment]
moving to done
