### ISSUE TITLE
the Admin Router is causing circular import issues due to it importing database functions

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#3652]
### Bug Description

`from fides.api.db.database import migrate_db` will throw an error, due to a circular import caused by the `admin.py` defined endpoint

This is annoying but doesn't currently break `fides` directly, however it did require some workarounds in `plus`

**Comment by ThomasLaPiana** [comment]
@Kelsey-Ethyca FYI I found this bug while working on updating `fidesplus`. I've worked my way around it over there for this release but we should still fix it 🙂 can be in the next release

**Comment by ThomasLaPiana** [comment]
We've already had quite a few PRs that are working to solve this, so this might not be necessary after all

**Comment by rsilvery** [comment]
@ThomasLaPiana  can we close this?

**Comment by ThomasLaPiana** [comment]
@rsilvery sure, closing for now, we can revisit if we have to

**Comment by Roger-Ethyca** [comment]
moving to done
