### ISSUE TITLE
Release bug: email connector test passes without entering an email address

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3656]
I can run an email connector test without putting in a test email. It's successful. Should either not be a required field or test should fail. Do we need this field at all?

![Image](https://user-images.githubusercontent.com/8682444/248044592-57e6df6d-5171-4709-af54-ef04b261f1a5.png)

**Comment by galvana** [comment]
Hi @rsilvery, can you try this again using a new system? I haven't been able to reproduce this on my end.

**Comment by galvana** [comment]
Not reproducible in current version, closing out
