### ISSUE TITLE
Release bug: YAML editor can't edit datasets

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3658]
Cannot edit a linked dataset using YAML editor: 

![Image](https://user-images.githubusercontent.com/8682444/248046274-db79db8c-b9cf-4a92-a56c-745025faffd9.png)

**Comment by Kelsey-Ethyca** [comment]
1. create new db connector in integrations tag, add dataset, dataset name doesn't show in dropdown till save (bug 1), after cannot edit dataset (bug 2). this exists today, unless you work around it by choosing select, there is not workaround in integration tab.
2. create db connector in connection manager, link in integration tab, dataset editor is blank (bug 3)
3. go to integration tab that has save connector in dataset, click edit button to see blank editor (bug 4), click dropdown and edit a different dataset to see a populated editor, change dropdown to another dataset and click edit to see the wrong dataset in the editor (bug 5)

Note: SaaS datasets are not meant to be editable

**Comment by rsilvery** [comment]
@Kelsey-Ethyca  the dataset editor doesn't show up anymore for SaaS datasets, only for DBs.

**Comment by Kelsey-Ethyca** [comment]
We want to fix the DB dataset not be editable in this ticket during the sprint .

We want to fix the dataset modal being blank and the selection showing wrong dataset before the release. Creating separate ticket and will link here.

**Comment by rsilvery** [comment]
Determined this was intentional. Will focus on a new UX for all of this instead.
