### ISSUE TITLE
Release bug: not handling dedicated system routes right

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3661]
When you create a new system and go to the integrations tab and link a connector, it doesn't appear to work. It does work if you go find the system in the map but you never see what you've saved and it seems to be a route or refresh issue: https://www.loom.com/share/6aadda7e0f3a4e08b50a8b9cebfc0fd0

**Comment by Roger-Ethyca** [comment]
connection manager no longer allows for adding DB. 


![Image](https://github.com/ethyca/fides/assets/115798183/f3b55f5c-3719-43ed-a02d-06cfee091a13)

linking through add system 


![Image](https://github.com/ethyca/fides/assets/115798183/5d81f357-6f08-4164-89bf-01d0e70d7849)



moving to done
