### ISSUE TITLE
Release bug: Dataset dropdown/editor not displaying the correct dataset selection

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#3667]
### Bug Description

You do not always see the dataset you selected in the dropdown when opening the editor. Sometimes the editor is even blank. 

#### Steps to Reproduce

1. create new db connector in integrations tag
2. add dataset
3. click save
4. click edit button to see blank editor
5. change dropdown to another dataset and click edit to see the wrong dataset in the editor

### Expected behavior

You should see the dataset you have selected when opening the editor 

### Screenshots

https://www.loom.com/share/082c754d10204c64b7d37fde539b9e37

### Environment

https://fides-plus-rc.fides-staging.ethyca.com/

**Comment by Roger-Ethyca** [comment]
moving to done
