### ISSUE TITLE
Bug: Integration search focus jumps after two chars have been entered.

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3681]
To reproduce:
1. Type 3 letters into search
2. Focus will have jumped down to list after 2

https://www.loom.com/share/1a88eaad1c494a8a813f92b3400134eb?sid=c9cabf66-6794-4eb4-9c38-533e552495b2

**Comment by Roger-Ethyca** [comment]
moving to done 


![Image](https://github.com/ethyca/fides/assets/115798183/faf3f186-f767-47fc-b4ef-b96d5f950231)
![Image](https://github.com/ethyca/fides/assets/115798183/33a7cbfc-3cbb-4dd2-81af-42b408fb4c13)
