### ISSUE TITLE
Fides pull not working as expected and Fides evaluate not working as expected

### ISSUE THREAD

**Issue by Roger-Ethyca** [ethyca/fides#3689]
### Bug Description

_A description of what the bug is._

#### Steps to Reproduce
From @nicolas-ethyca 
1. Did Fides classify on CLI for postgres since I don't have a postgres instance to test against - BOLO: python warnings and chatty debug
fides classify db \
    --context \
    --content \
    --aggregate \
    --exclude-none \
    --dataset-yaml \
    --outfile ".fides/application_db_dataset.yml" \
    "postgresql://postgres:postgres@postgres-test:5432/postgres_example"    
2. Successfully classified same dataset in the UI and assigned it to a system
3. **:alert:** - Fides pull not working as expected - not pulling down new system made in UI nor dataset
4. Was able to add a forbidden category ([user.date_of_birth) to](http://user.to/) an existing system that was in the systems.yml, fides evaluate failed
5. **:alert:** Fides evaluate not working as expected - Changed the forbidden category to something that is acceptable and re-ran evaluate - (user.contact), fides evaluate still thinks (user.date_of_birth) is there and its failing? I changed it to something else that is forbidden (user.genetic) and it still sees user.date_of_birth. When I checked out the original systems.yml file, the evaluate passed so something is caching and not sure why/how.
6. After checking out the .fides folder to reset state from last step, I added user.contact and ran evaluate and it successfully pushed this to the UI
With this said, I would suggest avoid using the UI pull and show the happy path for fides evaluate without switching it back to a good state. Happy path being:
Add an allowed field such as user.contact and do fides evaluate and show the UI
Add a forbidden field like user.date_of_birth and show it failing and end the demo there

### Expected behavior

_A description of what you expected to happen._

### Screenshots
![image](https://github.com/ethyca/fides/assets/115798183/1fbcd3f4-40d0-4848-87d0-4d28fb463422)

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by Kelsey-Ethyca** [comment]
Closing
- fides evaluate issue I wasn’t able to repro in the 2.15 release candidate (no idea why/how)
- fides pull behavior is now in the new documentation clarifying how it behaves. It doesn’t necessarily align with how I would imagine a developer would work with it but I don’t consider it a bug but a RFE
