### ISSUE TITLE
Modeling Third Party Processors

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fides#371]
### Is your feature request related to a specific problem?

An additional attribute for third party processors is may be required as part of the data map

### Describe the solution you'd like

An additional output column / attribute to list any third party processors that may exist

### Describe alternatives you've considered, if any

I was not clear if this was potentially fulfilled by the recipients listed in the extended data use, some further discussion may be required

### Additional context

This issue is still in a less refined state and can likely be implemented as one of the later issues to allow for more discussion opportunity

**Comment by Kelsey-Ethyca** [comment]
closing all tickets older than a year as not planned
