### ISSUE TITLE
FE: add toggle to disable taxonomy elements to Taxonomy Manager

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3710]
We need to add a toggle that enables our users to mark a particular element in the taxonomy as `disabled` so that these elements don't show up when labeling systems.

![Image](https://github.com/ethyca/fides/assets/8682444/ac98b678-a379-4c06-ae4b-626f85a59df6)

**Comment by rsilvery** [comment]
Let's use the same design we use to indicate custom fields for indicating that the element has been disabled:
<img width="668" alt="image" src="https://github.com/ethyca/fides/assets/8682444/0f56abfa-5dbc-4efb-ab3b-45aea75892bb">

**Comment by Roger-Ethyca** [comment]
moving to done 

![Image](https://github.com/ethyca/fides/assets/115798183/e68ced8e-9225-4e79-87e4-7bd2a69f8389)
![Image](https://github.com/ethyca/fides/assets/115798183/646a3bc1-9bd7-4b15-80b5-b54eb8f74a2f)
![Image](https://github.com/ethyca/fides/assets/115798183/3437cdfa-2255-4147-bfff-0ba4b8e7ded9)



![Image](https://github.com/ethyca/fides/assets/115798183/55bd3782-5e44-4e64-98a6-5f7d32d13b0a)
![Image](https://github.com/ethyca/fides/assets/115798183/3a5cbd3c-4e20-4698-9618-3668e8b41f7f)
