### ISSUE TITLE
Make list of systems in `View Systems` deterministic and sorted by alphabetical descending

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3711]
Currently this list is non-deterministic and not sorted by any field. Should be deterministically sorted alphabetically by system name

**Comment by allisonking** [comment]
Can probably do something like this at the redux level: https://github.com/ethyca/fides/blob/f526d9ffb176006d701493c9d0eff6b4884e811f/clients/admin-ui/src/features/data-qualifier/data-qualifier.slice.ts#L12-L13

**Comment by Roger-Ethyca** [comment]
moving to done 

![Image](https://github.com/ethyca/fides/assets/115798183/73a8d5b4-0fb8-4f9c-8c75-d2e9103130a7)
