### ISSUE TITLE
Auditing Compliance / Completion of Data Map Attributes

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fides#372]
### Is your feature request related to a specific problem?

With so many attributes and potential need for manual attribution a method to score/measure compliance or completeness of the data map would be a useful tool for fides users.

### Describe the solution you'd like

A CLI command to audit completeness of the combined data map model (`scan` command potentially?) and provide not only an overview of the completeness but also actionable items as required to have full coverage.

### Describe alternatives you've considered, if any

n/a

### Additional context

This has been discussed internally at a number of points and seems to fit well to ship with the run state of the data map. Having something like this will be a huge boost in providing clarity around what is required as well as (potentially) who has the action to complete.

**Comment by SteveDMurphy** [comment]
@ThomasLaPiana and @iamkelllly - this issue was touched on when discussing some of the other priorities around a data map a couple of weeks ago. I think a design doc will be required around the full scope of data map compliance, alerting, and creating actionable data around this but at the time it was something I wanted to get an issue out to capture based on user feedback. 

Additionally, coupling some of these items with a UI component will add a lot of value. In the meantime, do we want to narrow the scope on some of this to be similar to a coverage type of command (validating the legal basis is set for instance) or even defer this issue until later?

**Comment by ThomasLaPiana** [comment]
For a single ticket, I think the scope is just `write a function that can check what missing data map attributes there are`, then other tickets would be `add data map audit to the CLI` and `add data map audit to the UI`
