### ISSUE TITLE
[Frontend] UI components for TCF modal design

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#3723]

**Comment by allisonking** [comment]
* [ ] Implement tabs component (keeping a11y in mind!)


![Image](https://github.com/ethyca/fides/assets/24641006/4994830b-2a44-4876-b799-8d703bfe0cab)


* [ ] Toggles need to be able to have subsections



![Image](https://github.com/ethyca/fides/assets/24641006/1ffb2bb7-85f8-412b-b9b9-1a1fa2811c5d)


* [ ] GVL tag


![Image](https://github.com/ethyca/fides/assets/24641006/44ea18d4-d267-4dc3-86e5-634a965db16a)


* [ ] GVL vendors filter



![Image](https://github.com/ethyca/fides/assets/24641006/3eaa0d90-4813-4e97-bec1-0237bd568c19)


* [ ] Cookie table


![Image](https://github.com/ethyca/fides/assets/24641006/d61d3994-21c8-408a-a08e-74d618f3c2d8)

**Comment by Roger-Ethyca** [comment]
moving to done
