### ISSUE TITLE
Privacy Center has no HTTP logging

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#3730]

**Comment by ThomasLaPiana** [comment]
@allisonking @TheAndrewJackson

Do either of you know how I might go about enabling this or point me in the right direction?

Do we already have this for the admin-ui? If so, I can just look at the code there and work on porting over the functionality

**Comment by TheAndrewJackson** [comment]
The admin-ui is client side only. We don't have an established logging pattern yet that stores logs on the BE.

For the privacy center, it looks like you'll need to create a `middleware.ts` file at the same level of the `pages/` directory. Within that file you'll be able to create a middleware function that runs on every api request and logs whatever data you need.

This page here goes over how to set some of it up: [https://nextjs.org/docs/pages/building-your-application/routing/middleware](https://nextjs.org/docs/pages/building-your-application/routing/middleware)

I'm pretty sure this seems like the right path. I'd start with `console.log()` at first and try to add a logging library if it seems like we need one. I'm not sure what the most popular nodejs logging library is at the moment.

Does this seem correct @allisonking?

**Comment by ThomasLaPiana** [comment]
@TheAndrewJackson thank you!! I'll definitely go down this path and see what I find 😄

**Comment by Roger-Ethyca** [comment]
moving to done
