### ISSUE TITLE
Resolve failing tests on `main`

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fides#3736]
### Bug Description

Some tests are failing from the security vulnerability fix in [GHSA-r25m-cr6v-p9hq](https://github.com/ethyca/fides/security/advisories/GHSA-r25m-cr6v-p9hq)

#### Steps to Reproduce

The tests on main can be referenced as well but they are related to `pylint` and a new `ops-unit` test.

on `main`:
* `nox -s dev`
* `fides user login`
* `pytest tests/ops/util/test_api_router.py::TestApiRouter::test_malicious_url`

For the other, `nox -s pylint`

### Expected behavior

The test should pass, it appears to be set to pass when the frontend is unavailable (which may have been ideal for the fork)

As the response appears to be dynamic, it may make sense to mock the path response to a known path instead.

### Screenshots

n/a

### Environment

* Version: `2.15.1`
* OS: Darwin
* Python Version: 3.10
* Docker Version:

### Additional context

Found during the release of `2.15.1`, #3720

**Comment by Roger-Ethyca** [comment]
moving to done
