### ISSUE TITLE
Update Integration tab to use new delete route

### ISSUE THREAD

**Issue by TheAndrewJackson** [ethyca/fides#3739]
# Description
A new delete route was added in #3707. The integration tab needs to be updated to use it to enforce that user role permissions.

## Small bug fix
The FE currently clears out the connection form even if the delete request fails. Update the FE to only clear it out _after_ the request succeeds

**Comment by Roger-Ethyca** [comment]
moving to done 


![Image](https://github.com/ethyca/fides/assets/115798183/d6e4b699-fe49-4a78-ab26-6b7e8d95733c)
![Image](https://github.com/ethyca/fides/assets/115798183/37108558-8639-455d-86f9-ecafd3f4a71c)
![Image](https://github.com/ethyca/fides/assets/115798183/8d53151e-588f-4155-b73c-732284a59eb0)
