### ISSUE TITLE
Autogenerate integration identifier and hide field from connector templates

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3755]
The integration identifier field should be autogenerated from the system name and then hidden. If this needs to be two separate tickets, let me know. 

![Image](https://user-images.githubusercontent.com/8682444/252005315-f728527e-c527-4130-9a6c-272daab60215.png)

**Comment by galvana** [comment]
@rsilvery the integration identifier is used as one component of a dataset reference, a way to reference data retrieved by this integration for use by other integrations. For example, if we retrieved customer information from a Postgres database, we way we could reference the customer ID by the dataset reference `postgres.customer.id`. In this example, "`postgres`" is the identifier provided by the user, but it could have a name that better describes the dataset such as `cookie_house_prod`. My concern is that if we autogenerate these identifiers, we're removing the ability for the integrations to be easily identifiable outside the context of the system integration tab. Additionally level of effort to update our tests is disproportionate to the benefit we'd get.

If the goal is to simplify the setup for demo purposes, would it be acceptable to focus on specific improvements to the way we seed data for the demo environment?

**Comment by rsilvery** [comment]
This one is actually not about the demo environment directly although it's really annoying to have to fill it in when demo'ing - which is done live.
The problem is that it's really frustrating to have to make up a unique field name, particularly with no context for how it will be used. It seems pretty standard to generate a name with a random set of numbers after it to both keep context and also just to solve a problem our users shouldn't have to care about.
For example, System is named: `systemA` so we generate an identifier like `SystemA-connector-123412`. I feel like this is super common. Am I wrong @Kelsey-Ethyca ?

**Comment by Roger-Ethyca** [comment]
tests fixed moving to done
