### ISSUE TITLE
RC bug: all database connector templates can't save with error about `name None`

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3757]
STR:
1. Go to RC
2. Try to create a DynamoDB connector using our creds from 1p (Ask me)
3. fill in fields
4. Try to save connection

![Image](https://user-images.githubusercontent.com/8682444/252028413-49beb12c-8a7a-4749-a160-94af4cb58b30.png)

**Comment by rsilvery** [comment]
Guessing it's because it's related to [this PR](https://github.com/ethyca/fides/pull/3468/files#diff-cfcfc7e88bf00fdbe1692b0b779757b3366b21049a8b16a745bb3c06d83857b9) and these fields need to have `None` in there? 

    aws_access_key_id: str = Field(title="AWS Access Key ID")
    aws_secret_access_key: str = Field(title="AWS Secret Access Key", sensitive=True)

**Comment by rsilvery** [comment]
I have draft PR here to update this file so please incorporate those changes too https://github.com/ethyca/fides/pull/3753/commits/3c102d43c5b6f9e6921b245b9bbec6aa8d5d1970

**Comment by Kelsey-Ethyca** [comment]
Hey @rsilvery this issue is separate from your PR. To follow best practices and reduce what we cherry pick into the release branch, I have asked Adrian to review your PR separately.

**Comment by Roger-Ethyca** [comment]
moving to done 


![Image](https://github.com/ethyca/fides/assets/115798183/074df675-e17f-4fd9-a976-490154fd9f16)
