### ISSUE TITLE
Remove dataset field from BigQuery connector template

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3766]
In the RC build, the BigQuery connector template has a URL field that it shouldn't and the Dataset field isn't operating as expected (just form input):

![Image](https://user-images.githubusercontent.com/8682444/252403270-3f8f9a78-ee00-4173-8b62-9f29c4b59302.png)

**Comment by galvana** [comment]
This was most likely hidden by the faulty form but the `Dataset` field is required, it's the way to specify which "database" to run access and erasures on. Closing ticket.

**Comment by Roger-Ethyca** [comment]
@galvana should this field be marked as required?

**Comment by galvana** [comment]
Hey @Roger-Ethyca, yes, this should be marked as required, that's going to be added as part of https://github.com/ethyca/fides/pull/3753

**Comment by rsilvery** [comment]
@galvana I'm still confused here: are we referring to the BigQuery database here or our dataset? If the latter, why aren't we using the dataset selector we have for all other databases?

**Comment by galvana** [comment]
Hi @rsilvery, I'm referring to what BigQuery refers to as dataset, we unfortunately have a name collision between their concept of a dataset and ours.

**Comment by Roger-Ethyca** [comment]
closing
