### ISSUE TITLE
Add tooltips to database connector templates

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3768]
Adrian to show Rachel example of how to do this.

**Comment by Roger-Ethyca** [comment]
moving to done 


![Image](https://github.com/ethyca/fides/assets/115798183/f9b596df-f59d-46f5-a994-d50a9fbd45d2)
![Image](https://github.com/ethyca/fides/assets/115798183/e39380a0-d1c9-4791-91cf-c1b14f971ffb)
![Image](https://github.com/ethyca/fides/assets/115798183/81bc9113-03ff-4f0e-8210-97486591bb69)
![Image](https://github.com/ethyca/fides/assets/115798183/e80caa0a-aaa3-4596-abea-16c72de15ab3)
![Image](https://github.com/ethyca/fides/assets/115798183/cf09aad9-15f9-45bb-81f5-4134be77e799)
![Image](https://github.com/ethyca/fides/assets/115798183/62582991-5c20-4baa-9b55-3f0b0f0ffe4c)
![Image](https://github.com/ethyca/fides/assets/115798183/dc28f9ac-4158-4cf1-85f2-ba2e07a9a73d)
![Image](https://github.com/ethyca/fides/assets/115798183/53d09a33-7ec6-46b3-85a5-b8a61ab26ed2)
![Image](https://github.com/ethyca/fides/assets/115798183/a805117b-230a-447a-8bb6-0bafb5e42be3)
![Image](https://github.com/ethyca/fides/assets/115798183/5daeee1e-1c78-49e9-a4ab-8f3fa65b14fa)
![Image](https://github.com/ethyca/fides/assets/115798183/e4cdf3c4-10c1-43fb-9a46-6ec3780ebdef)
