### ISSUE TITLE
Remove the /add-systems/manual system selector screen

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3774]
As discussed in #985, we're going to deprecate this part of the UI for now. Swapping this issue into the sprint for #983 which we closed.

![Image](https://user-images.githubusercontent.com/8682444/252738130-651c72f7-4d06-4e83-8133-9dcdbe45b003.png)

**Comment by Roger-Ethyca** [comment]
automation tests have been updated 
moving to done
