### ISSUE TITLE
Update Integration Tab UI

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#3776]

**Comment by Roger-Ethyca** [comment]
moving to done 

![Image](https://github.com/ethyca/fides/assets/115798183/f0fa20ca-0cf4-47f3-82d7-fa79df65bf29)
![Image](https://github.com/ethyca/fides/assets/115798183/425d9f51-a94c-4cb3-a49a-2ef838fbfa2f)
![Image](https://github.com/ethyca/fides/assets/115798183/32af70a7-887c-412f-b6a9-eec4ae4b15c5)
![Image](https://github.com/ethyca/fides/assets/115798183/950424fc-55a8-45b1-8417-a15e8964712f)
