### ISSUE TITLE
Add calls for consent reporting to `fides-js` and `privacy-center`

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3780]
### Is your feature request related to a specific problem?

https://github.com/ethyca/fides/pull/3777 adds endpoints related to consent reporting which `fides-js` and `privacy-center` need to be updated to call.

#### For fides-js

When notices are shown, `PATCH http://localhost:8080/api/v1/notices-served`. Example payload:
```
{
  "browser_identity": {
    "fides_user_device_id": "3e2e5f7c-5367-47d4-b672-9427626c71db"
  },
  "privacy_notice_history_ids": [
    "pri_52008ca3-406e-420f-8509-9429c73ef859"
  ],
  "privacy_experience_id": "pri_6ec7166a-28a8-49d9-9984-9b429d393d11",
  "user_geography": "us_ca",
  "acknowledge_mode": false,
  "serving_component": "overlay"
}
```
This will return an array of `served_notice_history_id`

Then when we do a PATCH http://localhost:8080/api/v1/privacy-preferences, include the `served_notice_history_id`:
```
{
  "browser_identity": {
    "fides_user_device_id": "3e2e5f7c-5367-47d4-b672-9427626c71db"
  },
  "preferences": [
    {
      "privacy_notice_history_id": "pri_52008ca3-406e-420f-8509-9429c73ef859",
      "preference": "opt_in",
      "served_notice_history_id": "ser_e83dd23c-cc82-44bc-9046-824089f80e2e"
    }
  ],
  "policy_key": "default_consent_policy",
  "privacy_experience_id": "pri_6ec7166a-28a8-49d9-9984-9b429d393d11",
  "user_geography": "us_ca",
  "method": "button"
}
```

#### For privacy center
PATCH `http://localhost:8080/api/v1/consent-request/<consent_request_id>/notices-served`
```
{
  "browser_identity": {
    "fides_user_device_id": "3e2e5f7c-5367-47d4-b672-9427626c71db"
  },
  "privacy_notice_history_ids": [
    "pri_52008ca3-406e-420f-8509-9429c73ef859"
  ],
  "privacy_experience_id": "pri_6ec7166a-28a8-49d9-9984-9b429d393d11",
  "user_geography": "us_ca",
  "acknowledge_mode": false,
  "serving_component": "privacy_center"
}
```
which returns a list of `served_notice_history_id`

`PATCH http://localhost:8080/api/v1/consent-request/<consent_request_id>/privacy-preferences`
and include the `served_notice_history_id`s
```
{
  "browser_identity": {
    "fides_user_device_id": "3e2e5f7c-5367-47d4-b672-9427626c71db"
  },
  "preferences": [
    {
      "privacy_notice_history_id": "pri_52008ca3-406e-420f-8509-9429c73ef859",
      "preference": "opt_in",
      "served_notice_history_id": "ser_64565af7-0686-4e69-9100-352d1d11dfce"
    }
  ],
  "policy_key": "default_consent_policy",
  "privacy_experience_id": "pri_6ec7166a-28a8-49d9-9984-9b429d393d11",
  "user_geography": "us_ca",
  "method": "button"
}
```
### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by allisonking** [comment]
Two PR's:
* fides-js: https://github.com/ethyca/fides/pull/3845
* Privacy center: https://github.com/ethyca/fides/pull/3847

The privacy center one is more straightforward. The fides-js one is blocked by a decision on if we want to storing an entry to `/notices-served` on GPC, on banner show, on modal show, or just once.

**Comment by Roger-Ethyca** [comment]
moving to done
