### ISSUE TITLE
Cannot configure Privacy Notice locations with updated country codes

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#3786]
### Bug Description

The format of the locations used in the default privacy notices doesn't match the locations listed and editable from the edit page for a privacy notice. This means that, when editing a notice, I cannot add locations like "FR" and "DE", despite those being valid locations that are used by the defaults.

#### Steps to Reproduce

1. Login to Fides Plus nightly build
1. Navigate to Privacy Notices and observe the locations for the "Essential" notice include the expected country locations:
<img width="1674" alt="image" src="https://github.com/ethyca/fides/assets/1834295/679836c1-20a8-460a-939f-6ee4d0816b50">
3. Click to edit the notice, and then try to edit/add the locations: 
<img width="1671" alt="image" src="https://github.com/ethyca/fides/assets/1834295/bb4f6087-dd9d-4423-bea4-ce7df98a94de">

### Expected behavior

The list of locations displayed on the edit form should match, and we should provide options for all the valid EU countries 👍 

### Screenshots

See steps to reproduce

### Environment

* Version: 2.16.0

### Additional context

See https://github.com/ethyca/fides/issues/3611 for the change made to the EU location format and the related PR, etc.

**Comment by Roger-Ethyca** [comment]
moving to done
