### ISSUE TITLE
Fideslang taxonomy migrations for version 2.0.0

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3795]
In order to support the GVL taxonomy as needed for TCF v2.2, we'll need to map all of the GVL purposes to FidesLang data uses. CK, MB, and I did this exercise and, as a result, we need the following data use updates:
https://ethyca.atlassian.net/wiki/spaces/PM/pages/2740027499/Taxonomy+updates#Data-uses%3A

**Comment by rsilvery** [comment]
@Kelsey-Ethyca  this is a duplicate of #141 in the fideslang repo. Can I close this one?

**Comment by ThomasLaPiana** [comment]
Work in `Fideslang` is happening [here](https://github.com/ethyca/fideslang/pull/144)

**Comment by Kelsey-Ethyca** [comment]
@ThomasLaPiana should this ticket be closed?

**Comment by ThomasLaPiana** [comment]
@Kelsey-Ethyca it'll get closed when we finish the migration PR

**Comment by Roger-Ethyca** [comment]
testing

**Comment by Roger-Ethyca** [comment]
moving to done.
