### ISSUE TITLE
Update system forms to match design

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3827]
System forms will need to be updated to match these designs: https://www.figma.com/file/dmEwdK3xZwjKfGVQ9t66xe/Fides-v.2-Master-Working-Files?type=design&node-id=5542-180091&mode=design&t=QuQaGFGCJ5szviCb-0

To make this easier, I have a list of the form fields, tooltips, and tags here: https://ethyca.atlassian.net/wiki/spaces/PM/pages/2742648890/Dictionary+forms

AC:
- The list of fields, their labels, and their tooltips match design and instructions
- Users can fill out the fields 

Out of scope but be aware
- Fields will be able to integrate with the dictionary to autofill
- Fields all show up in data map as columns in the table

A stretch goal is to have the regulation labels like `gdpr` but they are not required for this phase.

@rsilvery and @Kelsey-Ethyca to create separate tickets for be updates

**Comment by rsilvery** [comment]
When this is complete we need to do https://github.com/ethyca/fides/issues/3827

**Comment by Roger-Ethyca** [comment]
after creating a new system when you return back to that system using edit the system name is no longer displayed 

when editing a system the description field does not enable the save button 

selecting anything below dataset reference does not enable the save button when editing

**Comment by Roger-Ethyca** [comment]
I also noticed that when you edit a newly created system and click on the Data use or data flow tabs you are prompted with a message about unsaved changes. you can click on integrations without seeing this message and after that go to data use and data flow without getting the messages.

**Comment by Roger-Ethyca** [comment]
when using the suggestion icon then saving the suggestions and returning back to the system info screen I noticed that most of them are not saved



![Image](https://github.com/ethyca/fides/assets/115798183/addc1589-8e98-4238-95b7-e32431468964)
![Image](https://github.com/ethyca/fides/assets/115798183/4976d37b-0227-4139-83a9-104656c56453)
![Image](https://github.com/ethyca/fides/assets/115798183/8323b159-c954-4aa7-853b-5485735c3d2b)
![Image](https://github.com/ethyca/fides/assets/115798183/b7ee19fc-62d5-4e71-b445-28756b3de28b)
