### ISSUE TITLE
Fields from updated system forms need to show up in data map as columns in the table

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3832]
Similar to #3827. We need to make sure that all new fields that appear on the system or in the data use declarations appear as columns in the data map. This has to do with the data map export code and @adamsachs  will have a lot of context here. 
<img width="2254" alt="image" src="https://github.com/ethyca/fides/assets/8682444/79210f4e-0d26-4eb7-90cc-26de5503e924">

**Comment by Roger-Ethyca** [comment]
moving to done 


![Image](https://github.com/ethyca/fides/assets/115798183/e5b8da1e-8f6b-40cd-9a97-dce6b39b78a3)
![Image](https://github.com/ethyca/fides/assets/115798183/103a6a89-d586-4f40-b382-bedd1e64c68b)
![Image](https://github.com/ethyca/fides/assets/115798183/71d3e2cc-d4e5-4a14-bee4-83f2e811da38)
![Image](https://github.com/ethyca/fides/assets/115798183/05138c6d-ec78-4aeb-b38a-7868dfa3f028)
