### ISSUE TITLE
Backend work to support expanded system forms

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3833]
Need to determine which backend changes will be needed to support saving fields added in #3827
Also need to store features from the GVL

**Comment by rsilvery** [comment]
@adamsachs  some thoughts:
- We need to add features for GVL
- We need to add a place to link logo

**Comment by adamsachs** [comment]
very initial proposed updates to `fideslang` are commited on this draft PR: https://github.com/ethyca/fideslang/pull/143/files

**Comment by pattisdr** [comment]
New Fideslang PR here to replace previous: https://github.com/ethyca/fideslang/pull/146

**Comment by Roger-Ethyca** [comment]
moving to done
