### ISSUE TITLE
Update navigation

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3867]
We're going to make some changes to the navigation to highlight the consent offering.

Top nav:

- Home
- Data mapping
- Privacy requests
- Consent

Within `Data mapping`

- View map -> graph view
- View systems
- Add systems
- Manage datasets
- Create reports -> table view

Within `Privacy requests`

- Manage requests -> Request manager
- Manage connections -> only appears when unlinked connections exist

Within `Consent`

- Manage notices -> Privacy notices
- Manage experiences -> Privacy experiences

[Design](https://www.figma.com/file/8vQ9W05FlwbVyw3JwBRPAj/Navigation-proposal?type=design&node-id=1001%3A3638&mode=design&t=WfNy1SCNgmcJrnAi-1)

Update tests, docs, and training deck

**Comment by rsilvery** [comment]
We're going to make some changes to the navigation to highlight the consent offering.

Top nav:
- Home
- Data mapping
- Privacy requests
- Consent

Within `Data mapping`
- View map -> graph view
- View systems
- Add systems 
- Manage datasets 
- Create reports -> table view

Within `Privacy requests`
- Manage requests -> Request manager
- Manage connections -> only appears when unlinked connections exist

Within `Consent`
- Manage notices -> Privacy notices
- Manage experiences -> Privacy experiences

https://www.figma.com/file/8vQ9W05FlwbVyw3JwBRPAj/Navigation-proposal?type=design&node-id=1001%3A3638&mode=design&t=WfNy1SCNgmcJrnAi-1

**Comment by Roger-Ethyca** [comment]
@Kelsey-Ethyca I'm not seeing create reports from the table view.

**Comment by Roger-Ethyca** [comment]
Need to update automation tests for user permission navigation

**Comment by Kelsey-Ethyca** [comment]
@Roger-Ethyca the create reports page doesn't exist yet today. i have confirmed with Rachel.
