### ISSUE TITLE
Enhance the document of extending taxonomy model

### ISSUE THREAD

**Issue by bestmoon** [ethyca/fides#388]
### Docs Update Description

* Default taxonomy is not sufficient if users have particular labels they want to use. 
* For example, the default `data subject` types only contain [15 labels](https://ethyca.github.io/fides/language/taxonomy/data_subjects/) and we want to extend to use service-specific terms (such as `contractor`, `supplier`, `provider`, etc). Could you help enhance the document to show how to extend the taxonomy model? Thank you!

**Comment by SteveDMurphy** [comment]
Hi @bestmoon !! Thank you for submitting this as an issue 💙 

I'm currently working on some of the taxonomy extensions and was hoping to get your thoughts and input on the documentation changes. We recently added a guide for extending the `data_use` and I was planning to extend it for all taxonomy types in PR #413. Would you mind seeing if something [like this documentation change](https://github.com/ethyca/fides/blob/520f501add0624f5bb92414645276e64bf9e055c/docs/fides/docs/guides/extending_data_use.md) would address the issue you opened here? Ideally, all of the examples used will also be available in the `demo_resources/` directory as a working example. Thank you!
