### ISSUE TITLE
Update DSR email templates

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3888]
Story:  As a Fides customer, I should be able to change some of the wording around DSR emails to suit my company. 

Goal: Currently, the email content is sent as one big blob. The ask to support sales and CS is:

- [ ] Send this as a string so they can use the CSS editor in mailgun to decorate if needed
- [ ] Make it possible to edit in a config file or simliar
- [ ] Send in discreet sections with variables to fill in the values (see below)
- [ ] Fix number of days for link expiry in access requests email
- [ ] [Stretch] send one-time codes in the subject line

**Example for Access request:**

Subject: [Editable text with a default:  “Your data is ready to be downloaded”]

Body: [Your data access request has been completed and can be downloaded at the link below. For security purposes, this secret link will expire in $# days]: $link

**Example for Approved request:**

Subject: Editable text with a default:  “Your request has been approved”

Body:  Editable text with a default: Your privacy request has been approved and is currently processing.

**Example for Received request:**

Subject: Editable text with a default:  “Your request has been received”

Body:  Editable text with a default: Your privacy request has been received and is currently processing.

**Example for Denial request:**

Subject: Editable text with a default:  “Your request has been rejected”

Body:  Editable text with a default: “Your privacy request has been denied for the reason specified below. For more information, please visit **our** privacy center ($link) for more details. “

$reason_for_denial (example: Need more identification)

**There is also an identity verification email not sampled here but not to be forgotten**

**Comment by rsilvery** [comment]
Story:  As a Fides customer, I should be able to change some of the wording around DSR emails to suit my company. 



Goal: Currently, the email content is sent as one big blob. The ask to support sales and CS is:

- [ ] Send this as a string so they can use the CSS editor in mailgun to decorate if needed
- [ ] Make it possible to edit in a config file or simliar
- [ ] Send in discreet sections with variables to fill in the values (see below)
- [ ] Fix number of days for link expiry in access requests email
- [ ] [Stretch] send one-time codes in the subject line



**Example for Access request:**

Subject: [Editable text with a default:  “Your data is ready to be downloaded”]

Body: [Your data access request has been completed and can be downloaded at the link below. For security purposes, this secret link will expire in $# days]: $link

**Example for Approved request:**

Subject: Editable text with a default:  “Your request has been approved”

Body:  Editable text with a default: Your privacy request has been approved and is currently processing.

**Example for Received request:**

Subject: Editable text with a default:  “Your request has been received”

Body:  Editable text with a default: Your privacy request has been received and is currently processing.

**Comment by Roger-Ethyca** [comment]
moving to done
