### ISSUE TITLE
Hide fields in taxonomy that don't belong there post migration

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3907]
As part of the migration of fields that Dawn, Andrew, and Jeremy are doing, we'll need to hide the following fields in the taxonomy editor:
- Data Use:legal_basis
- Data Use:recipients 
- Data Use:special_category
- Data Use: legitimate_interest
- Data Use: legitimate_interest_impact_assessment

**Comment by rsilvery** [comment]
@Kelsey-Ethyca , @pattisdr as FYI

**Comment by TheAndrewJackson** [comment]
@pattisdr Are the above fields going to be made optional and or completely removed after the migration is done? I have the form fields removed but I can't submit the form due to failing the schema validation check from the BE.

**Comment by pattisdr** [comment]
Good callout @TheAndrewJackson.  I am not removing anything yet to reduce risk, just adding all new fields.  I will mark these as optional in fideslang (I think there was only one of these that wasn't?)

**Comment by TheAndrewJackson** [comment]
Thanks, I'll try making a small change locally while developing to get around the schema issue.

That's correct. The field that is failing  is `legitimate_interest_impact_assessment`

**Comment by Roger-Ethyca** [comment]
moving to. done
