### ISSUE TITLE
Refactor worker healthchecks

### ISSUE THREAD

**Issue by daveqnet** [ethyca/fides#3912]
### Is your feature request related to a specific problem?

* To fix #2517, the worker part of `/health` API request processing was eliminated - see #3898 for details on the code change.
* The fix above is quick and dirty, but leaves fides without a reliable method of checking worker health.
* This feature request is to re-introduce worker health checking in some form without a regression of the API latency impacts of #2517 

### Describe the solution you'd like

As discussed with @ThomasLaPiana:

* Move the worker health check to a separate endpoint. This keeps health lean and quick, while still giving us the ability to check in on the workers if we need to
* Dig in and find a better, more performant replacement for the old worker check

### Describe alternatives you've considered, if any

Do nothing, but this leaves fides open to reliability issues.

**Comment by ThomasLaPiana** [comment]
@daveqnet FYI I've got a PR up that should fix this. It is still relatively high latency but it now has its own endpoint so we can set that accordingly
