### ISSUE TITLE
Build 1st layer of TCF modal with stacks

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3927]
### Is your feature request related to a specific problem?

As part of TCF requirements, we need a "first layer" of the modal which shows stacks (groups of purposes)

### Describe the solution you'd like

Will fill in more after some team discussion...

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

Design: https://www.figma.com/file/dmEwdK3xZwjKfGVQ9t66xe/Fides-v.2-Master-Working-Files?type=design&node-id=7781-250419&mode=design&t=PGSiiqpK8HENjzjY-0

**Comment by Roger-Ethyca** [comment]
closing
