### ISSUE TITLE
Remove the banner from the TCF overlay view

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3934]
### Is your feature request related to a specific problem?

It turns out we likely do not need a banner in the TCF overlay. The TCF overlay will have "layers", where the initial layer acts as a summary of the second layer. If we had the banner too, then there'd be an additional layer the user would have to click through in order to manage their preferences.

### Describe the solution you'd like

We should remove the banner and instead have the modal pop up automatically 

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

Slack discussion: https://ethyca.slack.com/archives/C05E74TR0BB/p1692280502388099

**Comment by pattisdr** [comment]
Also not sure if the FE is using this flag for TCF experiences, but the backend is currently hardcoded to always say "show_banner" for TCF experiences.

**Comment by allisonking** [comment]
Change in plans—this banner should actually show the first layer of our TCF modal. So we should still keep the banner around, but remove the first layer from the modal, plop it in the banner, and let the second layer be the only thing in the modal.
