### ISSUE TITLE
Add data categories to TCF modal

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3938]
### Is your feature request related to a specific problem?

We need to add a table for data categories in the vendor tab.

### Describe the solution you'd like

Awaiting more info from @rsilvery on where this data comes from.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by allisonking** [comment]
Closed by https://github.com/ethyca/fides/pull/4167

**Comment by Roger-Ethyca** [comment]
moving to done
