### ISSUE TITLE
`fidesctl init` writes server_url as "localhost:8080" when it should be "fidesctl:8080"

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fides#394]
### Bug Description
When doing the QA for #386 , found that when running `fidesctl init` and then attempting to ping the server, was getting `Connection failed, webserver is unreachable.` when I was expecting the success message "Fidesctl API service is healthy!"

#### Steps to Reproduce

1. pull main
1. run `make cli`
2. run `fidesctl init`
3. run `fidesctl ping`
4. get the following message:
```
~% fidesctl ping
Pinging http://localhost:8080/health...
Connection failed, webserver is unreachable.
```

6. check .fides/fidesctl.toml, and under [cli] it currently reads: 
```
[cli]
server_url = "http://localhost:8080"
```

### Expected behavior

Instead the server_url should read `http://fidesctl:8080`

### Environment

* OS: linux
* Python Version: Python 3.8.2
* Docker Version: 20.10.8, build 3967b7d

**Comment by hannahcoles** [comment]
Hello! This will be my first time contributing to a GitHub project and this issue looks like a good one to start with. Am I able to claim it?

**Comment by iamkelllly** [comment]
@hannahcoles of course! we welcome any and all external contributors. I can assign it to you now 👍

**Comment by ThomasLaPiana** [comment]
@iamkelllly we talked about this during the fidesctl core team meeting, it looks like the solution here is to add an env var that gets used with `make cli` that overrides the default server host

`FIDESCTL__CLI__SERVER_URL: http:fidesctl:8080` in the `docker-compose.yml` file
