### ISSUE TITLE
consume "pristine" GVL JSON from new API

### ISSUE THREAD

**Issue by adamsachs** [ethyca/fides#3941]
### Is your feature request related to a specific problem?

in https://github.com/ethyca/fidesplus/issues/1044 we are adding to `fidesplus` an API/endpoint that will serve the up-to-date, "pristine" GVL information. we should switch the FE code to get its GVL "source" from this endpoint, rather than using the hardcoded, static asset that we'd started using as an initial cut.

### Describe the solution you'd like

- API details still TBD pending https://github.com/ethyca/fidesplus/issues/1044 work
- API should be assumed to have minimal latency
- should be a relatively "clean" swap out of our existing code, i.e. the response from the API should look identical to the static GVL JSON we're using currently -- at least on our first iteration this.

### Describe alternatives you've considered, if any

continue using static JSON asset, but then we'd need to update that ~every week

### Additional context

blocked by https://github.com/ethyca/fidesplus/issues/1044

**Comment by allisonking** [comment]
Closed by https://github.com/ethyca/fides/pull/4143
