### ISSUE TITLE
Dynamically send TCF bundle based on location

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#3957]
### Is your feature request related to a specific problem?

We currently have a `/consent-settings` endpoint which allows turning TCF on/off. With the new [TCF bundling work](https://github.com/ethyca/fides/pull/3859), the privacy center needs to know whether TCF is on/off in order to determine whether to serve `fides.js` or `fides-tcf.js`. As a temporary measure, we use an environment variable `FIDES_PRIVACY_CENTER__TCF_ENABLED=true turbo dev` to run the privacy center. However, this should really be derived from the backend instead.

### Describe the solution you'd like

The backend `/consent-settings` endpoint is not currently public, which I believe we would need in order for the privacy center to be able to ping it (unless the privacy center has some oauth? I don't think it currently does, but I might be wrong). 

If `/consent-settings` becomes public, then the privacy center should be able to prefetch the settings like we do with experience and geolocation. 

This approach would involve both backend and frontend work.

### Describe alternatives you've considered, if any

Continue using an environment variable?

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by pattisdr** [comment]
great, no problem @allisonking, this was a small change, I will revert to make it private in the TCF backend which will be safer anyway going forward
