### ISSUE TITLE
Banner resurfaces after user consent for pre-fetch experience

### ISSUE THREAD

**Issue by eastandwestwind** [ethyca/fides#4001]
Bug: Banner resurfaces after user consent for pre-fetch experience 

Expectation: Banner does not resurface after collecting user consent for pre-fetched experience

Recommended approach:

- Prefetched experience should rely on cookie (on the client, instead of on the server), if exists, to populate existing consent for all notices
- If client cookie does not exist, we surface the banner, as normal
- If there are notice(s) that are still missing consent, we will make an API call to the server with the fides_user_device_id
- If the response from the server still has notice(s) that are missing consent, we surface the banner

**Comment by Roger-Ethyca** [comment]
moving to done
