### ISSUE TITLE
Flag analytics events as "developer events" while in test mode

### ISSUE THREAD

**Issue by PSalant726** [ethyca/fides#401]
### Is your feature request related to a specific problem?

While developing fidesctl locally (i.e. `FIDESCTL_TEST_MODE == True`), any created analytics events should be specified as "developer events".

### Describe the solution you'd like

When creating an instance of `AnalyticsEvent`, ensure the `developer` property is set to `True` if the `FIDESCTL_TEST_MODE` environment variable is `"true"`.

### Additional context

Blocked by https://github.com/ethyca/fideslog/issues/40.

**Comment by SteveDMurphy** [comment]
Stewing about this some @PSalant726 - would this potentially mean events sent from users cloning the repository, opting in, and getting started would be sent to an alternative test schema?

Alternatively, could we set our config via env vars that have a known `analytics_id` for testing purposes and be able to exclude them from downstream analytics but still maintain a single dataset of anonymous data?

**Comment by PSalant726** [comment]
@SteveDMurphy

> would this potentially mean events sent from users cloning the repository, opting in, and getting started would be sent to an alternative test schema?

The intent of this change is "no", but in reviewing the code it looks like `FIDESCTL_TEST_MODE` is always set to `"True"` automatically in our `docker-compose.yml` file:

https://github.com/ethyca/fides/blob/9e9232ac655c608ed7bb235fca68bb97fecdb2a2/docker-compose.yml#L22-L23

Events should only be sent to the test event database when fidesctl is in test mode, but I didn't realize we always set that value in containers started by running `make cli`. Either 1) I'm misunderstanding the intent of test mode, or 2) this is a bug. Without also making changes to this behavior, it would apply automatically for everyone when developing locally.

I tried digging through previous commits to find some context, but I hit a dead end. Going to need some input from @ThomasLaPiana on this one.

**Comment by SteveDMurphy** [comment]
> Without also making changes to this behavior, it would apply automatically for everyone when developing locally.

As a near-term solution, what do you think about having us set our `FIDESCTL__CLI__ANALYTICS_ID` to a known value so we can at least exclude our own events from the dataset? I don't believe that would require a supplemental release or anything either while we get to the bottom of `FIDESCTL_TEST_MODE`

**Comment by PSalant726** [comment]
How do you see that implementation looking? My first thought would be to include something like `cli.analytics_id = "excluded"` or `"internal"` in `fidesctl.toml`. The concern is that by pushing that `fidesctl.toml` change to VCS, we might mislead new users and result in them creating "excluded" analytics events unknowingly.

**Comment by SteveDMurphy** [comment]
> How do you see that implementation looking?

I was thinking we could potentially just add something in the make file for that env var and store it as part of our local setup, if empty it should get created as part of the opt out routine for new users. Any other users could also store their own `analytics_id` as an env var as well but our known value could still be filtered off of the user data. Heavy emphasis on the near-term of course :)

**Comment by PSalant726** [comment]
Per our discussion this morning, we will continue to capture analytics events sent while `FIDESCTL_TEST_MODE = "true"`, but simply flag those events as "developer events".
