### ISSUE TITLE
Write tests for new updateExperienceFromCookieConsent method in cookie.ts

### ISSUE THREAD

**Issue by eastandwestwind** [ethyca/fides#4011]
https://github.com/ethyca/fides/issues/4001 add a `updateExperienceFromCookieConsent` method in `clients/fides-js/src/lib/cookie.ts` that requires unit tests in `clients/fides-js/__tests__/lib/cookie.test.ts`

**Comment by allisonking** [comment]
Going to tackle this as part of https://github.com/ethyca/fides/issues/4046 since that one edits this function quite a bit and will also need tests!

**Comment by Roger-Ethyca** [comment]
moving to done
