### ISSUE TITLE
Investigate/Solve new Logger errors

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#4020]
### Bug Description

We're starting to see a rash of new errors that seem to have been caused by some unseen version change somewhere.

It appears that when an Exception is thrown in our application, the logger is complaining instead of silently passing it. This actually seems like desirable behavior, but is causing lots of issues as we track down all of the places this is happening.

### Additional context

Here is a commit where I fixed this issue within a test, by using a proper HTTP Exception: https://github.com/ethyca/fides/commit/e933216a51991e2c172a4a4fd6b39e2da26e3880

**Comment by ThomasLaPiana** [comment]
@pattisdr @adamsachs please add more details here when you see some of those new errors around uncaught exceptions!

**Comment by adamsachs** [comment]
for now, quick link to an internal [slack thread](https://ethyca.slack.com/archives/CBKK8TS74/p1693609237987899) with some more details - will publish more specifics on the issue as we dig further...

**Comment by ThomasLaPiana** [comment]
I'm pretty sure these failures are related: https://github.com/ethyca/fides/actions/runs/6092533476/job/16531087165?pr=3933

These as well, which I'll fix in that PR: https://github.com/ethyca/fides/actions/runs/6092533476/job/16531087165?pr=3933

**Comment by pattisdr** [comment]
tests/ops/api/v1/endpoints/test_messaging_endpoints.py::TestGetActiveDefaultMessagingConfig::test_get_active_default_app_setting_invalid

https://github.com/ethyca/fides/actions/runs/6089902442/job/16524075129?pr=4010

**Comment by pattisdr** [comment]
From Adrian: it looks like the version of anyio that we pull in expects us to backport ExceptionGroup from Python 3.11 into older versions
