### ISSUE TITLE
Add a modal form for adding a vendor

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#4053]
### Is your feature request related to a specific problem?

As part of simplifying our consent UI, we'd like a modal form where we can easily add vendors to our data map.

### Describe the solution you'd like

We should be able to reuse a lot of our current system form. Maybe not the form component itself, but at least the API calls. A tricky interaction might be adding multiple data uses. We used to have an accordion thing which IMO was kind of confusing, and also difficult to implement. Our new data use form opens a modal, but we don't want to open a modal within a modal!

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

https://ethyca.atlassian.net/wiki/spaces/EN/pages/2778202186/2023-09-06+Simplify+consent+UI

**Comment by Roger-Ethyca** [comment]
moving to done
