### ISSUE TITLE
Add table for showing vendors and cookies

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#4054]
### Is your feature request related to a specific problem?

We'd like to be able to see our vendors in a table with their cookies grouped together.

### Describe the solution you'd like

We should build a table where cookies are grouped by vendor. We should be able to copy much of the logic in our datamap table, though we’re unlikely able to directly reuse that component as it is very specific to the datamap.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

https://ethyca.atlassian.net/wiki/spaces/EN/pages/2778202186/2023-09-06+Simplify+consent+UI
https://www.figma.com/file/YHpa7SRPqgMu7mTyPx2oTg/same-day-consent-UX?type=whiteboard&node-id=0-1&t=GHFh20M3dwbEScGr-0

**Comment by Roger-Ethyca** [comment]
testing

**Comment by Roger-Ethyca** [comment]
moving to done
