### ISSUE TITLE
Make `data_categories` optional

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#4059]
### Is your feature request related to a specific problem?

We need to make the `PrivacyDeclaration.`data_categories` an optional field to facilitate simplifying consent setup.

### Describe the solution you'd like

Some initial thoughts from @adamsachs :
* need to update both `fideslang` and `fides`
* requires a db update since the column isn't nullable currently (should be pretty minor)
* it def impacts the datamap table export API and that's always a pain
* systems and privacy declarations generally are central things so we just have to make sure there aren't other impacts

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

https://ethyca.atlassian.net/wiki/spaces/EN/pages/2778202186/2023-09-06+Simplify+consent+UI

**Comment by adamsachs** [comment]
not urgent at all, but would like @pattisdr to check my initial analysis here

**Comment by pattisdr** [comment]
The main headaches are likely in the datamap table export as you highlight!  a `5` is probably appropriate.

- First, empty data categories will cause there to be privacy declarations with N/A data use, same thing that happened for empty data subjects https://github.com/ethyca/fidesplus/pull/1074
- And then I think some double checking to make sure `union_data_categories_in_joined_dataframe` is working as expected.  It already had some handling for empty data categories on datasets, but I have no idea if it handles the scenario well where there are no data categories on declarations either.   I would just do a lot of testing around this. For example, I'd want to make sure combining datasets and privacy declarations all with empty categories don't result in something like:   `"N/A, N/A, N/A"`

**Comment by adamsachs** [comment]
@allisonking pointed out that in her testing, the API actually accepts an empty list for `data_categories`! it seems like we are not enforcing any constraint against that at the API/db level currently.

we'd still need to adjust the datamap table export per the above. we should also probably audit the rest of the application to make sure that a `[]` value for a privacy declaration's `data_categories` won't cause problems.

this would probably reduce the estimated LOE, maybe we'd adjust to a `3`? the datamap table export code is still notoriously fragile and cumbersome, so let's not overcorrect and consider this update trivial :)
