### ISSUE TITLE
Migrate System > meta > vendor > id to System > vendor id 

### ISSUE THREAD

**Issue by pattisdr** [ethyca/fides#4084]
### Is your feature request related to a specific problem?

Backend for https://github.com/ethyca/fides/issues/4033 

2.19 released dictionary work where FE was inadvertently writing to system > meta > vendor id.  

If this is set, (and there's not already a vendor_id), move this value over.

![Screenshot 2023-09-13 at 3 43 55 PM](https://github.com/ethyca/fides/assets/9755598/f62c669d-3b0e-4911-90ff-f7c507aa1124)

### Describe the solution you'd like

_A description of what you want to happen._

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by Roger-Ethyca** [comment]
moving to done
