### ISSUE TITLE
Fix incorrect migrations

### ISSUE THREAD

**Issue by galvana** [ethyca/fides#4105]
### Bug Description

_A description of what the bug is._

#### Steps to Reproduce

1. `nox -s shell`
2. `cd src/fides/api/alembic/`
3. `alembic revision --autogenerate -m "check check"`
 
Open the generated migration file, notice the entries for `messaging_template` and `plus_system_history`

### Expected behavior

There shouldn't be any migrations generated from the alembic revision --autogenerate command

**Comment by Roger-Ethyca** [comment]
moving to done
