### ISSUE TITLE
Filter data use options by consent category

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#4118]
There are 4 categories of consent that we care about for now:

- advertising
- analytics
- functional
- essential

For the sameday consent flow, the data use picker should offer these 4 options.  See Confluence doc for how to handle each: https://ethyca.atlassian.net/wiki/spaces/~63356b30748d1bfcb85a0d97/pages/2786525191/Same+day+consent+default+consent+config

**Comment by allisonking** [comment]
this makes sense to do as part of https://github.com/ethyca/fides/issues/4055. I'm going to close this ticket in favor of that one
