### ISSUE TITLE
`GET /connection` endpoint seems slow to respond with many connections present

### ISSUE THREAD

**Issue by adamsachs** [ethyca/fides#4123]
### Bug Description

I'm seeing on our plus-rc environment that the `GET /connection` endpoint is taking an exceedingly long time to respond, up to ~10 seconds. Some of our admin UI relies on this endpoint, e.g. the legacy "connection manager" page but also the "link integration" button on the "integrations" tab of a given system edit page. neither of these UI elements are particularly "mission critical", so we're probably not severely impacting most user experience currently, but any long-running API call is a potential problem lurking!

the specific API call that the UI is making to populate the "link integration" button is `GET api/v1/connection?size=25&page=1&orphaned_from_system=true`, but i've tried the same API call _without_ the `orphaned_from_system` parameter and it actually _increases_ latency. 

one guess is that it's a similar problem to https://github.com/ethyca/fides/issues/4028, and that the relationships on the `ConnectionConfig` model are somehow causing the latency here.

#### Steps to Reproduce

1. create many (5? 10? not sure...) connections/integrations on your fides instance
2. try hitting the above endpoint or going to the admin UI pages mentioned above

### Expected behavior

We should have a more performant endpoint. haven't confirmed this is strictly tied to the number of connections, but seems like it may be, in which case our endpoint latency shouldn't scale linearly with the number of connections we have!

One potential solution to try is to narrow down the response model on this endpoint so that it doesn't include all the relationships it has currently. That's what we did to solve https://github.com/ethyca/fides/issues/4028. It's a bit of a workaround and maybe not getting at the core of the inefficiencies, but could be a good near-term mitigation. Still TBD if that is effective in this case though!

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

Found when testing fix for https://github.com/ethyca/fides/issues/4028, funny enough. But i don't think it's strictly related in any way.

**Comment by adamsachs** [comment]
ok i've done some digging here, and i've gotten some good insight:
- with a remote debugger i was able to isolate the problem, here was the "stack" of what operations were long-running, with highest level first: 
    - `ConnectionConfigurationResponse::mask_sensitive_values` --> 
    - `connection_type::get_connection_type_secret_schema` --> 
    - `connection_type::get_connection_types` --> 
    - loop iterating over  _each_ connection type --> 
    - `ConnectorTemplate::authorization_required` property method & `ConnectorTemplate::user_guide` property method are called to populate arguments for the ConnectionSystemTypeMap call --> 
    - `SaaSConfig(**load_config_from_string(self.config)` operation is called within those property methods
- basically, our pydantic API response model initialization is dependent on some long-running operations - specifically it loops through all our connection types (including all saas types) and for each one, it deserializes some YAML config and initializes a pydantic model, which is a relatively expensive operation (i'm assuming the YAML deserialization - haven't pinned down though if its the deserialization or the model initialization), especially if/when repeated `n` times (with `n` connection types)
 - i confirmed that temporarily removing the `mask_sensitive_values` validator from the `ConnectionConfigurationResponse` API model basically bypassed this problem; that's a heavy-handed solution, but it demonstrates a basic workaround path if we'd want to pursue that
    - i added some print statements to track timing and confirm what operations were taking a long time based on what i'd noticed anecdotally in the remote debugger. see [this commit](https://github.com/ethyca/fides/commit/8c9f6baa8378954624be637e4fca4474196e38ed). if you run off this commit locally and hit the mentioned endpoint, you should see a bunch of statements printed to stdout that can be used to understand timing. see an excerpt from the `stripe` loading, which shows that the `authorization_required` and `user_guide` methods add up to the .24 seconds it takes to load this template. multiplied by `n` connection types, timing on this order of magnitude leads to ~2-3 second response time in general: 
 
```
fides  | took 0.12242187501396984 to load config of Stripe
fides  | took 0.12242266605608165 for full authorization required operation of Stripe
fides  | took 0.12042337493039668 for full user_guide operation of Stripe
fides  | took 5.830079317092896e-07 for adding map entry of stripe
fides  | took 0.2435196249280125 for creating map entry stripe
fides  | took 1.7167069017887115e-05 for loading template stripe
fides  | took 0.2435373750049621 for full template operation stripe
....
fides  | took 2.776415833970532 for all templates
```


- i haven't dug super deep on this, but i'm pretty sure this **is** the same root cause of https://github.com/ethyca/fides/issues/4028, the issue with the `/system` bulk endpoint. specifically, that endpoint was (before the fix/workaround was implemented) populating the `connection_configs` of each `System`,  which have the same API model here `ConnectionConfigurationResponse` that's problematic.


i don't have a firm opinion yet on the best way to fix the root of this problem, but my gut tells me we should be able to populate a static/"global"  set of `ConnectionSystemTypeMap` entries that we store in our `ConnectorRegistry`, alongside and similar to the stored connector templates. essentially, i'd expect the deserialization and model initialization to be run only once on startup or if we want to explicitly reload our connector templates -- it's not something we want run every time these properties `authorization_required` or `user_guide` are needed.

**Comment by ThomasLaPiana** [comment]
@adamsachs agreed, sounds like a little bit of caching will go a long way here

**Comment by Roger-Ethyca** [comment]
moving to done
