### ISSUE TITLE
422 error when updating a taxonomy entity 

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fides#4134]
### Bug Description

When updating a default data use, data subject, or data category in the taxonomy an error is thrown and the update is not saved.

#### Steps to Reproduce

1. run fides or use the rc env
2. go to the taxonomy page https://fides-plus-rc.fides-staging.ethyca.com/taxonomy
3. hover over an entity 
4. click the pencil 
5. make an edit 
6. click Update entity 
7. see the error 

### Expected behavior

Updates should save without error 

### Screenshots

![image](https://github.com/ethyca/fides/assets/101993653/98b27642-f73c-499e-854e-6a3f42e41c3a)

### Environment

* Version: 2.20.1

**Comment by Roger-Ethyca** [comment]
moving to done
