### ISSUE TITLE
Update Quickstart documentation in Step 1 removing `fidesctl db init`

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fides#414]
### Docs Update Description

1. User git clones fidesctl repo
2. User runs `make cli`
3. User runs `fidesctl db init`

Fairly certain that this `fidesctl db init` is deprecated in favor of `fidesctl init` (see issue #313) , and the path you're supposed to run it from is "fidesctl" and not "fides" which is says in the documentation 

![Screen Shot 2022-03-24 at 3 02 58 PM](https://user-images.githubusercontent.com/85575406/159991518-2c9c771f-3a81-4a9f-8654-383b3ecb40e6.png)

**Comment by PSalant726** [comment]
> Fairly certain that this `fidesctl db init` is deprecated in favor of `fidesctl init`

The `fidesctl db init` command isn't deprecated, it's just not the correct command for this scenario. The `fidesctl init` command does a lot to create/populate the config file, and ensure the fidesctl instance is ready to run. The `fidesctl db init` command is focused only on initializing the fidesctl Postgres database.

**Comment by ThomasLaPiana** [comment]
confirmed with @conceptualshark that this got completed but somehow missed getting closed
