### ISSUE TITLE
Make Features and Special Purposes "notice only" in TCF

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#4141]
### Is your feature request related to a specific problem?

Related to https://github.com/ethyca/fides/issues/4137, these TCF entities should effectively be notice-only.

### Describe the solution you'd like

We should change the backend so that if the entity is "Feature" or "Special Purpose", then the consent mechanism should be "notice only".

We also need to change the frontend to respect this. If the mechanism is notice only, then most of the FE should fall into place, but there will probably be a few tweaks needed (and tests/fixtures updated)

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

As of https://github.com/ethyca/fides/pull/4139, we do not send any preferences for Features or Special Purposes

**Comment by pattisdr** [comment]
Just noting here, Allison already noticed this, https://github.com/ethyca/fides/pull/4201 updates the backend to make the default preferences "acknowledge" for feature and special purpose.  That PR updates the default preferences for many of the TCF sections so I just did these altogether -
