### ISSUE TITLE
make clean impacts docker images outside of fidesctl

### ISSUE THREAD

**Issue by brentonmallen1** [ethyca/fides#417]
### Is your feature request related to a specific problem?

When doing a `make clean`, as a last resort in an attempt to debug, it removes all images, including those that aren't connected with the fidesctl product, due to it executing a `docker system prune -a`.  This feels like an over reach.

### Describe the solution you'd like

A filter on the pruning would be nice so that it only impacts images with a `fidesctl` tag, if possible. Otherwise, maybe some documentation on how the command is meant to be used and a warning of the consequences.

### Describe alternatives you've considered, if any

The only alternative I can think of is handling everything to docker natively.  This seems to call into question the necessity of the `make clean` though; other than convenience.

**Comment by ThomasLaPiana** [comment]
`make clean` is definitely a convenience thing but also seems to get overused on the development side. It should only be a last resort or something run to make you feel better about having a totally clean machine.

I like the idea of just pruning the images that are listed in the compose file, that sounds like a good solution.

Then we could rename the current `make clean` to `make prune` or something that is more clear that it is a drastic measure?
