### ISSUE TITLE
Split vendor toggles into separate toggles for consent and legitimate interest

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#4175]
### Is your feature request related to a specific problem?

Vendor toggles need to be two separate toggles instead of one toggle.

### Describe the solution you'd like

Render two toggles instead of just one toggle for vendors. One controls vendor legitimate interest, and one controls vendor consent. Not all vendors will have both though.

We will need to save this to the TC string/cookie and read from it since the backend won't be quite ready yet.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

https://www.figma.com/file/dmEwdK3xZwjKfGVQ9t66xe/Fides-v.2-Master-Working-Files?node-id=10555%3A605238&mode=dev

Split out of this ticket: https://github.com/ethyca/fides/issues/4166

**Comment by Roger-Ethyca** [comment]
moving to done
