### ISSUE TITLE
Support an option to prevent dismissing the Fides.js consent banner

### ISSUE THREAD

**Issue by galvana** [ethyca/fides#4184]
### Description
We should allow for a config option (likely in the experience config in Admin UI) to remove the "x" close button on the banner. Additionally, if this config option is set, you should not be able to dismiss the banner by using ESC or clicking outside the banner.

Follow-up Q:

Should this apply to the modal as well as the banner?
Should this apply to TCF and non-TCF?

**Comment by Roger-Ethyca** [comment]
closing dup...
