### ISSUE TITLE
Update `fides-js` to handle saving vendors with a legal basis dimension

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#4209]
### Is your feature request related to a specific problem?

https://github.com/ethyca/fidesplus/issues/1128 is adding a legal basis dimension for both purposes and vendors. Once the backend is updated with a new payload format, we'll need to make updates on the FE to make it all work together!

### Describe the solution you'd like

https://github.com/ethyca/fides/pull/4189 added double vendor toggles in the FE, but currently it is only persisted to the TC string. It should read these values and persist them to both the backend and to a cookie.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

https://ethyca.atlassian.net/wiki/spaces/EN/pages/2800451585/2023-09-30+Saving+Backend+Legal+Basis+Dimension+alongside+Purposes+and+Vendors?focusedCommentId=2801074353

**Comment by allisonking** [comment]
Closed by https://github.com/ethyca/fides/pull/4216

**Comment by Roger-Ethyca** [comment]
moving to done
