### ISSUE TITLE
Handle legal basis dimension for `purposes`

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#4210]
### Is your feature request related to a specific problem?

https://github.com/ethyca/fidesplus/issues/1128 adds a legal basis dimension for purposes. There's already been some work to handle this for vendors, but we need to do the same work for purposes.

### Describe the solution you'd like

After the backend is updated, we need to update all the fides-js code to split purposes up by legal basis. This will require:
* updates to the cookie saving logic
* updates to the UI to render multiple toggles for purposes

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

https://github.com/ethyca/fides/issues/4209

Do we still want the legal basis filter to work in the same way for this? It has always felt like a filter dropdown to me, but it seems like it's really meant to totally switch the view.

**Comment by allisonking** [comment]
Closed by https://github.com/ethyca/fides/pull/4234

**Comment by Roger-Ethyca** [comment]
moving to done
