### ISSUE TITLE
Update privacy center call to patch privacy preferences due to new API response

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#4225]
### Is your feature request related to a specific problem?

https://github.com/ethyca/fides/pull/4201 changes the response type of patching privacy preferences. Only the privacy center uses this response right now. We need to make sure we update it so that nothing breaks.

### Describe the solution you'd like

Update NoticeDrivenConsent to handle the new response payload. Also update TS types!

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by allisonking** [comment]
Closed by https://github.com/ethyca/fides/pull/4235

**Comment by Roger-Ethyca** [comment]
closing
