### ISSUE TITLE
Fides-js: add link to privacy policy on banner

### ISSUE THREAD

**Issue by eastandwestwind** [ethyca/fides#4229]
### Acceptance Criteria
We currently display a link to the privacy policy on the modal, but need to add it by default (no config option needed here) on th consent  banner.

### Input needed
How should we style the link on the banner? Should we put it inline with the buttons or below the buttons, as we do in the modal?

<img width="741" alt="Screenshot 2023-10-05 at 2 09 49 PM" src="https://github.com/ethyca/fides/assets/7697292/4923648e-82c5-4d55-865f-dee5e6c46b8c">

**Comment by galvana** [comment]
Covered by https://github.com/ethyca/fides/pull/4222
