### ISSUE TITLE
De-duplicate data categories in `fidesctl export datamap`

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#455]
### Is your feature request related to a specific problem?

When generating the datamap via `fidesctl export datamap`, I immediately noticed that I tend to get a lot of duplicate rows. Here's an example generated from https://github.com/ethyca/fidesdemo where I've sorted the output by data category to highlight this:
![image](https://user-images.githubusercontent.com/1834295/161987446-220eb788-14ea-42b0-b3e7-650ea62c8ee1.png)

From a compliance perspective this kind of duplication isn't needed, and the terser the output, the better.

### Describe the solution you'd like

I'd think are options are:
1. De-duplicate rows for export
2. OR de-duplicate rows and also *summarize* the data categories for a system+dataset combo into a single cell
3. Something else entirely!

For option 2 what I mean is that instead of individual rows for each unique dataset+system+category combination, we summarize them. For example:

Before:
| Dataset | System | Categories |
|---|---|---|
| Users Dataset | Web App | user.provided.identifiable.name |
| Users Dataset | Web App | user.provided.identifiable.contact.email |
| Users Dataset | Web App | user.provided.identifiable.contact.country |

Summarized:
| Dataset | System | Categories |
|---|---|---|
| Users Dataset | Web App | user.provided.identifiable.name, user.provided.identifiable.contact.email, user.provided.identifiable.contact.country  |

(Note that Excel should allow you to do line breaks between categories which would be much more legible!

### Describe alternatives you've considered, if any

Someone could manually de-duplicate the Excel output today as a workaround, but it's not very fun.

**Comment by NevilleS** [comment]
While I'm on the topic, another reasonable thing to do would be to export the display `name` of the category instead of the fully-qualified fides key. So `user.provided.identifiable.contact.email` becomes `User Provided Email`. That reads much plainer to the audience for this kind of document.

That's somewhat unrelated to this feature request though, so maybe you'd prefer to open a separate ticket for it - please go ahead and just mention me there 👍

**Comment by SteveDMurphy** [comment]
@NevilleS thanks for opening this up! Before running through it deeper, can you confirm if this was using version `1.4.2` or the latest from `main`? 
#434 is a part of `1.5.0` and addresses some previously known duplication, was curious if this issue could focus more on the summarizing/grouping of data categories or if we are still seeing further row duplication. Thanks!

**Comment by SteveDMurphy** [comment]
Confirmed with `1.5.2` that duplication still exists, this is due to the added `data_qualifier`'s in the dataset in how we are trying to align data categories. Will plan to refactor the work in `export_helpers.py` as part of 1.6 if we can and ensure the `fidesdemo` looks sharp. Thanks again for bringing this up @NevilleS !

**Comment by SteveDMurphy** [comment]
Confirmed with `1.5.2` that duplication still exists, this is due to the added `data_qualifier`'s in the dataset in how we are trying to align data categories. Will plan to refactor the work in `export_helpers.py` as part of 1.6 if we can and ensure the `fidesdemo` looks sharp. Thanks again for bringing this up @NevilleS !
