### ISSUE TITLE
Add a CI check that builds the docs

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#456]
### Is your feature request related to a specific problem?

It is possible for the docs to work just fine locally, but break in CI due to dependency issues

### Describe the solution you'd like

A CI check that builds the documentation to verify that it is valid and won't break on the `publish_docs` step

### Describe alternatives you've considered, if any

Nothing, as it is currently

### Additional context

This happens often due to optional dependencies that are actually needed for type information when importing fidesctl wholesale

**Comment by earmenda** [comment]
Example PR that passes CI checks but breaks docs:
PR - https://github.com/ethyca/fides/pull/440
Merge Action - https://github.com/ethyca/fides/actions/runs/2097577219
