### ISSUE TITLE
Deployment badges don't point to the proper workflow

### ISSUE THREAD

**Issue by brentonmallen1** [ethyca/fides#472]
### Is your feature request related to a specific problem?

The recently added badges for CI status point to the github actions page, but it would be a quality of life improvement for them to point to the workflow for which they're reporting status.

### Describe the solution you'd like

When I click on `Publish fidesctl` (and others) I'd like it to open the `Publish fidesctl` workflow on the github actions page.

**Comment by ThomasLaPiana** [comment]
it was definitely _supposed_ to do this...

will add to 1.6.0 as this should be a small fix. agreed this current implementation is wonky and hoping GitHub supports what we want to do
