### ISSUE TITLE
Create a flow for having a proper CHANGELOG.md and updating it with every PR

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#481]
### Is your feature request related to a specific problem?

We aren't currently using a proper CHANGELOG, and we made some breaking changes with 1.5 that could be painful for existing users.

### Describe the solution you'd like

We can be more transparent and better communicate our changes to users if we implement a proper changelog.

### Describe alternatives you've considered, if any

Using more descriptive PR titles would help somewhat

### Additional context

There are going to be a few ways to do this probably, but we need a scalable solution that will work with automated deployments (no manual steps are allowed). Will require some research as for what the best solution might be.

**Comment by sanders41** [comment]
I have used [release-drafter](https://github.com/release-drafter/release-drafter) for this and it has worked well for me. It adds the changes to the GitHub release tags, and not a CHANGELOG.md file so it would depend on how you want to do it if it would work here.

**Comment by ThomasLaPiana** [comment]
@sanders41 that looks like a cool project!

We're currently doing very basic auto-changelogs for our releases, but I think having the actual append-only file is just a bit nicer. There have been plenty of times I've opened up a changelog for a project I use and done a `ctrl+f` to figure our where a feature I use was changed/updated
