### ISSUE TITLE
Investigate replacing the `Makefile` with `nox`

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#518]
### Is your feature request related to a specific problem?

Make lacks some features in the programmatic department, and although one can resort to bash it then breaks across platforms. Our Makefile is getting a bit messy/complex and as seen on fidesops, additional python files had to be written due to limited Make functionality. 

### Describe the solution you'd like

Replace Make as a dev tool with [nox](https://nox.thea.codes/en/stable/index.html). It is purely pythonic, which means we can use the full power of python to handle our dev tasks as well as natively supports things like matrix testing (testing across multiple python versions, for instance).

### Describe alternatives you've considered, if any

Continuing to use the Makefile as-is or writing more custom python scripts to deal with additional complexity.

### Additional context

This is very much a "does this make sense? Is it feasible?" type of change proposal. I'm not sure how this will look in practice but its worth trying.

**Comment by sanders41** [comment]
This sounds like a good idea to explore to me. There is a good chance Python developers haven't used Make before so this could be more intuitive for contributors also.
