### ISSUE TITLE
calculate_data_subject_rights test failure loading enum

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fides#539]
### Bug Description

We currently are receiving a failure when trying to load a default set of enum values in `DataSubjectRightsEnum`

#### Steps to Reproduce

Within fidesctl...
1. `make cli`
2. `python`
3. `from fideslang.models import DataSubjectRightsEnum`
4. `all_rights = DataSubjectRightsEnum()`

### Expected behavior

This should load a list of all of the enum key:value pairs to be used when setting the data subject rights available.

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version: 1.5.3
* OS: Darwin
* Python Version: 3.9
* Docker Version: 4.6.1

### Additional context

This was split off from #533 where it was discovered the test was not marked properly

**Comment by NevilleS** [comment]
I ran into this issue as well, it seems every time I try to do a `fidesctl datamap export` in the fidesdemo repo.
