### ISSUE TITLE
The first user for fidesctl should be an admin in the UI

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#566]
### Is your feature request related to a specific problem?

There has to be an admin to create other users, or we'll have a chicken/egg problem

### Describe the solution you'd like

The first user that registers with fidesctl should be considered the admin user 

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

The implementation should probably be something along the lines of checking the database for users, and forcing the first user to be admin or something like that

**Comment by LKCSmith** [comment]
Points: 2 - I didn't implement this on ops, so would require some research on my part.

**Comment by ThomasLaPiana** [comment]
no longer relevant
