### ISSUE TITLE
Create a page for organization setup in the Config UI

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#570]
### Is your feature request related to a specific problem?

Users need to be able to enter their organizational information within the Config UI

### Describe the solution you'd like

A minimalist form that allows users to enter their organization's details

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

* MUST display the correct step for the config-ui (Step 1)
* MUST display the following text:
    * Page Title: “Step 1 - Name your organization”
    * Page text: “Provide your organization information. This information is used to configure your organization in Fidesctl for data map reporting purposes.”
* MUST require user to input:
    * Organization Name: textfield
    * Description: textfield
* MUST have tooltips for each input field, explaining what the purpose of the information is:
     * Organization Name: “The legal name of your organization.”
     * Description: “An explanation of the type of organization and primary activity. For example “Acme Inc. is an e-commerce company that sells scarves.””
* MUST validate all input fields to ensure they are correctly completed
* MUST provide a but to “Save & Continue” to the next step
* MUST provide a “Back” link for user to return to the prior page
* MUST provide link to Fides documentation for “help”

**Comment by LKCSmith** [comment]
Points - 3 - the biggest complexity will come from the save and back steps
