### ISSUE TITLE
Create a page that allows users to choose which system setup route they want to take

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#573]
### Is your feature request related to a specific problem?

In the config UI, we need a page that allows users to decide which method of system setup they'd like to choose: AWS/Okta/Manual

### Describe the solution you'd like

see: `step 3` [here](https://ethyca.atlassian.net/wiki/spaces/OSS/pages/2274361345/Fidesctl+Self-guided+Wizard+Requirements)

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by LKCSmith** [comment]
Points - unknown -- QUESTION: Will this require actual integration with AWS or Okta, or has this already been handled?

**Comment by ThomasLaPiana** [comment]
@LKCSmith we've re-scoped this to 1.8, but to answer your question all of the backend work for this ticket is getting done in 1.7
