### ISSUE TITLE
Refactor the Okta scanner to produce systems instead of datasets

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#574]
### Is your feature request related to a specific problem?

Currently the Okta scanner returns datasets

### Describe the solution you'd like

The Okta scanner should output systems, as Okta gives information about the various systems that an organization is using.

### Describe alternatives you've considered, if any

Leaving it as datasets

### Additional context

Okta system scanning is a critical part of the new Config UI flow

**Comment by ThomasLaPiana** [comment]
@earmenda can you note here what is possible to get from the Okta api?

**Comment by earmenda** [comment]
#751 will close this, created #752 for the question above.
