### ISSUE TITLE
Create a config UI page for AWS scanning

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#576]
### Is your feature request related to a specific problem?

_A description of what the problem is._
_Ex. I'm always frustrated when [...]_

### Describe the solution you'd like

Needs to include a form that asks the user for their credentials

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

Aha! Link: https://ethyca.aha.io/features/CTL-120

**Comment by ssangervasi** [comment]
@ThomasLaPiana is that Aha link outdated in favor of the Figma? 
https://www.figma.com/file/NeFvOOb1RT2fcdqZT0vBF2/Fidesctl-Management-UI?node-id=42%3A1612

**Comment by ThomasLaPiana** [comment]
@ssangervasi I think Michael slipped that in, @mfbrown can confirm?

**Comment by mfbrown** [comment]
@ssangervasi Definitely use Figma. Sorry for the confusion with the Aha link. I'll look to see what that was added.

**Comment by ssangervasi** [comment]
Note for reference - It took me a minute to find the API this uses: "generate" instead of "scan". The CLI uses "scan" for both AWS and Okta.

**Comment by SteveDMurphy** [comment]
> Note for reference - It took me a minute to find the API this uses: "generate" instead of "scan". The CLI uses "scan" for both AWS and Okta.

There was some considerable conversation around the naming in here as part of #642 

The current difference is `generate` will generate the manifest for found infrastructure while `scan` will compare existing fides manifests against what is found. I don't think we have found a solid path forward yet but `discover` had been mooted as a possible command at some point as well

**Comment by ssangervasi** [comment]
I wanted to try out my branch calling the actual API but got hung up on the "obscure string" requirement of the key fields. [Here is my attempt](https://github.com/ethyca/fides/commit/5b96dbc26757fcfee019db3b79d23519098632a8) to use a zlib compatible package and JS text encoding that is _supposed_ to work. It didn't work. I think the problem on that branch is that [btoa](https://developer.mozilla.org/en-US/docs/Web/API/btoa) won't decode from a byte array, but it also doesn't have a convention for escaping UTF-8 sequences. So we'd need some other dependency for a working base64 encoder... and that encoder has to use the _same_ convention as python's encoder, which is not guaranteed.

@SteveDMurphy you had some 🤔 about how the frontend would obscure strings in your [PR](https://github.com/ethyca/fides/pull/642), and the answer is 🙀

**Comment by SteveDMurphy** [comment]
Ya there was a bit of hesitation around how this might play out @ssangervasi!
In the meantime, maybe we can unblock just by disabling the `obscure` steps in your branch to buy time to work through potential avenues?
