### ISSUE TITLE
Create a config UI page for Okta scanning

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#577]
### Is your feature request related to a specific problem?

_A description of what the problem is._
_Ex. I'm always frustrated when [...]_

### Describe the solution you'd like

Needs to collect user credentials

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by ssangervasi** [comment]
@thomas - it looks like Okta support for the [generate endpoint](https://github.com/ethyca/fides/blob/c694c124e00ed746c4ef63c09736ce5a85377852/src/fidesapi/routes/generate.py#L114) hasn't been implemented yet. The CLI has `fidesctl scan system okta` so it's a matter of making a version for the API. The UI will have to placeholder the call until that's ready.

**Comment by ThomasLaPiana** [comment]
looks like the PR is ready for review here: #842

**Comment by ThomasLaPiana** [comment]
closing, completed via another ticket
