### ISSUE TITLE
Add an API endpoint for generating resources

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#581]
### Is your feature request related to a specific problem?

Similar to #530 we need an endpoint that can kick off a `scan` and return the results.

### Describe the solution you'd like

A single endpoint that can scan various resources given a set of credentials and being told what type to scan

### Describe alternatives you've considered, if any

A totally different endpoint per scan type

### Additional context

The initial work should only include running the scan and returning the results synchronously.

Update 2022-05-11 @SteveDMurphy - Some smaller issues in support of this have been split off, the intent of this issue is still the same however to have an endpoint that kicks off a scan and returns the output from the `generate` commands

**Comment by ThomasLaPiana** [comment]
use the http spec for passing credentials

**Comment by SteveDMurphy** [comment]
Helpful notes copied over from Slack

* currently `fidesops` protects nearly every endpoint with oauth authentication.
  * No body encryption as expectation is users will have SSL protections in place along with the oauth security in place already
* Some emphasis around the idea that we should potentially encode the body regardless of SSL or other authentication mechanisms in place

Based on the feedback from @PSalant726 and @NevilleS, to keep this moving along will plan to initially just encode the values in transit. Rolling in user authentication will come as part of #564 which can then get us caught up with `fidesops` as far as protecting the endpoints.

Feel free to let me know if there are any other thoughts around this as we get after it!

**Comment by SteveDMurphy** [comment]
> fyi @SteveDMurphy kicking this out to 1.8 because it's not required for the MVP versions of the Config wizard nor the Management UI

@earmenda and I are working on closing the PR for this today most likely as part of 1.7, with that in mind should we keep it around @iamkelllly ?

**Comment by SteveDMurphy** [comment]
A comment from the PR description around the naming as well and how we got here:
> In [9e805d0](https://github.com/ethyca/fides/pull/642/commits/9e805d030cae5234e6e6e7d692a7f22523704f41) all mention of the word scan was removed. There is some existing confusion around the generate and scan commands that could benefit from combining those commands (similar to what was discussed with audit/evaluate) but for consistency purposes today this will use generate exclusively.
