### ISSUE TITLE
Create a page for showing in-progress infra scanning

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#587]
### Is your feature request related to a specific problem?

We need a config UI page that communicates to the user that a scan is taking place and to wait a bit while it runs

### Describe the solution you'd like

A simple title like `Infrastructure Scanning In Progress` as well as an active `loading` type animation

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by LKCSmith** [comment]
Points: 1

**Comment by ThomasLaPiana** [comment]
@LKCSmith since we aren't adding infra scanning until `1.8`, im moving this ticket
