### ISSUE TITLE
Create a success page for registering a system in the Config UI

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#597]
### Is your feature request related to a specific problem?

After a user registers a system, they should be shown a "success" page

### Describe the solution you'd like

Needs to give the user to option to "finish now" or "register another system"

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by LKCSmith** [comment]
Points: 1
