### ISSUE TITLE
Issue with generating dataset for SQL server express

### ISSUE THREAD

**Issue by waghsac** [ethyca/fides#605]
Tried to generate dataset using SQL server express using various connecting strings but getting the below errors.
First one:
fidesctl generate dataset db mssql://WAGHSAC\\SQLEXPRESS/AdventureWorks2019?trusted_connection=yes adw_scan/sample.yml
Server is reachable and the client/server application versions match.
/usr/local/lib/python3.8/site-packages/sqlalchemy/connectors/pyodbc.py:82: SAWarning: No driver name specified; this is expected by PyODBC when using DSN-less connections
  util.warn(
Database connection failed with engine:
Engine(mssql://WAGHSAC\SQLEXPRESS/AdventureWorks2019?trusted_connection=yes)!
(pyodbc.InterfaceError) ('IM002', '[IM002] [unixODBC][Driver Manager]Data source name not found and no default driver specified (0) (SQLDriverConnect)')
(Background on this error at: http://sqlalche.me/e/14/rvf5)

Second one:
fidesctl generate dataset db mssql+pyodbc://WAGHSAC\\SQLEXPRESS/AdventureWorks2019?driver=ODBC+Driver+17+for+SQL+Server?trusted_connection=yes adw_scan/sample.yml
Server is reachable and the client/server application versions match.
Database connection failed with engine:
Engine(mssql+pyodbc://WAGHSAC\SQLEXPRESS/AdventureWorks2019?driver=ODBC+Driver+17+for+SQL+Server)!
(pyodbc.OperationalError) ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
(Background on this error at: http://sqlalche.me/e/14/e3q8)

**Comment by sanders41** [comment]
Are you installing from pypi with `pip install fidesctl` or from a clone with `pip install -e .`? If from pypi does `pip install fidesctl[mssql]` make a difference? Or if from a clone try `pip install -r optional-requirements.txt`.

**Comment by waghsac** [comment]
Thanks @sanders41 will check this out and let you know.

**Comment by NevilleS** [comment]
Hey @waghsac are you still having trouble here? We could do some debugging with you if you're running into issues.

**Comment by waghsac** [comment]
> Hey @waghsac are you still having trouble here? We could do some debugging with you if you're running into issues.

Yes @NevilleS still getting this error.

**Comment by NevilleS** [comment]
OK thanks @waghsac. Can you confirm if you've tried using `pip install fidesctl[mssql]`? This is needed to enable the MSSQL connector.

**Comment by NevilleS** [comment]
You can see a bit more information about these optional dependencies here: https://ethyca.github.io/fides/1.6.0/installation/pypi/#installing-optional-dependencies

**Comment by sanders41** [comment]
@waghsac if you do have the optional dependencies installed can you try wrapping your connection string in quotes to see if it makes any difference?

`fidesctl generate dataset db "mssql://WAGHSAC\SQLEXPRESS/AdventureWorks2019?trusted_connection=yes adw_scan/sample.yml"`

**Comment by waghsac** [comment]
@sanders41 does not work with the quotes as well. Gives the same error.

**Comment by ThomasLaPiana** [comment]
@waghsac can you confirm that you're able to connect to the database otherwise via sqlalchemy? using that connection string?

**Comment by NevilleS** [comment]
Closing as stale, but happy to reopen and troubleshoot further with your help!
