### ISSUE TITLE
Migrate all endpoints to have `/api/v1` prefix

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#623]
### Is your feature request related to a specific problem?
Now that we will have a frontend app, we should prefix all of our API endpoints with `/api` so that the backend and frontend routes don't clash.

### Describe the solution you'd like
Prefix all of our backend API's with `/api`. That will also allow https://github.com/ethyca/fides/pull/621 to be a little smarter about which paths to 404 vs which paths to just reroute to the frontend home page (status quo is to reroute everyone to the home page since there is no easy way to say what is a backend endpoint vs a frontend route)

### Describe alternatives you've considered, if any
Could do nothing, or serve frontend at a specific path, but that would make the user facing URL weird

### Additional context
See https://github.com/ethyca/fides/issues/560#issuecomment-1121537768

**Comment by NevilleS** [comment]
Good point! I'd vote for `/api/v1` specifically, to match the URI structure of fideops
