### ISSUE TITLE
Internal server errors are being swallowed in endpoints

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#691]
### Bug Description

When there is an error in an endpoint, we do not get a log in the console about what it is.

#### Steps to Reproduce

1. Run `nox -s api`
1. Add a `raise Exception('error')` to one of the endpoints, i.e. in `/api/v1/health`
2. Navigate to the endpoint, which will display "Internal Server Error" in the browser, but nothing in the logs

### Expected behavior

A stack trace with the error to show up in the logs

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version: main
* OS: macOS Monterey
* Python Version: 3.8
* Docker Version: 20.10.14

### Additional context

_Add any other context about the problem here._

**Comment by ThomasLaPiana** [comment]
closing as per @NevilleS 's comment, I think he meant to
