### ISSUE TITLE
Build a view to modify a dataset collection

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#706]
### Is your feature request related to a specific problem?

I want to be able to edit a collection.

### Describe the solution you'd like

Should be similar to https://github.com/ethyca/fides/issues/703 but hook it up to modify a collection instead of a field.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

Time estimate: 1 day

**Comment by rsilvery** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UX fixes for table view](https://trello.com/c/kTlUoIkz/1-ux-fixes-for-table-view)
