### ISSUE TITLE
Fidesctl User Management UI

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#729]
Create user facing documentation for the fidesctl user management UI. This experience will be ported directly from fidesops, in case there is already any documentation on user management from that project.

**Links**
- User Management Requirements: https://ethyca.atlassian.net/wiki/spaces/PM/pages/2149646337/Fidesctl+Management+UI+-+Feature+requirements+WIP#User-Management 
- **Fidesops User Management Designs:** https://www.figma.com/file/MTbZohIGvB4bq2f2wkiDHO/?node-id=94%3A1273 (we should expect fidesctl to be nearly the same.

**Comment by mfbrown** [comment]
@conceptualshark  we can deprioritize this

**Comment by conceptualshark** [comment]
Closing this as unneeded with upcoming changes.
