### ISSUE TITLE
fidesdemo failing using documented tutorial

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fides#730]
### Bug Description

Currently, the [fidesdemo](https://github.com/ethyca/fidesdemo) fails due to using the `latest` tag from Docker in the docs and `fidesctl>=1.0.0`. in `requirements.txt`. 

When using the latest from DockerHub it is the latest from `main`. Currently that requires the `API_PREFIX`, which is not present in a release to `PyPI`. This will inevitably cause further issues down the road however with other changes driving mismatched versions.

There are many ways to combat this, but one attractive option could be using a `stable` tag for Docker as well and pointing to that image to keep the versions consistent with PyPI.

As a near term workaround, maybe pointing to the same versions found in `main` would suffice as well with another update for `1.7.0`

`main` in [fidesdemo](https://github.com/ethyca/fidesdemo) currently has both of these version pinned to `1.6.0` but the documentation for the tutorial does not.

#### Steps to Reproduce

Running through the tutorial steps of fidesdemo, the trouble begins after [Run fidesctl via Docker](https://ethyca.github.io/fides/1.6.0/tutorial/add/#run-fidesctl-via-docker)

### Expected behavior

Ideally, both the image and installed versions from PyPI are aligned and the tutorial functions.

### Screenshots
![Screen Shot 2022-06-02 at 11 23 04 AM](https://user-images.githubusercontent.com/6758661/171664885-86bb1212-6c65-41e4-84da-681a2fdeda0c.png)
<img width="633" alt="Screen Shot 2022-06-02 at 11 26 50 AM" src="https://user-images.githubusercontent.com/6758661/171664889-363a915a-f5dd-4e1c-8550-911a57d874ed.png">

### Environment

* Version: 1.6.0
* OS: Darwin
* Python Version: 3.9.12
* Docker Version: 20.10.14

### Additional context

This was found by @mfbrown and discussed live with @allisonking and @brentonmallen1

**Comment by SteveDMurphy** [comment]
> General questions, do we need to publish the dev containers to docker hub? If we only published the containers when releasing to PyPI that seems like it would also fix the issues, and I don't think we really want people using the dev containers as a general practice anyways?

Good call @sanders41! 👍🏽 
This came up during `fideslog` development as well where we decided to only push to docker on release like you are suggesting. Maybe something to validate with @ThomasLaPiana in case of benefits or reasons to publishing the `fidesctl` image to docker when merging to main?

**Comment by NevilleS** [comment]
Also just so I understand @SteveDMurphy: the `fidesdemo` repo itself works, right? Just not our documentation that walks a user through essentially _recreating_ that demo repo themselves?

**Comment by ThomasLaPiana** [comment]
@sanders41 @SteveDMurphy y'all are totally right! This is a legacy bug that should be changed. We should only push to dockerhub on releases

**Comment by SteveDMurphy** [comment]
> Also just so I understand @SteveDMurphy: the `fidesdemo` repo itself works, right? Just not our documentation that walks a user through essentially _recreating_ that demo repo themselves?

@NevilleS I believe that is the case, we opened this issue thinking it could be addressed through docs and/or ci changes in here 👍🏽 

If we want to keep things aligned going forward, we may want to decide on having our docs either point to the same pinned version and update regularly or flip `fidesdemo` to also use the latest released

**Comment by ThomasLaPiana** [comment]
addressed in #731
