### ISSUE TITLE
CORS Middleware Required for UI

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fides#766]
### Is your feature request related to a specific problem?

As part of the `fidesctl` UI development, some CORS related headers are required

### Describe the solution you'd like

Provide an option for CORS Middleware, similar to `fidesops`

### Describe alternatives you've considered, if any

n/a

### Additional context

@elliotbonneville can you confirm the localhost addresses to be whitelisted in here

**Comment by SteveDMurphy** [comment]
@allisonking am I correct in thinking we can close this as not planned?

**Comment by allisonking** [comment]
yah I think so!
