### ISSUE TITLE
Serve Admin UI from `/` instead of `/static/index.html`

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fides#777]

**Comment by ThomasLaPiana** [comment]
@seanpreston can you elaborate on this? As far as I can tell, we're properly serving at `/`

i.e. run `nox -s dev` on `main` branch and navigate to `localhost:3000`, it'll show the landing page as expected

**Comment by allisonking** [comment]
I confirmed with @TheAndrewJackson that we do already do this, and Andrew is working on https://github.com/ethyca/fidesops/pull/720 to get fidesops to the same place. So I don't think there is anything we need to do on our side for this, but lemme know if there is, Andrew!
