### ISSUE TITLE
Standardize error handling for dataset API

### ISSUE THREAD

**Issue by ssangervasi** [ethyca/fides#803]
I went looking for a related info fidesops but couldn't pin down what you meant. Maybe create an issue to document or implement this.

_Originally posted by @ssangervasi in https://github.com/ethyca/fides/pull/782#discussion_r903174350_

**Comment by allisonking** [comment]
Oh right, more context here: https://github.com/ethyca/fides/pull/772#discussion_r900690619

Basically I believe we want to marshal our error responses through type predicates in order for the code to know what type of error we received and how to display it. I did this on the fidesops side (really I was just trying to fix linting, but typescript was unhappy about the error parsing, so I went down this rabbit hole) https://github.com/ethyca/fidesops/blob/main/clients/admin-ui/src/features/common/helpers.ts

**Comment by allisonking** [comment]
Closed by https://github.com/ethyca/fides/pull/896
