### ISSUE TITLE
Meta tag in system API should accept multiple types of values

### ISSUE THREAD

**Issue by LKCSmith** [ethyca/fides#804]
### Is your feature request related to a specific problem?
Currently in our systems API, the meta tag only accepts properties with values that are strings. This doesn't cover our use case in the UI where we want the user to set tags, which should be an array of strings under the meta property in the API. Such as:
`meta: { tags: ["Tag1", "Tag2", "Tag3] } `

Without this, it will make it difficult for a user to search for systems by tag in future UI enhancements.

### Describe the solution you'd like

I would like the API to accommodate the change above and a subsequent UI change needs to be made to reflect the change from string to array of strings.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by NevilleS** [comment]
Rather than use `meta`, I prefer we use the explicit `tags` field that was added to fideslang here: https://github.com/ethyca/fideslang/issues/43

I believe we need to bump the `fideslang` import to pull this change in though?
