### ISSUE TITLE
Docker prod push workflow skipped on release

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fides#807]
### Bug Description

Originally discovered by @mfbrown, the action to push all new tagged images on release failed to execute the prod step for `1.7.0`

We pushed the images manually this time around, but we should prioritize this to have it ready for the next release.

When running the steps manually, it was also discovered that the tagged version image is not pushed (just `:latest`)

#### Steps to Reproduce
(not as trivial, maybe use a test repo)
1. Cut a release
1. The workflow skips the step to push to prod
2. [example workflow](https://github.com/ethyca/fides/runs/7029464455?check_suite_focus=true)

### Expected behavior

3 tagged images should be pushed, (`:dev`, `:latest`, `:released_version`)

### Screenshots

<img width="696" alt="image" src="https://user-images.githubusercontent.com/6758661/175753708-5a54a835-a2e1-4b19-9605-abea70243ff7.png">

### Environment

* Version: 1.7.0
* OS: Darwin
* Python Version: 3.9.12
* Docker Version: 20.10.14

### Additional context

Some quick preliminary research yielded the potential for `github.event.release.tag_name` to be null when releasing manually. This could be why the step was skipped in the first place. Deferred further research to prioritize getting the images pushed.

**Comment by ThomasLaPiana** [comment]
the jobs with the same check are also not running here, which explains why our docs haven't been versioning (there isn't a history of versions, just the current version and the dev version)

https://github.com/ethyca/fides/runs/7029374113?check_suite_focus=true

**Comment by ThomasLaPiana** [comment]
I think we can use the technique in this SO answer: https://stackoverflow.com/questions/59052527/how-do-i-get-the-event-type-that-triggered-a-github-action

We can check if the trigger was a merge to main or a release, and then base it off of that instead of the tag name
