### ISSUE TITLE
Port cypress test harness over to fides tooling

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#828]
### Is your feature request related to a specific problem?

We are going to go ahead and set up Cypress tests for fidesctl so that we can stay unblocked. https://github.com/ethyca/fides/issues/713

However, we should port over the config we end up with to https://github.com/ethyca/fidesui-tooling. 

### Describe the solution you'd like

Once we have Cypress configured, port it over to the fidesui-tooling repo so that other fides projects can use the same setup.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

https://github.com/ethyca/fidesui/issues/5

**Comment by ssangervasi** [comment]
[Noting](https://github.com/ethyca/fidesui/issues/5#issuecomment-1190934305) that the fidesui-tooling repo has lost some responsibility in favor of putting more in fidesui directly. If the harness can live in the fidesui repo, either in the config package or in a new one, go for that.

**Comment by ssangervasi** [comment]
Giving this 8 points because testing is slow, abstracting between projects is tricky, and the publish+update cycle has some overhead.

**Comment by NevilleS** [comment]
Closing this one out - we've made many other changes!
