### ISSUE TITLE
Local mode (`--local`) doesn't seem to allow using the `fidesctl generate` commands

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#840]
### Bug Description

I was wanting to use `fidesctl` to generate a YAML without spinning up the webserver locally, and figured I'd take `--local` mode for a spin as I hadn't used it recently.

Unfortunately, I think `--local` doesn't disable the reliance on API like we thought anymore, as I immediately get errors:
```
$ fidesctl --local generate dataset db foo
Connection failed, webserver is unreachable at URL:
http://localhost/api/v1/health.
```

#### Steps to Reproduce

```
~% mkdir ~/fidesctl-local-test
~% cd fidesctl-local-test
~/fidesctl-local-test% python3 -m venv venv
~/fidesctl-local-test% ./venv/bin/pip install fidesctl
...
~/fidesctl-local-test% ./venv/bin/fidesctl --local generate db foo
No config file found
Using default configuration values.
Connection failed, webserver is unreachable at URL:
http://localhost/api/v1/health.
```

### Expected behavior

I'd like as many of the CLI commands as possible to work without the webserver - but especially commands like `generate`, `scan` and similar that are meant to help me author my YAML files 👍 

### Environment

* Version: 1.7.0
* OS: macOS-12.4-x86_64-i386-64bit
* Python Version: 3.10.5
* Docker Version: 20.10.11

```
~/fidesctl-local-test% ./venv/bin/fidesctl --version
fidesctl, version 1.7.0
~/fidesctl-local-test% ./venv/bin/python --version
Python 3.10.5
~/fidesctl-local-test% ./venv/bin/python -m platform
macOS-12.4-x86_64-i386-64bit
~/fidesctl-local-test% docker --version
Docker version 20.10.11, build dea9396
```

**Comment by ThomasLaPiana** [comment]
to tag onto this, when running `fidesctl --local -h` it should show the only the commands that are available locally, as-is it shows the entire list of commands which doesn't make sense

**Comment by sanders41** [comment]
@ThomasLaPiana `--local` is a flag so that is why it doesn't only show the local commands with `-h`. If it was instead setup to work as `fidesctl local -h` I think it would would as you expect.

**Comment by ThomasLaPiana** [comment]
@sanders41 we're adding commands programmatically, i found the bug locally and got it working as intended. will push up a fix shortly 

```
fides> fidesctl --local
Usage: fidesctl [OPTIONS] COMMAND [ARGS]...

  The parent group for the Fidesctl CLI.

Options:
  --version               Show the version and exit.
  -f, --config-path TEXT  Path to a configuration file.
                          Use 'fidesctl view-config' to
                          print the config. Not
                          compatible with the 'fidesctl
                          webserver' subcommand.
  --local                 Run in 'local_mode'. This mode
                          doesn't make API calls and can
                          be used without the API
                          server/database.
  -h, --help              Show this message and exit.

Commands:
  evaluate   Compare your System's Privacy...
  init       Initializes a Fidesctl instance,...
  parse      Reads the resource files that are...
  view       View various resources types.
  webserver  Starts the fidesctl API server using...
```
