### ISSUE TITLE
Update review requirements for low-risk changes

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides#888]
### Is your feature request related to a specific problem?

Right now it can be oppressive to merge a relatively simple file change, such as a CHANGELOG update that then triggers an entire build/test suite.

### Describe the solution you'd like

Where possible, aka where there is minimal risk, we should decrease the friction to make small changes. This should be a general audit of our review rules, what triggers various code checks in PRs, etc.

**Comment by ThomasLaPiana** [comment]
@ethyca/fidesctl-team any ideas here for things we should simplify/streamline?

for instance not running tests on `CHANGELOG` changes and not requiring a reviewer for `CHANGELOG` changes?

Looking for insight here on where the team feels there is potentially unnecessary friction in the dev process

**Comment by SteveDMurphy** [comment]
I think this would be a big enabler as part of the release process, can see this being handy with cutting a release 👍🏽 thanks for opening this up!

**Comment by ThomasLaPiana** [comment]
@SteveDMurphy any more thoughts here? am I good to close this? still any major issues we can think of that we could address here? although this is technically no longer in my ballpark!
