### ISSUE TITLE
Add a command that allows starting up fidesctl in prod mode

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#928]
### Is your feature request related to a specific problem?

Right now it's difficult to actually see the built UI since our docker-compose overwrites the built static files with the user's local environment.

### Describe the solution you'd like

We should add a command that mirrors the real deployment as much as possible.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

https://github.com/ethyca/fides/pull/757#discussion_r901296645

This would also help us out with https://github.com/ethyca/fidesctl-plus/issues/30

I suspect @ThomasLaPiana has some good ideas on how to do this :)

**Comment by ThomasLaPiana** [comment]
so you're saying add a `nox -s prod` in addition to a `nox -s dev`? Makes sense to me! I'm sure I could cook something up :)

**Comment by allisonking** [comment]
Closing this one in favor of https://github.com/ethyca/fides/issues/2385
