### ISSUE TITLE
Configure the python package to include the UI

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#940]
### Is your feature request related to a specific problem?

Right now, the python package `fidesctl` does not include the admin-ui. Instead, we include it via docker.

### Describe the solution you'd like

We should instead include the static build assets with the python package so that when we run `fidesctl webserver` everything will work, even without docker.

### Describe alternatives you've considered, if any

Keeping everything done via docker

### Additional context

This will help us get the admin-ui running in fidesctl+ as well
https://ethyca.atlassian.net/wiki/spaces/PM/pages/2392260631/Hosting+the+datamap+UI+along+with+fidesctl+UI

I think this will also remove the need for these lines in the Dockerfile (or we'll need to update them) https://github.com/ethyca/fides/blob/main/Dockerfile#L6-L18

**Comment by sanders41** [comment]
The admin-ui is in TypeScript right? Will it work to include that in the pypi package? I don't think so. Even if the files could be included it would only work if the user also has node installed right?

**Comment by allisonking** [comment]
This would be to include the built static files that are a result from an `npm run export` which will build vanilla html, js, css files, that can be hosted without node. So there are kind of two steps to this PR:

1. Figure out how to build the typescript files into static files as part of packaging
2. Include those files in the package (this part seems more straightforward, i.e. using `MANIFEST.in` or maybe [`package_data`](https://setuptools.pypa.io/en/latest/userguide/datafiles.html#package-data)

**Comment by sanders41** [comment]
Got it. Yes, part 2 seems fairly easy, part 1 where is where my think on the potential issue would be. But I guess it should work if you find a way to get them generated as part of packaging.

**Comment by sanders41** [comment]
Oh, and one thing to watch out for here that @PSalant726 and I found is the files will only included with the `pip install` if they are in the `src/fidesctl` directory.

We did something similar to this and found that even though the files were included in the build if they are outside that directory, they don't get included when doing the `pip install`.

**Comment by allisonking** [comment]
> Oh, and one thing to watch out for here that @PSalant726 and I found is the files will only included with the `pip install` if they are in the `src/fidesctl` directory.
> 
> We did something similar to this and found that even though the files were included in the build if they are outside that directory, they don't get included when doing the `pip install`.

Oh dang, thanks for the tip, that's great to know! 

This looks like a useful resource that I'll probably be basing my approach on: http://markneumann.xyz/blog/packaging_uis_in_python/

It doesn't really have a step that automates the frontend build, though. However, Sebastian found that jupyterlab does something like what we want! Here's its [setup.py](https://github.com/jupyterlab/jupyterlab/blob/master/setup.py) which looks like it calls npm directly 🤯 

If it can be built directly in setup.py, that might work? Otherwise I think we may need to add some steps in both the [github workflow that publishes the package](https://github.com/ethyca/fides/blob/main/.github/workflows/publish_package.yaml), and also the [dockerfile](https://github.com/ethyca/fides/blob/main/Dockerfile).

**Comment by sanders41** [comment]
Without having tested it I think the setup.py route could work as long as the person building it has node/npm. Maybe that is ok since the build and release will be done from a GitHub action. Could be confusing for a developer that wants to work with the code since something like `pip install -e .` would also require node/npm. A note in the contributing guide could be used to explain that.
