### ISSUE TITLE
Docs publishing uses invalid github event for release 1.7.1

### ISSUE THREAD

**Issue by earmenda** [ethyca/fides#947]
### Bug Description

Docs publishing failed for release 1.7.1
workflow - https://github.com/ethyca/fides/runs/7567297168?check_suite_focus=true

#### Steps to Reproduce

1. Release a new release
2. boom

### Expected behavior

We should publish new version of docs on releases

### Additional context

#901 Fixed the docker release not working. This was not working before because the docker logic was depending on a release event `github.event.release.tag_name`. This didnt work because the docker event is actually a push event, not a release event. Unfortunately this fix was also applied to the docs workflow but this one actually is triggered by a release event.

**Comment by ThomasLaPiana** [comment]
@earmenda I just updated the fidesops repo to use the same docker workflow. From the description it sounds like the docker workflow runs just fine? It's only the docs workflow that breaks?

**Comment by SteveDMurphy** [comment]
> @earmenda I just updated the fidesops repo to use the same docker workflow. From the description it sounds like the docker workflow runs just fine? It's only the docs workflow that breaks?

Correct @ThomasLaPiana  👍🏽 Docker looks sharp -> https://hub.docker.com/r/ethyca/fidesctl/tags

**Comment by earmenda** [comment]
> @earmenda I just updated the fidesops repo to use the same docker workflow. From the description it sounds like the docker workflow runs just fine? It's only the docs workflow that breaks?

@ThomasLaPiana  Right, the change is to the docs.
