### ISSUE TITLE
Update Documentation for Data Use - Legitimate Interests

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#949]
### Docs Update Description

On the data use documentation, https://ethyca.github.io/fides/language/taxonomy/data_uses/ update the legal_basis enum list to say "Legitimate Interests" instead of "Legitimate Interest" - The API only accepts Legitimate Interests.

### Additional context

_Add any other context about the problem here._

**Comment by sanders41** [comment]
The enum itself in fideslang has a mix for [this value](https://github.com/ethyca/fideslang/blob/16d694889395b94d7b7782ecd23e9bf1fe479a8f/src/fideslang/models.py#L115). It is the only one in the enum where the value doesn't  match the key. Should we update there also?

**Comment by mfbrown** [comment]
@sanders41 As in, there's a mix of plural and singular or am I looking at the wrong thing?

**Comment by sanders41** [comment]
Right it is `LEGITIMATE_INTEREST = "Legitimate Interests"`

**Comment by conceptualshark** [comment]
@mfbrown @sanders41 Did we decide where this should be updated? It makes more sense to me if it remains `legitimate interest`to match the others. This is already correct [in fideslang](https://ethyca.github.io/fideslang/taxonomy/data_uses/#object-structure) - the remaining fides taxonomy docs will be removed shortly. I think this can be closed.
