### ISSUE TITLE
Make 1.8.0 fideslib config changes backwards compatible

### ISSUE THREAD

**Issue by earmenda** [ethyca/fides#956]
### Bug Description

Configs like `FIDESCTL__API__DATABASE_NAME` were replaced with new fideslib based configs like `FIDESCTL__DATABASE__DB`. No migration path was provided for this change. We should decide if we want to make configs and environment variables for old configs map to new configs. 

### Additional context

https://github.com/ethyca/fides/pull/913

**Comment by ThomasLaPiana** [comment]
duplicate of #957
