### ISSUE TITLE
Update "start contributing" link in community docs

### ISSUE THREAD

**Issue by conceptualshark** [ethyca/fides#966]
### Docs Update Description

The "Start Contributing" link at https://ethyca.github.io/fides/1.8.0/community/overview/ should link to Github, but links back to the docs.

**Comment by maitreyi14522** [comment]
hey! is this issue resolved?

**Comment by sanders41** [comment]
Hi @maitreyi14522. There is a PR open to fix it, it's just waiting to be reviewed and merged #968
